"""A2A Mesh Diagnostics — self-analysis, config suggestions, and diagnostic channel.

Diagnostic messages flow through the PG `diagnostic_channel` NOTIFY/LISTEN channel.
Any node can generate diagnostic_report and config_suggestion messages.
These are stored locally and optionally forwarded to developer nodes for analysis.

Message types:
- diagnostic_report: Periodic self-analysis (memory, errors, mesh health, performance)
- config_suggestion: Actionable suggestions for improving the mesh

The diagnostic channel is separate from mesh_channel and delegation_channel
to keep diagnostic traffic isolated and allow fine-grained filtering.
"""

import asyncio
import json
import os
import platform
import time
import traceback
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import logging

from .delegation import _safe_ascii

log = logging.getLogger("a2a_mesh.diagnostics")


@dataclass
class DiagnosticReport:
    """A diagnostic report generated by a node."""
    report_id: str = ""
    node: str = ""
    timestamp: str = ""
    report_type: str = "periodic"  # periodic, on_demand, incident
    severity: str = "info"  # info, warning, critical
    
    # Sections
    memory_stats: Dict[str, Any] = field(default_factory=dict)
    error_patterns: Dict[str, Any] = field(default_factory=dict)
    mesh_health: Dict[str, Any] = field(default_factory=dict)
    performance: Dict[str, Any] = field(default_factory=dict)
    
    # Summary
    summary: str = ""
    recommendations: List[str] = field(default_factory=list)
    
    def to_dict(self) -> dict:
        d = asdict(self)
        # Replace Infinity/NaN values (invalid in JSON)
        def _sanitize(obj):
            if isinstance(obj, dict):
                return {k: _sanitize(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [_sanitize(v) for v in obj]
            if isinstance(obj, float):
                if obj != obj:  # NaN
                    return 0
                if obj == float('inf'):
                    return 1e18
                if obj == float('-inf'):
                    return -1e18
            return obj
        return _sanitize(d)
    
    @classmethod
    def from_dict(cls, d: dict) -> "DiagnosticReport":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class ConfigSuggestion:
    """A config suggestion for improving the mesh."""
    suggestion_id: str = ""
    node: str = ""
    timestamp: str = ""
    category: str = "general"  # performance, reliability, security, feature
    priority: str = "low"  # low, medium, high, critical
    title: str = ""
    description: str = ""
    current_value: str = ""
    suggested_value: str = ""
    rationale: str = ""
    affected_nodes: List[str] = field(default_factory=list)
    status: str = "pending"  # pending, accepted, rejected, implemented
    
    def to_dict(self) -> dict:
        return asdict(self)
    
    @classmethod
    def from_dict(cls, d: dict) -> "ConfigSuggestion":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


class DiagnosticEngine:
    """Generates and manages diagnostic reports and config suggestions.
    
    Suggestions are persisted to the mesh_suggestions PG table for long-term storage.
    In-memory list is used as a cache; on startup, suggestions are loaded from PG.
    """
    
    def __init__(self, node):
        """Initialize with reference to the mesh node."""
        self.node = node
        self.config = getattr(node.config, 'diagnostic', None)
        if self.config is None:
            from core.config import DiagnosticConfig
            self.config = DiagnosticConfig()
        
        self._reports: List[DiagnosticReport] = []
        self._suggestions: List[ConfigSuggestion] = []
        self._task: Optional[asyncio.Task] = None
        self._last_report_time: float = 0
        self._error_counts: Dict[str, int] = {}  # error_type -> count
        self._performance_samples: List[Dict] = []
        self._max_samples: int = 60  # Keep last 60 samples
        self._pg_loaded: bool = False  # Whether we've loaded suggestions from PG

    def _get_min_target_peers(self) -> int:
        """Get the minimum target peers from config, default 2."""
        try:
            discovery_cfg = getattr(self.node.config, "discovery", None)
            if discovery_cfg:
                return getattr(discovery_cfg, "min_target_peers", 2)
        except Exception:
            pass
        return 2
    
    async def start(self):
        """Start the periodic diagnostic report generator."""
        if not self.config.enabled:
            log.info("Diagnostics disabled by config")
            return
        
        # Load persisted suggestions from PG
        await self._load_suggestions_from_pg()
        
        log.info(f"🔍 Diagnostics engine started (interval={self.config.report_interval}s, {len(self._suggestions)} persisted suggestions loaded)")
        self._task = asyncio.create_task(self._periodic_report_loop())
        # Auto-implement loop — periodically accepts and implements safe suggestions
        self._auto_impl_task = asyncio.create_task(self._auto_implement_loop())
    
    async def stop(self):
        """Stop the diagnostic engine."""
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
        if hasattr(self, '_auto_impl_task') and self._auto_impl_task:
            self._auto_impl_task.cancel()
            try:
                await self._auto_impl_task
            except asyncio.CancelledError:
                pass
            log.info("🔍 Diagnostics engine stopped")
    
    async def _periodic_report_loop(self):
        """Periodically generate diagnostic reports and auto-suggestions."""
        while True:
            try:
                await asyncio.sleep(self.config.report_interval)
                report = await self.generate_report()
                if report:
                    self._store_report(report)
                    await self._broadcast_report(report)
                    # Auto-generate suggestions from report data
                    try:
                        await self._generate_suggestions_from_report(report)
                    except Exception as e:
                        log.warning(f"Failed to auto-generate suggestions: {e}")
            except asyncio.CancelledError:
                break
            except Exception as e:
                log.error(f"Error in diagnostic report loop: {e}")
                await asyncio.sleep(60)  # Back off on error
    
    async def _auto_implement_loop(self):
        """Periodically auto-accept and implement safe diagnostic suggestions.
        
        Runs every 5 minutes. Accepts pending suggestions matching known-safe
        patterns and marks them as 'accepted'. Does NOT auto-restart or modify
        config — only accepts the suggestion so it's visible to the operator.
        """
        interval = 300  # 5 minutes
        while True:
            try:
                await asyncio.sleep(interval)
                implemented = await self.auto_implement_suggestions()
                if implemented:
                    log.info(f"📋 Auto-implemented {len(implemented)} suggestions: {implemented}")
            except asyncio.CancelledError:
                break
            except Exception as e:
                log.error(f"Error in auto-implement loop: {e}")
                await asyncio.sleep(60)
    
    async def generate_report(self, report_type: str = "periodic") -> Optional[DiagnosticReport]:
        """Generate a diagnostic report by analyzing the node's state."""
        now = datetime.now(timezone.utc)
        report = DiagnosticReport(
            report_id=f"diag-{self.node.config.node_name}-{int(now.timestamp())}",
            node=self.node.config.node_name,
            timestamp=now.isoformat(),
            report_type=report_type,
        )
        
        # Memory statistics
        if self.config.include_memory_stats:
            report.memory_stats = self._collect_memory_stats()
        
        # Error patterns
        if self.config.include_error_patterns:
            report.error_patterns = self._collect_error_patterns()
        
        # Mesh health
        if self.config.include_mesh_health:
            report.mesh_health = await self._collect_mesh_health()
        
        # Performance
        if self.config.include_performance:
            report.performance = self._collect_performance()
        
        # Generate summary and recommendations
        report.summary = self._generate_summary(report)
        report.recommendations = self._generate_recommendations(report)
        report.severity = self._assess_severity(report)
        
        return report
    
    async def generate_suggestion(self, category: str, title: str, description: str,
                                     current_value: str = "", suggested_value: str = "",
                                     rationale: str = "", priority: str = "medium",
                                     affected_nodes: List[str] = None,
                                     node_name_override: str = None) -> ConfigSuggestion:
        """Generate a config suggestion and persist it to PG.
        
        Args:
            node_name_override: When generating suggestions from a received
                diagnostic report, set this to the source node name so the
                suggestion is attributed to the correct node (not the local
                receiver). This prevents cross-node deduplication failures.
        """
        own_name = node_name_override or self.node.config.node_name
        now = datetime.now(timezone.utc)
        suggestion = ConfigSuggestion(
            suggestion_id=f"sugg-{own_name}-{int(now.timestamp())}",
            node=own_name,
            timestamp=now.isoformat(),
            category=category,
            priority=priority,
            title=title,
            description=description,
            current_value=current_value,
            suggested_value=suggested_value,
            rationale=rationale,
            affected_nodes=affected_nodes if affected_nodes is not None else [self.node.config.node_name],
        )
        self._suggestions.append(suggestion)
        # Keep only last N suggestions in memory
        if len(self._suggestions) > self.config.max_reports_stored:
            self._suggestions = self._suggestions[-self.config.max_reports_stored:]
        
        # Persist to PG
        await self._persist_suggestion_to_pg(suggestion)
        
        await self._broadcast_suggestion(suggestion)
        return suggestion
    
    def _collect_memory_stats(self) -> Dict[str, Any]:
        """Collect memory and system statistics."""
        import psutil
        try:
            process = psutil.Process(os.getpid())
            mem_info = process.memory_info()
            # Use a proper sampling interval for accurate sustained CPU measurement.
            # psutil.cpu_percent(interval=0.0) returns the delta since the last call,
            # which after cpu_times_percent(interval=0.1) produces a misleading spike.
            # First call seeds the baseline; second call with interval measures accurately.
            psutil.cpu_percent(interval=0.0)  # discard baseline
            cpu_raw = psutil.cpu_percent(interval=0.5)  # 500ms sample for real usage
            cpu_times_pct = psutil.cpu_times_percent(interval=0.0)  # non-blocking, uses cached data
            cpu_steal = getattr(cpu_times_pct, 'steal', 0.0)
            cpu_effective = max(0.0, cpu_raw - cpu_steal) if cpu_steal > 0 else cpu_raw

            return {
                "process_rss_mb": round(mem_info.rss / 1024 / 1024, 1),
                "process_vms_mb": round(mem_info.vms / 1024 / 1024, 1),
                "system_memory_percent": psutil.virtual_memory().percent,
                "system_cpu_percent": cpu_raw,
                "process_cpu_percent": round(process.cpu_percent(interval=0.0), 1),
                "cpu_effective_percent": round(cpu_effective, 1),
                "cpu_steal_percent": round(cpu_steal, 1),
                "disk_usage_percent": psutil.disk_usage('/').percent,
                "open_files": len(process.open_files()) if hasattr(process, 'open_files') else 0,
                "connections": len(process.connections()) if hasattr(process, 'connections') else 0,
                "threads": process.num_threads(),
            }
        except ImportError:
            # psutil not available, collect basic stats
            import resource
            return {
                "process_rss_mb": round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024, 1),
                "note": "psutil not available, limited stats",
            }
        except Exception as e:
            return {"error": str(e)}
    
    def _collect_error_patterns(self) -> Dict[str, Any]:
        """Analyze recent error patterns."""
        return {
            "error_counts": dict(self._error_counts),
            "total_errors": sum(self._error_counts.values()),
            "unique_error_types": len(self._error_counts),
        }
    
    async def _collect_mesh_health(self) -> Dict[str, Any]:
        """Collect mesh health information."""
        try:
            status = self.node.get_status()
            # Extract peer info from peer_discovery stats (get_status uses "peer_discovery" key)
            peer_disc = status.get("peer_discovery", {})
            connected_count = peer_disc.get("connected_peers", 0)
            peers_dict = peer_disc.get("peers", {})
            peer_list = [
                {"name": name, "status": "available" if p.get("p2p_available") else "unavailable", "version": p.get("version", "?")}
                for name, p in peers_dict.items()
            ] if isinstance(peers_dict, dict) else []
            
            # Also try P2P transport for live peer info — merge with discovery data
            p2p_info = status.get("p2p", {})
            p2p_peer_names = set()
            if isinstance(p2p_info, dict) and "peers" in p2p_info:
                p2p_peers = p2p_info.get("peers", [])
                if isinstance(p2p_peers, list):
                    p2p_peer_names = set(p2p_peers)
                    # Add P2P-connected peers not yet in peer_list (e.g. connected before discovery tracked them)
                    existing_names = {p["name"] for p in peer_list}
                    for name in p2p_peers:
                        if name not in existing_names:
                            peer_list.append({"name": name, "status": "connected", "version": "?"})
                    # Correct connected_count: P2P-connected peers count even if discovery missed them
                    if len(p2p_peer_names) > connected_count:
                        connected_count = len(p2p_peer_names)
            
            # Uptime: prefer status value, fallback to _start_time calculation
            uptime_val = status.get("uptime", 0)
            if uptime_val == 0 and hasattr(self.node, '_start_time') and self.node._start_time:
                uptime_val = int(time.time() - self.node._start_time)
            
            # Version: prefer _resolved_version, fallback to config
            version_val = getattr(self.node, '_resolved_version', None)
            if not version_val or version_val == 'unknown':
                version_val = getattr(self.node.config, '_resolve_version', lambda: 'unknown')()
                if not version_val:
                    version_val = 'unknown'
            
            return {
                "node_name": self.node.config.node_name,
                "uptime_seconds": uptime_val,
                "version": version_val,
                "role": status.get("role", "unknown"),
                "peer_count": connected_count,
                "peers": peer_list,
                "transports": self._sanitize_transport_latencies(status.get("transports", {})),
                "delegations_active": status.get("delegations", {}).get("active", 0),
                "delegations_completed": status.get("delegations", {}).get("completed", 0),
                "delegations_failed": status.get("delegations", {}).get("failed", 0),
            }
        except Exception as e:
            return {"error": str(e)}
    

    @staticmethod
    def _sanitize_transport_latencies(transports: dict) -> dict:
        """Clamp negative latency values to 0 (clock skew protection).
        
        P2P ACK-based RTT measurement uses (local_time - remote_timestamp).
        If clocks are not NTP-synchronized, this can produce negative values.
        Clamp them to 0 to prevent nonsensical negative latency in reports.
        """
        sanitized = {}
        for name, info in transports.items():
            if isinstance(info, dict):
                info = dict(info)  # shallow copy
                lat = info.get("latency_ms")
                if isinstance(lat, (int, float)) and lat < 0:
                    log.warning(f"Transport {name} reported negative latency ({lat:.2f}ms) — "
                                f"likely clock skew. Clamping to 0.")
                    info["latency_ms"] = 0.0
                # Also sanitize per-peer RTT if present
                peers = info.get("peers")
                if isinstance(peers, list):
                    info["peers"] = peers  # no modification needed for list of names
                elif isinstance(peers, dict):
                    for pname, pdata in peers.items():
                        if isinstance(pdata, dict):
                            rtt = pdata.get("rtt_ms")
                            if isinstance(rtt, (int, float)) and rtt < 0:
                                log.warning(f"Peer {pname} RTT negative ({rtt:.2f}ms) — clamping to 0")
                                pdata["rtt_ms"] = 0.0
            sanitized[name] = info
        return sanitized

    def _collect_performance(self) -> Dict[str, Any]:
        """Collect performance metrics."""
        sample = {
            "timestamp": time.time(),
            "uptime_seconds": time.time() - getattr(self.node, '_start_time', time.time()),
            "message_queue_size": 0,
            "offline_queue_size": 0,
        }
        
        # Collect queue sizes
        if hasattr(self.node, '_message_queue'):
            sample["message_queue_size"] = self.node._message_queue.qsize() if hasattr(self.node._message_queue, 'qsize') else 0
        if hasattr(self.node, 'offline_queue') and hasattr(self.node.offline_queue, 'pending_count'):
            sample["offline_queue_size"] = self.node.offline_queue.pending_count
        
        self._performance_samples.append(sample)
        if len(self._performance_samples) > self._max_samples:
            self._performance_samples = self._performance_samples[-self._max_samples:]
        
        return {
            "current": sample,
            "samples_collected": len(self._performance_samples),
        }
    
    def _generate_summary(self, report: DiagnosticReport) -> str:
        """Generate a human-readable summary of the diagnostic report."""
        parts = []
        parts.append(f"Node {report.node} diagnostic report ({report.report_type})")
        
        mem = report.memory_stats
        if mem:
            rss = mem.get("process_rss_mb", "?")
            sys_mem = mem.get("system_memory_percent", "?")
            parts.append(f"Memory: {rss}MB RSS, {sys_mem}% system")
        
        errs = report.error_patterns
        if errs:
            total = errs.get("total_errors", 0)
            unique = errs.get("unique_error_types", 0)
            parts.append(f"Errors: {total} total ({unique} unique types)")
        
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            parts.append(f"Mesh: {peers} peers connected")
        
        return " | ".join(parts)
    
    def _generate_recommendations(self, report: DiagnosticReport) -> List[str]:
        """Generate recommendations based on the report data."""
        recs = []
        
        # Memory recommendations
        mem = report.memory_stats
        if mem:
            rss = mem.get("process_rss_mb", 0)
            if rss > 500:
                recs.append(f"High memory usage ({rss}MB) — consider restarting or investigating memory leaks")
            sys_mem = mem.get("system_memory_percent", 0)
            if sys_mem > 85:
                recs.append(f"System memory at {sys_mem}% — risk of OOM kill")
        
        # Error recommendations
        errs = report.error_patterns
        if errs:
            for err_type, count in errs.get("error_counts", {}).items():
                if count > 10:
                    recs.append(f"Recurring error '{err_type}' occurred {count} times — investigate root cause")
        
        # Mesh recommendations
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            if peers == 0:
                recs.append("No peers connected — node is isolated, check P2P transport and network connectivity")
            elif peers < self._get_min_target_peers():
                recs.append(f"Only {peers} peer(s) connected (target: ≥{self._get_min_target_peers()}) — mesh resilience is low, check network connectivity")
            
            # Check transport availability
            transports = health.get("transports", {})
            if isinstance(transports, dict):
                unavailable = [name for name, info in transports.items() 
                               if isinstance(info, dict) and not info.get("available", True)]
                if len(unavailable) == len(transports) and transports:
                    recs.append(f"All transports unavailable ({', '.join(unavailable)}) — node cannot communicate")
                elif unavailable:
                    recs.append(f"Transport(s) unavailable: {', '.join(unavailable)} — check connectivity")
            
            failed = health.get("delegations_failed", 0)
            if failed > 5:
                recs.append(f"{failed} failed delegations — check agent capabilities and LLM availability")
        
        return recs
    
    async def _generate_suggestions_from_report(self, report: DiagnosticReport) -> List[ConfigSuggestion]:
        """Automatically generate config suggestions based on diagnostic report data.
        
        Each agent analyzes its own report and creates actionable suggestions
        that appear in the dashboard with status tracking (pending/accepted/rejected/implemented).
        """
        new_suggestions = []
        node_name = report.node
        
        # Helper: check if similar suggestion already exists to avoid duplicates
        # Check title substring AND node name AND not rejected (so pending/accepted/implemented blocks re-creation)
        def _suggestion_exists(title_substring: str) -> bool:
            # Normalized check: compare first 30 chars of title (case-insensitive)
            # This catches near-duplicates like "Csak 1 peer csatlakozva" vs "Csak 1 peer csatlakozva — alacsony"
            target = title_substring.lower().strip()[:30]
            return any(
                target in s.title.lower()[:60]
                and s.node == node_name
                and s.status in ("pending", "accepted", "implemented", "investigated")
                for s in self._suggestions
            )
        
        # ─── Memory suggestions ────────────────────────────────────
        mem = report.memory_stats
        if mem:
            sys_mem = mem.get("system_memory_percent", 0)
            if sys_mem > 90 and not _suggestion_exists("memóriahasználat"):
                s = await self.generate_suggestion(
                    category="memory",
                    priority="critical",
                    title=f"Kritikus memóriahasználat ({sys_mem:.0f}%) — OOM kockázat",
                    description=f"A {node_name} node rendszer memóriahasználata {sys_mem:.0f}%, ami OOM kill kockázatot jelent. Az agent processzek memóriafogyasztásának csökkentése vagy a rendszer memóriabővítése javasolt.",
                    current_value=f"{sys_mem:.1f}%",
                    suggested_value="<85%",
                    rationale="OOM kill esetén az agent nem válaszol, a mesh instabillá válik, és adatvesztés történhet.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
            elif sys_mem > 80 and not _suggestion_exists("memóriahasználat"):
                s = await self.generate_suggestion(
                    category="memory",
                    priority="high",
                    title=f"Magas memóriahasználat ({sys_mem:.0f}%)",
                    description=f"A {node_name} node rendszer memóriahasználata {sys_mem:.0f}%. Ha a trend folytatódik, OOM kockázat léphet fel.",
                    current_value=f"{sys_mem:.1f}%",
                    suggested_value="<75%",
                    rationale="A magas memóriahasználat ronthatja a teljesítményt és OOM kill-hez vezethet.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
            
            rss = mem.get("process_rss_mb", 0)
            if rss > 500 and not _suggestion_exists("RSS memória"):
                s = await self.generate_suggestion(
                    category="memory",
                    priority="high",
                    title=f"Magas RSS memória ({rss:.0f}MB) — lehetséges memóriaszivárgás",
                    description=f"A {node_name} agent folyamata {rss:.0f}MB RSS memóriát használ. Ez memóriaszivárgásra utalhat.",
                    current_value=f"{rss:.0f}MB",
                    suggested_value="<400MB",
                    rationale="A memóriaszivárgás idővel OOM kill-hez vezet. Az agent újraindítása ideiglenesen megoldja, de a root cause vizsgálata szükséges.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
        
        # ─── CPU suggestions (using effective CPU, accounting for steal time) ──
        if mem:
            cpu_raw = mem.get("system_cpu_percent", 0)
            cpu_steal = mem.get("cpu_steal_percent", 0)
            cpu_effective = mem.get("cpu_effective_percent", cpu_raw)
            process_cpu = mem.get("process_cpu_percent", 0)
            # Use effective CPU for thresholds (excludes hypervisor steal)
            # BUT: on Proxmox/VM hosts, system CPU is often 97-100% due to host-wide
            # measurement including all VMs. If process CPU is low (<10%), the mesh
            # process itself is not CPU-bound — skip the critical suggestion.
            cpu = cpu_effective
            if cpu > 90 and process_cpu < 10:
                # System CPU high but mesh process idle → Proxmox host noise
                cpu = process_cpu  # Use process CPU instead, avoids false positive

            # Steal time warning (KVM/VM environments)
            if cpu_steal > 20 and not _suggestion_exists("steal time"):
                s = await self.generate_suggestion(
                    category="performance",
                    priority="high",
                    title=f"Magas CPU steal time ({cpu_steal:.0f}%) — hipervízor túlterheltség",
                    description=f"A {node_name} node CPU steal time {cpu_steal:.0f}%, ami azt jelenti, hogy a hipervízor ennyi CPU időt vesz el a VM-től. A valós (effektív) CPU használat {cpu_effective:.0f}%, a nyers érték {cpu_raw:.0f}% lenne steal nélkül. A probléma a gazdagépen (Proxmox) oldható meg: CPU pinning, kevesebb VM, vagy erősebb gazdagép.",
                    current_value=f"steal={cpu_steal:.0f}% eff={cpu_effective:.0f}%",
                    suggested_value="steal<10%",
                    rationale="A magas steal time a gazdagép túlterheltségét jelzi, nem a VM lokális problémáját. Az agent válaszideje lassulhat, de a megoldás a Proxmox szinten van.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)

            if cpu > 90 and not _suggestion_exists("CPU használat"):
                s = await self.generate_suggestion(
                    category="performance",
                    priority="critical",
                    title=f"Kritikus effektív CPU használat ({cpu:.0f}%)",
                    description=f"A {node_name} node effektív CPU használata {cpu:.0f}% (steal: {cpu_steal:.0f}%). Ez a mesh késleltetését és a válaszidő romlását okozza.",
                    current_value=f"eff={cpu:.0f}% steal={cpu_steal:.0f}%",
                    suggested_value="eff<75%",
                    rationale="A magas effektív CPU használat lassítja az üzenetfeldolgozást, növeli a hálózati késleltetést, és ronthatja az agent válaszainak minőségét.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
            elif cpu > 75 and not _suggestion_exists("CPU használat"):
                s = await self.generate_suggestion(
                    category="performance",
                    priority="medium",
                    title=f"Magas effektív CPU használat ({cpu:.0f}%)",
                    description=f"A {node_name} node effektív CPU használata {cpu:.0f}% (steal: {cpu_steal:.0f}%). Ha tartósan magas, érdemes vizsgálni a CPU-igényes folyamatokat.",
                    current_value=f"eff={cpu:.0f}% steal={cpu_steal:.0f}%",
                    suggested_value="eff<60%",
                    rationale="A tartósan magas effektív CPU használat ronthatja az agent válaszidejét.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
        
        # ─── Disk suggestions ────────────────────────────────────────
        if mem:
            disk = mem.get("disk_usage_percent", 0)
            if disk > 90 and not _suggestion_exists("lemezterület"):
                s = await self.generate_suggestion(
                    category="storage",
                    priority="critical",
                    title=f"Kritikus lemezterület ({disk:.0f}%)",
                    description=f"A {node_name} node lemezterülete {disk:.0f}% használt. Ha elfogy a hely, a node leállhat.",
                    current_value=f"{disk:.0f}%",
                    suggested_value="<80%",
                    rationale="A lemezterület hiánya megakadályozza a naplózást, az adatbázis működést és a fájlműveleteket.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
            elif disk > 80 and not _suggestion_exists("lemezterület"):
                s = await self.generate_suggestion(
                    category="storage",
                    priority="medium",
                    title=f"Magas lemezterület használat ({disk:.0f}%)",
                    description=f"A {node_name} node lemezterülete {disk:.0f}% használt. Érdemes tisztítani a régi fájlokat.",
                    current_value=f"{disk:.0f}%",
                    suggested_value="<70%",
                    rationale="A közelgő lemezterület hiány megakadályozhatja a normál működést.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
        
        # ─── Mesh connectivity suggestions ──────────────────────────
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            if peers == 0 and not _suggestion_exists("peer csatlakozás"):
                s = await self.generate_suggestion(
                    category="network",
                    priority="critical",
                    title="Nincs peer csatlakozva — izolált node",
                    description=f"A {node_name} node nem csatlakozott egyetlen peer-hez sem. A mesh kommunikáció megszakadhat.",
                    current_value="0 peer",
                    suggested_value=f"≥{self._get_min_target_peers()} peer",
                    rationale="Izolált node nem tud delegálni, üzeneteket küldeni vagy fogadni. A hálózati konfiguráció ellenőrzése szükséges.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
            elif peers < self._get_min_target_peers() and not _suggestion_exists("peer csatlakozás"):
                s = await self.generate_suggestion(
                    category="network",
                    priority="medium",
                    title=f"Csak {peers} peer csatlakozva — alacsony mesh reziliencia",
                    description=f"A {node_name} node csak {peers} peer-hez csatlakozik. Ha az a peer leáll, a node izolálódik.",
                    current_value=f"{peers} peer",
                    suggested_value=f"≥{self._get_min_target_peers()} peer",
                    rationale=f"A mesh reziliencia növelése érdekében legalább {self._get_min_target_peers()} peer ajánlott.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
            
            # Transport suggestions
            transports = health.get("transports", {})
            if isinstance(transports, dict):
                unavailable = [name for name, info in transports.items() 
                               if isinstance(info, dict) and not info.get("available", True)]
                if unavailable and not _suggestion_exists("transport"):
                    s = await self.generate_suggestion(
                        category="network",
                        priority="high",
                        title=f"Transport nem elérhető: {', '.join(unavailable)}",
                        description=f"A {node_name} node-on a következő transportok nem elérhetők: {', '.join(unavailable)}. Ez korlátozza a mesh kommunikációt.",
                        current_value=f"Elérhetetlen: {', '.join(unavailable)}",
                        suggested_value="Minden transport elérhető",
                        rationale="A nem elérhető transportok miatt a node csak korlátozottan tud kommunikálni. Hálózati beállítások ellenőrzése javasolt.",
                        affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                    new_suggestions.append(s)
            
            # Connection count
            connections = mem.get("connections", 0) if mem else 0
            if connections > 100 and not _suggestion_exists("kapcsolatszám"):
                s = await self.generate_suggestion(
                    category="network",
                    priority="medium",
                    title=f"Nagy kapcsolatszám ({connections})",
                    description=f"A {node_name} node {connections} aktív kapcsolattal rendelkezik. Ez kapcsolatszivárgásra utalhat.",
                    current_value=f"{connections} kapcsolat",
                    suggested_value="<50 kapcsolat",
                    rationale="A felesleges kapcsolatok erőforrásokat fogyasztanak és kapcsolatszivárgásra utalnak.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
        
        # ─── Performance suggestions ────────────────────────────────
        perf = report.performance
        if perf:
            queue_size = perf.get("message_queue_size", 0)
            if queue_size > 50 and not _suggestion_exists("üzenetsor"):
                s = await self.generate_suggestion(
                    category="performance",
                    priority="high",
                    title=f"Nagy üzenetsor ({queue_size} üzenet)",
                    description=f"A {node_name} node üzenetsora {queue_size} üzenetet tartalmaz. Ez feldolgozási késleltetést jelent.",
                    current_value=f"{queue_size} üzenet",
                    suggested_value="<10 üzenet",
                    rationale="A nagy üzenetsor késleltetést okoz a mesh kommunikációban. A feldolgozás gyorsítása vagy a terhelés csökkentése javasolt.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
        
        # ─── Error suggestions ──────────────────────────────────────
        errs = report.error_patterns
        if errs:
            total = errs.get("total_errors", 0)
            if total > 10 and not _suggestion_exists("hibaszám"):
                # Find most common error
                error_counts = errs.get("error_counts", {})
                top_error = max(error_counts.items(), key=lambda x: x[1]) if error_counts else ("ismeretlen", total)
                s = await self.generate_suggestion(
                    category="stability",
                    priority="high" if total > 50 else "medium",
                    title=f"Magas hibaszám ({total} hiba)",
                    description=f"A {node_name} node {total} hibát észlelt. A leggyakoribb hiba: '{top_error[0]}' ({top_error[1]} előfordulás).",
                    current_value=f"{total} hiba",
                    suggested_value="0 hiba",
                    rationale=f"A magas hibaszám instabilitást jelez. A leggyakoribb hiba ('{top_error[0]}') root cause vizsgálata javasolt.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
        
        # ─── Delegation suggestions ─────────────────────────────────
        if health:
            failed = health.get("delegations_failed", 0)
            if failed > 3 and not _suggestion_exists("delegáció"):
                s = await self.generate_suggestion(
                    category="delegation",
                    priority="medium",
                    title=f"Sikertelen delegációk ({failed})",
                    description=f"A {node_name} node {failed} sikertelen delegációt észlelt. A cél agentek LLM elérhetősége vagy képességei ellenőrizendők.",
                    current_value=f"{failed} sikertelen",
                    suggested_value="0 sikertelen",
                    rationale="A sikertelen delegációk rontják a mesh együttműködési képességét.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)
        
        # ─── Development suggestions (actionable improvement proposals) ───
        # Analyze error patterns for development opportunities
        errs = report.error_patterns
        if errs:
            error_counts = errs.get("error_counts", {})
            # Common recurring errors → development suggestions
            for err_type, count in error_counts.items():
                if count >= 5:
                    # Map common error patterns to dev suggestions
                    dev_suggestion = self._map_error_to_dev_suggestion(node_name, err_type, count)
                    if dev_suggestion and not _suggestion_exists(dev_suggestion["title_substring"]):
                        s = await self.generate_suggestion(**dev_suggestion)
                        new_suggestions.append(s,
                    node_name_override=node_name,
                )

        # Version mismatch across nodes → development suggestion
        if health:
            peers = health.get("peers", [])
            if isinstance(peers, list) and len(peers) > 0:
                versions = set()
                for p in peers:
                    v = p.get("version", "?")
                    if v and v != "?":
                        versions.add(v)
                own_ver = getattr(self.node, '_resolved_version', None) or 'unknown'
                if own_ver and own_ver != 'unknown':
                    versions.add(own_ver)
                if len(versions) > 1 and not _suggestion_exists("verzió"):
                    s = await self.generate_suggestion(
                        category="development",
                        priority="medium",
                        title=f"Verzióeltérés a mesh-ben ({', '.join(sorted(versions))})",
                        description=f"A {node_name} node és a peer-ek között verzióeltérés van: {', '.join(sorted(versions))}. Ez kompatibilitási problémákat okozhat.",
                        current_value=", ".join(sorted(versions)),
                        suggested_value="Egyetlen verzió",
                        rationale="A verzióeltérés miatt delegációk, üzenetek és funkciók nem kompatibilisek lehetnek. Minden node frissítése ajánlott.",
                        affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                    new_suggestions.append(s)

        # OOM risk → development suggestion for restart resilience
        if mem:
            rss = mem.get("process_rss_mb", 0)
            if rss > 300 and not _suggestion_exists("OOM védelem"):
                s = await self.generate_suggestion(
                    category="development",
                    priority="medium",
                    title=f"OOM védelem javítása — {node_name} RSS: {rss:.0f}MB",
                    description=f"A {node_name} agent folyamata {rss:.0f}MB memóriát használ. A Restart=always beállítás véd, de a root cause (memóriaszivárgás) vizsgálata javasolt.",
                    current_value=f"{rss:.0f}MB RSS",
                    suggested_value="<200MB RSS",
                    rationale="A memóriaszivárgás idővel OOM kill-hez vezet. Restart=always biztosítja az újraindítást, de a szivárgás forrását is meg kell találni.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)

        # ─── Proactive development suggestions (mesh optimization) ─────
        if health:
            # Peer connection quality
            peers_data = health.get("peers", [])
            if isinstance(peers_data, list):
                offline_peers = [p for p in peers_data if not p.get("p2p_available", True)]
                if offline_peers and not _suggestion_exists("peer elérhetőség"):
                    peer_names = ", ".join(p.get("name", "?") for p in offline_peers)
                    s = await self.generate_suggestion(
                        category="development",
                        priority="medium",
                        title=f"Peer elérhetőség javítása — {peer_names}",
                        description=f"A {node_name} node {len(offline_peers)} peer nem elérhető: {peer_names}. A P2P kapcsolat stabilitásának javítása, reconnection logika finomhangolása javasolt.",
                        current_value=f"{len(offline_peers)}/{len(peers_data)} peer offline",
                        suggested_value="0 offline peer",
                        rationale="A nem elérhető peer-ek csökkentik a mesh rugalmasságát. A reconnection backoff és heartbeat timeout optimalizálása javasolt.",
                        affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                    new_suggestions.append(s)

            # CPU load optimization
            cpu_load = health.get("cpu_percent", 0)
            if cpu_load > 70 and not _suggestion_exists("CPU terhelés"):
                s = await self.generate_suggestion(
                    category="development",
                    priority="high" if cpu_load > 90 else "medium",
                    title=f"Magas CPU terhelés — {node_name}: {cpu_load:.0f}%",
                    description=f"A {node_name} node CPU terhelése {cpu_load:.0f}%. A diagnosztikai ciklusok és polling optimalizálása javasolt.",
                    current_value=f"{cpu_load:.0f}% CPU",
                    suggested_value="<50% CPU",
                    rationale="A magas CPU terhelés lassítja a mesh kommunikációt és delegációkat. A felesleges polling ciklusok csökkentése, async optimalizálás javasolt.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)

            # Dashboard external access
            http = health.get("transports", {}).get("http", True)
            if not http and not _suggestion_exists("Dashboard"):
                s = await self.generate_suggestion(
                    category="development",
                    priority="low",
                    title=f"Dashboard külső hozzáférés — {node_name}",
                    description=f"A {node_name} node HTTP transzport nem elérhető külsőleg. A host binding 0.0.0.0-ra módosítása javasolt a távoli eléréshez.",
                    current_value="127.0.0.1 (csak localhost)",
                    suggested_value="0.0.0.0 (minden interfész)",
                    rationale="A dashboard csak localhost-on elérhető. A 0.0.0.0 binding engedélyezi a hálózati monitorozást és adminisztrációt.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)

            # Delegation throughput optimization
            delegations_completed = health.get("delegations_completed", 0)
            delegations_failed = health.get("delegations_failed", 0)
            total_delegations = delegations_completed + delegations_failed
            if total_delegations > 5 and delegations_failed / total_delegations > 0.2 and not _suggestion_exists("delegáció sikeresség"):
                fail_rate = delegations_failed / total_delegations * 100
                s = await self.generate_suggestion(
                    category="development",
                    priority="medium",
                    title=f"Delegáció sikeresség javítása — {fail_rate:.0f}% hiba",
                    description=f"A {node_name} node delegációinak {fail_rate:.0f}%-a sikertelen ({delegations_failed}/{total_delegations}). A timeout értékek és retry logika finomhangolása javasolt.",
                    current_value=f"{fail_rate:.0f}% sikertelen",
                    suggested_value="<5% sikertelen",
                    rationale="A magas delegációs hibaarány csökkenti a mesh együttműködési hatékonyságát. A timeout növelése és az exponential backoff javasolt.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)

            # Uptime stability — frequent restarts
            uptime = health.get("uptime_seconds", 0)
            if 0 < uptime < 600 and not _suggestion_exists("restart stabilitás"):
                mins = uptime / 60
                s = await self.generate_suggestion(
                    category="development",
                    priority="high",
                    title=f"Gyakori restart — {node_name} uptime: {mins:.0f} perc",
                    description=f"A {node_name} node csak {mins:.0f} perce fut. Ez gyakori restart-ra utal, amit OOM kill, nem kezelt exception vagy auto-updater okozhat.",
                    current_value=f"{mins:.0f} perc uptime",
                    suggested_value=">24 óra uptime",
                    rationale="A gyakori restartok szolgáltatáskimaradást és adatvesztést okozhatnak. A root cause (OOM, crash, update rollback) azonosítása és javítása javasolt.",
                    affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                new_suggestions.append(s)

            # Message throughput
            msgs_sent = health.get("messages_sent", 0)
            msgs_received = health.get("messages_received", 0)
            if msgs_sent > 0 and msgs_received > 0:
                ratio = msgs_sent / msgs_received if msgs_received > 0 else 0
                if ratio > 3 and not _suggestion_exists("üzenet arány"):
                    s = await self.generate_suggestion(
                        category="development",
                        priority="low",
                        title=f"Üzenet arány egyensúly — {node_name} küld/fogad: {ratio:.1f}x",
                        description=f"A {node_name} node {ratio:.1f}x több üzenetet küld mint fogad ({msgs_sent} küldött, {msgs_received} fogadott). Ez aszimmetrikus kommunikációt jelez.",
                        current_value=f"Küldés/fogadás: {ratio:.1f}x",
                        suggested_value="Küldés/fogadás: ~1.0x",
                        rationale="Az aszimmetrikus üzenetarány jelzi, hogy a node többet kommunikál, mint amennyit feldolgoz. A delegációk és üzenetek optimalizálása javasolt.",
                        affected_nodes=[node_name],
                    node_name_override=node_name,
                )
                    new_suggestions.append(s)

        if new_suggestions:
            log.info(f"💡 Generated {len(new_suggestions)} auto-suggestions from report {report.report_id}")
            # Auto-delegate high/critical suggestions to the developer (nova)
            await self._auto_delegate_suggestions(new_suggestions)
        
        return new_suggestions

    def _map_error_to_dev_suggestion(self, node_name: str, err_type: str, count: int) -> Optional[Dict]:
        """Map recurring error patterns to development suggestions."""
        err_lower = err_type.lower() if isinstance(err_type, str) else ""

        # Common error patterns → dev suggestions
        if "time" in err_lower and "not defined" in err_lower:
            return dict(
                category="development",
                priority="high",
                title=f"Bug: import hiányzik — {err_type[:40]}",
                description=f"A {node_name} node {count} alkalommal észlelte a '{err_type[:60]}' hibát. Ez valószínűleg hiányzó import (pl. 'import time') miatt van.",
                current_value=f"{count} hiba",
                suggested_value="0 hiba (import javítása)",
                rationale="A hiányzó import futásidőű hibát okoz, ami megakadályozza a funkció működését. Gyors javítás: import hozzáadása.",
                affected_nodes=[node_name],
            )
        if "timeout" in err_lower or "timed out" in err_lower:
            return dict(
                category="development",
                priority="medium",
                title=f"Timeout probléma — {err_type[:40]}",
                description=f"A {node_name} node {count} alkalommal észlelte a '{err_type[:60]}' timeout hibát. A timeout értékek növelése vagy a hálózati stabilitás javítása szükséges.",
                current_value=f"{count} timeout",
                suggested_value="0 timeout",
                rationale="A gyakori timeoutok instabil hálózatot vagy túl alacsony timeout értékeket jeleznek. A retry logika és timeout értékek finomhangolása javasolt.",
                affected_nodes=[node_name],
            )
        if "connection" in err_lower or "connect" in err_lower:
            return dict(
                category="development",
                priority="medium",
                title=f"Kapcsolódási hiba — {err_type[:40]}",
                description=f"A {node_name} node {count} alkalommal észlelt kapcsolódási hibát: '{err_type[:60]}'. A reconnection logika és a connection pooling javítása javasolt.",
                current_value=f"{count} connection error",
                suggested_value="Robusztus reconnection",
                rationale="A gyakori kapcsolódási hibák rontják a mesh stabilitását. Exponenciális backoff és connection pooling bevezetése javasolt.",
                affected_nodes=[node_name],
            )
        if "none" in err_lower and ("subscript" in err_lower or "attribute" in err_lower):
            return dict(
                category="development",
                priority="high",
                title=f"NoneType hiba — {err_type[:40]}",
                description=f"A {node_name} node {count} alkalommal észlelte: '{err_type[:60]}'. Ez nem kezelt None értéket jelez, ami None-safe kódolást igényel.",
                current_value=f"{count} NoneType error",
                suggested_value="0 hiba (None-check hozzáadása)",
                rationale="A NoneType hibák nem kezelt edge case-eket jeleznek. None-safe kódolás (pl. 'x or default' minták) javasolt.",
                affected_nodes=[node_name],
            )

        # Generic recurring error → development suggestion
        if count >= 10:
            return dict(
                category="development",
                priority="medium",
                title=f"Ismétlődő hiba vizsgálata — {err_type[:40]}",
                description=f"A {node_name} node {count} alkalommal észlelte: '{err_type[:60]}'. A root cause vizsgálata és javítása javasolt.",
                current_value=f"{count} előfordulás",
                suggested_value="0 előfordulás",
                rationale=f"A {count} alkalommal ismétlődő hiba root cause vizsgálatot igényel. A hibaüzenet alapján a forráskód megfelelő javítása javasolt.",
                affected_nodes=[node_name],
            )
        return None

    async def _auto_delegate_suggestions(self, suggestions: List[ConfigSuggestion]):
        """Auto-delegate high/critical development suggestions as tasks to nova (developer)."""
        if not hasattr(self.node, 'delegation') or not self.node.delegation:
            return
        for s in suggestions:
            if s.category == "development" and s.priority in ("high", "critical"):
                try:
                    task_title = f"[DEV] {s.title}"
                    task_desc = f"**Fejlesztési javaslat ({s.priority} prioritás)**\n\n{s.description}\n\n**Jelenlegi érték:** {s.current_value}\n**Célérték:** {s.suggested_value}\n**Indoklás:** {s.rationale}\n\n**Érintett node:** {', '.join(s.affected_nodes)}\n**Javaslat ID:** {s.suggestion_id}"
                    await self.node.delegation.delegate_task(
                        to_agent="any",
                        subject=task_title,
                        description=task_desc,
                        task_type="code",
                        priority=7 if s.priority == "critical" else 5,
                        available=True,
                        eligible_agents=["morzsa", "runa"],
                    )
                    log.info(f"📋 Auto-delegated development suggestion: {s.title}")
                except Exception as e:
                    log.warning(f"Failed to auto-delegate suggestion {s.suggestion_id}: {e}")
    
    def _assess_severity(self, report: DiagnosticReport) -> str:
        """Assess overall severity of the report."""
        mem = report.memory_stats
        if mem:
            rss = mem.get("process_rss_mb", 0)
            sys_mem = mem.get("system_memory_percent", 0)
            if rss > 1000 or sys_mem > 95:
                return "critical"
            if rss > 500 or sys_mem > 85:
                return "warning"
        
        # Isolated node (0 peers) = warning
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            transports = health.get("transports", {})
            all_down = (isinstance(transports, dict) and 
                       all(not info.get("available", True) for info in transports.values() 
                           if isinstance(info, dict)) and transports)
            if peers == 0 and all_down:
                return "critical"  # Node is completely isolated
            if peers == 0:
                return "warning"  # No peers but some transports available
        
        errs = report.error_patterns
        if errs and errs.get("total_errors", 0) > 20:
            return "warning"
        
        return "info"
    
    def _store_report(self, report: DiagnosticReport):
        """Store report in memory, capped at max_reports_stored."""
        self._reports.append(report)
        if len(self._reports) > self.config.max_reports_stored:
            self._reports = self._reports[-self.config.max_reports_stored:]
    
    async def _broadcast_report(self, report: DiagnosticReport):
        """Broadcast diagnostic report through the mesh."""
        try:
            payload = {
                "type": "diagnostic_report",
                "source": self.node.config.node_name,
                "data": report.to_dict(),
            }
            await self.node.broadcast(
                msg_type="diagnostic_report",
                payload=payload,
            )
            # Also publish to PG diagnostic_channel for cross-node delivery
            if self.node._pg_pool and self.node._pg_pool.is_connected():
                try:
                    await self.node._pg_pool.execute(
                        "SELECT pg_notify($1, $2)",
                        "diagnostic_channel",
                        json.dumps(payload)
                    )
                    log.debug(f"📊 Diagnostic report PG NOTIFY sent to diagnostic_channel")
                except Exception as e:
                    log.warning(f"Failed to PG NOTIFY diagnostic report: {e}")
            log.info(f"📊 Diagnostic report broadcasted: {report.report_id}")
        except Exception as e:
            log.error(f"Failed to broadcast diagnostic report: {e}")
    
    async def _broadcast_suggestion(self, suggestion: ConfigSuggestion):
        """Broadcast config suggestion through the mesh."""
        try:
            payload = {
                "type": "config_suggestion",
                "source": self.node.config.node_name,
                "data": suggestion.to_dict(),
            }
            await self.node.broadcast(
                msg_type="config_suggestion",
                payload=payload,
            )
            # Also publish to PG diagnostic_channel for cross-node delivery
            if self.node._pg_pool and self.node._pg_pool.is_connected():
                try:
                    await self.node._pg_pool.execute(
                        "SELECT pg_notify($1, $2)",
                        "diagnostic_channel",
                        json.dumps(payload)
                    )
                    log.debug(f"💡 Config suggestion PG NOTIFY sent to diagnostic_channel")
                except Exception as e:
                    log.warning(f"Failed to PG NOTIFY config suggestion: {e}")
            log.info(f"💡 Config suggestion broadcasted: {suggestion.title}")
        except Exception as e:
            log.error(f"Failed to broadcast config suggestion: {e}")
    
    async def handle_diagnostic_message(self, message: dict):
        """Handle incoming diagnostic message from the mesh."""
        msg_type = message.get("type", "")
        source = message.get("source", "unknown")
        data = message.get("data", {})
        
        if msg_type == "diagnostic_report":
            report = DiagnosticReport.from_dict(data)
            # Deduplicate by report_id — same report may arrive via P2P and PG NOTIFY
            if any(r.report_id == report.report_id for r in self._reports):
                log.debug(f"📊 Duplicate diagnostic report from {source}: {report.report_id} — skipping")
                return
            self._store_report(report)
            log.info(f"📊 Received diagnostic report from {source}: {report.report_id}")
            # NOTE: Do NOT auto-generate suggestions from received reports.
            # Each node generates suggestions only from its OWN local report
            # (in _periodic_report_loop), then broadcasts them to peers.
            # This prevents 3x triplication (each of 3 nodes generating
            # duplicate suggestions from the same received report).
        
        elif msg_type == "config_suggestion":
            suggestion = ConfigSuggestion.from_dict(data)
            # Deduplicate by suggestion_id
            if any(s.suggestion_id == suggestion.suggestion_id for s in self._suggestions):
                log.debug(f"💡 Duplicate config suggestion from {source}: {suggestion.title} — skipping")
                return
            self._suggestions.append(suggestion)
            if len(self._suggestions) > self.config.max_reports_stored:
                self._suggestions = self._suggestions[-self.config.max_reports_stored:]
            log.info(f"💡 Received config suggestion from {source}: {suggestion.title}")
    
    def record_error(self, error_type: str):
        """Record an error occurrence for pattern analysis."""
        self._error_counts[error_type] = self._error_counts.get(error_type, 0) + 1
    
    def get_reports(self, limit: int = 20, severity: Optional[str] = None) -> List[DiagnosticReport]:
        """Get stored diagnostic reports, optionally filtered by severity."""
        reports = self._reports
        if severity:
            reports = [r for r in reports if r.severity == severity]
        return reports[-limit:]
    
    def get_suggestions(self, limit: int = 20, category: Optional[str] = None) -> List[ConfigSuggestion]:
        """Get stored config suggestions, optionally filtered by category."""
        suggestions = self._suggestions
        if category:
            suggestions = [s for s in suggestions if s.category == category]
        return suggestions[-limit:]
    
    def update_suggestion_status(self, suggestion_id: str, new_status: str) -> Optional[ConfigSuggestion]:
        """Update the status of a suggestion (pending/accepted/rejected/implemented).
        Also persists the status change to PG."""
        valid = {"pending", "accepted", "rejected", "implemented"}
        if new_status not in valid:
            return None
        for s in self._suggestions:
            if s.suggestion_id == suggestion_id:
                old_status = s.status
                s.status = new_status
                log.info(f"📋 Suggestion {suggestion_id}: {old_status} → {new_status}")
                # Persist status change to PG (fire and forget)
                asyncio.ensure_future(self._update_suggestion_status_pg(suggestion_id, new_status))
                return s
        return None
    
    def get_status(self) -> Dict[str, Any]:
        """Get current diagnostic engine status."""
        return {
            "enabled": self.config.enabled,
            "report_interval": self.config.report_interval,
            "developer_nodes": self.config.developer_nodes,
            "reports_stored": len(self._reports),
            "suggestions_stored": len(self._suggestions),
            "last_report_time": self._last_report_time,
            "error_types_tracked": len(self._error_counts),
            "performance_samples": len(self._performance_samples),
            "pg_loaded": self._pg_loaded,
        }

    # ── PG Persistence ──

    async def _load_suggestions_from_pg(self):
        """Load suggestions from PG on startup."""
        try:
            pg_pool = getattr(self.node, '_pg_pool', None)
            if not pg_pool:
                log.debug("No PG pool available for loading suggestions")
                return
            rows = await pg_pool.fetch(
                """SELECT * FROM mesh_suggestions 
                   ORDER BY created_at DESC LIMIT 100"""
            )
            for row in rows:
                d = dict(row)
                suggestion = ConfigSuggestion(
                    suggestion_id=d.get("suggestion_id", ""),
                    node=d.get("node", ""),
                    timestamp=d.get("created_at", datetime.now(timezone.utc)).isoformat() if d.get("created_at") else "",
                    category=d.get("category", "general"),
                    priority=d.get("priority", "low"),
                    title=d.get("title", ""),
                    description=d.get("description", ""),
                    current_value=d.get("current_value", ""),
                    suggested_value=d.get("suggested_value", ""),
                    rationale=d.get("rationale", ""),
                    affected_nodes=d.get("affected_nodes", []),
                    status=d.get("status", "pending"),
                )
                self._suggestions.append(suggestion)
            self._pg_loaded = True
            log.info(f"📋 Loaded {len(rows)} persisted suggestions from PG")
        except Exception as e:
            log.warning(f"Failed to load suggestions from PG: {e}")
            self._pg_loaded = False

    async def _persist_suggestion_to_pg(self, suggestion: ConfigSuggestion):
        """Persist a suggestion to the mesh_suggestions PG table."""
        try:
            pg_pool = getattr(self.node, '_pg_pool', None)
            if not pg_pool:
                return
            affected_nodes = suggestion.affected_nodes or []
            await pg_pool.execute(
                """INSERT INTO mesh_suggestions 
                   (suggestion_id, node, category, priority, title, description,
                    current_value, suggested_value, rationale, affected_nodes, status, source)
                   VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
                   ON CONFLICT (suggestion_id) DO UPDATE SET
                   status = EXCLUDED.status, updated_at = NOW()""",
                suggestion.suggestion_id, suggestion.node, suggestion.category,
                suggestion.priority, _safe_ascii(suggestion.title),
                _safe_ascii(suggestion.description),
                _safe_ascii(suggestion.current_value),
                _safe_ascii(suggestion.suggested_value),
                _safe_ascii(suggestion.rationale),
                affected_nodes, suggestion.status, "auto",
            )
            log.debug(f"📋 Persisted suggestion {suggestion.suggestion_id} to PG")
        except Exception as e:
            log.warning(f"Failed to persist suggestion to PG: {e}")

    async def _update_suggestion_status_pg(self, suggestion_id: str, new_status: str):
        """Update suggestion status in PG."""
        try:
            pg_pool = getattr(self.node, '_pg_pool', None)
            if not pg_pool:
                return
            implemented_at = "NOW()" if new_status == "implemented" else None
            if new_status == "implemented":
                await pg_pool.execute(
                    """UPDATE mesh_suggestions 
                       SET status = $1, implemented_at = NOW(), updated_at = NOW()
                       WHERE suggestion_id = $2""",
                    new_status, suggestion_id,
                )
            else:
                await pg_pool.execute(
                    """UPDATE mesh_suggestions 
                       SET status = $1, updated_at = NOW()
                       WHERE suggestion_id = $2""",
                    new_status, suggestion_id,
                )
            log.info(f"📋 Updated suggestion {suggestion_id} → {new_status} in PG")
        except Exception as e:
            log.warning(f"Failed to update suggestion status in PG: {e}")

    # ── Auto-Implement & Dedup ──

    async def auto_implement_suggestions(self) -> List[str]:
        """Auto-implement pending suggestions that have safe, known fixes.
        
        1. Deduplicates: marks duplicate pending suggestions as 'superseded'
        2. Auto-accepts unique suggestions matching known patterns
        3. Returns list of implemented suggestion IDs.
        """
        implemented_ids: List[str] = []
        
        # Step 1: Deduplicate pending suggestions in PG
        await self._dedup_pending_suggestions_pg()
        
        # Step 2: Reload suggestions from PG (post-dedup)
        self._suggestions = []
        await self._load_suggestions_from_pg()
        
        # Step 3: Auto-implement known-safe patterns
        safe_patterns = {
            "Verzioelteres": "accepted",       # Version drift → accept (needs manual deploy)
            "Csak 1 peer": "accepted",         # Low resilience → accept
            "Nincs peer": "accepted",           # Isolated node → accept
            "Gyakori restart": "accepted",      # Frequent restart → accept
            "Magas CPU": "accepted",            # High CPU → accept
            "Magas memoriahasznalat": "accepted", # High memory → accept + action
            "Kritikus effektiv CPU": "accepted", # Critical CPU → accept
        }

        # Step 4: Auto-actions for specific patterns
        for s in self._suggestions:
            if s.status != "pending":
                continue
            for pattern, target_status in safe_patterns.items():
                if pattern.lower() in s.title.lower():
                    self.update_suggestion_status(s.suggestion_id, target_status)
                    implemented_ids.append(s.suggestion_id)

                    # Auto-action: high memory → trigger GC + cache cleanup
                    if "memoriahasznalat" in pattern.lower():
                        try:
                            import gc
                            collected = gc.collect()
                            log.info(f"📋 Auto-action: GC collected {collected} objects for {s.suggestion_id}")
                        except Exception:
                            pass

                    # Auto-action: high dedup cache → flush old entries
                    if "dedup" in s.title.lower():
                        try:
                            dedup = getattr(self.node, 'dedup', None)
                            if dedup and hasattr(dedup, 'cache'):
                                old_size = len(dedup.cache)
                                dedup.cache.clear()
                                log.info(f"📋 Auto-action: dedup cache cleared ({old_size} entries) for {s.suggestion_id}")
                        except Exception:
                            pass

                    break
        
        log.info(f"📋 auto_implement: {len(implemented_ids)} suggestions processed, "
                  f"{len([s for s in self._suggestions if s.status == 'superseded'])} superseded")
        return implemented_ids

    async def _dedup_pending_suggestions_pg(self):
        """Mark duplicate pending suggestions as 'superseded' in PG.
        
        Groups by (title, category) and keeps only the most recent one as 'pending'.
        """
        try:
            pg_pool = getattr(self.node, '_pg_pool', None)
            if not pg_pool:
                return
            
            # Mark duplicates as superseded — keep only the latest per (title, category)
            result = await pg_pool.execute(
                """UPDATE mesh_suggestions s1
                   SET status = 'superseded', updated_at = NOW()
                   WHERE s1.status = 'pending'
                   AND s1.created_at < (
                       SELECT MAX(s2.created_at)
                       FROM mesh_suggestions s2
                       WHERE s2.title = s1.title
                       AND s2.category = s1.category
                       AND s2.status = 'pending'
                   )""",
            )
            # pg_pool.execute returns 'UPDATE N' string
            if hasattr(result, 'split'):
                count = result.split()[-1] if ' ' in str(result) else str(result)
                log.info(f"📋 Dedup: {count} duplicate suggestions marked as superseded")
            else:
                log.info(f"📋 Dedup: duplicate suggestions processed")
                
        except Exception as e:
            log.warning(f"Failed to dedup suggestions in PG: {e}")