"""A2A Mesh Diagnostics — self-analysis, config suggestions, and diagnostic channel.

Diagnostic messages flow through the PG `diagnostic_channel` NOTIFY/LISTEN channel.
Any node can generate diagnostic_report and config_suggestion messages.
These are stored locally and optionally forwarded to developer nodes for analysis.

Message types:
- diagnostic_report: Periodic self-analysis (memory, errors, mesh health, performance)
- config_suggestion: Actionable suggestions for improving the mesh

The diagnostic channel is separate from mesh_channel and delegation_channel
to keep diagnostic traffic isolated and allow fine-grained filtering.
"""

import asyncio
import json
import os
import platform
import time
import traceback
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import logging

log = logging.getLogger("a2a_mesh.diagnostics")


@dataclass
class DiagnosticReport:
    """A diagnostic report generated by a node."""
    report_id: str = ""
    node: str = ""
    timestamp: str = ""
    report_type: str = "periodic"  # periodic, on_demand, incident
    severity: str = "info"  # info, warning, critical
    
    # Sections
    memory_stats: Dict[str, Any] = field(default_factory=dict)
    error_patterns: Dict[str, Any] = field(default_factory=dict)
    mesh_health: Dict[str, Any] = field(default_factory=dict)
    performance: Dict[str, Any] = field(default_factory=dict)
    
    # Summary
    summary: str = ""
    recommendations: List[str] = field(default_factory=list)
    
    def to_dict(self) -> dict:
        d = asdict(self)
        # Replace Infinity/NaN values (invalid in JSON)
        def _sanitize(obj):
            if isinstance(obj, dict):
                return {k: _sanitize(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [_sanitize(v) for v in obj]
            if isinstance(obj, float):
                if obj != obj:  # NaN
                    return 0
                if obj == float('inf'):
                    return 1e18
                if obj == float('-inf'):
                    return -1e18
            return obj
        return _sanitize(d)
    
    @classmethod
    def from_dict(cls, d: dict) -> "DiagnosticReport":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


@dataclass
class ConfigSuggestion:
    """A config suggestion for improving the mesh."""
    suggestion_id: str = ""
    node: str = ""
    timestamp: str = ""
    category: str = "general"  # performance, reliability, security, feature
    priority: str = "low"  # low, medium, high, critical
    title: str = ""
    description: str = ""
    current_value: str = ""
    suggested_value: str = ""
    rationale: str = ""
    affected_nodes: List[str] = field(default_factory=list)
    status: str = "pending"  # pending, accepted, rejected, implemented
    
    def to_dict(self) -> dict:
        return asdict(self)
    
    @classmethod
    def from_dict(cls, d: dict) -> "ConfigSuggestion":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


class DiagnosticEngine:
    """Generates and manages diagnostic reports and config suggestions."""
    
    def __init__(self, node):
        """Initialize with reference to the mesh node."""
        self.node = node
        self.config = getattr(node.config, 'diagnostic', None)
        if self.config is None:
            from core.config import DiagnosticConfig
            self.config = DiagnosticConfig()
        
        self._reports: List[DiagnosticReport] = []
        self._suggestions: List[ConfigSuggestion] = []
        self._task: Optional[asyncio.Task] = None
        self._last_report_time: float = 0
        self._error_counts: Dict[str, int] = {}  # error_type -> count
        self._performance_samples: List[Dict] = []
        self._max_samples: int = 60  # Keep last 60 samples
    
    async def start(self):
        """Start the periodic diagnostic report generator."""
        if not self.config.enabled:
            log.info("Diagnostics disabled by config")
            return
        
        log.info(f"🔍 Diagnostics engine started (interval={self.config.report_interval}s)")
        self._task = asyncio.create_task(self._periodic_report_loop())
    
    async def stop(self):
        """Stop the diagnostic engine."""
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            log.info("🔍 Diagnostics engine stopped")
    
    async def _periodic_report_loop(self):
        """Periodically generate diagnostic reports and auto-suggestions."""
        while True:
            try:
                await asyncio.sleep(self.config.report_interval)
                report = await self.generate_report()
                if report:
                    self._store_report(report)
                    await self._broadcast_report(report)
                    # Auto-generate suggestions from report data
                    try:
                        await self._generate_suggestions_from_report(report)
                    except Exception as e:
                        log.warning(f"Failed to auto-generate suggestions: {e}")
                    # Auto-accept and implement suggestions
                    try:
                        implemented = await self.auto_implement_suggestions()
                        if implemented:
                            log.info(f"🔧 Auto-implemented {len(implemented)} suggestions")
                    except Exception as e:
                        log.warning(f"Failed to auto-implement suggestions: {e}")
            except asyncio.CancelledError:
                break
            except Exception as e:
                log.error(f"Error in diagnostic report loop: {e}")
                await asyncio.sleep(60)  # Back off on error
    
    async def generate_report(self, report_type: str = "periodic") -> Optional[DiagnosticReport]:
        """Generate a diagnostic report by analyzing the node's state."""
        now = datetime.now(timezone.utc)
        report = DiagnosticReport(
            report_id=f"diag-{self.node.config.node_name}-{int(now.timestamp())}",
            node=self.node.config.node_name,
            timestamp=now.isoformat(),
            report_type=report_type,
        )
        
        # Memory statistics
        if self.config.include_memory_stats:
            report.memory_stats = self._collect_memory_stats()
        
        # Error patterns
        if self.config.include_error_patterns:
            report.error_patterns = self._collect_error_patterns()
        
        # Mesh health
        if self.config.include_mesh_health:
            report.mesh_health = await self._collect_mesh_health()
        
        # Performance
        if self.config.include_performance:
            report.performance = self._collect_performance()
        
        # Generate summary and recommendations
        report.summary = self._generate_summary(report)
        report.recommendations = self._generate_recommendations(report)
        report.severity = self._assess_severity(report)
        
        return report
    
    async def generate_suggestion(self, category: str, title: str, description: str,
                                     current_value: str = "", suggested_value: str = "",
                                     rationale: str = "", priority: str = "medium",
                                     affected_nodes: Optional[List[str]] = None,
                                     source_node: str = None) -> ConfigSuggestion:
        """Generate a config suggestion."""
        now = datetime.now(timezone.utc)
        suggestion = ConfigSuggestion(
            suggestion_id=f"sugg-{source_node or self.node.config.node_name}-{int(now.timestamp())}",
            node=source_node or self.node.config.node_name,
            timestamp=now.isoformat(),
            category=category,
            priority=priority,
            title=title,
            description=description,
            current_value=current_value,
            suggested_value=suggested_value,
            rationale=rationale,
            affected_nodes=affected_nodes if affected_nodes is not None else [source_node or self.node.config.node_name],
        )
        self._suggestions.append(suggestion)
        # Keep only last N suggestions
        if len(self._suggestions) > self.config.max_reports_stored:
            self._suggestions = self._suggestions[-self.config.max_reports_stored:]
        
        await self._broadcast_suggestion(suggestion)
        return suggestion
    
    def _collect_memory_stats(self) -> Dict[str, Any]:
        """Collect memory and system statistics."""
        import psutil
        try:
            process = psutil.Process(os.getpid())
            mem_info = process.memory_info()
            return {
                "process_rss_mb": round(mem_info.rss / 1024 / 1024, 1),
                "process_vms_mb": round(mem_info.vms / 1024 / 1024, 1),
                "system_memory_percent": psutil.virtual_memory().percent,
                "system_cpu_percent": psutil.cpu_percent(interval=0.1),
                "disk_usage_percent": psutil.disk_usage('/').percent,
                "open_files": len(process.open_files()) if hasattr(process, 'open_files') else 0,
                "connections": len(process.connections()) if hasattr(process, 'connections') else 0,
                "threads": process.num_threads(),
            }
        except ImportError:
            # psutil not available, collect basic stats
            import resource
            return {
                "process_rss_mb": round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024, 1),
                "note": "psutil not available, limited stats",
            }
        except Exception as e:
            return {"error": str(e)}
    
    def _collect_error_patterns(self) -> Dict[str, Any]:
        """Analyze recent error patterns."""
        return {
            "error_counts": dict(self._error_counts),
            "total_errors": sum(self._error_counts.values()),
            "unique_error_types": len(self._error_counts),
        }
    
    async def _collect_mesh_health(self) -> Dict[str, Any]:
        """Collect mesh health information."""
        try:
            status = self.node.get_status()
            # Extract peer info from peer_discovery stats (get_status uses "peer_discovery" key)
            peer_disc = status.get("peer_discovery", {})
            connected_count = peer_disc.get("connected_peers", 0)
            peers_dict = peer_disc.get("peers", {})
            peer_list = [
                {"name": name, "status": "available" if p.get("p2p_available") else "unavailable", "version": p.get("version", "?")}
                for name, p in peers_dict.items()
            ] if isinstance(peers_dict, dict) else []
            
            # Also try P2P transport for live peer info
            p2p_info = status.get("p2p", {})
            if isinstance(p2p_info, dict) and "peers" in p2p_info:
                p2p_peers = p2p_info.get("peers", [])
                if isinstance(p2p_peers, list) and not peer_list:
                    peer_list = [{"name": name, "status": "connected", "version": "?"} for name in p2p_peers]
            
            # Uptime: prefer status value, fallback to _start_time calculation
            uptime_val = status.get("uptime", 0)
            if uptime_val == 0 and hasattr(self.node, '_start_time') and self.node._start_time:
                uptime_val = int(time.time() - self.node._start_time)
            
            # Version: prefer _resolved_version, fallback to config
            version_val = getattr(self.node, '_resolved_version', None)
            if not version_val or version_val == 'unknown':
                version_val = getattr(self.node.config, '_resolve_version', lambda: 'unknown')()
                if not version_val:
                    version_val = 'unknown'
            
            return {
                "node_name": self.node.config.node_name,
                "uptime_seconds": uptime_val,
                "version": version_val,
                "role": status.get("role", "unknown"),
                "peer_count": connected_count,
                "peers": peer_list,
                "transports": self._sanitize_transport_latencies(status.get("transports", {})),
                "delegations_active": status.get("delegations", {}).get("active", 0),
                "delegations_completed": status.get("delegations", {}).get("completed", 0),
                "delegations_failed": status.get("delegations", {}).get("failed", 0),
            }
        except Exception as e:
            return {"error": str(e)}
    

    @staticmethod
    def _sanitize_transport_latencies(transports: dict) -> dict:
        """Clamp negative latency values to 0 (clock skew protection).
        
        P2P ACK-based RTT measurement uses (local_time - remote_timestamp).
        If clocks are not NTP-synchronized, this can produce negative values.
        Clamp them to 0 to prevent nonsensical negative latency in reports.
        
        Also converts TransportStatus dataclass objects to dicts so they
        serialize properly in diagnostic reports.
        """
        sanitized = {}
        for name, info in transports.items():
            # Convert TransportStatus dataclass objects to dicts
            if hasattr(info, '__dataclass_fields__'):
                from dataclasses import asdict as _asdict
                info = _asdict(info)
            if isinstance(info, dict):
                info = dict(info)  # shallow copy
                lat = info.get("latency_ms")
                if isinstance(lat, (int, float)):
                    if lat == -1:
                        # -1 = available but isolated (no peers connected)
                        info["latency_ms"] = -1
                        info["isolated"] = True
                        info["note"] = "Transport available but no peers connected"
                    elif lat < 0:
                        log.warning(f"Transport {name} reported negative latency ({lat:.2f}ms) — "
                                    f"likely clock skew. Clamping to 0.")
                        info["latency_ms"] = 0.0
                    elif lat == float('inf'):
                        # Infinity is not valid JSON — replace with large but finite value
                        info["latency_ms"] = 1e6  # 1,000,000ms = 1000s = effectively "unavailable"
                # Also sanitize per-peer RTT if present
                peers = info.get("peers")
                if isinstance(peers, list):
                    info["peers"] = peers  # no modification needed for list of names
                elif isinstance(peers, dict):
                    for pname, pdata in peers.items():
                        if isinstance(pdata, dict):
                            rtt = pdata.get("rtt_ms")
                            if isinstance(rtt, (int, float)) and rtt < 0:
                                log.warning(f"Peer {pname} RTT negative ({rtt:.2f}ms) — clamping to 0")
                                pdata["rtt_ms"] = 0.0
            sanitized[name] = info
        return sanitized

    def _collect_performance(self) -> Dict[str, Any]:
        """Collect performance metrics."""
        sample = {
            "timestamp": time.time(),
            "uptime_seconds": time.time() - getattr(self.node, '_start_time', time.time()),
            "message_queue_size": 0,
            "offline_queue_size": 0,
        }
        
        # Collect queue sizes
        if hasattr(self.node, '_message_queue'):
            sample["message_queue_size"] = self.node._message_queue.qsize() if hasattr(self.node._message_queue, 'qsize') else 0
        if hasattr(self.node, 'offline_queue') and hasattr(self.node.offline_queue, 'pending_count'):
            sample["offline_queue_size"] = self.node.offline_queue.pending_count
        
        self._performance_samples.append(sample)
        if len(self._performance_samples) > self._max_samples:
            self._performance_samples = self._performance_samples[-self._max_samples:]
        
        return {
            "current": sample,
            "samples_collected": len(self._performance_samples),
        }
    
    def _generate_summary(self, report: DiagnosticReport) -> str:
        """Generate a human-readable summary of the diagnostic report."""
        parts = []
        parts.append(f"Node {report.node} diagnostic report ({report.report_type})")
        
        mem = report.memory_stats
        if mem:
            rss = mem.get("process_rss_mb", "?")
            sys_mem = mem.get("system_memory_percent", "?")
            parts.append(f"Memory: {rss}MB RSS, {sys_mem}% system")
        
        errs = report.error_patterns
        if errs:
            total = errs.get("total_errors", 0)
            unique = errs.get("unique_error_types", 0)
            parts.append(f"Errors: {total} total ({unique} unique types)")
        
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            parts.append(f"Mesh: {peers} peers connected")
            # Check for isolated transports
            transports = health.get("transports", {})
            if isinstance(transports, dict):
                isolated = [name for name, info in transports.items()
                            if isinstance(info, dict) and info.get("isolated", False)]
                if isolated:
                    parts.append(f"ISOLATED: {', '.join(isolated)} (available but no peers)")
        
        return " | ".join(parts)
    
    def _generate_recommendations(self, report: DiagnosticReport) -> List[str]:
        """Generate recommendations based on the report data."""
        recs = []
        
        # Memory recommendations
        mem = report.memory_stats
        if mem:
            rss = mem.get("process_rss_mb", 0)
            if rss > 500:
                recs.append(f"High memory usage ({rss}MB) — consider restarting or investigating memory leaks")
            sys_mem = mem.get("system_memory_percent", 0)
            if sys_mem > 85:
                if rss < 100 and sys_mem > 90:
                    # Node itself is lightweight — memory pressure is external
                    recs.append(f"System memory at {sys_mem}% (OOM risk) — node RSS only {rss}MB, external processes consuming memory. Investigate other services on the host.")
                else:
                    recs.append(f"System memory at {sys_mem}% — risk of OOM kill")
        
        # CPU recommendations
        if mem:
            cpu = mem.get("system_cpu_percent", 0)
            if cpu > 90:
                recs.append(f"Critical CPU usage ({cpu:.0f}%) — investigate high-load processes or scale resources")
            elif cpu > 75:
                recs.append(f"High CPU usage ({cpu:.0f}%) — monitor for sustained load")
        
        # Error recommendations
        errs = report.error_patterns
        if errs:
            for err_type, count in errs.get("error_counts", {}).items():
                if count > 10:
                    recs.append(f"Recurring error '{err_type}' occurred {count} times — investigate root cause")
        
        # Mesh recommendations
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            if peers == 0:
                recs.append("No peers connected — node is isolated, check P2P transport and network connectivity")
            elif peers < 2:
                recs.append(f"Only {peers} peer(s) connected — mesh resilience is low, check network connectivity")
            
            # Check transport availability
            transports = health.get("transports", {})
            if isinstance(transports, dict):
                unavailable = [name for name, info in transports.items() 
                               if isinstance(info, dict) and not info.get("available", True)]
                if len(unavailable) == len(transports) and transports:
                    recs.append(f"All transports unavailable ({', '.join(unavailable)}) — node cannot communicate")
                elif unavailable:
                    recs.append(f"Transport(s) unavailable: {', '.join(unavailable)} — check connectivity")
            
            failed = health.get("delegations_failed", 0)
            if failed > 5:
                recs.append(f"{failed} failed delegations — check agent capabilities and LLM availability")
        
        return recs
    
    async def _generate_suggestions_from_report(self, report: DiagnosticReport) -> List[ConfigSuggestion]:
        """Automatically generate config suggestions based on diagnostic report data.
        
        Each agent analyzes its own report and creates actionable suggestions
        that appear in the dashboard with status tracking (pending/accepted/rejected/implemented).
        """
        new_suggestions = []
        node_name = report.node
        
        # Helper: check if similar suggestion already exists to avoid duplicates
        # Checks both title substring AND affected node to prevent cross-node duplicates
        def _suggestion_exists(title_substring: str, node: str = None) -> bool:
            for s in self._suggestions:
                if title_substring.lower() in s.title.lower():
                    if node is None or node in getattr(s, 'affected_nodes', []) or node in str(getattr(s, 'description', '')):
                        return True
            return False
        
        # ─── Memory suggestions ────────────────────────────────────
        mem = report.memory_stats
        if mem:
            sys_mem = mem.get("system_memory_percent", 0)
            if sys_mem > 90 and not _suggestion_exists("memóriahasználat", node_name):
                # Distinguish: is the node itself consuming memory or external processes?
                rss_mb = mem.get("process_rss_mb", 0)
                if rss_mb < 100:
                    desc = f"A {node_name} node rendszer memóriahasználata {sys_mem:.0f}%, de az agent maga csak {rss_mb:.0f}MB-t használ. Külső folyamatok fogyasztják a memóriát — vizsgáld a gazdagépen futó más szolgáltatásokat (pl. docker, adatbázis, más agentek)."
                else:
                    desc = f"A {node_name} node rendszer memóriahasználata {sys_mem:.0f}%, ami OOM kill kockázatot jelent. Az agent processzek memóriafogyasztásának csökkentése vagy a rendszer memóriabővítése javasolt."
                s = await self.generate_suggestion(
                    category="memory",
                    priority="critical",
                    title=f"Kritikus memóriahasználat ({sys_mem:.0f}%) — OOM kockázat",
                    description=desc,
                    current_value=f"{sys_mem:.1f}%",
                    suggested_value="<85%",
                    rationale="OOM kill esetén az agent nem válaszol, a mesh instabillá válik, és adatvesztés történhet.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
            elif sys_mem > 80 and not _suggestion_exists("memóriahasználat", node_name):
                s = await self.generate_suggestion(
                    category="memory",
                    priority="high",
                    title=f"Magas memóriahasználat ({sys_mem:.0f}%)",
                    description=f"A {node_name} node rendszer memóriahasználata {sys_mem:.0f}%. Ha a trend folytatódik, OOM kockázat léphet fel.",
                    current_value=f"{sys_mem:.1f}%",
                    suggested_value="<75%",
                    rationale="A magas memóriahasználat ronthatja a teljesítményt és OOM kill-hez vezethet.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
            
            rss = mem.get("process_rss_mb", 0)
            if rss > 500 and not _suggestion_exists("RSS memória", node_name):
                s = await self.generate_suggestion(
                    category="memory",
                    priority="high",
                    title=f"Magas RSS memória ({rss:.0f}MB) — lehetséges memóriaszivárgás",
                    description=f"A {node_name} agent folyamata {rss:.0f}MB RSS memóriát használ. Ez memóriaszivárgásra utalhat.",
                    current_value=f"{rss:.0f}MB",
                    suggested_value="<400MB",
                    rationale="A memóriaszivárgás idővel OOM kill-hez vezet. Az agent újraindítása ideiglenesen megoldja, de a root cause vizsgálata szükséges.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
        
        # ─── CPU suggestions ────────────────────────────────────────
        if mem:
            cpu = mem.get("system_cpu_percent", 0)
            if cpu > 90 and not _suggestion_exists("CPU használat", node_name):
                s = await self.generate_suggestion(
                    category="performance",
                    priority="critical",
                    title=f"Kritikus CPU használat ({cpu:.0f}%)",
                    description=f"A {node_name} node CPU használata {cpu:.0f}%. Ez a mesh késleltetését és a válaszidő romlását okozza.",
                    current_value=f"{cpu:.0f}%",
                    suggested_value="<75%",
                    rationale="A magas CPU használat lassítja az üzenetfeldolgozást, növeli a hálózati késleltetést, és ronthatja az agent válaszainak minőségét.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
            elif cpu > 75 and not _suggestion_exists("CPU használat", node_name):
                s = await self.generate_suggestion(
                    category="performance",
                    priority="medium",
                    title=f"Magas CPU használat ({cpu:.0f}%)",
                    description=f"A {node_name} node CPU használata {cpu:.0f}%. Ha tartósan magas, érdemes vizsgálni a CPU-igényes folyamatokat.",
                    current_value=f"{cpu:.0f}%",
                    suggested_value="<60%",
                    rationale="A tartósan magas CPU használat ronthatja az agent válaszidejét.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
        
        # ─── Disk suggestions ────────────────────────────────────────
        if mem:
            disk = mem.get("disk_usage_percent", 0)
            if disk > 90 and not _suggestion_exists("lemezterület", node_name):
                s = await self.generate_suggestion(
                    category="storage",
                    priority="critical",
                    title=f"Kritikus lemezterület ({disk:.0f}%)",
                    description=f"A {node_name} node lemezterülete {disk:.0f}% használt. Ha elfogy a hely, a node leállhat.",
                    current_value=f"{disk:.0f}%",
                    suggested_value="<80%",
                    rationale="A lemezterület hiánya megakadályozza a naplózást, az adatbázis működést és a fájlműveleteket.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
            elif disk > 80 and not _suggestion_exists("lemezterület", node_name):
                s = await self.generate_suggestion(
                    category="storage",
                    priority="medium",
                    title=f"Magas lemezterület használat ({disk:.0f}%)",
                    description=f"A {node_name} node lemezterülete {disk:.0f}% használt. Érdemes tisztítani a régi fájlokat.",
                    current_value=f"{disk:.0f}%",
                    suggested_value="<70%",
                    rationale="A közelgő lemezterület hiány megakadályozhatja a normál működést.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
        
        # ─── Mesh connectivity suggestions ──────────────────────────
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            if peers == 0 and not _suggestion_exists("peer csatlakozás", node_name):
                s = await self.generate_suggestion(
                    category="network",
                    priority="critical",
                    title="Nincs peer csatlakozva — izolált node",
                    description=f"A {node_name} node nem csatlakozott egyetlen peer-hez sem. A mesh kommunikáció megszakadhat.",
                    current_value="0 peer",
                    suggested_value="≥2 peer",
                    rationale="Izolált node nem tud delegálni, üzeneteket küldeni vagy fogadni. A hálózati konfiguráció ellenőrzése szükséges.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
            elif peers == 1 and not _suggestion_exists("peer csatlakozás", node_name):
                s = await self.generate_suggestion(
                    category="network",
                    priority="medium",
                    title=f"Csak {peers} peer csatlakozva — alacsony mesh reziliencia",
                    description=f"A {node_name} node csak {peers} peer-hez csatlakozik. Ha az a peer leáll, a node izolálódik.",
                    current_value=f"{peers} peer",
                    suggested_value="≥2 peer",
                    rationale="A mesh reziliencia növelése érdekében legalább 2 peer ajánlott.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
            
            # Transport suggestions
            transports = health.get("transports", {})
            if isinstance(transports, dict):
                unavailable = [name for name, info in transports.items() 
                               if isinstance(info, dict) and not info.get("available", True)]
                if unavailable and not _suggestion_exists("transport", node_name):
                    s = await self.generate_suggestion(
                        category="network",
                        priority="high",
                        title=f"Transport nem elérhető: {', '.join(unavailable)}",
                        description=f"A {node_name} node-on a következő transportok nem elérhetők: {', '.join(unavailable)}. Ez korlátozza a mesh kommunikációt.",
                        current_value=f"Elérhetetlen: {', '.join(unavailable)}",
                        suggested_value="Minden transport elérhető",
                        rationale="A nem elérhető transportok miatt a node csak korlátozottan tud kommunikálni. Hálózati beállítások ellenőrzése javasolt.",
                        affected_nodes=[node_name],
                    
                    source_node=node_name)
                    new_suggestions.append(s)
            
            # Connection count
            connections = mem.get("connections", 0) if mem else 0
            if connections > 100 and not _suggestion_exists("kapcsolatszám", node_name):
                s = await self.generate_suggestion(
                    category="network",
                    priority="medium",
                    title=f"Nagy kapcsolatszám ({connections})",
                    description=f"A {node_name} node {connections} aktív kapcsolattal rendelkezik. Ez kapcsolatszivárgásra utalhat.",
                    current_value=f"{connections} kapcsolat",
                    suggested_value="<50 kapcsolat",
                    rationale="A felesleges kapcsolatok erőforrásokat fogyasztanak és kapcsolatszivárgásra utalnak.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
        
        # ─── Performance suggestions ────────────────────────────────
        perf = report.performance
        if perf:
            queue_size = perf.get("message_queue_size", 0)
            if queue_size > 50 and not _suggestion_exists("üzenetsor", node_name):
                s = await self.generate_suggestion(
                    category="performance",
                    priority="high",
                    title=f"Nagy üzenetsor ({queue_size} üzenet)",
                    description=f"A {node_name} node üzenetsora {queue_size} üzenetet tartalmaz. Ez feldolgozási késleltetést jelent.",
                    current_value=f"{queue_size} üzenet",
                    suggested_value="<10 üzenet",
                    rationale="A nagy üzenetsor késleltetést okoz a mesh kommunikációban. A feldolgozás gyorsítása vagy a terhelés csökkentése javasolt.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
        
        # ─── Error suggestions ──────────────────────────────────────
        errs = report.error_patterns
        if errs:
            total = errs.get("total_errors", 0)
            if total > 10 and not _suggestion_exists("hibaszám", node_name):
                # Find most common error
                error_counts = errs.get("error_counts", {})
                top_error = max(error_counts.items(), key=lambda x: x[1]) if error_counts else ("ismeretlen", total)
                s = await self.generate_suggestion(
                    category="stability",
                    priority="high" if total > 50 else "medium",
                    title=f"Magas hibaszám ({total} hiba)",
                    description=f"A {node_name} node {total} hibát észlelt. A leggyakoribb hiba: '{top_error[0]}' ({top_error[1]} előfordulás).",
                    current_value=f"{total} hiba",
                    suggested_value="0 hiba",
                    rationale=f"A magas hibaszám instabilitást jelez. A leggyakoribb hiba ('{top_error[0]}') root cause vizsgálata javasolt.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
        
        # ─── Delegation suggestions ─────────────────────────────────
        if health:
            failed = health.get("delegations_failed", 0)
            if failed > 3 and not _suggestion_exists("delegáció", node_name):
                s = await self.generate_suggestion(
                    category="delegation",
                    priority="medium",
                    title=f"Sikertelen delegációk ({failed})",
                    description=f"A {node_name} node {failed} sikertelen delegációt észlelt. A cél agentek LLM elérhetősége vagy képességei ellenőrizendők.",
                    current_value=f"{failed} sikertelen",
                    suggested_value="0 sikertelen",
                    rationale="A sikertelen delegációk rontják a mesh együttműködési képességét.",
                    affected_nodes=[node_name],
                
                    source_node=node_name)
                new_suggestions.append(s)
        
        if new_suggestions:
            log.info(f"💡 Generated {len(new_suggestions)} auto-suggestions from report {report.report_id}")
        
        return new_suggestions
    
    def _assess_severity(self, report: DiagnosticReport) -> str:
        """Assess overall severity of the report."""
        mem = report.memory_stats
        if mem:
            rss = mem.get("process_rss_mb", 0)
            sys_mem = mem.get("system_memory_percent", 0)
            if rss > 1000 or sys_mem > 95:
                return "critical"
            if rss > 500 or sys_mem > 85:
                return "warning"
        
        # Isolated node (0 peers) = warning
        health = report.mesh_health
        if health:
            peers = health.get("peer_count", 0)
            transports = health.get("transports", {})
            all_down = (isinstance(transports, dict) and 
                       all(not info.get("available", True) for info in transports.values() 
                           if isinstance(info, dict)) and transports)
            if peers == 0 and all_down:
                return "critical"  # Node is completely isolated
            if peers == 0:
                return "warning"  # No peers but some transports available
        
        errs = report.error_patterns
        if errs and errs.get("total_errors", 0) > 20:
            return "warning"
        
        return "info"
    
    def _store_report(self, report: DiagnosticReport):
        """Store report in memory, capped at max_reports_stored."""
        self._reports.append(report)
        if len(self._reports) > self.config.max_reports_stored:
            self._reports = self._reports[-self.config.max_reports_stored:]
    
    async def _broadcast_report(self, report: DiagnosticReport):
        """Broadcast diagnostic report through the mesh."""
        try:
            payload = {
                "type": "diagnostic_report",
                "source": self.node.config.node_name,
                "data": report.to_dict(),
            }
            await self.node.broadcast(
                msg_type="diagnostic_report",
                payload=payload,
            )
            # Also publish to PG diagnostic_channel for cross-node delivery
            if self.node._pg_pool and self.node._pg_pool.is_connected():
                try:
                    await self.node._pg_pool.execute(
                        "SELECT pg_notify($1, $2)",
                        "diagnostic_channel",
                        json.dumps(payload)
                    )
                    log.debug(f"📊 Diagnostic report PG NOTIFY sent to diagnostic_channel")
                except Exception as e:
                    log.warning(f"Failed to PG NOTIFY diagnostic report: {e}")
            log.info(f"📊 Diagnostic report broadcasted: {report.report_id}")
        except Exception as e:
            log.error(f"Failed to broadcast diagnostic report: {e}")
    
    async def _broadcast_suggestion(self, suggestion: ConfigSuggestion):
        """Broadcast config suggestion through the mesh."""
        try:
            payload = {
                "type": "config_suggestion",
                "source": self.node.config.node_name,
                "data": suggestion.to_dict(),
            }
            await self.node.broadcast(
                msg_type="config_suggestion",
                payload=payload,
            )
            # Also publish to PG diagnostic_channel for cross-node delivery
            if self.node._pg_pool and self.node._pg_pool.is_connected():
                try:
                    await self.node._pg_pool.execute(
                        "SELECT pg_notify($1, $2)",
                        "diagnostic_channel",
                        json.dumps(payload)
                    )
                    log.debug(f"💡 Config suggestion PG NOTIFY sent to diagnostic_channel")
                except Exception as e:
                    log.warning(f"Failed to PG NOTIFY config suggestion: {e}")
            log.info(f"💡 Config suggestion broadcasted: {suggestion.title}")
        except Exception as e:
            log.error(f"Failed to broadcast config suggestion: {e}")
    
    async def handle_diagnostic_message(self, message: dict):
        """Handle incoming diagnostic message from the mesh."""
        msg_type = message.get("type", "")
        source = message.get("source", "unknown")
        data = message.get("data", {})
        
        if msg_type == "diagnostic_report":
            report = DiagnosticReport.from_dict(data)
            # Sanitize transport latencies from remote reports (clock skew, invalid values)
            if report.mesh_health and isinstance(report.mesh_health, dict):
                transports = report.mesh_health.get("transports", {})
                if isinstance(transports, dict):
                    report.mesh_health["transports"] = self._sanitize_transport_latencies(transports)
            # Deduplicate by report_id — same report may arrive via P2P and PG NOTIFY
            if any(r.report_id == report.report_id for r in self._reports):
                log.debug(f"📊 Duplicate diagnostic report from {source}: {report.report_id} — skipping")
                return
            self._store_report(report)
            log.info(f"📊 Received diagnostic report from {source}: {report.report_id}")
            # Auto-generate suggestions from received report
            try:
                await self._generate_suggestions_from_report(report)
            except Exception as e:
                log.warning(f"Failed to auto-generate suggestions from received report: {e}")
        
        elif msg_type == "config_suggestion":
            suggestion = ConfigSuggestion.from_dict(data)
            # Deduplicate by suggestion_id
            if any(s.suggestion_id == suggestion.suggestion_id for s in self._suggestions):
                log.debug(f"💡 Duplicate config suggestion from {source}: {suggestion.title} — skipping")
                return
            self._suggestions.append(suggestion)
            if len(self._suggestions) > self.config.max_reports_stored:
                self._suggestions = self._suggestions[-self.config.max_reports_stored:]
            log.info(f"💡 Received config suggestion from {source}: {suggestion.title}")
    
    def record_error(self, error_type: str):
        """Record an error occurrence for pattern analysis."""
        self._error_counts[error_type] = self._error_counts.get(error_type, 0) + 1
    
    def get_reports(self, limit: int = 20, severity: Optional[str] = None) -> List[DiagnosticReport]:
        """Get stored diagnostic reports, optionally filtered by severity."""
        reports = self._reports
        if severity:
            reports = [r for r in reports if r.severity == severity]
        return reports[-limit:]
    
    def get_suggestions(self, limit: int = 20, category: Optional[str] = None) -> List[ConfigSuggestion]:
        """Get stored config suggestions, optionally filtered by category."""
        suggestions = self._suggestions
        if category:
            suggestions = [s for s in suggestions if s.category == category]
        return suggestions[-limit:]
    
    def update_suggestion_status(self, suggestion_id: str, new_status: str) -> Optional[ConfigSuggestion]:
        """Update the status of a suggestion (pending/accepted/rejected/implemented)."""
        valid = {"pending", "accepted", "rejected", "implemented"}
        if new_status not in valid:
            return None
        for s in self._suggestions:
            if s.suggestion_id == suggestion_id:
                old_status = s.status
                s.status = new_status
                log.info(f"📋 Suggestion {suggestion_id}: {old_status} → {new_status}")
                return s
        return None
    

    async def auto_implement_suggestions(self) -> List[str]:
        """Auto-accept and implement pending suggestions where possible.
        
        Returns list of implemented suggestion IDs.
        For suggestions that can't be auto-implemented, they stay as 'accepted'.
        """
        implemented = []
        for s in self._suggestions:
            if s.status != 'pending':
                continue
            
            # Auto-accept all pending suggestions
            s.status = 'accepted'
            log.info(f"📋 Auto-accepted suggestion: {s.title} ({s.suggestion_id})")
            
            # Try to auto-implement based on category
            try:
                result = await self._implement_suggestion(s)
                if result:
                    s.status = 'implemented'
                    implemented.append(s.suggestion_id)
                    log.info(f"✅ Auto-implemented suggestion: {s.title} ({s.suggestion_id})")
                    # Broadcast the status change
                    await self._broadcast_suggestion(s)
            except Exception as e:
                log.warning(f"⚠️ Could not auto-implement suggestion {s.suggestion_id}: {e}")
        
        return implemented
    
    async def _implement_suggestion(self, suggestion: ConfigSuggestion) -> bool:
        """Try to auto-implement a suggestion. Returns True if successful.
        
        Implementation logic by category:
        - memory: restart self if OOM risk, set memory limits
        - performance: log CPU-intensive processes for investigation
        - network: trigger peer reconnect, restart P2P transport
        - storage: clean old logs and temp files
        - stability: restart error-prone subsystems
        """
        cat = suggestion.category
        node_name = suggestion.node
        
        if cat == 'memory':
            # Check if this node is the affected one
            if node_name == self.node.config.node_name:
                # High memory: try garbage collection and memory optimization
                import gc
                gc.collect()
                log.info(f"🧹 Triggered garbage collection for memory suggestion on {node_name}")
                
                # If RSS is very high, consider restarting the agent
                rss_mb = float(suggestion.current_value.replace('MB', '').strip()) if 'MB' in suggestion.current_value else 0
                if rss_mb > 500:
                    log.warning(f"🔴 RSS memory {rss_mb}MB exceeds 500MB — agent restart recommended")
                    # Don't auto-restart to avoid loop, just log
                
                return True  # GC was triggered
            
            # For remote nodes: send a directive to trigger GC
            if hasattr(self.node, 'broadcast'):
                try:
                    await self.node.broadcast(
                        msg_type="directive",
                        payload={
                            "type": "gc_collect",
                            "target": node_name,
                            "reason": suggestion.title,
                            "suggestion_id": suggestion.suggestion_id,
                        },
                    )
                    log.info(f"📡 Sent GC directive to {node_name}")
                    return True
                except Exception as e:
                    log.warning(f"Failed to send GC directive to {node_name}: {e}")
        
        elif cat == 'performance':
            # Log current CPU usage for investigation
            import psutil
            cpu = psutil.cpu_percent(interval=0.1)
            log.info(f"⚡ CPU investigation: current CPU={cpu}%, suggestion says {suggestion.current_value}")
            
            # For remote nodes, send CPU investigation directive
            if node_name != self.node.config.node_name and hasattr(self.node, 'broadcast'):
                try:
                    await self.node.broadcast(
                        msg_type="directive",
                        payload={
                            "type": "cpu_investigate",
                            "target": node_name,
                            "reason": suggestion.title,
                            "suggestion_id": suggestion.suggestion_id,
                        },
                    )
                    log.info(f"📡 Sent CPU investigation directive to {node_name}")
                    return True
                except Exception:
                    pass
            return True  # Logged investigation
        
        elif cat == 'network':
            # Try to reconnect isolated peers
            if 'izolált' in suggestion.title or 'peer' in suggestion.title.lower():
                if hasattr(self.node, 'peer_discovery') and self.node.peer_discovery:
                    log.info(f"🌐 Triggering peer discovery refresh for network suggestion")
                    try:
                        await self.node.peer_discovery.discover_peers()
                        return True
                    except Exception as e:
                        log.warning(f"Peer discovery refresh failed: {e}")
            return False  # Can't fully auto-implement network issues
        
        elif cat == 'storage':
            # Clean old logs and temp files
            if node_name == self.node.config.node_name:
                import glob
                import os
                cleaned = 0
                # Clean __pycache__
                for f in glob.glob(os.path.join(os.path.dirname(__file__), '..', '**', '__pycache__'), recursive=True):
                    try:
                        import shutil
                        shutil.rmtree(f)
                        cleaned += 1
                    except Exception:
                        pass
                # Clean old log files
                log_dir = os.path.expanduser('~/.hermes/logs')
                if os.path.isdir(log_dir):
                    for f in glob.glob(os.path.join(log_dir, '*.log.*')):
                        try:
                            os.remove(f)
                            cleaned += 1
                        except Exception:
                            pass
                log.info(f"🧹 Cleaned {cleaned} files for storage suggestion")
                return cleaned > 0
            return False
        
        elif cat == 'stability':
            # Restart error-prone subsystems
            log.info(f"🔧 Stability suggestion logged: {suggestion.title}")
            return True  # Logged, manual intervention recommended
        
        return False  # Unknown category — manual implementation needed
    def get_status(self) -> Dict[str, Any]:
        """Get current diagnostic engine status."""
        return {
            "enabled": self.config.enabled,
            "report_interval": self.config.report_interval,
            "developer_nodes": self.config.developer_nodes,
            "reports_stored": len(self._reports),
            "suggestions_stored": len(self._suggestions),
            "last_report_time": self._last_report_time,
            "error_types_tracked": len(self._error_counts),
            "performance_samples": len(self._performance_samples),
        }