#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generated by runa via A2A Mesh delegation

Szoba-közi dedup: ugyanaz az ötlet több szobában születik → mesh-szintű egyesítés,
hogy ne fejlesszük kétszer ugyanazt.

Ez a modul a mesh szintjén detektálja és egyesíti a több szobában függetlenül
felmerült azonos/duplikált ötleteket. Szöveghasonlítás alapján (TF-IDF +
cosine similarity) találja meg a duplikációkat, majd egyesíti őket egyetlen
mesh-szintű "merged idea" objektummá, megőrizve az eredeti szoba-közi
provenance-t.
"""

import os
import sys
import json
import hashlib
import math
import re
import argparse
from datetime import datetime, timezone
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Tuple, Set
from collections import defaultdict, Counter

# ---------------------------------------------------------------------------
# Adatmodellek
# ---------------------------------------------------------------------------

@dataclass
class Idea:
    """Egyetlen ötlet egy adott szobából."""
    idea_id: str
    room_id: str
    title: str
    description: str
    submitted_by: str
    submitted_at: str
    tags: List[str] = field(default_factory=list)
    status: str = "open"  # open | merged | developed

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Idea":
        return cls(**d)


@dataclass
class MergedIdea:
    """Mesh-szintű egyesített ötlet, ami több szoba ötletéből jött létre."""
    merged_id: str
    canonical_title: str
    canonical_description: str
    source_ideas: List[str]  # idea_id-k
    source_rooms: List[str]
    similarity_score: float
    merged_at: str
    merged_by: str
    tags: List[str] = field(default_factory=list)
    status: str = "merged"

    def to_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------------------
# Szöveghasonlítás: TF-IDF + cosine similarity
# ---------------------------------------------------------------------------

def _tokenize(text: str) -> List[str]:
    """Egyszerű tokenizáló: kisbetűsít, szavakra bont, eltávolítja a rövid
    tokeneket. Magyar és angol szöveghez is használható."""
    text = text.lower()
    # Szóközök és írásjelek mentén bontás
    tokens = re.findall(r"[a-záéíóöőúüű]+", text)
    return [t for t in tokens if len(t) >= 2]


def _compute_tfidf_vectors(
    documents: List[str],
) -> Tuple[List[Dict[str, float]], Dict[str, float]]:
    """TF-IDF vektorokat számít a dokumentumokhoz.

    Visszatér: (vektor_lista, idf_map)
    """
    n_docs = len(documents)
    if n_docs == 0:
        return [], {}

    tokenized = [_tokenize(doc) for doc in documents]

    # Document frequency
    df: Dict[str, int] = defaultdict(int)
    for tokens in tokenized:
        unique = set(tokens)
        for t in unique:
            df[t] += 1

    # IDF
    idf: Dict[str, float] = {}
    for term, freq in df.items():
        idf[term] = math.log((1 + n_docs) / (1 + freq)) + 1.0

    # TF-IDF vektorok
    vectors: List[Dict[str, float]] = []
    for tokens in tokenized:
        tf: Dict[str, float] = defaultdict(float)
        for t in tokens:
            tf[t] += 1.0
        total = len(tokens) if tokens else 1
        vec: Dict[str, float] = {}
        for term, count in tf.items():
            vec[term] = (count / total) * idf.get(term, 0.0)
        vectors.append(vec)

    return vectors, idf


def _cosine_similarity(v1: Dict[str, float], v2: Dict[str, float]) -> float:
    """Két TF-IDF vektor koszinusz hasonlósága."""
    if not v1 or not v2:
        return 0.0
    # Skaláris szorzat
    common_terms = set(v1.keys()) & set(v2.keys())
    dot = sum(v1[t] * v2[t] for t in common_terms)
    # Normák
    norm1 = math.sqrt(sum(v * v for v in v1.values()))
    norm2 = math.sqrt(sum(v * v for v in v2.values()))
    if norm1 == 0 or norm2 == 0:
        return 0.0
    return dot / (norm1 * norm2)


# ---------------------------------------------------------------------------
# Dedup motor
# ---------------------------------------------------------------------------

class CrossRoomDeduplicator:
    """Szoba-közi deduplikációs motor.

    Összehasonlítja az összes nyitott ötletet a mesh szintjén, és egyesíti
    azokat, amelyek hasonlósága meghaladja a küszöböt.
    """

    def __init__(
        self,
        threshold: float = 0.65,
        data_dir: str = None,
        merged_by: str = "runa",
    ):
        self.threshold = threshold
        self.merged_by = merged_by
        if data_dir is None:
            # A repó gyökéréhez viszonyítva
            repo_root = os.path.dirname(os.path.abspath(__file__))
            data_dir = os.path.join(repo_root, "data", "dedup")
        self.data_dir = data_dir
        self.ideas_file = os.path.join(data_dir, "ideas.json")
        self.merged_file = os.path.join(data_dir, "merged_ideas.json")
        self._ensure_dirs()

    def _ensure_dirs(self):
        os.makedirs(self.data_dir, exist_ok=True)
        if not os.path.exists(self.ideas_file):
            self._write_json(self.ideas_file, [])
        if not os.path.exists(self.merged_file):
            self._write_json(self.merged_file, [])

    @staticmethod
    def _write_json(path: str, data):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    @staticmethod
    def _read_json(path: str) -> list:
        if not os.path.exists(path):
            return []
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    # --- Idea management ---

    def add_idea(self, idea: Idea) -> str:
        """Hozzáad egy ötletet a mesh-szintű ötletadatbázishoz."""
        ideas_data = self._read_json(self.ideas_file)
        ideas_data.append(idea.to_dict())
        self._write_json(self.ideas_file, ideas_data)
        return idea.idea_id

    def load_ideas(self) -> List[Idea]:
        raw = self._read_json(self.ideas_file)
        return [Idea.from_dict(d) for d in raw]

    def load_merged(self) -> List[MergedIdea]:
        raw = self._read_json(self.merged_file)
        return [MergedIdea(**d) for d in raw]

    def _mark_ideas_merged(self, idea_ids: List[str]):
        """Frissíti az ötletek státuszát 'merged'-re."""
        ideas_data = self._read_json(self.ideas_file)
        id_set = set(idea_ids)
        for d in ideas_data:
            if d["idea_id"] in id_set:
                d["status"] = "merged"
        self._write_json(self.ideas_file, ideas_data)

    # --- Core dedup logic ---

    def find_duplicates(self) -> List[Tuple[List[Idea], float]]:
        """Megtalálja a duplikált ötlet-csoportokat.

        Visszatér: lista, ahol minden elem (ötlet_lista, átlag_hasonlóság).
        Csak olyan csoportokat ad vissza, ahol legalább 2 ötlet van és
        legalább 2 különböző szobából származnak.
        """
        ideas = [i for i in self.load_ideas() if i.status == "open"]
        if len(ideas) < 2:
            return []

        # Összeállítjuk a dokumentumokat: title + description + tags
        documents = []
        for idea in ideas:
            text = f"{idea.title} {idea.description} {' '.join(idea.tags)}"
            documents.append(text)

        vectors, _ = _compute_tfidf_vectors(documents)

        # Union-Find a csoportosításhoz
        parent = list(range(len(ideas)))

        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        def union(x, y):
            rx, ry = find(x), find(y)
            if rx != ry:
                parent[rx] = ry

        # Páronkénti hasonlóság
        similarity_scores: Dict[Tuple[int, int], float] = {}
        for i in range(len(ideas)):
            for j in range(i + 1, len(ideas)):
                sim = _cosine_similarity(vectors[i], vectors[j])
                if sim >= self.threshold:
                    union(i, j)
                    similarity_scores[(i, j)] = sim

        # Csoportok összegyűjtése
        groups: Dict[int, List[int]] = defaultdict(list)
        for idx in range(len(ideas)):
            groups[find(idx)].append(idx)

        results: List[Tuple[List[Idea], float]] = []
        for indices in groups.values():
            if len(indices) < 2:
                continue
            group_ideas = [ideas[i] for i in indices]
            # Legalább 2 különböző szoba
            rooms = set(i.room_id for i in group_ideas)
            if len(rooms) < 2:
                continue
            # Átlag hasonlóság a csoporton belül
            sims = []
            for a in range(len(indices)):
                for b in range(a + 1, len(indices)):
                    key = (indices[a], indices[b])
                    if key in similarity_scores:
                        sims.append(similarity_scores[key])
            avg_sim = sum(sims) / len(sims) if sims else self.threshold
            results.append((group_ideas, avg_sim))

        # Rendezés: legmagasabb hasonlóság előre
        results.sort(key=lambda x: x[1], reverse=True)
        return results

    def merge_duplicates(self, dry_run: bool = False) -> List[MergedIdea]:
        """Egyesíti a duplikált ötleteket mesh-szintű merged idea-kká.

        dry_run=True esetén csak jelzi, mit egyesítene, de nem módosítja az
        adatbázist.
        """
        dup_groups = self.find_duplicates()
        if not dup_groups:
            print("[dedup] Nincs duplikált ötlet a szobák között.")
            return []

        merged_ideas = self.load_merged() if not dry_run else []
        new_merged: List[MergedIdea] = []

        for group_ideas, avg_sim in dup_groups:
            # Canonical: a legrégebbi ötlet a canonical (elsőként beküldött)
            oldest = min(group_ideas, key=lambda i: i.submitted_at)
            canonical_title = oldest.title
            canonical_desc = oldest.description

            # Tags uniója
            all_tags: Set[str] = set()
            for idea in group_ideas:
                all_tags.update(idea.tags)

            # Merged ID generálása
            source_ids = [i.idea_id for i in group_ideas]
            merged_id = "merged_" + hashlib.sha256(
                ":".join(sorted(source_ids)).encode()
            ).hexdigest()[:12]

            source_rooms = sorted(set(i.room_id for i in group_ideas))

            merged = MergedIdea(
                merged_id=merged_id,
                canonical_title=canonical_title,
                canonical_description=canonical_desc,
                source_ideas=source_ids,
                source_rooms=source_rooms,
                similarity_score=round(avg_sim, 4),
                merged_at=datetime.now(timezone.utc).isoformat(),
                merged_by=self.merged_by,
                tags=sorted(all_tags),
                status="merged",
            )

            new_merged.append(merged)

            # Jelentés
            print(f"\n[dedup] Egyesítés: {merged.merged_id}")
            print(f"  Canonical: {merged.canonical_title}")
            print(f"  Hasonlóság: {merged.similarity_score:.2%}")
            print(f"  Forrás szobák: {', '.join(merged.source_rooms)}")
            print(f"  Forrás ötletek ({len(source_ids)}):")
            for sid in source_ids:
                print(f"    - {sid}")

            if not dry_run:
                # Jelöljük az eredeti ötleteket merged-nek
                self._mark_ideas_merged(source_ids)

        if not dry_run and new_merged:
            merged_ideas.extend(new_merged)
            self._write_json(self.merged_file, [m.to_dict() for m in merged_ideas])
            print(f"\n[dedup] {len(new_merged)} egyesített ötlet mentve: {self.merged_file}")
        elif dry_run:
            print(f"\n[dedup] (dry-run) {len(new_merged)} egyesítés lenne.")

        return new_merged

    def get_merge_report(self) -> str:
        """Szöveges jelentés az eddigi egyesítésekről."""
        merged = self.load_merged()
        if not merged:
            return "[dedup] Még nincs egyesített ötlet."
        lines = ["[dedup] Mesh-szintű egyesített ötletek:", ""]
        for m in merged:
            lines.append(f"  {m.merged_id}: {m.canonical_title}")
            lines.append(f"    Szobák: {', '.join(m.source_rooms)}")
            lines.append(f"    Források: {len(m.source_ideas)} ötlet")
            lines.append(f"    Hasonlóság: {m.similarity_score:.2%}")
            lines.append(f"    Státusz: {m.status}")
            lines.append("")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Demo / CLI
# ---------------------------------------------------------------------------

def _seed_demo_data(dedup: CrossRoomDeduplicator):
    """Feltölti a rendszert demo adatokkal, hogy a dedup azonnal látható legyen."""
    now = datetime.now(timezone.utc).isoformat()

    demo_ideas = [
        Idea(
            idea_id="idea_room_a_001",
            room_id="room_alpha",
            title="Döntési lezárás: szoba végén pontozás",
            description="A szoba végén a top 3 ötlet automatikusan Gitea issue-ként landol, ötletből feladat lesz.",
            submitted_by="runa",
            submitted_at=now,
            tags=["döntés", "gitea", "issue"],
        ),
        Idea(
            idea_id="idea_room_b_042",
            room_id="room_beta",
            title="Szoba végi pontozás és Gitea issue generálás",
            description="A beszélgetés végén a legjobb három ötletből automatikusan Gitea issue jön létre, így ötletből feladat lesz.",
            submitted_by="agent_x",
            submitted_at=now,
            tags=["gitea", "pontozás", "issue"],
        ),
        Idea(
            idea_id="idea_room_c_007",
            room_id="room_gamma",
            title="Konfliktus-párosítás kompromisszum javaslattal",
            description="Ütközés-jelzés mellé generált kompromisszum-javaslat is, különben csak konfliktus marad.",
            submitted_by="runa",
            submitted_at=now,
            tags=["konfliktus", "kompromisszum"],
        ),
        Idea(
            idea_id="idea_room_a_009",
            room_id="room_alpha",
            title="Ütközés észlelés és kompromisszum generálás",
            description="Amikor két ötlet ütközik, a rendszer automatikusan generál egy kompromisszum javaslatot.",
            submitted_by="agent_y",
            submitted_at=now,
            tags=["konfliktus", "kompromisszum", "ütközés"],
        ),
        Idea(
            idea_id="idea_room_b_100",
            room_id="room_beta",
            title="Mesh-szintű ötlet deduplikáció",
            description="Ugyanaz az ötlet több szobában születik, mesh-szintű egyesítés, hogy ne fejlesszük kétszer ugyanazt.",
            submitted_by="runa",
            submitted_at=now,
            tags=["dedup", "mesh", "egyesítés"],
        ),
        # Ez egy egyedi ötlet, nem duplikátum
        Idea(
            idea_id="idea_room_gamma_020",
            room_id="room_gamma",
            title="Automatikus szoba archiválás",
            description="A lezárt szobák automatikusan archiválásra kerülnek 30 nap után.",
            submitted_by="agent_z",
            submitted_at=now,
            tags=["archiválás", "szoba"],
        ),
    ]

    for idea in demo_ideas:
        dedup.add_idea(idea)
    print(f"[dedup] {len(demo_ideas)} demo ötlet betöltve.")


def main():
    parser = argparse.ArgumentParser(
        description="Szoba-közi dedup: mesh-szintű ötlet-egyesítés"
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.65,
        help="Hasonlósági küszöb (0.0-1.0), alapértelmezett: 0.65",
    )
    parser.add_argument(
        "--seed",
        action="store_true",
        help="Demo adatok betöltése a dedup bemutatásához",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Csak jelzi a duplikációkat, nem módosítja az adatbázist",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="Jelentés az eddigi egyesítésekről",
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        default=None,
        help="Adatkönyvtár (alapértelmezett: ./data/dedup)",
    )

    args = parser.parse_args()

    dedup = CrossRoomDeduplicator(
        threshold=args.threshold,
        data_dir=args.data_dir,
        merged_by="runa",
    )

    if args.seed:
        # Ha már vannak adatok, nem seedelünk újra
        existing = dedup.load_ideas()
        if existing:
            print(f"[dedup] Már {len(existing)} ötlet van, seed kihagyva.")
        else:
            _seed_demo_data(dedup)

    if args.report:
        print(dedup.get_merge_report())
        return

    # Alapértelmezett művelet: dedup futtatása
    print(f"[dedup] Küszöb: {args.threshold:.2f}")
    print(f"[dedup] Dry-run: {args.dry_run}")
    print()

    # Először mutatjuk a talált duplikációkat
    dup_groups = dedup.find_duplicates()
    if dup_groups:
        print(f"[dedup] {len(dup_groups)} duplikált csoport található:\n")
        for idx, (group, sim) in enumerate(dup_groups, 1):
            rooms = set(i.room_id for i in group)
            print(f"  Csoport {idx} (hasonlóság: {sim:.2%}):")
            for idea in group:
                print(f"    [{idea.room_id}] {idea.idea_id}: {idea.title}")
            print()
    else:
        print("[dedup] Nincs duplikált ötlet a szobák között.")
        return

    # Egyesítés
    merged = dedup.merge_duplicates(dry_run=args.dry_run)
    if merged:
        print(f"\n[dedup] Összesen {len(merged)} egyesítés történt.")
        print("\n" + "=" * 60)
        print(dedup.get_merge_report())


if __name__ == "__main__":
    main()