#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
CPU Steal Time Monitor & Adaptive Mitigator for A2A Mesh.

Monitors CPU steal time (st%) on the node. When steal time exceeds the
threshold (default 10%), the module:

  1. Identifies the top CPU-consuming processes (python/ollama/postgres).
  2. If the mesh-node itself is the culprit, doubles the diagnostics
     interval and caps performance_samples to 30.
  3. Logs recommendations for off-peak scheduling of cron/LLM tasks.
  4. Persists a cgroup-based CPU limit (best-effort) and enables
     load-aware scheduling hints.
  5. Emits a Proxmox-level recommendation (CPU pinning / VM reduction)
     since steal time is a hypervisor-side problem.

Run from repo root:
    python3 runa_steal_time_monitor.py
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import List, Optional, Tuple

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent
CONFIG_PATH = REPO_ROOT / "runa_steal_config.json"
STATE_PATH = REPO_ROOT / "runa_steal_state.json"
LOG_PATH = REPO_ROOT / "runa_steal_monitor.log"

STEAL_THRESHOLD = 10.0          # % — recommended target: steal < 10
STEAL_CRITICAL = 25.0           # % — critical, immediate mitigation
DIAG_INTERVAL_NORMAL = 300      # seconds
DIAG_INTERVAL_BACKOFF = 600     # seconds (doubled)
PERF_SAMPLES_NORMAL = 60
PERF_SAMPLES_BACKOFF = 30
TOP_PROCESS_COUNT = 8
MESH_NODE_KEYWORDS = ("python", "ollama", "mesh", "runa", "uvicorn", "gunicorn")
DB_KEYWORDS = ("postgres", "redis", "mongod")


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class CPUSample:
    timestamp: float
    steal_pct: float
    effective_pct: float
    raw_pct: float
    user_pct: float = 0.0
    system_pct: float = 0.0
    iowait_pct: float = 0.0


@dataclass
class ProcessInfo:
    pid: int
    name: str
    cpu_pct: float
    mem_pct: float
    command: str


@dataclass
class StealState:
    samples: List[CPUSample] = field(default_factory=list)
    backoff_active: bool = False
    backoff_since: float = 0.0
    last_mitigation: float = 0.0
    mitigation_count: int = 0
    diag_interval: int = DIAG_INTERVAL_NORMAL
    perf_samples: int = PERF_SAMPLES_NORMAL
    cgroup_limit_set: bool = False
    proxmox_warning_emitted: bool = False

    def save(self, path: Path = STATE_PATH) -> None:
        data = {
            "samples": [asdict(s) for s in self.samples[-100:]],
            "backoff_active": self.backoff_active,
            "backoff_since": self.backoff_since,
            "last_mitigation": self.last_mitigation,
            "mitigation_count": self.mitigation_count,
            "diag_interval": self.diag_interval,
            "perf_samples": self.perf_samples,
            "cgroup_limit_set": self.cgroup_limit_set,
            "proxmox_warning_emitted": self.proxmox_warning_emitted,
        }
        path.write_text(json.dumps(data, indent=2))

    @classmethod
    def load(cls, path: Path = STATE_PATH) -> "StealState":
        if not path.exists():
            return cls()
        try:
            data = json.loads(path.read_text())
            samples = [CPUSample(**s) for s in data.get("samples", [])]
            return cls(
                samples=samples,
                backoff_active=data.get("backoff_active", False),
                backoff_since=data.get("backoff_since", 0.0),
                last_mitigation=data.get("last_mitigation", 0.0),
                mitigation_count=data.get("mitigation_count", 0),
                diag_interval=data.get("diag_interval", DIAG_INTERVAL_NORMAL),
                perf_samples=data.get("perf_samples", PERF_SAMPLES_NORMAL),
                cgroup_limit_set=data.get("cgroup_limit_set", False),
                proxmox_warning_emitted=data.get("proxmox_warning_emitted", False),
            )
        except (json.JSONDecodeError, TypeError, KeyError):
            return cls()


# ---------------------------------------------------------------------------
# CPU sampling
# ---------------------------------------------------------------------------

def _read_proc_stat() -> Optional[dict]:
    """Parse /proc/stat for CPU line (Linux only)."""
    stat_path = Path("/proc/stat")
    if not stat_path.exists():
        return None
    try:
        first_line = stat_path.read_text().splitlines()[0]
        parts = first_line.split()
        # cpu user nice system idle iowait irq softirq steal guest guest_nice
        labels = ["user", "nice", "system", "idle", "iowait", "irq",
                  "softirq", "steal", "guest", "guest_nice"]
        values = {}
        for i, label in enumerate(labels):
            if i + 1 < len(parts):
                values[label] = int(parts[i + 1])
        return values
    except Exception:
        return None


def sample_cpu() -> CPUSample:
    """
    Sample CPU steal time. Uses /proc/stat on Linux, falls back to
    a heuristic from `top` on other platforms.
    """
    s1 = _read_proc_stat()
    if s1 is not None:
        time.sleep(0.5)
        s2 = _read_proc_stat()
        if s2 is not None:
            total1 = sum(v for k, v in s1.items() if k != "guest" and k != "guest_nice")
            total2 = sum(v for k, v in s2.items() if k != "guest" and k != "guest_nice")
            dt = total2 - total1
            if dt <= 0:
                return CPUSample(time.time(), 0.0, 0.0, 0.0)
            steal = ((s2["steal"] - s1["steal"]) / dt) * 100.0
            user = ((s2["user"] - s1["user"]) / dt) * 100.0
            system = ((s2["system"] - s1["system"]) / dt) * 100.0
            iowait = ((s2["iowait"] - s1["iowait"]) / dt) * 100.0
            idle = ((s2["idle"] - s1["idle"]) / dt) * 100.0
            effective = 100.0 - idle - steal
            raw = effective + steal
            return CPUSample(
                timestamp=time.time(),
                steal_pct=round(steal, 2),
                effective_pct=round(effective, 2),
                raw_pct=round(raw, 2),
                user_pct=round(user, 2),
                system_pct=round(system, 2),
                iowait_pct=round(iowait, 2),
            )

    # Fallback: try `top` parsing
    return _sample_cpu_top_fallback()


def _sample_cpu_top_fallback() -> CPUSample:
    """Parse `top -b -n2` output for steal time (non-/proc/stat fallback)."""
    try:
        result = subprocess.run(
            ["top", "-b", "-n2", "-d0.5"],
            capture_output=True, text=True, timeout=10
        )
        lines = result.stdout.splitlines()
        # Find the last Cpu(s) line
        cpu_line = None
        for line in reversed(lines):
            if "Cpu(s)" in line or "%Cpu" in line:
                cpu_line = line
                break
        if cpu_line is None:
            return CPUSample(time.time(), 0.0, 0.0, 0.0)

        steal = 0.0
        user = 0.0
        system = 0.0
        iowait = 0.0
        idle = 0.0
        for token in cpu_line.replace(",", " ").split():
            if token.endswith("st") and token[0].isdigit():
                steal = float(token.rstrip("st"))
            elif token.endswith("us") and token[0].isdigit():
                user = float(token.rstrip("us"))
            elif token.endswith("sy") and token[0].isdigit():
                system = float(token.rstrip("sy"))
            elif token.endswith("wa") and token[0].isdigit():
                iowait = float(token.rstrip("wa"))
            elif token.endswith("id") and token[0].isdigit():
                idle = float(token.rstrip("id"))
        effective = 100.0 - idle - steal
        raw = effective + steal
        return CPUSample(
            timestamp=time.time(),
            steal_pct=round(steal, 2),
            effective_pct=round(effective, 2),
            raw_pct=round(raw, 2),
            user_pct=round(user, 2),
            system_pct=round(system, 2),
            iowait_pct=round(iowait, 2),
        )
    except Exception:
        return CPUSample(time.time(), 0.0, 0.0, 0.0)


# ---------------------------------------------------------------------------
# Process inspection
# ---------------------------------------------------------------------------

def get_top_processes(count: int = TOP_PROCESS_COUNT) -> List[ProcessInfo]:
    """Return top CPU-consuming processes."""
    procs: List[ProcessInfo] = []
    try:
        result = subprocess.run(
            ["ps", "aux", "--sort=-%cpu"],
            capture_output=True, text=True, timeout=5
        )
        lines = result.stdout.strip().splitlines()
        if len(lines) < 2:
            return procs
        for line in lines[1:count + 1]:
            parts = line.split(None, 10)
            if len(parts) < 11:
                continue
            try:
                pid = int(parts[1])
                cpu_pct = float(parts[2])
                mem_pct = float(parts[3])
                name = parts[10].split()[0] if parts[10].split() else parts[10]
                name = os.path.basename(name)
                procs.append(ProcessInfo(
                    pid=pid, name=name, cpu_pct=cpu_pct,
                    mem_pct=mem_pct, command=parts[10][:200]
                ))
            except (ValueError, IndexError):
                continue
    except FileNotFoundError:
        pass
    return procs


def classify_processes(procs: List[ProcessInfo]) -> dict:
    """Classify processes into categories."""
    categories = {
        "mesh_node": [],
        "database": [],
        "other": [],
    }
    for p in procs:
        name_lower = p.name.lower()
        cmd_lower = p.command.lower()
        if any(kw in name_lower or kw in cmd_lower for kw in MESH_NODE_KEYWORDS):
            categories["mesh_node"].append(p)
        elif any(kw in name_lower or kw in cmd_lower for kw in DB_KEYWORDS):
            categories["database"].append(p)
        else:
            categories["other"].append(p)
    return categories


# ---------------------------------------------------------------------------
# Mitigation actions
# ---------------------------------------------------------------------------

def log(msg: str, level: str = "INFO") -> None:
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    line = f"[{ts}] [{level}] {msg}"
    print(line, flush=True)
    try:
        with open(LOG_PATH, "a") as f:
            f.write(line + "\n")
    except OSError:
        pass


def apply_backoff(state: StealState) -> None:
    """Double diagnostics interval, cap performance_samples to 30."""
    if not state.backoff_active:
        state.backoff_active = True
        state.backoff_since = time.time()
        state.diag_interval = DIAG_INTERVAL_BACKOFF
        state.perf_samples = PERF_SAMPLES_BACKOFF
        log(f"Backoff activated: diag_interval={DIAG_INTERVAL_BACKOFF}s, "
            f"perf_samples={PERF_SAMPLES_BACKOFF}", "WARN")


def release_backoff(state: StealState) -> None:
    """Restore normal diagnostics settings."""
    if state.backoff_active:
        state.backoff_active = False
        state.diag_interval = DIAG_INTERVAL_NORMAL
        state.perf_samples = PERF_SAMPLES_NORMAL
        log("Backoff released: normal diagnostics restored", "INFO")


def try_cgroup_cpu_limit(state: StealState, steal: float) -> None:
    """
    Attempt to set a cgroup v2 CPU limit on the current process group
    to reduce pressure. Best-effort — silently skips if not available.
    """
    if state.cgroup_limit_set and steal < STEAL_THRESHOLD:
        # Remove limit when steal is back to normal
        cgroup_path = _get_cgroup_path()
        if cgroup_path and (cgroup_path / "cpu.max").exists():
            try:
                (cgroup_path / "cpu.max").write_text("max 100000")
                log("cgroup CPU limit removed (steal normalised)", "INFO")
            except OSError:
                pass
        state.cgroup_limit_set = False
        return

    if state.cgroup_limit_set or steal < STEAL_THRESHOLD:
        return

    cgroup_path = _get_cgroup_path()
    if cgroup_path is None or not (cgroup_path / "cpu.max").exists():
        log("cgroup v2 not available — skipping CPU limit", "DEBUG")
        return

    # Limit to 50% of one CPU during high-steal periods
    quota = 50000  # 50ms per 100ms period = 50%
    try:
        (cgroup_path / "cpu.max").write_text(f"{quota} 100000")
        state.cgroup_limit_set = True
        log(f"cgroup CPU limit set to 50% (quota={quota}us/100000us)", "WARN")
    except OSError as e:
        log(f"Failed to set cgroup CPU limit: {e}", "WARN")


def _get_cgroup_path() -> Optional[Path]:
    """Return the cgroup v2 path for the current process."""
    self_cgroup = Path(f"/proc/{os.getpid()}/cgroup")
    mountinfo = Path("/proc/self/mountinfo")
    if not self_cgroup.exists() or not mountinfo.exists():
        return None
    try:
        cgroup_line = self_cgroup.read_text().strip().splitlines()[0]
        # v2 format: 0::/path
        if "::" not in cgroup_line:
            return None
        cgroup_rel = cgroup_line.split("::", 1)[1].strip()
        # Find mount point
        for line in mountinfo.read_text().splitlines():
            parts = line.split()
            if len(parts) >= 9 and "cgroup2" in parts[-2]:
                mount_point = parts[4]
                return Path(mount_point) / cgroup_rel.lstrip("/")
    except Exception:
        pass
    return None


def emit_proxmox_recommendation(steal: float) -> str:
    """Generate Proxmox-level recommendation text."""
    rec = (
        "=== PROXMOX HYPERVISOR RECOMMENDATION ===\n"
        f"  CPU steal time: {steal:.1f}% (target: <{STEAL_THRESHOLD:.0f}%)\n"
        "  Root cause: hypervisor overcommit, NOT VM-local issue.\n"
        "  Actions (on Proxmox host):\n"
        "    1. Enable CPU pinning for this VM (qm set <vmid> --cpus 0-3,host)\n"
        "    2. Reduce number of co-located VMs on this host\n"
        "    3. Upgrade host CPU or migrate VMs to less-loaded nodes\n"
        "    4. Check: `pvesh get /nodes/<node>/status` for host load\n"
        "    5. Consider: `qm set <vmid> --cpuunits 1024` for priority\n"
        "=========================================="
    )
    log(rec, "ERROR")
    return rec


def emit_offpeak_recommendation(procs: List[ProcessInfo]) -> str:
    """Recommend off-peak scheduling for non-mesh heavy processes."""
    rec_lines = ["=== OFF-PEAK SCHEDULING RECOMMENDATION ==="]
    found = False
    for p in procs:
        name_lower = p.name.lower()
        if any(kw in name_lower for kw in ("cron", "backup", "ollama", "llm", "train")):
            rec_lines.append(
                f"  PID {p.pid} ({p.name}, {p.cpu_pct:.1f}% CPU): "
                f"reschedule to off-peak hours (02:00-06:00)"
            )
            found = True
    if not found:
        rec_lines.append("  No cron/LLM/backup processes detected in top consumers.")
    rec_lines.append("===========================================")
    rec = "\n".join(rec_lines)
    log(rec, "INFO")
    return rec


# ---------------------------------------------------------------------------
# Config persistence (for mesh-node integration)
# ---------------------------------------------------------------------------

def save_mesh_config(state: StealState) -> None:
    """Write a config snippet that the mesh-node can read for diag settings."""
    config = {
        "idea_id": "idea_b4dce4819f5e",
        "steal_monitor": {
            "diag_interval_s": state.diag_interval,
            "performance_samples_max": state.perf_samples,
            "backoff_active": state.backoff_active,
            "steal_threshold": STEAL_THRESHOLD,
            "steal_critical": STEAL_CRITICAL,
        },
    }
    CONFIG_PATH.write_text(json.dumps(config, indent=2))


# ---------------------------------------------------------------------------
# Main monitoring loop
# ---------------------------------------------------------------------------

def run_monitor(iterations: int = 0, interval: float = 60.0) -> None:
    """
    Run the steal-time monitor.

    Args:
        iterations: Number of sampling iterations (0 = infinite).
        interval: Base sampling interval in seconds.
    """
    state = StealState.load()
    log(f"Steal-time monitor started (pid={os.getpid()}, threshold={STEAL_THRESHOLD}%)")
    log(f"Current state: backoff={state.backoff_active}, "
        f"diag_interval={state.diag_interval}s, "
        f"perf_samples={state.perf_samples}")

    i = 0
    while iterations == 0 or i < iterations:
        i += 1
        sample = sample_cpu()
        state.samples.append(sample)
        # Keep last 100 samples
        if len(state.samples) > 100:
            state.samples = state.samples[-100:]

        log(f"Sample #{i}: steal={sample.steal_pct:.1f}% "
            f"eff={sample.effective_pct:.1f}% "
            f"raw={sample.raw_pct:.1f}% "
            f"(user={sample.user_pct:.1f}% sys={sample.system_pct:.1f}% "
            f"iowait={sample.iowait_pct:.1f}%)")

        # --- Threshold logic ---
        if sample.steal_pct >= STEAL_THRESHOLD:
            log(f"Steal time {sample.steal_pct:.1f}% exceeds threshold "
                f"{STEAL_THRESHOLD}%", "WARN")

            # Step 1: identify top processes
            procs = get_top_processes()
            categories = classify_processes(procs)

            log("Top CPU processes:")
            for p in procs:
                cat = "MESH" if p in categories["mesh_node"] else \
                      "DB" if p in categories["database"] else "OTHER"
                log(f"  [{cat}] PID={p.pid} {p.name} "
                    f"cpu={p.cpu_pct:.1f}% mem={p.mem_pct:.1f}%")

            # Step 2: if mesh-node is the culprit → backoff
            mesh_cpu = sum(p.cpu_pct for p in categories["mesh_node"])
            if mesh_cpu > 30.0 or sample.steal_pct >= STEAL_CRITICAL:
                apply_backoff(state)
                log(f"Mesh-node processes consuming {mesh_cpu:.1f}% CPU — "
                    "applying diagnostics backoff", "WARN")
            else:
                # Step 3: non-mesh process — off-peak recommendation
                emit_offpeak_recommendation(procs)

            # Step 4: cgroup CPU limit (best-effort)
            try_cgroup_cpu_limit(state, sample.steal_pct)

            # Step 5: Proxmox recommendation (emit once per critical episode)
            if sample.steal_pct >= STEAL_CRITICAL and not state.proxmox_warning_emitted:
                emit_proxmox_recommendation(sample.steal_pct)
                state.proxmox_warning_emitted = True
            elif sample.steal_pct < STEAL_THRESHOLD:
                state.proxmox_warning_emitted = False

            state.last_mitigation = time.time()
            state.mitigation_count += 1

        elif sample.steal_pct < STEAL_THRESHOLD and state.backoff_active:
            # Steal normalised — release backoff
            if len(state.samples) >= 3:
                recent = state.samples[-3:]
                if all(s.steal_pct < STEAL_THRESHOLD for s in recent):
                    release_backoff(state)
                    try_cgroup_cpu_limit(state, sample.steal_pct)
                    state.proxmox_warning_emitted = False

        # Persist state and config
        state.save()
        save_mesh_config(state)

        # Adaptive sleep: use backoff interval if active
        sleep_time = state.diag_interval if state.backoff_active else interval
        # But for sampling we use the shorter interval; backoff affects
        # the mesh-node's own diagnostics, not this monitor's poll rate
        sleep_time = min(sleep_time, interval) if not state.backoff_active else interval
        time.sleep(sleep_time)

    log(f"Monitor finished after {i} iterations.")


# ---------------------------------------------------------------------------
# One-shot diagnostic report
# ---------------------------------------------------------------------------

def diagnostic_report() -> dict:
    """Produce a single-shot diagnostic report and print it."""
    state = StealState.load()
    sample = sample_cpu()
    procs = get_top_processes()
    categories = classify_processes(procs)

    report = {
        "idea_id": "idea_b4dce4819f5e",
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "cpu_sample": asdict(sample),
        "steal_threshold": STEAL_THRESHOLD,
        "steal_status": (
            "CRITICAL" if sample.steal_pct >= STEAL_CRITICAL
            else "HIGH" if sample.steal_pct >= STEAL_THRESHOLD
            else "OK"
        ),
        "top_processes": [asdict(p) for p in procs],
        "process_categories": {
            "mesh_node": [asdict(p) for p in categories["mesh_node"]],
            "database": [asdict(p) for p in categories["database"]],
            "other": [asdict(p) for p in categories["other"]],
        },
        "current_backoff": state.backoff_active,
        "diag_interval": state.diag_interval,
        "perf_samples": state.perf_samples,
        "mitigation_count": state.mitigation_count,
        "recommendations": [],
    }

    if sample.steal_pct >= STEAL_THRESHOLD:
        report["recommendations"].append(
            "Apply diagnostics backoff (interval→600s, samples→30)"
            if categories["mesh_node"]
            else "Reschedule non-mesh heavy tasks to off-peak"
        )
        report["recommendations"].append(
            "Set cgroup CPU limit during high-steal periods"
        )
    if sample.steal_pct >= STEAL_CRITICAL:
        report["recommendations"].append(
            "PROXMOX: CPU pinning / reduce VM count / upgrade host"
        )

    print(json.dumps(report, indent=2))
    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="CPU Steal Time Monitor for A2A Mesh (runa node)"
    )
    parser.add_argument(
        "--mode", choices=["monitor", "report", "status"],
        default="report",
        help="monitor=continuous, report=one-shot diagnostic, status=show state"
    )
    parser.add_argument(
        "--interval", type=float, default=60.0,
        help="Sampling interval in seconds (monitor mode)"
    )
    parser.add_argument(
        "--iterations", type=int, default=0,
        help="Number of iterations (0=infinite, monitor mode)"
    )
    parser.add_argument(
        "--threshold", type=float, default=STEAL_THRESHOLD,
        help="Steal time threshold %%"
    )

    args = parser.parse_args()

    global STEAL_THRESHOLD
    STEAL_THRESHOLD = args.threshold

    if args.mode == "monitor":
        run_monitor(iterations=args.iterations, interval=args.interval)
    elif args.mode == "report":
        diagnostic_report()
    elif args.mode == "status":
        state = StealState.load()
        print(json.dumps({
            "backoff_active": state.backoff_active,
            "diag_interval": state.diag_interval,
            "perf_samples": state.perf_samples,
            "mitigation_count": state.mitigation_count,
            "cgroup_limit_set": state.cgroup_limit_set,
            "recent_samples": [asdict(s) for s in state.samples[-10:]],
        }, indent=2))


if __name__ == "__main__":
    main()