#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
Session DB: SQLite → PG (mesh-wide online status)

Migrates per-node SQLite session storage to PostgreSQL so that
all mesh nodes share a single session table. This enables
mesh-wide online status: when a user logs in on Runa's dashboard,
Nova (and every other node) can see the WS connection state via
_broadcast_session_update.

This module provides:
  - PgSessionStore: PostgreSQL-backed session store (replaces SQLite)
  - SessionManager: high-level create/validate/destroy + online status
  - SQLite migration helper (reads existing ~/.hermes/mesh_users.db
    and imports sessions into PG)
  - A standalone HTTP+WS server for testing mesh-wide online status

Run from repo root:
    python session_pg.py
"""

from __future__ import annotations

import os
import sys
import json
import time
import uuid
import asyncio
import sqlite3
import logging
import hashlib
import secrets
from dataclasses import dataclass, asdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

try:
    import asyncpg
except ImportError:
    print("ERROR: asyncpg is required. Install with: pip install asyncpg", file=sys.stderr)
    sys.exit(1)

try:
    from aiohttp import web, WSMsgType
except ImportError:
    print("ERROR: aiohttp is required. Install with: pip install aiohttp", file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)
log = logging.getLogger("session_pg")

# PG connection — read from env or use defaults
PG_DSN = os.environ.get(
    "MESH_PG_DSN",
    "postgresql://mesh:mesh@localhost:5432/a2a_mesh",
)

# Node identity — each mesh node has a unique id
NODE_ID = os.environ.get("MESH_NODE_ID", "node_local")

# Session expiry in seconds (default 24h)
SESSION_TTL = int(os.environ.get("MESH_SESSION_TTL", str(60 * 60 * 24)))

# SQLite path to migrate from
SQLITE_PATH = Path(
    os.environ.get("MESH_SQLITE_PATH", str(Path.home() / ".hermes" / "mesh_users.db"))
)

# HTTP/WS listen
HTTP_HOST = os.environ.get("MESH_HTTP_HOST", "0.0.0.0")
HTTP_PORT = int(os.environ.get("MESH_HTTP_PORT", "8765"))


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Session:
    """Represents a user session stored in PG."""
    session_id: str
    user_id: str
    username: str
    node_id: str
    created_at: float
    expires_at: float
    last_seen: float
    ws_connected: bool = False
    metadata: str = "{}"

    def is_expired(self) -> bool:
        return time.time() > self.expires_at

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["metadata"] = json.loads(d["metadata"]) if d["metadata"] else {}
        d["online"] = self.ws_connected and not self.is_expired()
        return d


# ---------------------------------------------------------------------------
# PgSessionStore — replaces SQLite session storage
# ---------------------------------------------------------------------------

class PgSessionStore:
    """
    PostgreSQL-backed session store.

    Schema (created automatically):
        mesh_sessions (
            session_id   TEXT PRIMARY KEY,
            user_id      TEXT NOT NULL,
            username     TEXT NOT NULL,
            node_id      TEXT NOT NULL,
            created_at   DOUBLE PRECISION NOT NULL,
            expires_at   DOUBLE PRECISION NOT NULL,
            last_seen    DOUBLE PRECISION NOT NULL,
            ws_connected BOOLEAN NOT NULL DEFAULT FALSE,
            metadata     JSONB NOT NULL DEFAULT '{}'::jsonb
        )
        mesh_users (
            user_id    TEXT PRIMARY KEY,
            username   TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at DOUBLE PRECISION NOT NULL
        )
    """

    SCHEMA_SQL = """
    CREATE TABLE IF NOT EXISTS mesh_users (
        user_id        TEXT PRIMARY KEY,
        username       TEXT UNIQUE NOT NULL,
        password_hash  TEXT NOT NULL,
        created_at     DOUBLE PRECISION NOT NULL
    );

    CREATE TABLE IF NOT EXISTS mesh_sessions (
        session_id     TEXT PRIMARY KEY,
        user_id        TEXT NOT NULL REFERENCES mesh_users(user_id) ON DELETE CASCADE,
        username       TEXT NOT NULL,
        node_id        TEXT NOT NULL,
        created_at     DOUBLE PRECISION NOT NULL,
        expires_at     DOUBLE PRECISION NOT NULL,
        last_seen      DOUBLE PRECISION NOT NULL,
        ws_connected   BOOLEAN NOT NULL DEFAULT FALSE,
        metadata       JSONB NOT NULL DEFAULT '{}'::jsonb
    );

    CREATE INDEX IF NOT EXISTS idx_sessions_user_id    ON mesh_sessions(user_id);
    CREATE INDEX IF NOT EXISTS idx_sessions_node_id    ON mesh_sessions(node_id);
    CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON mesh_sessions(expires_at);
    CREATE INDEX IF NOT EXISTS idx_sessions_ws_connected ON mesh_sessions(ws_connected);

    CREATE TABLE IF NOT EXISTS mesh_node_heartbeats (
        node_id     TEXT PRIMARY KEY,
        last_heartbeat DOUBLE PRECISION NOT NULL,
        metadata    JSONB NOT NULL DEFAULT '{}'::jsonb
    );
    """

    def __init__(self, dsn: str, node_id: str):
        self.dsn = dsn
        self.node_id = node_id
        self.pool: Optional[asyncpg.Pool] = None

    async def connect(self) -> None:
        """Create connection pool and ensure schema exists."""
        self.pool = await asyncpg.create_pool(
            self.dsn,
            min_size=2,
            max_size=10,
            command_timeout=30,
        )
        async with self.pool.acquire() as conn:
            await conn.execute(self.SCHEMA_SQL)
        log.info("PgSessionStore connected to %s (node=%s)", self.dsn, self.node_id)

    async def close(self) -> None:
        if self.pool:
            await self.pool.close()
            self.pool = None
        log.info("PgSessionStore closed")

    # -- User management --------------------------------------------------

    async def create_user(self, username: str, password: str) -> str:
        """Create a user in mesh_users. Returns user_id."""
        user_id = str(uuid.uuid4())
        pw_hash = self._hash_password(password)
        async with self.pool.acquire() as conn:
            try:
                await conn.execute(
                    "INSERT INTO mesh_users (user_id, username, password_hash, created_at) "
                    "VALUES ($1, $2, $3, $4)",
                    user_id, username, pw_hash, time.time(),
                )
            except asyncpg.UniqueViolationError:
                raise ValueError(f"Username '{username}' already exists")
        log.info("Created user '%s' (id=%s)", username, user_id)
        return user_id

    async def verify_user(self, username: str, password: str) -> Optional[str]:
        """Verify credentials. Returns user_id if valid, None otherwise."""
        async with self.pool.acquire() as conn:
            row = await conn.fetchrow(
                "SELECT user_id, password_hash FROM mesh_users WHERE username = $1",
                username,
            )
        if not row:
            return None
        if not self._verify_password(password, row["password_hash"]):
            return None
        return row["user_id"]

    async def get_user(self, user_id: str) -> Optional[Dict[str, Any]]:
        async with self.pool.acquire() as conn:
            row = await conn.fetchrow(
                "SELECT user_id, username, created_at FROM mesh_users WHERE user_id = $1",
                user_id,
            )
        if not row:
            return None
        return dict(row)

    # -- Session management -----------------------------------------------

    async def create_session(
        self,
        user_id: str,
        username: str,
        ttl: int = SESSION_TTL,
        metadata: Optional[Dict] = None,
    ) -> Session:
        """Create a new session in PG. Visible mesh-wide."""
        session_id = secrets.token_urlsafe(32)
        now = time.time()
        session = Session(
            session_id=session_id,
            user_id=user_id,
            username=username,
            node_id=self.node_id,
            created_at=now,
            expires_at=now + ttl,
            last_seen=now,
            ws_connected=False,
            metadata=json.dumps(metadata or {}),
        )
        async with self.pool.acquire() as conn:
            await conn.execute(
                "INSERT INTO mesh_sessions "
                "(session_id, user_id, username, node_id, created_at, expires_at, "
                " last_seen, ws_connected, metadata) "
                "VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::jsonb)",
                session.session_id, session.user_id, session.username,
                session.node_id, session.created_at, session.expires_at,
                session.last_seen, session.ws_connected, session.metadata,
            )
        log.info("Created session %s for user '%s' on node '%s'",
                 session_id[:12], username, self.node_id)
        return session

    async def get_session(self, session_id: str) -> Optional[Session]:
        """Fetch a session by ID from PG."""
        async with self.pool.acquire() as conn:
            row = await conn.fetchrow(
                "SELECT session_id, user_id, username, node_id, created_at, "
                "       expires_at, last_seen, ws_connected, metadata::text "
                "FROM mesh_sessions WHERE session_id = $1",
                session_id,
            )
        if not row:
            return None
        return Session(
            session_id=row["session_id"],
            user_id=row["user_id"],
            username=row["username"],
            node_id=row["node_id"],
            created_at=row["created_at"],
            expires_at=row["expires_at"],
            last_seen=row["last_seen"],
            ws_connected=row["ws_connected"],
            metadata=row["metadata"],
        )

    async def validate_session(self, session_id: str) -> Optional[Session]:
        """Validate and touch a session. Returns Session if valid, None if expired/missing."""
        session = await self.get_session(session_id)
        if not session:
            return None
        if session.is_expired():
            await self.destroy_session(session_id)
            return None
        # Touch last_seen
        now = time.time()
        async with self.pool.acquire() as conn:
            await conn.execute(
                "UPDATE mesh_sessions SET last_seen = $1 WHERE session_id = $2",
                now, session_id,
            )
        session.last_seen = now
        return session

    async def destroy_session(self, session_id: str) -> bool:
        """Delete a session from PG."""
        async with self.pool.acquire() as conn:
            result = await conn.execute(
                "DELETE FROM mesh_sessions WHERE session_id = $1",
                session_id,
            )
        deleted = result.endswith("1")
        if deleted:
            log.info("Destroyed session %s", session_id[:12])
        return deleted

    async def set_ws_connected(self, session_id: str, connected: bool) -> None:
        """Update WS connection state — visible to all nodes."""
        async with self.pool.acquire() as conn:
            await conn.execute(
                "UPDATE mesh_sessions SET ws_connected = $1, last_seen = $2 "
                "WHERE session_id = $3",
                connected, time.time(), session_id,
            )

    async def get_online_sessions(self) -> List[Session]:
        """Get all sessions with active WS connections (mesh-wide)."""
        now = time.time()
        async with self.pool.acquire() as conn:
            rows = await conn.fetch(
                "SELECT session_id, user_id, username, node_id, created_at, "
                "       expires_at, last_seen, ws_connected, metadata::text "
                "FROM mesh_sessions "
                "WHERE ws_connected = TRUE AND expires_at > $1 "
                "ORDER BY username",
                now,
            )
        return [
            Session(
                session_id=r["session_id"],
                user_id=r["user_id"],
                username=r["username"],
                node_id=r["node_id"],
                created_at=r["created_at"],
                expires_at=r["expires_at"],
                last_seen=r["last_seen"],
                ws_connected=r["ws_connected"],
                metadata=r["metadata"],
            )
            for r in rows
        ]

    async def get_online_users(self) -> List[Dict[str, Any]]:
        """Get distinct online users (mesh-wide)."""
        sessions = await self.get_online_sessions()
        seen: Dict[str, Dict[str, Any]] = {}
        for s in sessions:
            if s.user_id not in seen:
                seen[s.user_id] = {
                    "user_id": s.user_id,
                    "username": s.username,
                    "nodes": [],
                    "session_count": 0,
                }
            seen[s.user_id]["nodes"].append(s.node_id)
            seen[s.user_id]["session_count"] += 1
        return list(seen.values())

    async def get_sessions_for_node(self, node_id: str) -> List[Session]:
        """Get all sessions belonging to a specific node."""
        async with self.pool.acquire() as conn:
            rows = await conn.fetch(
                "SELECT session_id, user_id, username, node_id, created_at, "
                "       expires_at, last_seen, ws_connected, metadata::text "
                "FROM mesh_sessions WHERE node_id = $1 AND expires_at > $2",
                node_id, time.time(),
            )
        return [
            Session(
                session_id=r["session_id"],
                user_id=r["user_id"],
                username=r["username"],
                node_id=r["node_id"],
                created_at=r["created_at"],
                expires_at=r["expires_at"],
                last_seen=r["last_seen"],
                ws_connected=r["ws_connected"],
                metadata=r["metadata"],
            )
            for r in rows
        ]

    async def cleanup_expired(self) -> int:
        """Remove expired sessions. Returns count deleted."""
        now = time.time()
        async with self.pool.acquire() as conn:
            result = await conn.execute(
                "DELETE FROM mesh_sessions WHERE expires_at < $1",
                now,
            )
        count = int(result.split()[-1]) if result else 0
        if count:
            log.info("Cleaned up %d expired sessions", count)
        return count

    async def update_node_heartbeat(self, node_id: str, metadata: Optional[Dict] = None) -> None:
        """Upsert node heartbeat."""
        async with self.pool.acquire() as conn:
            await conn.execute(
                "INSERT INTO mesh_node_heartbeats (node_id, last_heartbeat, metadata) "
                "VALUES ($1, $2, $3::jsonb) "
                "ON CONFLICT (node_id) DO UPDATE SET "
                "  last_heartbeat = EXCLUDED.last_heartbeat, "
                "  metadata = EXCLUDED.metadata",
                node_id, time.time(), json.dumps(metadata or {}),
            )

    async def get_active_nodes(self, max_age: float = 60.0) -> List[Dict[str, Any]]:
        """Get nodes that have sent heartbeat within max_age seconds."""
        cutoff = time.time() - max_age
        async with self.pool.acquire() as conn:
            rows = await conn.fetch(
                "SELECT node_id, last_heartbeat, metadata::text "
                "FROM mesh_node_heartbeats WHERE last_heartbeat > $1",
                cutoff,
            )
        return [
            {
                "node_id": r["node_id"],
                "last_heartbeat": r["last_heartbeat"],
                "metadata": json.loads(r["metadata"]) if r["metadata"] else {},
            }
            for r in rows
        ]

    # -- Password helpers -------------------------------------------------

    @staticmethod
    def _hash_password(password: str) -> str:
        salt = secrets.token_hex(16)
        h = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 100_000)
        return f"pbkdf2_sha256${salt}${h.hex()}"

    @staticmethod
    def _verify_password(password: str, stored: str) -> bool:
        try:
            algo, salt, hash_hex = stored.split("$", 2)
        except ValueError:
            return False
        if algo != "pbkdf2_sha256":
            return False
        h = hashlib.pbkdf2_hmac("sha256", password.encode(), salt.encode(), 100_000)
        return secrets.compare_digest(h.hex(), hash_hex)


# ---------------------------------------------------------------------------
# SQLite → PG migration
# ---------------------------------------------------------------------------

async def migrate_sqlite_to_pg(store: PgSessionStore, sqlite_path: Path) -> int:
    """
    Read existing sessions from per-node SQLite and import into PG.
    Returns number of sessions migrated.
    """
    if not sqlite_path.exists():
        log.info("SQLite DB not found at %s — skipping migration", sqlite_path)
        return 0

    log.info("Migrating sessions from SQLite (%s) to PG...", sqlite_path)
    count = 0

    conn_sqlite = sqlite3.connect(str(sqlite_path))
    conn_sqlite.row_factory = sqlite3.Row

    # Try to read users
    try:
        cursor = conn_sqlite.execute(
            "SELECT user_id, username, password_hash, created_at FROM mesh_users"
        )
        users = cursor.fetchall()
        for u in users:
            try:
                async with store.pool.acquire() as pg_conn:
                    await pg_conn.execute(
                        "INSERT INTO mesh_users (user_id, username, password_hash, created_at) "
                        "VALUES ($1, $2, $3, $4) ON CONFLICT (user_id) DO NOTHING",
                        u["user_id"], u["username"], u["password_hash"], u["created_at"],
                    )
            except Exception as e:
                log.warning("Could not migrate user '%s': %s", u["username"], e)
        log.info("Migrated %d users from SQLite", len(users))
    except sqlite3.OperationalError:
        log.info("No mesh_users table in SQLite — creating fresh")

    # Try to read sessions
    try:
        cursor = conn_sqlite.execute(
            "SELECT session_id, user_id, username, node_id, created_at, "
            "       expires_at, last_seen, ws_connected, metadata "
            "FROM mesh_sessions"
        )
        sessions = cursor.fetchall()
        for s in sessions:
            try:
                async with store.pool.acquire() as pg_conn:
                    await pg_conn.execute(
                        "INSERT INTO mesh_sessions "
                        "(session_id, user_id, username, node_id, created_at, "
                        " expires_at, last_seen, ws_connected, metadata) "
                        "VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::jsonb) "
                        "ON CONFLICT (session_id) DO NOTHING",
                        s["session_id"], s["user_id"], s["username"],
                        s["node_id"] or NODE_ID, s["created_at"], s["expires_at"],
                        s["last_seen"], bool(s["ws_connected"]),
                        s["metadata"] if s["metadata"] else "{}",
                    )
                count += 1
            except Exception as e:
                log.warning("Could not migrate session %s: %s", s["session_id"][:12], e)
    except sqlite3.OperationalError:
        log.info("No mesh_sessions table in SQLite — nothing to migrate")

    conn_sqlite.close()
    log.info("Migration complete: %d sessions imported", count)
    return count


# ---------------------------------------------------------------------------
# SessionManager — high-level orchestration with WS broadcast
# ---------------------------------------------------------------------------

class SessionManager:
    """
    High-level session manager that wraps PgSessionStore and handles
    mesh-wide online status broadcasting via WebSocket fan-out.
    """

    def __init__(self, store: PgSessionStore):
        self.store = store
        # Local WS connections: session_id -> web.WebSocketResponse
        self.ws_connections: Dict[str, web.WebSocketResponse] = {}
        # Subscribed WS clients that want online-status updates
        self.status_subscribers: Set[web.WebSocketResponse] = set()
        self._cleanup_task: Optional[asyncio.Task] = None
        self._heartbeat_task: Optional[asyncio.Task] = None

    async def start(self) -> None:
        """Start background tasks."""
        self._cleanup_task = asyncio.create_task(self._cleanup_loop())
        self._heartbeat_task = asyncio.create_task(self._heartbeat_loop())
        log.info("SessionManager started (node=%s)", self.store.node_id)

    async def stop(self) -> None:
        """Stop background tasks and close all WS."""
        if self._cleanup_task:
            self._cleanup_task.cancel()
        if self._heartbeat_task:
            self._heartbeat_task.cancel()
        # Close all WS
        for ws in list(self.ws_connections.values()):
            try:
                await ws.close()
            except Exception:
                pass
        for ws in list(self.status_subscribers):
            try:
                await ws.close()
            except Exception:
                pass
        self.ws_connections.clear()
        self.status_subscribers.clear()
        log.info("SessionManager stopped")

    async def login(self, username: str, password: str) -> Optional[Session]:
        """Authenticate and create a session."""
        user_id = await self.store.verify_user(username, password)
        if not user_id:
            log.warning("Login failed for user '%s'", username)
            return None
        session = await self.store.create_session(user_id, username)
        await self._broadcast_session_update("login", session)
        return session

    async def logout(self, session_id: str) -> bool:
        """Destroy a session and broadcast."""
        session = await self.store.get_session(session_id)
        if not session:
            return False
        # Close local WS if any
        ws = self.ws_connections.pop(session_id, None)
        if ws and not ws.closed:
            await ws.close()
        await self.store.destroy_session(session_id)
        await self._broadcast_session_update("logout", session)
        return True

    async def register_ws(self, session_id: str, ws: web.WebSocketResponse) -> bool:
        """Register a WebSocket connection for a session."""
        session = await self.store.validate_session(session_id)
        if not session:
            return False
        self.ws_connections[session_id] = ws
        await self.store.set_ws_connected(session_id, True)
        await self._broadcast_session_update("ws_connect", session)
        return True

    async def unregister_ws(self, session_id: str) -> None:
        """Unregister a WebSocket connection."""
        self.ws_connections.pop(session_id, None)
        await self.store.set_ws_connected(session_id, False)
        session = await self.store.get_session(session_id)
        if session:
            await self._broadcast_session_update("ws_disconnect", session)

    async def subscribe_status(self, ws: web.WebSocketResponse) -> None:
        """Subscribe a WS client to receive online-status updates."""
        self.status_subscribers.add(ws)
        # Send current online state immediately
        online = await self.store.get_online_users()
        await self._safe_send(ws, {
            "type": "online_status",
            "action": "snapshot",
            "online_users": online,
            "node_id": self.store.node_id,
            "timestamp": time.time(),
        })

    def unsubscribe_status(self, ws: web.WebSocketResponse) -> None:
        self.status_subscribers.discard(ws)

    async def _broadcast_session_update(
        self, action: str, session: Session
    ) -> None:
        """
        Broadcast a session update to all subscribed WS clients.
        Because sessions are in PG, every node sees the same state.
        """
        online = await self.store.get_online_users()
        message = {
            "type": "online_status",
            "action": action,
            "session": session.to_dict(),
            "online_users": online,
            "node_id": self.store.node_id,
            "timestamp": time.time(),
        }
        # Fan-out to local subscribers
        dead: List[web.WebSocketResponse] = []
        for ws in self.status_subscribers:
            if ws.closed:
                dead.append(ws)
                continue
            await self._safe_send(ws, message)
        for ws in dead:
            self.status_subscribers.discard(ws)

    async def _safe_send(self, ws: web.WebSocketResponse, msg: Dict) -> None:
        try:
            await ws.send_json(msg)
        except Exception as e:
            log.debug("WS send failed: %s", e)

    async def _cleanup_loop(self) -> None:
        """Periodically clean up expired sessions."""
        while True:
            try:
                await asyncio.sleep(300)  # every 5 minutes
                await self.store.cleanup_expired()
            except asyncio.CancelledError:
                break
            except Exception as e:
                log.error("Cleanup error: %s", e)

    async def _heartbeat_loop(self) -> None:
        """Periodically send node heartbeat to PG."""
        while True:
            try:
                await asyncio.sleep(15)
                await self.store.update_node_heartbeat(
                    self.store.node_id,
                    {"ws_count": len(self.ws_connections)},
                )
            except asyncio.CancelledError:
                break
            except Exception as e:
                log.error("Heartbeat error: %s", e)


# ---------------------------------------------------------------------------
# HTTP + WebSocket server (standalone, for testing / dashboard integration)
# ---------------------------------------------------------------------------

INDEX_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>A2A Mesh — Session PG (mesh-wide online status)</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #0d1117; color: #c9d1d9; padding: 2rem; }
h1 { color: #58a6ff; margin-bottom: 1rem; font-size: 1.5rem; }
h2 { color: #8b949e; font-size: 1.1rem; margin: 1.5rem 0 0.5rem; }
.card { background: #161b22; border: 1px solid #30363d; border-radius: 8px;
        padding: 1.5rem; margin-bottom: 1rem; }
input, button { padding: 0.6rem 1rem; border-radius: 6px; border: 1px solid #30363d;
                background: #0d1117; color: #c9d1d9; font-size: 0.9rem; }
input { width: 200px; margin-right: 0.5rem; }
button { cursor: pointer; background: #238636; border-color: #238636; color: #fff; }
button:hover { background: #2ea043; }
button.secondary { background: #21262d; border-color: #30363d; }
button.secondary:hover { background: #30363d; }
.row { display: flex; gap: 0.5rem; align-items: center; margin-bottom: 0.5rem; flex-wrap: wrap; }
.status-dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
.online { background: #3fb950; }
.offline { background: #484f58; }
.user-list { list-style: none; }
.user-list li { padding: 0.5rem; border-bottom: 1px solid #21262d;
                display: flex; align-items: center; gap: 0.5rem; }
.badge { font-size: 0.75rem; padding: 2px 8px; border-radius: 12px;
         background: #1f6feb; color: #fff; }
.node-badge { background: #6e7681; }
#log { background: #0d1117; border: 1px solid #30363d; border-radius: 6px;
       padding: 1rem; height: 200px; overflow-y: auto; font-family: monospace;
       font-size: 0.8rem; color: #8b949e; }
.log-entry { margin-bottom: 4px; }
.log-entry .ts { color: #484f58; }
.info { color: #58a6ff; }
.success { color: #3fb950; }
.warn { color: #d29922; }
.error { color: #f85149; }
.session-info { font-size: 0.8rem; color: #8b949e; margin-top: 0.5rem; }
</style>
</head>
<body>
<h1>A2A Mesh — Session PG</h1>
<p style="color:#8b949e;margin-bottom:1rem;">
  Mesh-wide online status via PostgreSQL session store.
  Node: <span class="badge" id="nodeId">—</span>
</p>

<div class="card">
  <h2>Register New User</h2>
  <div class="row">
    <input type="text" id="regUser" placeholder="username">
    <input type="password" id="regPass" placeholder="password">
    <button onclick="register()">Register</button>
  </div>
</div>

<div class="card">
  <h2>Login</h2>
  <div class="row">
    <input type="text" id="loginUser" placeholder="username">
    <input type="password" id="loginPass" placeholder="password">
    <button onclick="login()">Login</button>
    <button class="secondary" onclick="logout()">Logout</button>
  </div>
  <div class="session-info" id="sessionInfo">No active session.</div>
</div>

<div class="card">
  <h2>Online Users (mesh-wide)</h2>
  <ul class="user-list" id="userList">
    <li><span class="status-dot offline"></span> Loading...</li>
  </ul>
</div>

<div class="card">
  <h2>Event Log</h2>
  <div id="log"></div>
</div>

<script>
let sessionId = null;
let ws = null;

function log(msg, level) {
  const el = document.getElementById('log');
  const entry = document.createElement('div');
  entry.className = 'log-entry';
  const ts = new Date().toLocaleTimeString();
  entry.innerHTML = '<span class="ts">[' + ts + ']</span> ' +
    '<span class="' + (level||'info') + '">' + msg + '</span>';
  el.prepend(entry);
}

function connectStatusWS() {
  const proto = location.protocol === 'https:' ? 'wss' : 'ws';
  ws = new WebSocket(proto + '://' + location.host + '/ws/status');
  ws.onopen = () => log('Status WS connected', 'success');
  ws.onmessage = (e) => {
    const data = JSON.parse(e.data);
    if (data.type === 'online_status') {
      renderOnlineUsers(data.online_users);
      if (data.action === 'login') log('User ' + data.session.username + ' logged in on node ' + data.session.node_id, 'success');
      if (data.action === 'logout') log('User ' + data.session.username + ' logged out', 'warn');
      if (data.action === 'ws_connect') log('WS connected: ' + data.session.username + ' @ ' + data.session.node_id, 'success');
      if (data.action === 'ws_disconnect') log('WS disconnected: ' + data.session.username + ' @ ' + data.session.node_id, 'warn');
    }
  };
  ws.onclose = () => { log('Status WS closed, reconnecting...', 'warn'); setTimeout(connectStatusWS, 3000); };
  ws.onerror = () => log('Status WS error', 'error');
}

function renderOnlineUsers(users) {
  const el = document.getElementById('userList');
  if (!users || users.length === 0) {
    el.innerHTML = '<li><span class="status-dot offline"></span> No users online</li>';
    return;
  }
  el.innerHTML = users.map(u => {
    const nodes = u.nodes.map(n => '<span class="badge node-badge">' + n + '</span>').join(' ');
    return '<li><span class="status-dot online"></span> <strong>' + u.username +
           '</strong> ' + nodes +
           ' <span style="color:#484f58;font-size:0.8rem">(' + u.session_count + ' session' + (u.session_count>1?'s':'') + ')</span></li>';
  }).join('');
}

async function register() {
  const username = document.getElementById('regUser').value.trim();
  const password = document.getElementById('regPass').value;
  if (!username || !password) { log('Enter username and password', 'warn'); return; }
  const res = await fetch('/api/register', {
    method: 'POST', headers: {'Content-Type':'application/json'},
    body: JSON.stringify({username, password})
  });
  const data = await res.json();
  if (data.ok) { log('Registered user: ' + username, 'success'); }
  else { log('Register failed: ' + data.error, 'error'); }
}

async function login() {
  const username = document.getElementById('loginUser').value.trim();
  const password = document.getElementById('loginPass').value;
  if (!username || !password) { log('Enter username and password', 'warn'); return; }
  const res = await fetch('/api/login', {
    method: 'POST', headers: {'Content-Type':'application/json'},
    body: JSON.stringify({username, password})
  });
  const data = await res.json();
  if (data.ok) {
    sessionId = data.session_id;
    document.getElementById('sessionInfo').textContent =
      'Session: ' + sessionId.substring(0,16) + '... | User: ' + data.username;
    log('Login successful: ' + data.username, 'success');
    connectSessionWS();
  } else { log('Login failed: ' + data.error, 'error'); }
}

async function logout() {
  if (!sessionId) { log('No active session', 'warn'); return; }
  const res = await fetch('/api/logout', {
    method: 'POST', headers: {'Content-Type':'application/json'},
    body: JSON.stringify({session_id: sessionId})
  });
  const data = await res.json();
  if (data.ok) {
    log('Logged out', 'success');
    sessionId = null;
    document.getElementById('sessionInfo').textContent = 'No active session.';
  }
}

function connectSessionWS() {
  if (!sessionId) return;
  const proto = location.protocol === 'https:' ? 'wss' : 'ws';
  const sws = new WebSocket(proto + '://' + location.host + '/ws/session?sid=' + sessionId);
  sws.onopen = () => log('Session WS connected (online status active)', 'success');
  sws.onclose = () => { log('Session WS closed', 'warn'); if (sessionId) { sessionId = null;
    document.getElementById('sessionInfo').textContent = 'No active session.'; } };
  sws.onerror = () => log('Session WS error', 'error');
}

// Init
fetch('/api/info').then(r => r.json()).then(d => {
  document.getElementById('nodeId').textContent = d.node_id;
});
connectStatusWS();
log('Dashboard initialized', 'info');
</script>
</body>
</html>"""


class SessionServer:
    """HTTP + WebSocket server for session management and online status."""

    def __init__(self, store: PgSessionStore, manager: SessionManager):
        self.store = store
        self.manager = manager
        self.app = web.Application()
        self._setup_routes()

    def _setup_routes(self) -> None:
        self.app.add_routes([
            web.get("/", self.index),
            web.get("/api/info", self.api_info),
            web.post("/api/register", self.api_register),
            web.post("/api/login", self.api_login),
            web.post("/api/logout", self.api_logout),
            web.get("/api/online", self.api_online),
            web.get("/api/sessions", self.api_sessions),
            web.get("/ws/status", self.ws_status),
            web.get("/ws/session", self.ws_session),
        ])
        self.app.on_cleanup.append(self._on_cleanup)

    async def _on_cleanup(self, app: web.Application) -> None:
        await self.manager.stop()
        await self.store.close()

    # -- HTTP handlers ----------------------------------------------------

    async def index(self, request: web.Request) -> web.Response:
        return web.Response(text=INDEX_HTML, content_type="text/html")

    async def api_info(self, request: web.Request) ->