#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
PG replica slot auto-heal: a meglévő slot-monitorozás kapjon auto-create lépést
(runa_replica / nova_replica) + WAL-validációt.

Ez a modul:
  1. Lekérdezi a meglévő logikai/fizikai replikációs slotokat a cél PG-n.
  2. Ellenőrzi, hogy az elvárt slotok (runa_replica, nova_replica) léteznek-e.
  3. Ha hiányzik -> auto-create logical slot (vagy physical, ha a config mondja).
  4. WAL-validáció: ha egy slot restart_lsn-je lemaradt, vagy a WAL már nem
     elérhető (retained < required), jelez + próbál advance-et.
  5. Ha egy slot inactive és a wal_status 'lost' -> drop + recreate.
  6. JSON reportot ír a stdout-ra, amit a mesh agent fel tud dolgozni.

Futtatható önállóan a repó gyökeréből:
    python tools/pg_slot_autoheal.py
vagy env-változókkal:
    PG_SLOT_HOST=... PG_SLOT_PORT=5432 PG_SLOT_DB=replica \
    PG_SLOT_USER=replicator PG_SLOT_PASSWORD=... \
    python tools/pg_slot_autoheal.py
"""

from __future__ import annotations

import os
import sys
import json
import time
import logging
import argparse
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

try:
    import psycopg2  # type: ignore
    from psycopg2.extras import RealDictCursor  # type: ignore
except ImportError:
    print(
        "ERROR: psycopg2 not installed. Run: pip install psycopg2-binary",
        file=sys.stderr,
    )
    sys.exit(2)

LOG = logging.getLogger("pg_slot_autoheal")

# ---------------------------------------------------------------------------
# Konfiguráció
# ---------------------------------------------------------------------------

DEFAULT_EXPECTED_SLOTS = ["runa_replica", "nova_replica"]

DEFAULT_CONFIG: Dict[str, Any] = {
    "host": os.environ.get("PG_SLOT_HOST", "localhost"),
    "port": int(os.environ.get("PG_SLOT_PORT", "5432")),
    "dbname": os.environ.get("PG_SLOT_DB", "postgres"),
    "user": os.environ.get("PG_SLOT_USER", "replicator"),
    "password": os.environ.get("PG_SLOT_PASSWORD", ""),
    "expected_slots": os.environ.get(
        "PG_SLOT_EXPECTED", ",".join(DEFAULT_EXPECTED_SLOTS)
    ).split(","),
    "slot_type": os.environ.get("PG_SLOT_TYPE", "logical"),  # logical | physical
    "plugin": os.environ.get("PG_SLOT_PLUGIN", "pgoutput"),
    "dry_run": os.environ.get("PG_SLOT_DRY_RUN", "0") == "1",
    "wal_max_lag_mb": int(os.environ.get("PG_SLOT_WAL_MAX_LAG_MB", "2048")),
    "max_recreate_attempts": int(os.environ.get("PG_SLOT_MAX_RECREATE", "2")),
    "connect_timeout": int(os.environ.get("PG_SLOT_CONNECT_TIMEOUT", "10")),
}


# ---------------------------------------------------------------------------
# Adatstruktúrák
# ---------------------------------------------------------------------------

@dataclass
class SlotInfo:
    slot_name: str
    slot_type: str
    plugin: Optional[str]
    database: Optional[str]
    active: bool
    restart_lsn: Optional[str]
    confirmed_flush_lsn: Optional[str]
    wal_status: str  # reserved | extended | unreserved | lost
    safe_wal_size: Optional[int]
    two_phase: bool

    @classmethod
    def from_row(cls, row: Dict[str, Any]) -> "SlotInfo":
        return cls(
            slot_name=row["slot_name"],
            slot_type=row["slot_type"],
            plugin=row.get("plugin"),
            database=row.get("database"),
            active=bool(row.get("active", False)),
            restart_lsn=row.get("restart_lsn"),
            confirmed_flush_lsn=row.get("confirmed_flush_lsn"),
            wal_status=row.get("wal_status", "unknown"),
            safe_wal_size=row.get("safe_wal_size"),
            two_phase=bool(row.get("two_phase", False)),
        )


@dataclass
class HealAction:
    action: str  # create | drop_recreate | advance | noop | alert
    slot_name: str
    detail: str
    success: bool = False
    error: Optional[str] = None


@dataclass
class HealReport:
    timestamp: float
    host: str
    db: str
    expected_slots: List[str]
    found_slots: List[str]
    missing_slots: List[str]
    lost_slots: List[str]
    actions: List[HealAction] = field(default_factory=list)
    healthy: bool = True
    dry_run: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "host": self.host,
            "db": self.db,
            "expected_slots": self.expected_slots,
            "found_slots": self.found_slots,
            "missing_slots": self.missing_slots,
            "lost_slots": self.lost_slots,
            "healthy": self.healthy,
            "dry_run": self.dry_run,
            "actions": [asdict(a) for a in self.actions],
        }


# ---------------------------------------------------------------------------
# DB kapcsolat
# ---------------------------------------------------------------------------

def connect(cfg: Dict[str, Any]):
    return psycopg2.connect(
        host=cfg["host"],
        port=cfg["port"],
        dbname=cfg["dbname"],
        user=cfg["user"],
        password=cfg["password"],
        connect_timeout=cfg["connect_timeout"],
    )


def is_replication_role(conn) -> bool:
    """Ellenőrzi, hogy a felhasználó rendelkezik-e REPLICATION/SUPERUSER jogosultsággal."""
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(
            """
            SELECT pg_catalog.has_database_privilege(current_user, current_database(), 'CREATE') AS can_create,
                   (SELECT rolreplication FROM pg_roles WHERE rolname = current_user) AS is_replication,
                   (SELECT rolsuper FROM pg_roles WHERE rolname = current_user) AS is_super,
                   current_setting('wal_level') AS wal_level
            """
        )
        row = cur.fetchone()
        return bool(
            row and (row["is_replication"] or row["is_super"])
            and row["wal_level"] in ("logical", "replica")
        )


def fetch_slots(conn) -> List[SlotInfo]:
    sql = """
        SELECT slot_name, slot_type, plugin, database, active,
               restart_lsn, confirmed_flush_lsn, wal_status,
               safe_wal_size, two_phase
        FROM pg_replication_slots
        ORDER BY slot_name;
    """
    with conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute(sql)
        return [SlotInfo.from_row(r) for r in cur.fetchall()]


def current_wal_lsn(conn) -> str:
    with conn.cursor() as cur:
        cur.execute("SELECT pg_current_wal_lsn()")
        return cur.fetchone()[0]


def lsn_diff_bytes(conn, a: str, b: str) -> int:
    """Visszaadja |a - b| bájtokban."""
    with conn.cursor() as cur:
        cur.execute("SELECT pg_wal_lsn_diff(%s, %s)", (a, b))
        return int(abs(cur.fetchone()[0]))


# ---------------------------------------------------------------------------
# Heal műveletek
# ---------------------------------------------------------------------------

def create_slot(conn, name: str, slot_type: str, plugin: str, database: str) -> HealAction:
    action = HealAction(action="create", slot_name=name, detail=f"create {slot_type} slot")
    try:
        with conn.cursor() as cur:
            if slot_type == "logical":
                cur.execute(
                    "SELECT pg_create_logical_replication_slot(%s, %s)",
                    (name, plugin),
                )
            else:
                cur.execute(
                    "SELECT pg_create_physical_replication_slot(%s)",
                    (name,),
                )
        conn.commit()
        action.success = True
        action.detail = f"created {slot_type} slot '{name}' (plugin={plugin}, db={database})"
    except Exception as exc:  # noqa: BLE001
        conn.rollback()
        action.success = False
        action.error = str(exc)
        LOG.error("create_slot(%s) failed: %s", name, exc)
    return action


def drop_slot(conn, name: str) -> bool:
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT pg_drop_replication_slot(%s)", (name,))
        conn.commit()
        return True
    except Exception as exc:  # noqa: BLE001
        conn.rollback()
        LOG.error("drop_slot(%s) failed: %s", name, exc)
        return False


def advance_slot(conn, name: str, target_lsn: str) -> HealAction:
    action = HealAction(
        action="advance", slot_name=name, detail=f"advance to {target_lsn}"
    )
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT pg_replication_slot_advance(%s, %s)",
                (name, target_lsn),
            )
        conn.commit()
        action.success = True
    except Exception as exc:  # noqa: BLE001
        conn.rollback()
        action.success = False
        action.error = str(exc)
        LOG.error("advance_slot(%s) failed: %s", name, exc)
    return action


def recreate_slot(
    conn, name: str, slot_type: str, plugin: str, database: str, attempts: int
) -> HealAction:
    action = HealAction(
        action="drop_recreate", slot_name=name, detail=f"recreate (attempts={attempts})"
    )
    last_err = None
    for i in range(attempts):
        if drop_slot(conn, name):
            time.sleep(0.5)
            inner = create_slot(conn, name, slot_type, plugin, database)
            if inner.success:
                action.success = True
                action.detail = f"recreated on attempt {i + 1}"
                return action
            last_err = inner.error
        else:
            last_err = "drop failed"
        time.sleep(1.0 * (i + 1))
    action.success = False
    action.error = last_err
    return action


# ---------------------------------------------------------------------------
# Fő heal logika
# ---------------------------------------------------------------------------

def run_heal(cfg: Dict[str, Any]) -> HealReport:
    report = HealReport(
        timestamp=time.time(),
        host=cfg["host"],
        db=cfg["dbname"],
        expected_slots=list(cfg["expected_slots"]),
        found_slots=[],
        missing_slots=[],
        lost_slots=[],
        dry_run=cfg["dry_run"],
    )

    conn = None
    try:
        conn = connect(cfg)
        conn.autocommit = False

        if not is_replication_role(conn):
            report.healthy = False
            report.actions.append(
                HealAction(
                    action="alert",
                    slot_name="-",
                    detail="user lacks REPLICATION/SUPERUSER or wal_level not logical/replica",
                    success=False,
                    error="insufficient_privileges",
                )
            )
            return report

        slots = fetch_slots(conn)
        slot_map = {s.slot_name: s for s in slots}
        report.found_slots = sorted(slot_map.keys())

        wal_lsn = current_wal_lsn(conn)

        for expected in cfg["expected_slots"]:
            expected = expected.strip()
            if not expected:
                continue

            if expected not in slot_map:
                report.missing_slots.append(expected)
                if cfg["dry_run"]:
                    report.actions.append(
                        HealAction(
                            action="create",
                            slot_name=expected,
                            detail="dry-run: would create slot",
                            success=False,
                            error="dry_run",
                        )
                    )
                else:
                    act = create_slot(
                        conn, expected, cfg["slot_type"], cfg["plugin"], cfg["dbname"]
                    )
                    report.actions.append(act)
                    if not act.success:
                        report.healthy = False
                continue

            slot = slot_map[expected]

            # WAL-validáció: lost slot -> drop + recreate
            if slot.wal_status == "lost":
                report.lost_slots.append(expected)
                if cfg["dry_run"]:
                    report.actions.append(
                        HealAction(
                            action="drop_recreate",
                            slot_name=expected,
                            detail="dry-run: would drop+recreate lost slot",
                            success=False,
                            error="dry_run",
                        )
                    )
                else:
                    act = recreate_slot(
                        conn,
                        expected,
                        cfg["slot_type"],
                        cfg["plugin"],
                        cfg["dbname"],
                        cfg["max_recreate_attempts"],
                    )
                    report.actions.append(act)
                    if not act.success:
                        report.healthy = False
                continue

            # WAL lag ellenőrzés
            if slot.restart_lsn:
                try:
                    lag = lsn_diff_bytes(conn, wal_lsn, slot.restart_lsn)
                    lag_mb = lag / (1024 * 1024)
                    if lag_mb > cfg["wal_max_lag_mb"]:
                        if cfg["dry_run"]:
                            report.actions.append(
                                HealAction(
                                    action="alert",
                                    slot_name=expected,
                                    detail=f"dry-run: WAL lag {lag_mb:.1f}MB > {cfg['wal_max_lag_mb']}MB",
                                    success=False,
                                    error="dry_run",
                                )
                            )
                        else:
                            # Próbáljuk advance-elni a current WAL LSN-re
                            act = advance_slot(conn, expected, wal_lsn)
                            report.actions.append(act)
                            if not act.success:
                                report.healthy = False
                except Exception as exc:  # noqa: BLE001
                    report.actions.append(
                        HealAction(
                            action="alert",
                            slot_name=expected,
                            detail=f"WAL lag check failed: {exc}",
                            success=False,
                            error=str(exc),
                        )
                    )
                    report.healthy = False

            # Inactive slot (nem lost) -> csak alert, nem töröljük
            if not slot.active and slot.wal_status != "lost":
                report.actions.append(
                    HealAction(
                        action="alert",
                        slot_name=expected,
                        detail=f"slot inactive (wal_status={slot.wal_status})",
                        success=True,
                    )
                )

        # Extra slotok (nem várt) -> info
        for extra in set(slot_map.keys()) - set(cfg["expected_slots"]):
            report.actions.append(
                HealAction(
                    action="noop",
                    slot_name=extra,
                    detail="unexpected slot present, leaving as-is",
                    success=True,
                )
            )

    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:  # noqa: BLE001
                pass

    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_argparser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="PG replica slot auto-heal (runa_replica / nova_replica) + WAL-validáció"
    )
    p.add_argument("--host", default=DEFAULT_CONFIG["host"])
    p.add_argument("--port", type=int, default=DEFAULT_CONFIG["port"])
    p.add_argument("--db", dest="dbname", default=DEFAULT_CONFIG["dbname"])
    p.add_argument("--user", default=DEFAULT_CONFIG["user"])
    p.add_argument("--password", default=DEFAULT_CONFIG["password"])
    p.add_argument(
        "--slots",
        default=",".join(DEFAULT_CONFIG["expected_slots"]),
        help="vesszővel elválasztott elvárt slot nevek",
    )
    p.add_argument(
        "--slot-type",
        choices=["logical", "physical"],
        default=DEFAULT_CONFIG["slot_type"],
    )
    p.add_argument("--plugin", default=DEFAULT_CONFIG["plugin"])
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--wal-max-lag-mb", type=int, default=DEFAULT_CONFIG["wal_max_lag_mb"])
    p.add_argument("--max-recreate", type=int, default=DEFAULT_CONFIG["max_recreate_attempts"])
    p.add_argument("--connect-timeout", type=int, default=DEFAULT_CONFIG["connect_timeout"])
    p.add_argument("--json", action="store_true", help="JSON report stdout-ra")
    p.add_argument("--verbose", "-v", action="store_true")
    return p


def main(argv: Optional[List[str]] = None) -> int:
    args = build_argparser().parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    cfg = {
        "host": args.host,
        "port": args.port,
        "dbname": args.dbname,
        "user": args.user,
        "password": args.password,
        "expected_slots": [s.strip() for s in args.slots.split(",") if s.strip()],
        "slot_type": args.slot_type,
        "plugin": args.plugin,
        "dry_run": args.dry_run,
        "wal_max_lag_mb": args.wal_max_lag_mb,
        "max_recreate_attempts": args.max_recreate,
        "connect_timeout": args.connect_timeout,
    }

    LOG.info(
        "Starting slot auto-heal: host=%s db=%s slots=%s dry_run=%s",
        cfg["host"], cfg["dbname"], cfg["expected_slots"], cfg["dry_run"],
    )

    try:
        report = run_heal(cfg)
    except Exception as exc:  # noqa: BLE001
        LOG.error("Heal failed: %s", exc)
        if args.json:
            print(json.dumps({
                "ok": False,
                "error": str(exc),
                "host": cfg["host"],
                "db": cfg["dbname"],
            }))
        return 1

    if args.json:
        print(json.dumps(report.to_dict(), indent=2, default=str))
    else:
        print(f"=== PG Slot Auto-Heal Report ===")
        print(f"Host: {report.host} / DB: {report.db}")
        print(f"Expected: {report.expected_slots}")
        print(f"Found:    {report.found_slots}")
        print(f"Missing:  {report.missing_slots}")
        print(f"Lost:     {report.lost_slots}")
        print(f"Healthy:  {report.healthy}  (dry_run={report.dry_run})")
        print(f"Actions ({len(report.actions)}):")
        for a in report.actions:
            status = "OK" if a.success else "FAIL"
            print(f"  [{status}] {a.action:14s} {a.slot_name:20s} {a.detail}"
                  + (f"  err={a.error}" if a.error else ""))

    return 0 if report.healthy else 3


if __name__ == "__main__":
    sys.exit(main())