#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
Sablon-validátor: küldés ELŐTT assert, hogy minden placeholder ki volt cserélve.
A mostani `{}` bug így sosem jutott volna ki élesbe, hanem első próbánál reject+log.

Ez a modul egy önálló, futtatható implementáció, amely:
  1. Sablonokat tölt be és helyettesíti a placeholder-eket.
  2. Küldés előtt validálja, hogy nem maradt ki nem cserélt `{placeholder}`.
  3. Ha maradt, reject + log, nem enged küldeni.
  4. Tartalmaz egy beépített tesztet / demót.
"""

import re
import logging
import json
import sys
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional

# ---------------------------------------------------------------------------
# Logging beállítás
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("template_validator")


# ---------------------------------------------------------------------------
# Placeholder regex — `{name}` formátum, mint Python str.format
# ---------------------------------------------------------------------------
PLACEHOLDER_RE = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")


class ValidationError(Exception):
    """Akkor dobódik, ha a sablon validálása elbukik."""


# ---------------------------------------------------------------------------
# ValidationResult
# ---------------------------------------------------------------------------
class ValidationStatus(Enum):
    OK = "ok"
    REJECTED = "rejected"


@dataclass
class ValidationResult:
    status: ValidationStatus
    message: str
    remaining_placeholders: list = field(default_factory=list)
    rendered: str = ""


# ---------------------------------------------------------------------------
# TemplateValidator
# ---------------------------------------------------------------------------
class TemplateValidator:
    """
    Sablon-validátor: küldés ELŐTT ellenőrzi, hogy minden placeholder
    ki volt cserélve. Ha nem → reject + log.
    """

    def __init__(self, strict: bool = True):
        self.strict = strict
        self._templates: Dict[str, str] = {}

    # --- sablon regisztráció ---
    def register_template(self, name: str, template: str) -> None:
        if not isinstance(template, str):
            raise TypeError(f"A sablon string kell legyen, kapott: {type(template)}")
        self._templates[name] = template
        logger.debug("Sablon regisztrálva: %s (%d byte)", name, len(template))

    def load_templates(self, templates: Dict[str, str]) -> None:
        for name, tmpl in templates.items():
            self.register_template(name, tmpl)

    # --- placeholder keresés ---
    @staticmethod
    def find_placeholders(text: str) -> list:
        return PLACEHOLDER_RE.findall(text)

    # --- render + validate ---
    def render(self, template_name: str, variables: Dict[str, Any]) -> ValidationResult:
        if template_name not in self._templates:
            raise KeyError(f"Ismeretlen sablon: {template_name}")

        template = self._templates[template_name]

        # 1) Helyettesítés
        try:
            rendered = template.format(**variables)
        except KeyError as exc:
            missing = exc.args[0] if exc.args else "?"
            msg = (
                f"[REJECT] Hiányzó változó '{missing}' a sablonhoz "
                f"'{template_name}'."
            )
            logger.error(msg)
            return ValidationResult(
                status=ValidationStatus.REJECTED,
                message=msg,
                remaining_placeholders=[missing],
            )
        except (ValueError, IndexError) as exc:
            msg = f"[REJECT] Formázási hiba a sablonhoz '{template_name}': {exc}"
            logger.error(msg)
            return ValidationResult(
                status=ValidationStatus.REJECTED,
                message=msg,
                remaining_placeholders=[],
            )

        # 2) Validáció: maradt-e ki nem cserélt placeholder?
        remaining = self.find_placeholders(rendered)

        if remaining:
            msg = (
                f"[REJECT] A sablon '{template_name}' még ki nem cserélt "
                f"placeholder-eket tartalmaz: {remaining}. "
                f"Renderelt tartalom: {rendered!r}"
            )
            logger.error(msg)
            return ValidationResult(
                status=ValidationStatus.REJECTED,
                message=msg,
                remaining_placeholders=remaining,
                rendered=rendered,
            )

        logger.info("[OK] Sablon '%s' validálva, küldés engedélyezve.", template_name)
        return ValidationResult(
            status=ValidationStatus.OK,
            message="OK",
            remaining_placeholders=[],
            rendered=rendered,
        )

    # --- küldés (szimulált) ---
    def send(self, template_name: str, variables: Dict[str, Any]) -> bool:
        """
        Küldés ELŐTT validál. Ha REJECTED → nem küld, csak log.
        Ha OK → szimulált küldés.
        """
        result = self.render(template_name, variables)

        if result.status == ValidationStatus.REJECTED:
            logger.warning(
                "Küldés MEGSZAKÍTVA (template=%s): %s",
                template_name,
                result.message,
            )
            return False

        # Szimulált küldés
        logger.info(">> KÜLDÉS: %s", result.rendered)
        return True


# ---------------------------------------------------------------------------
# Bemutató / teszt
# ---------------------------------------------------------------------------
DEMO_TEMPLATES = {
    # 1) Helyes sablon — minden placeholder ki lesz cserélve
    "greeting": "Hello {name}, a te szereped: {role}. Üzenet: {msg}",

    # 2) Hibás sablon — szándékosan marad ki nem cserélt placeholder
    #    (ez szimulálja a mostani `{}` bug-ot)
    "buggy_at_truncation": "Tisztelt @{name}! Értesítés: {msg} — kérjük válaszoljon {deadline}",

    # 3) Sablon, ahol hiányzik egy változó a hívásból
    "missing_var": "Feladó: {sender}, Címzett: {recipient}, Tárgy: {subject}",
}


def run_demo() -> int:
    print("=" * 70)
    print("SABLON-VALIDÁTOR DEMO — küldés ELŐTT assert")
    print("=" * 70)

    validator = TemplateValidator(strict=True)
    validator.load_templates(DEMO_TEMPLATES)

    results = []

    # --- Teszt 1: helyes küldés ---
    print("\n--- Teszt 1: helyes sablon, minden változó megadva ---")
    ok = validator.send("greeting", {
        "name": "morzsa",
        "role": "debate-participant",
        "msg": "Sablon-validátor ötlet",
    })
    results.append(("greeting_ok", ok))
    print(f"Eredmény: {'KÜLDVE' if ok else 'REJECT'}")

    # --- Teszt 2: a `{}` bug szimulálása ---
    # A 'deadline' változó nincs megadva → KeyError → REJECT
    print("\n--- Teszt 2: hiányzó változó (deadline) → REJECT ---")
    ok = validator.send("buggy_at_truncation", {
        "name": "runa",
        "msg": "Teszt üzenet",
        # deadline hiányzik!
    })
    results.append(("missing_deadline", ok))
    print(f"Eredmény: {'KÜLDVE' if ok else 'REJECT (várható)'}")

    # --- Teszt 3: olyan sablon, ahol a .format() nem dob KeyError-t,
    #     de a placeholder szövegben marad (pl. dupla zárójel escape) ---
    # Létrehozunk egy sablont, ahol {{name}} → {name} a kimenetben
    print("\n--- Teszt 3: escaped placeholder ({{name}}) → {name} marad ---")
    validator.register_template(
        "escaped_bug",
        "Hello {{name}}, ez egy escaped placeholder, ami {name} marad a kimenetben!",
    )
    ok = validator.send("escaped_bug", {})
    results.append(("escaped_bug", ok))
    print(f"Eredmény: {'KÜLDVE' if ok else 'REJECT (várható — {name} maradt)'}")

    # --- Teszt 4: hiányzó változó a missing_var sablonban ---
    print("\n--- Teszt 4: missing_var — subject hiányzik ---")
    ok = validator.send("missing_var", {
        "sender": "morzsa",
        "recipient": "runa",
        # subject hiányzik
    })
    results.append(("missing_subject", ok))
    print(f"Eredmény: {'KÜLDVE' if ok else 'REJECT (várható)'}")

    # --- Teszt 5: minden megadva → OK ---
    print("\n--- Teszt 5: missing_var — minden megadva → OK ---")
    ok = validator.send("missing_var", {
        "sender": "morzsa",
        "recipient": "runa",
        "subject": "Sablon-validátor",
    })
    results.append(("missing_var_ok", ok))
    print(f"Eredmény: {'KÜLDVE' if ok else 'REJECT'}")

    # --- Összegzés ---
    print("\n" + "=" * 70)
    print("ÖSSZEGZÉS")
    print("=" * 70)
    passed = sum(1 for _, ok in results if ok)
    rejected = len(results) - passed
    for name, ok in results:
        status = "✓ KÜLDVE" if ok else "✗ REJECT"
        print(f"  {name:25s} → {status}")
    print(f"\nÖsszesen: {len(results)} | Küldve: {passed} | Reject: {rejected}")
    print("A reject-ek pont azok, amiket a validátor MEGAKADÁLYOZOTT.")
    print("Ezzel a `{}` bug sosem jutott volna ki élesbe.\n")

    return 0


if __name__ == "__main__":
    sys.exit(run_demo())