#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
on_mesh_message guard: ha nincs `text` és nincs `content`,
early-return + WARN log a teljes msg-ről — így nem szennyezi a chatet.

Ez a modul a core/dashboard.py on_mesh_message függvényébe tervezett guard
önálló, futtatható implementációja + teszt harnessex.
"""

import json
import logging
import sys
from typing import Any, Dict, Optional

# ---------------------------------------------------------------------------
# Logging setup — a guard WARN szintű logot ír a teljes msg-ről
# ---------------------------------------------------------------------------
logger = logging.getLogger("a2a_mesh.dashboard")
if not logger.handlers:
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(
        logging.Formatter(
            "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
        )
    )
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)


# ---------------------------------------------------------------------------
# Guard helper — kinyeri a text/content mezőket a bejövő mesh üzenetből
# ---------------------------------------------------------------------------
def _extract_text(msg: Any) -> Optional[str]:
    """
    Visszaadja a szöveges tartalmat a mesh üzenetből.
    Sorrend: msg['text'] > msg['content'] > msg['payload']['text']
             > msg['payload']['content'] > None
    """
    if msg is None:
        return None

    # Ha maga az üzenet string
    if isinstance(msg, str):
        try:
            parsed = json.loads(msg)
        except (json.JSONDecodeError, TypeError):
            return msg if msg.strip() else None
        return _extract_text(parsed)

    if isinstance(msg, dict):
        text = msg.get("text")
        if isinstance(text, str) and text.strip():
            return text

        content = msg.get("content")
        if isinstance(content, str) and content.strip():
            return content

        # payload alá is nézünk
        payload = msg.get("payload")
        if isinstance(payload, dict):
            p_text = payload.get("text")
            if isinstance(p_text, str) and p_text.strip():
                return p_text
            p_content = payload.get("content")
            if isinstance(p_content, str) and p_content.strip():
                return p_content

    return None


# ---------------------------------------------------------------------------
# on_mesh_message — guard-dal
# ---------------------------------------------------------------------------
def on_mesh_message(msg: Any, chat_buffer: Optional[list] = None) -> Optional[str]:
    """
    Feldolgozza a bejövő mesh üzenetet.

    GUARD: ha nincs `text` és nincs `content` (sem közvetlenül, sem payload alatt),
    early-return + WARN log a teljes msg-ről — így nem szennyezi a chatet `{}`-rel.

    Visszatér a chatbe írandó szöveggel, vagy None-tal ha a guard leállította.
    """
    # --- GUARD -----------------------------------------------------------
    text = _extract_text(msg)
    if text is None:
        # Biztonságos repr — nagy üzenetek csonkolása
        try:
            msg_repr = json.dumps(msg, ensure_ascii=False, default=str)
        except (TypeError, ValueError):
            msg_repr = repr(msg)
        if len(msg_repr) > 2000:
            msg_repr = msg_repr[:2000] + "...[truncated]"

        logger.warning(
            "on_mesh_message guard: üzenetnek nincs `text` és nincs `content` "
            "mezője — early return, chat nem szennyeződik. msg=%s",
            msg_repr,
        )
        return None
    # --- /GUARD ----------------------------------------------------------

    # Normalizált payload felépítése (ez megy a chatbe / dashboardra)
    payload: Dict[str, Any] = {}
    if isinstance(msg, dict):
        raw_payload = msg.get("payload")
        if isinstance(raw_payload, dict):
            payload = raw_payload
        elif isinstance(raw_payload, str):
            try:
                payload = json.loads(raw_payload)
            except (json.JSONDecodeError, TypeError):
                payload = {}
        payload.setdefault("text", text)
    else:
        payload = {"text": text}

    # Chat buffer szimuláció (a valódi dashboard ide írja a sorokat)
    if chat_buffer is not None:
        chat_buffer.append(text)

    logger.debug("on_mesh_message OK: text=%r", text[:120])
    return text


# ---------------------------------------------------------------------------
# Tesztek / demo
# ---------------------------------------------------------------------------
def _run_tests() -> None:
    chat: list = []
    failures: list = []

    def check(label: str, msg: Any, expect_none: bool) -> None:
        chat.clear()
        result = on_mesh_message(msg, chat_buffer=chat)
        ok = (result is None) == expect_none
        status = "PASS" if ok else "FAIL"
        print(f"  [{status}] {label}")
        if not ok:
            failures.append(label)
        # Ha guard aktiválódik, chat nem szennyeződik
        if expect_none and chat:
            failures.append(f"{label} (chat polluted)")
            print(f"         !! chat polluted: {chat}")

    print("=== on_mesh_message guard tesztek ===\n")

    # Eset 1: None payload — ez volt a valódi bug ({} a chatbe)
    check("None üzenet", None, expect_none=True)

    # Eset 2: üres dict
    check("üres dict {}", {}, expect_none=True)

    # Eset 3: payload None
    check("payload=None", {"payload": None, "sender": "x"}, expect_none=True)

    # Eset 4: payload üres dict
    check("payload={}", {"payload": {}}, expect_none=True)

    # Eset 5: csak sender, nincs text/content
    check("csak sender", {"sender": "morzsa", "type": "ping"}, expect_none=True)

    # Eset 6: text mező jelen
    check("text mező", {"text": "hello world"}, expect_none=False)

    # Eset 7: content mező jelen
    check("content mező", {"content": "important msg"}, expect_none=False)

    # Eset 8: payload.text
    check("payload.text", {"payload": {"text": "deep text"}}, expect_none=False)

    # Eset 9: payload.content
    check("payload.content", {"payload": {"content": "deep content"}}, expect_none=False)

    # Eset 10: string üzenet
    check("plain string", "plain text message", expect_none=False)

    # Eset 11: üres string
    check("empty string", "   ", expect_none=True)

    # Eset 12: JSON string text-tel
    check("json string w/ text", '{"text": "parsed"}', expect_none=False)

    # Eset 13: JSON string text nélkül
    check("json string w/o text", '{"sender": "x"}', expect_none=True)

    # Eset 14: list (nem dict/string)
    check("list payload", [1, 2, 3], expect_none=True)

    # Eset 15: int
    check("int payload", 42, expect_none=True)

    print(f"\n{'='*40}")
    if failures:
        print(f"FAILED: {len(failures)} teszt")
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)
    else:
        print("Minden teszten átment — guard működik, chat nem szennyeződik.")


if __name__ == "__main__":
    _run_tests()