#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generated by runa via A2A Mesh delegation

Silence-consensus: "NEM VÁLASZTOLSZ" szavak aggregálása topic-szinten
— ha 2+ agent elhallgat, a téma auto-zárul, csökken a spam.

This module implements topic-level silence consensus for the A2A Mesh.
When 2 or more agents signal silence ("NEM VÁLASZTOLSZ") on a topic,
the topic is automatically closed, reducing noise/spam.

Features:
  - Track per-topic silence votes from agents
  - Auto-close topics when silence threshold (default 2) is reached
  - Persist state to JSON for crash recovery
  - Emit events for mesh integration
  - CLI for testing and inspection
"""

import json
import os
import time
import threading
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Callable, Set
from enum import Enum


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

SILENCE_SIGNAL = "NEM_VÁLASZTOLSZ"
DEFAULT_SILENCE_THRESHOLD = 2
DEFAULT_STATE_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "silence_consensus_state.json",
)
DEFAULT_TOPIC_TIMEOUT_SEC = 3600  # 1 hour idle → stale topic


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class TopicStatus(str, Enum):
    OPEN = "open"
    CLOSED = "closed"


@dataclass
class SilenceVote:
    agent_id: str
    topic_id: str
    timestamp: float
    signal: str = SILENCE_SIGNAL


@dataclass
class Topic:
    topic_id: str
    title: str
    status: TopicStatus = TopicStatus.OPEN
    created_at: float = field(default_factory=time.time)
    closed_at: Optional[float] = None
    silence_votes: Dict[str, float] = field(default_factory=dict)  # agent_id -> timestamp
    participants: Set[str] = field(default_factory=set)

    def to_dict(self) -> dict:
        return {
            "topic_id": self.topic_id,
            "title": self.title,
            "status": self.status.value,
            "created_at": self.created_at,
            "closed_at": self.closed_at,
            "silence_votes": self.silence_votes,
            "participants": list(self.participants),
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Topic":
        return cls(
            topic_id=d["topic_id"],
            title=d.get("title", ""),
            status=TopicStatus(d.get("status", "open")),
            created_at=d.get("created_at", time.time()),
            closed_at=d.get("closed_at"),
            silence_votes=d.get("silence_votes", {}),
            participants=set(d.get("participants", [])),
        )


# ---------------------------------------------------------------------------
# Event types
# ---------------------------------------------------------------------------

@dataclass
class ConsensusEvent:
    event_type: str  # "silence_vote", "topic_closed", "topic_opened"
    topic_id: str
    agent_id: Optional[str] = None
    timestamp: float = field(default_factory=time.time)
    details: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------------------
# Core engine
# ---------------------------------------------------------------------------

class SilenceConsensusEngine:
    """
    Aggregates silence signals at topic level.
    Auto-closes a topic when >= threshold agents go silent.
    """

    def __init__(
        self,
        state_file: str = DEFAULT_STATE_FILE,
        silence_threshold: int = DEFAULT_SILENCE_THRESHOLD,
        topic_timeout_sec: float = DEFAULT_TOPIC_TIMEOUT_SEC,
        event_callback: Optional[Callable[[ConsensusEvent], None]] = None,
    ):
        self.state_file = state_file
        self.silence_threshold = silence_threshold
        self.topic_timeout_sec = topic_timeout_sec
        self.event_callback = event_callback

        self._topics: Dict[str, Topic] = {}
        self._lock = threading.RLock()
        self._load_state()

    # -- persistence --------------------------------------------------------

    def _load_state(self):
        if not os.path.exists(self.state_file):
            return
        try:
            with open(self.state_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            for tdict in data.get("topics", []):
                t = Topic.from_dict(tdict)
                self._topics[t.topic_id] = t
        except (json.JSONDecodeError, KeyError, TypeError):
            # Corrupt state — start fresh
            self._topics = {}

    def _save_state(self):
        data = {
            "topics": [t.to_dict() for t in self._topics.values()],
            "saved_at": time.time(),
        }
        tmp = self.state_file + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        os.replace(tmp, self.state_file)

    # -- event helper -------------------------------------------------------

    def _emit(self, event: ConsensusEvent):
        if self.event_callback:
            try:
                self.event_callback(event)
            except Exception:
                pass

    # -- public API ---------------------------------------------------------

    def register_topic(self, topic_id: str, title: str = "", participants: Optional[List[str]] = None) -> Topic:
        """Create or update a topic for consensus tracking."""
        with self._lock:
            if topic_id not in self._topics:
                topic = Topic(topic_id=topic_id, title=title)
                self._topics[topic_id] = topic
                self._emit(ConsensusEvent(
                    event_type="topic_opened",
                    topic_id=topic_id,
                    details={"title": title},
                ))
            else:
                topic = self._topics[topic_id]
                if title:
                    topic.title = title

            if participants:
                for p in participants:
                    topic.participants.add(p)

            self._save_state()
            return topic

    def record_silence(self, agent_id: str, topic_id: str) -> bool:
        """
        Record a silence vote from an agent on a topic.
        Returns True if the topic was closed as a result.
        """
        with self._lock:
            if topic_id not in self._topics:
                self.register_topic(topic_id)

            topic = self._topics[topic_id]

            if topic.status == TopicStatus.CLOSED:
                return True  # already closed

            topic.silence_votes[agent_id] = time.time()
            topic.participants.add(agent_id)

            self._emit(ConsensusEvent(
                event_type="silence_vote",
                topic_id=topic_id,
                agent_id=agent_id,
                details={
                    "signal": SILENCE_SIGNAL,
                    "total_silence": len(topic.silence_votes),
                    "threshold": self.silence_threshold,
                },
            ))

            closed = False
            if len(topic.silence_votes) >= self.silence_threshold:
                topic.status = TopicStatus.CLOSED
                topic.closed_at = time.time()
                closed = True
                self._emit(ConsensusEvent(
                    event_type="topic_closed",
                    topic_id=topic_id,
                    details={
                        "reason": "silence_consensus",
                        "silent_agents": list(topic.silence_votes.keys()),
                        "threshold": self.silence_threshold,
                    },
                ))

            self._save_state()
            return closed

    def record_participation(self, agent_id: str, topic_id: str):
        """Mark that an agent is participating (not silent) — resets their silence vote."""
        with self._lock:
            if topic_id not in self._topics:
                self.register_topic(topic_id)
            topic = self._topics[topic_id]
            topic.participants.add(agent_id)
            # If agent previously voted silence but now participates, remove the silence vote
            if agent_id in topic.silence_votes:
                del topic.silence_votes[agent_id]
            self._save_state()

    def get_topic(self, topic_id: str) -> Optional[Topic]:
        with self._lock:
            return self._topics.get(topic_id)

    def get_open_topics(self) -> List[Topic]:
        with self._lock:
            return [t for t in self._topics.values() if t.status == TopicStatus.OPEN]

    def get_closed_topics(self) -> List[Topic]:
        with self._lock:
            return [t for t in self._topics.values() if t.status == TopicStatus.CLOSED]

    def is_topic_closed(self, topic_id: str) -> bool:
        t = self.get_topic(topic_id)
        return t is not None and t.status == TopicStatus.CLOSED

    def silence_count(self, topic_id: str) -> int:
        t = self.get_topic(topic_id)
        return len(t.silence_votes) if t else 0

    def cleanup_stale(self) -> int:
        """Close topics that have been idle beyond timeout. Returns count of closed."""
        now = time.time()
        closed_count = 0
        with self._lock:
            for topic in self._topics.values():
                if topic.status != TopicStatus.OPEN:
                    continue
                last_activity = max(
                    topic.created_at,
                    max(topic.silence_votes.values()) if topic.silence_votes else 0,
                )
                if now - last_activity > self.topic_timeout_sec:
                    topic.status = TopicStatus.CLOSED
                    topic.closed_at = now
                    closed_count += 1
                    self._emit(ConsensusEvent(
                        event_type="topic_closed",
                        topic_id=topic.topic_id,
                        details={"reason": "timeout", "idle_sec": now - last_activity},
                    ))
            if closed_count:
                self._save_state()
        return closed_count

    def reset(self):
        """Clear all state (for testing)."""
        with self._lock:
            self._topics.clear()
            if os.path.exists(self.state_file):
                os.remove(self.state_file)

    def summary(self) -> dict:
        with self._lock:
            return {
                "total_topics": len(self._topics),
                "open": sum(1 for t in self._topics.values() if t.status == TopicStatus.OPEN),
                "closed": sum(1 for t in self._topics.values() if t.status == TopicStatus.CLOSED),
                "threshold": self.silence_threshold,
                "topics": [t.to_dict() for t in self._topics.values()],
            }


# ---------------------------------------------------------------------------
# Integration helper: Mesh message filter
# ---------------------------------------------------------------------------

class SilenceConsensusFilter:
    """
    Drop-in filter for A2A Mesh message routing.
    Messages belonging to closed topics are silently dropped (spam reduction).
    """

    def __init__(self, engine: SilenceConsensusEngine):
        self.engine = engine

    def should_deliver(self, message: dict) -> bool:
        """
        Check if a message should be delivered.
        Messages with topic_id pointing to a closed topic are dropped.
        """
        topic_id = message.get("topic_id") or message.get("topic")
        if topic_id and self.engine.is_topic_closed(topic_id):
            return False
        return True

    def process_agent_response(self, agent_id: str, topic_id: str, responded: bool):
        """
        Call this after an agent has had a chance to respond.
        If the agent did NOT respond (responded=False), record a silence vote.
        If the agent DID respond, record participation.
        """
        if responded:
            self.engine.record_participation(agent_id, topic_id)
        else:
            self.engine.record_silence(agent_id, topic_id)


# ---------------------------------------------------------------------------
# Demo / CLI
# ---------------------------------------------------------------------------

def _print_event(event: ConsensusEvent):
    ts = time.strftime("%H:%M:%S", time.localtime(event.timestamp))
    if event.event_type == "silence_vote":
        print(f"  [{ts}] SILENCE: agent={event.agent_id} topic={event.topic_id} "
              f"({event.details.get('total_silence')}/{event.details.get('threshold')})")
    elif event.event_type == "topic_closed":
        reason = event.details.get("reason", "consensus")
        agents = event.details.get("silent_agents", [])
        print(f"  [{ts}] ✗ TOPIC CLOSED: {event.topic_id} (reason={reason}, silent={agents})")
    elif event.event_type == "topic_opened":
        print(f"  [{ts}] + TOPIC OPENED: {event.topic_id} ({event.details.get('title', '')})")


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Silence-consensus engine for A2A Mesh — auto-close topics when 2+ agents go silent."
    )
    parser.add_argument("--state", default=DEFAULT_STATE_FILE, help="Path to state JSON file")
    parser.add_argument("--threshold", type=int, default=DEFAULT_SILENCE_THRESHOLD,
                        help="Number of silent agents required to close a topic")
    parser.add_argument("--demo", action="store_true", help="Run a built-in demo scenario")
    parser.add_argument("--status", action="store_true", help="Print current state summary")
    parser.add_argument("--vote", nargs=2, metavar=("AGENT", "TOPIC"),
                        help="Record a silence vote for AGENT on TOPIC")
    parser.add_argument("--participate", nargs=2, metavar=("AGENT", "TOPIC"),
                        help="Record participation for AGENT on TOPIC")
    parser.add_argument("--register", nargs=2, metavar=("TOPIC", "TITLE"),
                        help="Register a new topic")
    parser.add_argument("--cleanup", action="store_true", help="Close stale topics")
    parser.add_argument("--reset", action="store_true", help="Reset all state")

    args = parser.parse_args()

    engine = SilenceConsensusEngine(
        state_file=args.state,
        silence_threshold=args.threshold,
        event_callback=_print_event,
    )

    if args.reset:
        engine.reset()
        print("State reset.")
        return

    if args.demo:
        print("=" * 60)
        print("SILENCE-CONSENSUS DEMO")
        print("=" * 60)
        engine.reset()
        # Re-init after reset
        engine = SilenceConsensusEngine(
            state_file=args.state,
            silence_threshold=2,
            event_callback=_print_event,
        )

        print("\n1. Registering topics...")
        engine.register_topic("topic_idea_dedup", "Engramm-dedup similarity filter")
        engine.register_topic("topic_idea_silence", "Silence-consensus aggregation")
        engine.register_topic("topic_idea_breaker", "Circuit breaker for peers")

        print("\n2. Agent 'runa' goes silent on topic_idea_dedup...")
        engine.record_silence("runa", "topic_idea_dedup")

        print("\n3. Agent 'nyx' goes silent on topic_idea_dedup...")
        closed = engine.record_silence("nyx", "topic_idea_dedup")
        print(f"   → Topic closed? {closed}")

        print("\n4. Agent 'runa' participates in topic_idea_silence (not silent)...")
        engine.record_participation("runa", "topic_idea_silence")

        print("\n5. Agent 'echo' goes silent on topic_idea_breaker...")
        engine.record_silence("echo", "topic_idea_breaker")

        print("\n6. Agent 'flux' goes silent on topic_idea_breaker...")
        closed = engine.record_silence("flux", "topic_idea_breaker")
        print(f"   → Topic closed? {closed}")

        print("\n7. Trying to vote on already-closed topic_idea_dedup...")
        already = engine.record_silence("late_agent", "topic_idea_dedup")
        print(f"   → Already closed? {already}")

        print("\n8. Message filter demo...")
        filt = SilenceConsensusFilter(engine)
        msgs = [
            {"topic_id": "topic_idea_dedup", "content": "spam about dedup"},
            {"topic_id": "topic_idea_silence", "content": "valid silence discussion"},
            {"topic_id": "topic_idea_breaker", "content": "spam about breaker"},
        ]
        for m in msgs:
            deliver = filt.should_deliver(m)
            status = "DELIVER" if deliver else "DROP (topic closed)"
            print(f"   [{m['topic_id']}] {status}: {m['content']}")

        print("\n9. Final summary:")
        s = engine.summary()
        print(f"   Total topics: {s['total_topics']}")
        print(f"   Open: {s['open']}, Closed: {s['closed']}")
        for t in s["topics"]:
            print(f"   - {t['topic_id']}: {t['status']} "
                  f"(silence_votes={len(t['silence_votes'])}, participants={t['participants']})")

        print("\n" + "=" * 60)
        print("DEMO COMPLETE — closed topics are filtered from mesh routing.")
        print("=" * 60)
        return

    if args.register:
        topic_id, title = args.register
        engine.register_topic(topic_id, title)
        print(f"Registered topic: {topic_id} ({title})")
        return

    if args.vote:
        agent_id, topic_id = args.vote
        closed = engine.record_silence(agent_id, topic_id)
        print(f"Silence vote recorded: {agent_id} → {topic_id}. Closed={closed}")
        return

    if args.participate:
        agent_id, topic_id = args.participate
        engine.record_participation(agent_id, topic_id)
        print(f"Participation recorded: {agent_id} → {topic_id}")
        return

    if args.cleanup:
        n = engine.cleanup_stale()
        print(f"Closed {n} stale topics.")
        return

    # Default: print status
    s = engine.summary()
    print(json.dumps(s, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()