#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
Kétrétegű memória-híd: mesh-nomic + Honcho L4 (qwen3) azonos identitástartással
idea_id: idea_honcho_mem_bridge

Architektúra:
  1) Core mesh lokális emlékek (memory_episodic, nomic-embed 768d, pgvector)
  2) Napi delta-szinkron: memory_episodic → Honcho documents (one-way mesh→Honcho)
  3) Honcho deriver: conclusions a beszélgetés-alapú emlékekből
  4) Identitás-megőrzés: peer_id/node címke minden documentumban
  5) Agent identitás + peer exchange (debate, /ask) változatlan
  6) Fordított irány: Honcho conclusions → shared_a2a_memory (TTL + emberi kapu)

A híd opcionális réteg — a mesh core nem függhet tőle.
qwen3 embedding csak a mély rétegnél.
"""

import os
import sys
import json
import time
import uuid
import hashlib
import logging
import sqlite3
import threading
import dataclasses
from datetime import datetime, timedelta, timezone
from typing import Optional, Any
from dataclasses import dataclass, field, asdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)
log = logging.getLogger("honcho_bridge")


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
@dataclass
class BridgeConfig:
    """Configuration for the two-layer memory bridge."""
    # Local mesh memory
    local_db_path: str = "data/mesh_memory.db"
    embedding_dim: int = 768  # nomic-embed-text dimension

    # Honcho L4
    honcho_enabled: bool = False  # optional layer — off by default
    honcho_base_url: str = "http://localhost:5173"
    honcho_timeout: float = 30.0

    # Sync
    sync_interval_hours: int = 24
    sync_batch_size: int = 100

    # Reverse direction
    shared_memory_ttl_hours: int = 72
    human_gate_required: bool = True

    # qwen3 embedding (CPU expensive — deep layer only)
    qwen3_model: str = "Qwen/Qwen3-Embedding-0.6B"
    qwen3_enabled: bool = False

    # Identity
    mesh_node_id: str = "runa"

    @classmethod
    def from_env(cls) -> "BridgeConfig":
        return cls(
            local_db_path=os.getenv("MESH_MEMORY_DB", "data/mesh_memory.db"),
            honcho_enabled=os.getenv("HONCHO_ENABLED", "false").lower() == "true",
            honcho_base_url=os.getenv("HONCHO_BASE_URL", "http://localhost:5173"),
            sync_interval_hours=int(os.getenv("SYNC_INTERVAL_HOURS", "24")),
            shared_memory_ttl_hours=int(os.getenv("SHARED_MEM_TTL_HOURS", "72")),
            human_gate_required=os.getenv("HUMAN_GATE", "true").lower() == "true",
            qwen3_enabled=os.getenv("QWEN3_ENABLED", "false").lower() == "true",
            mesh_node_id=os.getenv("MESH_NODE_ID", "runa"),
        )


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------
@dataclass
class EpisodicMemory:
    """Local mesh episodic memory entry — identity-tagged."""
    id: str
    node_id: str          # identity: which mesh node produced this
    peer_id: str          # identity: which peer was involved (or self)
    content: str
    embedding: list[float] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    synced_to_honcho: bool = False
    synced_at: Optional[str] = None

    def to_dict(self) -> dict:
        d = asdict(self)
        return d


@dataclass
class HonchoDocument:
    """Document sent to Honcho — preserves node/peer identity."""
    id: str
    node_id: str
    peer_id: str
    content: str
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""

    def to_honcho_payload(self) -> dict:
        return {
            "content": self.content,
            "metadata": {
                "mesh_node_id": self.node_id,
                "mesh_peer_id": self.peer_id,
                "mesh_memory_id": self.id,
                "source": "a2a_mesh_bridge",
                "created_at": self.created_at,
                **self.metadata,
            },
        }


@dataclass
class HonchoConclusion:
    """Conclusion derived by Honcho — identity-tagged per node."""
    id: str
    node_id: str
    peer_id: str
    conclusion: str
    confidence: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    approved_by_human: bool = False
    shared: bool = False
    shared_at: Optional[str] = None
    ttl_expires_at: Optional[str] = None


@dataclass
class SharedA2AMemory:
    """Reverse-direction shared memory entry with TTL."""
    id: str
    conclusion_id: str
    node_id: str
    peer_id: str
    content: str
    ttl_expires_at: str
    created_at: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Embedding providers
# ---------------------------------------------------------------------------
class NomicEmbedder:
    """nomic-embed-text 768d — used for local mesh memory (fast, local)."""

    def __init__(self, dim: int = 768):
        self.dim = dim
        self._model = None
        self._init_attempted = False

    def _try_init(self):
        if self._init_attempted:
            return
        self._init_attempted = True
        try:
            # Try sentence-transformers with nomic model
            from sentence_transformers import SentenceTransformer
            self._model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5")
            log.info("Nomic embedder loaded via sentence-transformers")
        except Exception:
            try:
                # Try ollama
                import requests
                r = requests.post(
                    "http://localhost:11434/api/embeddings",
                    json={"model": "nomic-embed-text", "prompt": "test"},
                    timeout=5,
                )
                if r.status_code == 200:
                    self._backend = "ollama"
                    log.info("Nomic embedder using ollama backend")
                    return
            except Exception:
                pass
            log.warning("Nomic embedder unavailable — using deterministic fallback")
            self._backend = "fallback"

    def embed(self, text: str) -> list[float]:
        self._try_init()
        if self._model is not None:
            vec = self._model.encode(text, normalize_to_numpy=True)
            return vec.tolist()
        if getattr(self, "_backend", None) == "ollama":
            import requests
            r = requests.post(
                "http://localhost:11434/api/embeddings",
                json={"model": "nomic-embed-text", "prompt": text},
                timeout=10,
            )
            if r.status_code == 200:
                return r.json()["embedding"]
        # Deterministic fallback — same dim, stable per text
        return self._deterministic_embedding(text)

    def _deterministic_embedding(self, text: str) -> list[float]:
        """Stable hash-based embedding for offline operation."""
        import struct
        result = []
        for i in range(self.dim):
            h = hashlib.sha256(f"{text}:{i}".encode()).digest()
            val = struct.unpack("f", h[:4])[0]
            result.append(val)
        # Normalize
        norm = sum(v * v for v in result) ** 0.5
        if norm > 0:
            result = [v / norm for v in result]
        return result


class Qwen3Embedder:
    """qwen3 embedding — CPU expensive, deep layer only."""

    def __init__(self, model_name: str = "Qwen/Qwen3-Embedding-0.6B"):
        self.model_name = model_name
        self._model = None
        self._init_attempted = False

    def _try_init(self):
        if self._init_attempted:
            return
        self._init_attempted = True
        try:
            from sentence_transformers import SentenceTransformer
            self._model = SentenceTransformer(self.model_name)
            log.info(f"Qwen3 embedder loaded: {self.model_name}")
        except Exception as e:
            log.warning(f"Qwen3 embedder unavailable ({e}) — using fallback")

    def embed(self, text: str) -> list[float]:
        self._try_init()
        if self._model is not None:
            vec = self._model.encode(text, normalize_to_numpy=True)
            return vec.tolist()
        # Fallback to nomic-style deterministic
        import struct
        dim = 1024
        result = []
        for i in range(dim):
            h = hashlib.sha256(f"qwen3:{text}:{i}".encode()).digest()
            val = struct.unpack("f", h[:4])[0]
            result.append(val)
        norm = sum(v * v for v in result) ** 0.5
        if norm > 0:
            result = [v / norm for v in result]
        return result


# ---------------------------------------------------------------------------
# Local Memory Store (SQLite + vector similarity)
# ---------------------------------------------------------------------------
class LocalMemoryStore:
    """
    Local episodic memory for the mesh node.
    Uses SQLite for persistence, cosine similarity for vector search.
    Identity (node_id, peer_id) is preserved on every entry.
    """

    def __init__(self, db_path: str, embedder: NomicEmbedder):
        self.db_path = db_path
        self.embedder = embedder
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._init_db()

    def _init_db(self):
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS episodic_memory (
                    id TEXT PRIMARY KEY,
                    node_id TEXT NOT NULL,
                    peer_id TEXT NOT NULL,
                    content TEXT NOT NULL,
                    embedding TEXT NOT NULL,
                    metadata TEXT DEFAULT '{}',
                    created_at TEXT NOT NULL,
                    synced_to_honcho INTEGER DEFAULT 0,
                    synced_at TEXT
                );
                CREATE INDEX IF NOT EXISTS idx_ep_node ON episodic_memory(node_id);
                CREATE INDEX IF NOT EXISTS idx_ep_peer ON episodic_memory(peer_id);
                CREATE INDEX IF NOT EXISTS idx_ep_synced ON episodic_memory(synced_to_honcho);

                CREATE TABLE IF NOT EXISTS honcho_conclusions (
                    id TEXT PRIMARY KEY,
                    node_id TEXT NOT NULL,
                    peer_id TEXT NOT NULL,
                    conclusion TEXT NOT NULL,
                    confidence REAL DEFAULT 0.0,
                    metadata TEXT DEFAULT '{}',
                    created_at TEXT NOT NULL,
                    approved_by_human INTEGER DEFAULT 0,
                    shared INTEGER DEFAULT 0,
                    shared_at TEXT,
                    ttl_expires_at TEXT
                );
                CREATE INDEX IF NOT EXISTS idx_hc_node ON honcho_conclusions(node_id);
                CREATE INDEX IF NOT EXISTS idx_hc_approved ON honcho_conclusions(approved_by_human);

                CREATE TABLE IF NOT EXISTS shared_a2a_memory (
                    id TEXT PRIMARY KEY,
                    conclusion_id TEXT NOT NULL,
                    node_id TEXT NOT NULL,
                    peer_id TEXT NOT NULL,
                    content TEXT NOT NULL,
                    ttl_expires_at TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    metadata TEXT DEFAULT '{}'
                );
                CREATE INDEX IF NOT EXISTS idx_sm_ttl ON shared_a2a_memory(ttl_expires_at);

                CREATE TABLE IF NOT EXISTS sync_state (
                    key TEXT PRIMARY KEY,
                    value TEXT
                );
            """)
            conn.commit()

    def add_memory(
        self,
        node_id: str,
        peer_id: str,
        content: str,
        metadata: Optional[dict] = None,
    ) -> EpisodicMemory:
        """Add a local episodic memory. Identity is always preserved."""
        mem_id = str(uuid.uuid4())
        embedding = self.embedder.embed(content)
        now = datetime.now(timezone.utc).isoformat()
        mem = EpisodicMemory(
            id=mem_id,
            node_id=node_id,
            peer_id=peer_id,
            content=content,
            embedding=embedding,
            metadata=metadata or {},
            created_at=now,
        )
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """INSERT INTO episodic_memory
                   (id, node_id, peer_id, content, embedding, metadata, created_at, synced_to_honcho)
                   VALUES (?, ?, ?, ?, ?, ?, ?, 0)""",
                (mem.id, mem.node_id, mem.peer_id, mem.content,
                 json.dumps(mem.embedding), json.dumps(mem.metadata), mem.created_at),
            )
            conn.commit()
        log.debug(f"Added episodic memory {mem_id[:8]} for node={node_id} peer={peer_id}")
        return mem

    def get_unsynced(self, limit: int = 100) -> list[EpisodicMemory]:
        with self._lock, sqlite3.connect(self.db_path) as conn:
            rows = conn.execute(
                """SELECT id, node_id, peer_id, content, embedding, metadata, created_at
                   FROM episodic_memory WHERE synced_to_honcho = 0
                   ORDER BY created_at ASC LIMIT ?""",
                (limit,),
            ).fetchall()
        return [
            EpisodicMemory(
                id=r[0], node_id=r[1], peer_id=r[2], content=r[3],
                embedding=json.loads(r[4]), metadata=json.loads(r[5]),
                created_at=r[6],
            )
            for r in rows
        ]

    def mark_synced(self, mem_id: str):
        now = datetime.now(timezone.utc).isoformat()
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute(
                "UPDATE episodic_memory SET synced_to_honcho = 1, synced_at = ? WHERE id = ?",
                (now, mem_id),
            )
            conn.commit()

    def search_local(
        self, query: str, node_id: Optional[str] = None,
        peer_id: Optional[str] = None, top_k: int = 5,
    ) -> list[tuple[EpisodicMemory, float]]:
        """Cosine similarity search over local memories. Identity-scoped."""
        q_vec = self.embedder.embed(query)
        with self._lock, sqlite3.connect(self.db_path) as conn:
            sql = "SELECT id, node_id, peer_id, content, embedding, metadata, created_at FROM episodic_memory"
            conditions = []
            params: list = []
            if node_id:
                conditions.append("node_id = ?")
                params.append(node_id)
            if peer_id:
                conditions.append("peer_id = ?")
                params.append(peer_id)
            if conditions:
                sql += " WHERE " + " AND ".join(conditions)
            rows = conn.execute(sql, params).fetchall()

        results = []
        for r in rows:
            mem = EpisodicMemory(
                id=r[0], node_id=r[1], peer_id=r[2], content=r[3],
                embedding=json.loads(r[4]), metadata=json.loads(r[5]),
                created_at=r[6],
            )
            sim = _cosine_sim(q_vec, mem.embedding)
            results.append((mem, sim))
        results.sort(key=lambda x: x[1], reverse=True)
        return results[:top_k]

    def save_conclusion(self, conc: HonchoConclusion):
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """INSERT OR REPLACE INTO honcho_conclusions
                   (id, node_id, peer_id, conclusion, confidence, metadata, created_at,
                    approved_by_human, shared, shared_at, ttl_expires_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (conc.id, conc.node_id, conc.peer_id, conc.conclusion,
                 conc.confidence, json.dumps(conc.metadata), conc.created_at,
                 int(conc.approved_by_human), int(conc.shared),
                 conc.shared_at, conc.ttl_expires_at),
            )
            conn.commit()

    def get_pending_conclusions(self) -> list[HonchoConclusion]:
        with self._lock, sqlite3.connect(self.db_path) as conn:
            rows = conn.execute(
                "SELECT id, node_id, peer_id, conclusion, confidence, metadata, created_at, "
                "approved_by_human, shared, shared_at, ttl_expires_at "
                "FROM honcho_conclusions WHERE approved_by_human = 0"
            ).fetchall()
        return [self._row_to_conclusion(r) for r in rows]

    def approve_conclusion(self, conc_id: str):
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute(
                "UPDATE honcho_conclusions SET approved_by_human = 1 WHERE id = ?",
                (conc_id,),
            )
            conn.commit()

    def get_approved_unshared_conclusions(self) -> list[HonchoConclusion]:
        with self._lock, sqlite3.connect(self.db_path) as conn:
            rows = conn.execute(
                "SELECT id, node_id, peer_id, conclusion, confidence, metadata, created_at, "
                "approved_by_human, shared, shared_at, ttl_expires_at "
                "FROM honcho_conclusions WHERE approved_by_human = 1 AND shared = 0"
            ).fetchall()
        return [self._row_to_conclusion(r) for r in rows]

    def mark_conclusion_shared(self, conc_id: str, ttl_hours: int):
        now = datetime.now(timezone.utc)
        expires = now + timedelta(hours=ttl_hours)
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute(
                "UPDATE honcho_conclusions SET shared = 1, shared_at = ?, ttl_expires_at = ? WHERE id = ?",
                (now.isoformat(), expires.isoformat(), conc_id),
            )
            conn.commit()

    def add_shared_memory(self, smem: SharedA2AMemory):
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute(
                """INSERT OR REPLACE INTO shared_a2a_memory
                   (id, conclusion_id, node_id, peer_id, content, ttl_expires_at, created_at, metadata)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (smem.id, smem.conclusion_id, smem.node_id, smem.peer_id,
                 smem.content, smem.ttl_expires_at, smem.created_at,
                 json.dumps(smem.metadata)),
            )
            conn.commit()

    def get_active_shared_memories(self) -> list[SharedA2AMemory]:
        now = datetime.now(timezone.utc).isoformat()
        with self._lock, sqlite3.connect(self.db_path) as conn:
            rows = conn.execute(
                "SELECT id, conclusion_id, node_id, peer_id, content, ttl_expires_at, created_at, metadata "
                "FROM shared_a2a_memory WHERE ttl_expires_at > ?",
                (now,),
            ).fetchall()
        return [
            SharedA2AMemory(
                id=r[0], conclusion_id=r[1], node_id=r[2], peer_id=r[3],
                content=r[4], ttl_expires_at=r[5], created_at=r[6],
                metadata=json.loads(r[7]),
            )
            for r in rows
        ]

    def cleanup_expired_shared(self):
        now = datetime.now(timezone.utc).isoformat()
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute("DELETE FROM shared_a2a_memory WHERE ttl_expires_at <= ?", (now,))
            conn.commit()

    def _row_to_conclusion(self, r) -> HonchoConclusion:
        return HonchoConclusion(
            id=r[0], node_id=r[1], peer_id=r[2], conclusion=r[3],
            confidence=r[4], metadata=json.loads(r[5]), created_at=r[6],
            approved_by_human=bool(r[7]), shared=bool(r[8]),
            shared_at=r[9], ttl_expires_at=r[10],
        )

    def get_sync_state(self, key: str) -> Optional[str]:
        with self._lock, sqlite3.connect(self.db_path) as conn:
            row = conn.execute(
                "SELECT value FROM sync_state WHERE key = ?", (key,)
            ).fetchone()
        return row[0] if row else None

    def set_sync_state(self, key: str, value: str):
        with self._lock, sqlite3.connect(self.db_path) as conn:
            conn.execute(
                "INSERT OR REPLACE INTO sync_state (key, value) VALUES (?, ?)",
                (key, value),
            )
            conn.commit()


def _cosine_sim(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = sum(x * x for x in a) ** 0.5
    nb = sum(y * y for y in b) ** 0.5
    if na == 0 or nb == 0:
        return 0.0
    return dot / (na * nb)


# ---------------------------------------------------------------------------
# Honcho L4 Client
# ---------------------------------------------------------------------------
class HonchoClient:
    """
    Client for Honcho L4. Falls back gracefully when Honcho is unavailable
    (e.g., only runs on Mac — SPOF). The bridge is optional.
    """

    def __init__(self, base_url: str, timeout: float = 30.0, enabled: bool = False):
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.enabled = enabled
        self._session = None

    def _get_session(self):
        if self._session is None:
            try:
                import requests
                self._session = requests.Session()
            except ImportError:
                log.warning("requests not available — Honcho client in stub mode")
        return self._session

    def is_available(self) -> bool:
        if not self.enabled:
            return False
        sess = self._get_session()
        if sess is None:
            return False
        try:
            r = sess.get(f"{self.base_url}/api/health", timeout=5)
            return r.status_code == 200
        except Exception:
            return False

    def ensure_user(self, node_id: str) -> bool:
        """Create or get a Honcho user for this mesh node identity."""
        if not self.is_available():
            return False
        sess = self._get_session()
        try:
            r = sess.post(
                f"{self.base_url}/api/users",
                json={"name": f"mesh_node_{node_id}"},
                timeout=self.timeout,
            )
            return r.status_code in (200, 201, 409)
        except Exception as e:
            log.warning(f"Honcho ensure_user failed: {e}")
            return False

    def add_document(self, node_id: str, doc: HonchoDocument) -> bool:
        """Upload a document to Honcho, preserving identity in metadata."""
        if not self.is_available():
            log.debug("Honcho unavailable — skipping document upload")
            return False
        sess = self._get_session()
        try:
            payload = doc.to_honcho_payload()
            r = sess.post(
                f"{self.base_url}/api/users/mesh_node_{node_id}/collections/a2a_mesh/documents",
                json=payload,
                timeout=self.timeout,
            )
            if r.status_code in (200, 201):
                log.info(f"Uploaded doc {doc.id[:8]} to Honcho for node={node_id}")
                return True
            log.warning(f"Honcho add_document status {r.status_code}: {r.text[:200]}")
            return False
        except Exception as e:
            log.warning(f"Honcho add_document failed: {e}")
            return False

    def get_conclusions(self, node_id: str) -> list[dict]:
        """Fetch derived conclusions from Honcho for a specific node identity."""
        if not self.is_available():
            return []
        sess = self._get_session()
        try:
            r = sess.get(
                f"{self.base_url}/api/users/mesh_node_{node_id}/collections/a2a_mesh/conclusions",
                timeout=self.timeout,
            )
            if r.status_code == 200:
                return r.json().get("conclusions", [])
            return []
        except Exception as e:
            log.warning(f"Honcho get_conclusions failed: {e}")
            return []

    def trigger_derive(self, node_id: str) -> bool:
        """Trigger Honcho's deriver to produce conclusions from conversation memories."""
        if not self.is_available():
            return False
        sess = self._get_session()
        try:
            r = sess.post(
                f"{self.base_url}/api/users/mesh_node_{node_id}/collections/a2a_mesh/derive",
                json={"deep_embedding": True},  # qwen3 at deep layer
                timeout=self.timeout * 2,
            )
            return r.status_code in (200, 202)
        except Exception as e:
            log.warning(f"Honcho trigger_derive failed: {e}")
            return False


# ---------------------------------------------------------------------------
# Sync Engine: mesh → Honcho (one-way delta sync)
# ---------------------------------------------------------------------------
class SyncEngine:
    """
    Daily delta sync: memory_episodic → Honcho documents.
    One-way (mesh → Honcho). Identity preserved per document.
    """

    def __init__(
        self,
        store: LocalMemoryStore,
        honcho: HonchoClient,
        config: BridgeConfig,
    ):
        self.store = store
        self.honcho = honcho
        self.config = config
        self._sync_lock = threading.Lock()

    def run_delta_sync(self) -> dict:
        """Sync unsynced episodic memories to Honcho. Returns stats."""
        stats = {"synced": 0, "failed": 0, "skipped": 0, "total": 0}
        with self._sync_lock:
            unsynced = self.store.get_unsynced(self.config.sync_batch_size)
            stats["total"] = len(unsynced)
            if not unsynced:
                log.info("Delta sync: nothing to sync")
                return stats

            if not self.honcho.is_available():
                log.info("Delta sync: Honcho unavailable — skipping (bridge is optional)")
                stats["skipped"] = len(unsynced)
                return stats

            for mem in unsynced:
                doc = HonchoDocument(
                    id=mem.id,
                    node_id=mem.node_id,
                    peer_id=mem.peer_id,
                    content=mem.content,
                    metadata=mem.metadata,
                    created_at=mem.created_at,
                )
                # Ensure user exists for this node identity
                self.honcho.ensure_user(mem.node_id)
                if self.honcho.add_document(mem.node_id, doc):
                    self.store.mark_synced(mem.id)
                    stats["synced"] += 1
                else:
                    stats["failed"] += 1

            # Record sync timestamp
            self.store.set_sync_state(
                "last_delta_sync", datetime.now(timezone.utc).isoformat()
            )
            log.info(f"Delta sync complete: {stats}")
        return stats

    def should_sync(self) -> bool:
        last = self.store.get_sync_state("last_delta_sync")
        if not last:
            return True
        try:
            last_dt = datetime.fromisoformat(last)
            elapsed = datetime.now(timezone.utc) - last_dt
            return elapsed >= timedelta(hours=self.config.sync_interval_hours)
        except Exception:
            return True

    def run_derive_and_collect(self) -> list[HonchoConclusion]:
        """Trigger Honcho deriver and collect conclusions (identity-tagged)."""
        if not self.honcho.is_available():
            log.info("Derive: Honcho unavailable — skipping")
            return []

        node_id = self.config.mesh_node_id
        if not self.honcho.trigger_derive(node_id):
            log.warning("Derive trigger failed")
            return []

        raw_conclusions = self.honcho.get_conclusions(node_id)
        conclusions = []
        for raw in raw_conclusions:
            # Identity is extracted from metadata — never mixed
            conc_node = raw.get("metadata", {}).get("mesh_node_id", node_id)
            conc_peer = raw.get("metadata", {}).get("mesh_peer_id", "unknown")
            conc = HonchoConclusion(
                id=raw.get("id", str(uuid.uuid4())),
                node_id=conc_node,
                peer_id=conc_peer,
                conclusion=raw.get("conclusion", ""),
                confidence=raw.get("confidence", 0.0),
                metadata=raw.get("metadata", {}),
                created_at=raw.get("created_at", datetime.now(timezone.utc).isoformat()),
            )
            self.store.save_conclusion(conc)
            conclusions.append(conc)
        log.info(f"Collected {len(conclusions)} conclusions from Honcho for node={node_id}")
        return conclusions


# ---------------------------------------------------------------------------
# Human Gate + Reverse Direction (Honcho → shared_a2a_memory)
# ---------------------------------------------------------------------------
class HumanGate:
    """
    Human gate for approving Honcho conclusions before sharing.
    Interactive CLI approval in standalone mode; programmatic in API mode.
    """

    def __init__(self, store: LocalMemoryStore, config: BridgeConfig):
        self.store = store
        self.config = config

    def get_pending(self) -> list[HonchoConclusion]:
        return self.store.get_pending_conclusions()

    def approve(self, conc_id: str):
        self.store.approve_conclusion(conc_id)
        log.info(f"Conclusion {conc_id[:8]} approved by human gate")

    def reject(self, conc_id: str):
        # Mark as not approved — simply leave it; could add a rejected flag
        log.info(f"Conclusion {conc_id[:8]} rejected (left unapproved)")

    def interactive_review(self) -> int:
        """CLI-based human gate review. Returns number approved."""
        pending = self.get_pending()
        if not pending:
            print("No pending conclusions for review.")
            return 0
        approved = 0
        print(f"\n{'='*60}")
        print(f"Human Gate: {len(pending)} conclusion(s) pending review")
        print(f"{'='*60}\n")
        for conc in pending:
            print(f"  ID:       {conc.id[:12]}...")
            print(f"  Node:     {conc.node_id}")
            print(f"  Peer:     {conc.peer_id}")
            print(f"  Confidence: {conc.confidence:.2f}")
            print(f"  Conclusion: {conc.conclusion[:200]}")
            print()
            choice = input("  Approve? [y/n/skip]: ").strip().lower()
            if choice == "y":
                self.approve(conc.id)
                approved += 1
            elif choice == "n":
                self.reject(conc.id)
            print()
        return approved


class SharedMemoryBridge:
    """
    Reverse direction: approved Honcho conclusions → shared_a2a_memory with TTL.
    This is the only way Honcho insights flow back to the mesh.
    """

    def __init__(self, store: LocalMemoryStore, config: BridgeConfig):
        self.store = store
        self.config = config

    def publish_approved(self) -> list[SharedA2AMemory]:
        """Publish human-approved, unshared conclusions to shared_a2a_memory."""
        if self.config.human_gate_required:
            approved = self.store.get_approved_unshared_conclusions()
        else:
            # If no human gate, auto-approve (not recommended for production)
            approved = self.store.get_approved_unshared_conclusions()

        published = []
        for conc in approved:
            smem = SharedA2AMemory(
                id=str(uuid.uuid4()),
                conclusion_id=conc.id,
                node_id=conc.node_id,
                peer_id=conc.peer_id,
                content=conc.conclusion,
                ttl_expires_at=(
                    datetime.now(timezone.utc) + timedelta(hours=self.config.shared_memory_ttl_hours)
                ).isoformat(),
                created_at=datetime.now(timezone.utc).isoformat(),
                metadata={
                    "confidence": conc.confidence,
                    "source": "honcho_l4",
                    **conc.metadata,
                },
            )
            self.store.add_shared_memory(smem)
            self.store.mark_conclusion_shared(conc.id, self.config.shared_memory_ttl_hours)
            published.append(smem)
            log.info(f"Published shared memory {smem.id[:8]} (TTL {self.config.shared_memory_ttl_hours}h)")
        return published

    def get_active(self) -> list[SharedA2AMemory]:
        """Get currently active shared memories (not expired)."""
        self.store.cleanup_expired_shared()
        return self.store.get_active_shared_memories()

    def cleanup(self):
        self.store.cleanup_expired_shared()


# ---------------------------------------------------------------------------
# Identity Manager — ensures identity is never mixed
# ---------------------------------------------------------------------------
class IdentityManager:
    """
    Ensures every memory, document, and conclusion carries its identity tag.
    The bridge only adds — never replaces or mixes node identities.
    """

    def __init__(self, node_id: str):
        self.node_id = node_id

    def tag_memory(self, peer_id: str, content: str, metadata: Optional[dict] = None) -> dict:
        """Prepare identity-tagged metadata for a new memory."""
        tagged = {
            "mesh_node_id": self.node_id,
            "mesh_peer_id": peer_id,
            "bridge_version": "1.0",
        }
        if metadata:
            tagged.update(metadata)
        return tagged

    def validate_identity(self, mem: EpisodicMemory) -> bool:
        """Verify a memory has proper identity tags."""
        return bool(mem.node_id and mem.peer_id)

    def validate_conclusion(self, conc: HonchoConclusion) -> bool:
        """Verify a conclusion has proper identity tags — never mixed."""
        return bool(conc.node_id and conc.peer_id)


# ---------------------------------------------------------------------------
# Main Bridge Orchestrator
# ---------------------------------------------------------------------------
class HonchoMemoryBridge:
    """
    Top-level orchestrator for the two-layer memory bridge.
    Coordinates: local memory, delta sync, deriver, human gate, shared memory.
    """

    def __init__(self, config: Optional[BridgeConfig] = None):
        self.config = config or BridgeConfig.from_env()
        self.nomic = NomicEmbedder(dim=self.config.embedding_dim)
        self.qwen3 = Qwen3Embedder(self.config.qwen3_model) if self.config.qwen3_enabled else None
        self.store = LocalMemoryStore(self.config.local_db_path, self.nomic)
        self.honcho = HonchoClient(
            base_url=self.config.honcho_base_url,
            timeout=self.config.honcho_timeout,
            enabled=self.config.honcho_enabled,
        )
        self.identity = IdentityManager(self.config.mesh_node_id)
        self.sync = SyncEngine(self.store, self.honcho, self.config)
        self.gate = HumanGate(self.store, self.config)
        self.shared = SharedMemoryBridge(self.store, self.config)

    # -- Core mesh operations (always work, independent of Honcho) --

    def remember(
        self,
        peer_id: