#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
P2P üzenetforgalom tömörítése (gzip/lz4) a szöveges payload-oknál.
~40% csökkenés a JSON serializációnál.

Ez a modul a A2A Mesh P2P üzenetek tömörítését valósítja meg,
támogatva gzip és lz4 algoritmusokat, automatikus választással
a payload mérete és típusa alapján.
"""

import gzip
import json
import zlib
import time
import struct
import hashlib
from typing import Any, Dict, Optional, Tuple, Union
from dataclasses import dataclass, field
from enum import IntEnum

# lz4 opcionális — ha nincs telepítve, gzip-re fallback
try:
    import lz4.frame as lz4_frame
    LZ4_AVAILABLE = True
except ImportError:
    LZ4_AVAILABLE = False


class CompressionAlgorithm(IntEnum):
    """Támogatott tömörítési algoritmusok."""
    NONE = 0
    GZIP = 1
    LZ4 = 2
    ZLIB = 3


# Header formátum: magic(4) + algo(1) + original_size(4) + compressed_size(4) + checksum(4) = 17 byte
MAGIC = b"A2AC"
HEADER_FORMAT = "<4sBIII"
HEADER_SIZE = struct.calcsize(HEADER_FORMAT)
COMPRESSION_THRESHOLD = 256  # 256 byte alatt nem éri meg tömöríteni


@dataclass
class CompressionStats:
    """Tömörítési statisztikák gyűjtése."""
    total_messages: int = 0
    compressed_messages: int = 0
    total_original_bytes: int = 0
    total_compressed_bytes: int = 0
    total_compression_time: float = 0.0
    total_decompression_time: float = 0.0
    algo_usage: Dict[str, int] = field(default_factory=dict)

    @property
    def avg_ratio(self) -> float:
        if self.total_original_bytes == 0:
            return 0.0
        return self.total_compressed_bytes / self.total_original_bytes

    @property
    def avg_savings(self) -> float:
        if self.total_original_bytes == 0:
            return 0.0
        return 1.0 - self.avg_ratio

    def reset(self) -> None:
        self.total_messages = 0
        self.compressed_messages = 0
        self.total_original_bytes = 0
        self.total_compressed_bytes = 0
        self.total_compression_time = 0.0
        self.total_decompression_time = 0.0
        self.algo_usage.clear()

    def __repr__(self) -> str:
        return (
            f"CompressionStats(messages={self.total_messages}, "
            f"compressed={self.compressed_messages}, "
            f"avg_savings={self.avg_savings:.1%}, "
            f"algo_usage={self.algo_usage})"
        )


class PayloadCompressor:
    """
    P2P payload tömörítő — gzip/lz4/zlib támogatással.

    Automatikusan választ algoritmust a payload mérete alapján:
    - < 256 byte: nincs tömörítés (overhead miatt)
    - 256 byte - 4KB: gzip (jobb arány kis méreteknél)
    - > 4KB: lz4 (ha elérhető, gyorsabb) vagy gzip
    """

    def __init__(
        self,
        default_algo: CompressionAlgorithm = CompressionAlgorithm.GZIP,
        compression_level: int = 6,
        threshold: int = COMPRESSION_THRESHOLD,
    ):
        self.default_algo = default_algo
        self.compression_level = compression_level
        self.threshold = threshold
        self.stats = CompressionStats()

    def _select_algorithm(self, data: bytes) -> CompressionAlgorithm:
        """Automatikus algoritmus választás a payload mérete alapján."""
        if len(data) < self.threshold:
            return CompressionAlgorithm.NONE

        if len(data) > 4096 and LZ4_AVAILABLE:
            return CompressionAlgorithm.LZ4

        return self.default_algo

    def _gzip_compress(self, data: bytes) -> bytes:
        return gzip.compress(data, compresslevel=self.compression_level)

    def _gzip_decompress(self, data: bytes) -> bytes:
        return gzip.decompress(data)

    def _lz4_compress(self, data: bytes) -> bytes:
        return lz4_frame.compress(
            data,
            compression_level=self.compression_level,
            content_checksum=True,
        )

    def _lz4_decompress(self, data: bytes) -> bytes:
        return lz4_frame.decompress(data)

    def _zlib_compress(self, data: bytes) -> bytes:
        return zlib.compress(data, self.compression_level)

    def _zlib_decompress(self, data: bytes) -> bytes:
        return zlib.decompress(data)

    def _checksum(self, data: bytes) -> int:
        return struct.unpack("I", hashlib.md5(data).digest()[:4])[0]

    def compress_payload(
        self,
        payload: Union[Dict[str, Any], str, bytes],
        algo: Optional[CompressionAlgorithm] = None,
    ) -> bytes:
        """
        Payload tömörítése P2P átvitelhez.

        Args:
            payload: JSON-serializálható dict, str vagy bytes
            algo: Opcionális algoritmus választás (None = automatikus)

        Returns:
            Tömörített bytes a A2AC header-rel
        """
        # Serialize to bytes
        if isinstance(payload, dict):
            raw = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        elif isinstance(payload, str):
            raw = payload.encode("utf-8")
        elif isinstance(payload, bytes):
            raw = payload
        else:
            raw = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")

        # Algoritmus választás
        if algo is None:
            algo = self._select_algorithm(raw)

        start = time.perf_counter()

        if algo == CompressionAlgorithm.NONE:
            compressed = raw
        elif algo == CompressionAlgorithm.GZIP:
            compressed = self._gzip_compress(raw)
        elif algo == CompressionAlgorithm.LZ4:
            compressed = self._lz4_compress(raw)
        elif algo == CompressionAlgorithm.ZLIB:
            compressed = self._zlib_compress(raw)
        else:
            compressed = raw
            algo = CompressionAlgorithm.NONE

        elapsed = time.perf_counter() - start

        # Csak tömörítsünk, ha kisebb lett
        if algo != CompressionAlgorithm.NONE and len(compressed) >= len(raw):
            algo = CompressionAlgorithm.NONE
            compressed = raw

        # Header építése
        checksum = self._checksum(raw)
        header = struct.pack(
            HEADER_FORMAT,
            MAGIC,
            int(algo),
            len(raw),
            len(compressed),
            checksum,
        )

        result = header + compressed

        # Statisztika
        self.stats.total_messages += 1
        if algo != CompressionAlgorithm.NONE:
            self.stats.compressed_messages += 1
        self.stats.total_original_bytes += len(raw)
        self.stats.total_compressed_bytes += len(compressed)
        self.stats.total_compression_time += elapsed
        algo_name = algo.name
        self.stats.algo_usage[algo_name] = self.stats.algo_usage.get(algo_name, 0) + 1

        return result

    def decompress_payload(self, data: bytes) -> Tuple[Union[Dict[str, Any], str, bytes], CompressionAlgorithm]:
        """
        Tömörített payload kicsomagolása.

        Args:
            data: A2AC header + tömörített adat

        Returns:
            (eredeti_payload, algoritmus) tuple
        """
        if len(data) < HEADER_SIZE:
            raise ValueError(f"Data too short for header: {len(data)} < {HEADER_SIZE}")

        magic, algo_int, orig_size, comp_size, checksum = struct.unpack(
            HEADER_FORMAT, data[:HEADER_SIZE]
        )

        if magic != MAGIC:
            raise ValueError(f"Invalid magic bytes: {magic}")

        algo = CompressionAlgorithm(algo_int)
        compressed = data[HEADER_SIZE:HEADER_SIZE + comp_size]

        start = time.perf_counter()

        if algo == CompressionAlgorithm.NONE:
            raw = compressed
        elif algo == CompressionAlgorithm.GZIP:
            raw = self._gzip_decompress(compressed)
        elif algo == CompressionAlgorithm.LZ4:
            raw = self._lz4_decompress(compressed)
        elif algo == CompressionAlgorithm.ZLIB:
            raw = self._zlib_decompress(compressed)
        else:
            raise ValueError(f"Unknown algorithm: {algo}")

        elapsed = time.perf_counter() - start
        self.stats.total_decompression_time += elapsed

        # Ellenőrzés
        if len(raw) != orig_size:
            raise ValueError(
                f"Size mismatch: expected {orig_size}, got {len(raw)}"
            )

        actual_checksum = self._checksum(raw)
        if actual_checksum != checksum:
            raise ValueError(
                f"Checksum mismatch: expected {checksum}, got {actual_checksum}"
            )

        # Próbáljuk JSON-ként visszaolvasni
        try:
            text = raw.decode("utf-8")
            try:
                return json.loads(text), algo
            except json.JSONDecodeError:
                return text, algo
        except UnicodeDecodeError:
            return raw, algo

    def compress_message(
        self,
        message: Dict[str, Any],
        algo: Optional[CompressionAlgorithm] = None,
    ) -> bytes:
        """
        A2A Mesh üzenet tömörítése.
        Convenience wrapper compress_payload-hoz.
        """
        return self.compress_payload(message, algo=algo)

    def decompress_message(self, data: bytes) -> Dict[str, Any]:
        """
        A2A Mesh üzenet kicsomagolása.
        Convenience wrapper decompress_payload-hoz, dict-et ad vissza.
        """
        payload, algo = self.decompress_payload(data)
        if isinstance(payload, dict):
            return payload
        raise ValueError(f"Expected dict, got {type(payload)}")


class CompressedMessageEnvelope:
    """
    A2A Mesh kompatibilis üzenet-boríték tömörített payload-dal.

    Struktúra:
    {
        "version": "1.0",
        "compressed": true,
        "algorithm": "gzip",
        "payload_size": 1234,
        "original_size": 2000,
        "payload": "<base64 tömörített adat>",
        "checksum": "abc123"
    }
    """

    def __init__(self, compressor: Optional[PayloadCompressor] = None):
        self.compressor = compressor or PayloadCompressor()

    def wrap(self, message: Dict[str, Any]) -> Dict[str, Any]:
        """Üzenet tömörítése és borítékba csomagolása."""
        compressed = self.compressor.compress_message(message)

        # Header kinyerése
        magic, algo_int, orig_size, comp_size, checksum = struct.unpack(
            HEADER_FORMAT, compressed[:HEADER_SIZE]
        )

        import base64

        algo = CompressionAlgorithm(algo_int)

        return {
            "version": "1.0",
            "compressed": algo != CompressionAlgorithm.NONE,
            "algorithm": algo.name,
            "payload_size": comp_size,
            "original_size": orig_size,
            "payload": base64.b64encode(compressed).decode("ascii"),
            "header_size": HEADER_SIZE,
        }

    def unwrap(self, envelope: Dict[str, Any]) -> Dict[str, Any]:
        """Boríték kicsomagolása és üzenet visszaolvasása."""
        import base64

        if not envelope.get("compressed", False):
            # Nem volt tömörítve — payload maga az üzenet
            if "payload" in envelope:
                raw = base64.b64decode(envelope["payload"])
                return json.loads(raw.decode("utf-8"))

        compressed = base64.b64decode(envelope["payload"])
        return self.compressor.decompress_message(compressed)


# ─── P2P Transport Layer Integration ──────────────────────────────────────────

class P2PCompressedTransport:
    """
    P2P transport réteg tömörítéssel.
    Drop-in replacement a sima JSON transport-hoz.
    """

    def __init__(
        self,
        algo: CompressionAlgorithm = CompressionAlgorithm.GZIP,
        level: int = 6,
    ):
        self.compressor = PayloadCompressor(default_algo=algo, compression_level=level)
        self.envelope = CompressedMessageEnvelope(self.compressor)
        self._sent_bytes = 0
        self._saved_bytes = 0

    def send(self, message: Dict[str, Any]) -> bytes:
        """Üzenet tömörítése és 'küldése' (bytes visszaadás)."""
        compressed = self.compressor.compress_message(message)
        # Header-ből eredeti méret
        _, _, orig_size, comp_size, _ = struct.unpack(
            HEADER_FORMAT, compressed[:HEADER_SIZE]
        )
        self._sent_bytes += comp_size + HEADER_SIZE
        self._saved_bytes += max(0, orig_size - comp_size)
        return compressed

    def receive(self, data: bytes) -> Dict[str, Any]:
        """Tömörített üzenet fogadása és kicsomagolása."""
        return self.compressor.decompress_message(data)

    @property
    def bandwidth_saved(self) -> float:
        total = self._sent_bytes + self._saved_bytes
        if total == 0:
            return 0.0
        return self._saved_bytes / total

    def stats_report(self) -> str:
        s = self.compressor.stats
        return (
            f"\n{'='*60}\n"
            f"P2P Compression Transport Report\n"
            f"{'='*60}\n"
            f"  Total messages:      {s.total_messages}\n"
            f"  Compressed messages: {s.compressed_messages}\n"
            f"  Original bytes:      {s.total_original_bytes:,}\n"
            f"  Compressed bytes:    {s.total_compressed_bytes:,}\n"
            f"  Bandwidth saved:     {self._saved_bytes:,} bytes ({self.bandwidth_saved:.1%})\n"
            f"  Avg compression:     {s.avg_savings:.1%}\n"
            f"  Avg compress time:   {s.total_compression_time/max(s.total_messages,1)*1000:.2f} ms\n"
            f"  Avg decompress time: {s.total_decompression_time/max(s.total_messages,1)*1000:.2f} ms\n"
            f"  Algorithm usage:     {s.algo_usage}\n"
            f"  LZ4 available:       {LZ4_AVAILABLE}\n"
            f"{'='*60}"
        )


# ─── Demo / Test ──────────────────────────────────────────────────────────────

def _generate_sample_a2a_messages() -> list:
    """Generál tipikus A2A Mesh üzeneteket demo célokra."""
    messages = []

    # 1. Task delegation message
    messages.append({
        "type": "task_delegate",
        "from": "nova",
        "to": "runa",
        "task_id": "task_abc123",
        "skill": "code_generation",
        "context": {
            "repo": "a2a_mesh",
            "branch": "main",
            "files": ["src/mesh.py", "src/transport.py", "src/agent.py"],
            "requirements": [
                "Generate complete working code",
                "No placeholders",
                "Include all imports",
            ],
        },
        "priority": "high",
        "timeout": 300,
        "metadata": {
            "created_at": "2024-01-15T10:30:00Z",
            "trace_id": "trace_xyz789",
            "parent_task": "task_parent_001",
        },
    })

    # 2. Agent capability advertisement
    messages.append({
        "type": "agent_advertise",
        "agent_id": "runa",
        "agent_name": "Runa",
        "capabilities": [
            {"skill": "code_generation", "proficiency": 0.95, "max_concurrent": 3},
            {"skill": "code_review", "proficiency": 0.88, "max_concurrent": 5},
            {"skill": "documentation", "proficiency": 0.82, "max_concurrent": 4},
            {"skill": "testing", "proficiency": 0.90, "max_concurrent": 3},
        ],
        "status": "available",
        "load": {"cpu": 0.35, "memory": 0.42, "tasks": 2},
        "heartbeat_interval": 30,
        "version": "1.2.0",
    })

    # 3. Heartbeat message
    messages.append({
        "type": "heartbeat",
        "agent_id": "runa",
        "timestamp": "2024-01-15T10:30:05Z",
        "status": "alive",
        "load": {"cpu": 0.35, "memory": 0.42, "tasks": 2},
        "uptime": 3600,
    })

    # 4. Large context message (skill result)
    large_context = {
        "type": "task_result",
        "task_id": "task_abc123",
        "from": "runa",
        "to": "nova",
        "status": "completed",
        "result": {
            "files_modified": ["src/compression.py", "src/transport.py"],
            "diff": "\n".join([
                f"--- a/src/file_{i}.py" for i in range(50)
            ] + [
                f"+++ b/src/file_{i}.py" for i in range(50)
            ] + [
                f"@@ -{i},10 +{i},15 @@" for i in range(50)
            ] + [
                f" +    new_line_{i} = 'data_{i}'" for i in range(200)
            ]),
            "summary": "Implemented P2P message compression with gzip/lz4 support. "
                       "Added PayloadCompressor class with automatic algorithm selection. "
                       "Integrated with P2PCompressedTransport for seamless drop-in replacement. "
                       "Achieved approximately 40% bandwidth reduction on JSON payloads.",
            "metrics": {
                "lines_added": 250,
                "lines_removed": 12,
                "files_changed": 2,
                "test_coverage": 0.92,
            },
        },
    }
    messages.append(large_context)

    # 5. Mesh topology update
    messages.append({
        "type": "topology_update",
        "from": "mesh_coordinator",
        "nodes": [
            {
                "id": f"node_{i:03d}",
                "address": f"192.168.1.{100+i}:8080",
                "status": "active" if i % 5 != 0 else "standby",
                "capabilities": ["code_gen", "review", "test"] if i % 3 == 0 else ["code_gen"],
                "load": {"cpu": i * 0.1 % 1.0, "memory": i * 0.07 % 1.0},
            }
            for i in range(30)
        ],
        "version": 42,
        "timestamp": "2024-01-15T10:30:10Z",
    })

    return messages


def _benchmark_algorithms(messages: list) -> Dict[str, Dict]:
    """Benchmark különböző algoritmusokkal."""
    results = {}

    for algo_name, algo in [
        ("NONE", CompressionAlgorithm.NONE),
        ("GZIP-1", CompressionAlgorithm.GZIP),  # will use level from compressor
        ("ZLIB", CompressionAlgorithm.ZLIB),
    ] + ([("LZ4", CompressionAlgorithm.LZ4)] if LZ4_AVAILABLE else []):
        comp = PayloadCompressor(
            default_algo=algo,
            compression_level=6 if algo != CompressionAlgorithm.LZ4 else 6,
        )
        total_orig = 0
        total_comp = 0
        total_ctime = 0
        total_dtime = 0

        for msg in messages:
            raw = json.dumps(msg, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
            total_orig += len(raw)

            t0 = time.perf_counter()
            compressed = comp.compress_message(msg, algo=algo if algo != CompressionAlgorithm.NONE else CompressionAlgorithm.NONE)
            t1 = time.perf_counter()
            total_ctime += t1 - t0

            _, _, orig_s, comp_s, _ = struct.unpack(HEADER_FORMAT, compressed[:HEADER_SIZE])
            total_comp += comp_s

            t2 = time.perf_counter()
            _ = comp.decompress_message(compressed)
            t3 = time.perf_counter()
            total_dtime += t3 - t2

        ratio = total_comp / total_orig if total_orig > 0 else 0
        results[algo_name] = {
            "original_bytes": total_orig,
            "compressed_bytes": total_comp,
            "ratio": ratio,
            "savings": 1 - ratio,
            "compress_ms": total_ctime * 1000,
            "decompress_ms": total_dtime * 1000,
        }

    return results


def main():
    """Demo és benchmark futtatás."""
    print("=" * 60)
    print("A2A Mesh — P2P Payload Compression Demo")
    print("Generated by runa via A2A Mesh delegation")
    print("=" * 60)

    # Sample üzenetek generálása
    messages = _generate_sample_a2a_messages()
    print(f"\nGenerated {len(messages)} sample A2A Mesh messages")

    # Transport demo
    transport = P2PCompressedTransport(
        algo=CompressionAlgorithm.GZIP,
        level=6,
    )

    print("\n--- Round-trip Test ---")
    for i, msg in enumerate(messages):
        compressed = transport.send(msg)
        decompressed = transport.receive(compressed)
        assert decompressed == msg, f"Round-trip failed for message {i}!"
        orig_json = json.dumps(msg, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        _, _, orig_size, comp_size, _ = struct.unpack(
            HEADER_FORMAT, compressed[:HEADER_SIZE]
        )
        savings = 1 - (comp_size / orig_size) if orig_size > 0 else 0
        print(
            f"  Message {i+1} ({msg['type']:20s}): "
            f"{orig_size:>7,} -> {comp_size:>7,} bytes "
            f"({savings:>5.1%} savings) ✓"
        )

    print(transport.stats_report())

    # Benchmark
    print("\n--- Algorithm Benchmark ---")
    results = _benchmark_algorithms(messages)

    print(f"\n{'Algorithm':<12} {'Original':>12} {'Compressed':>12} {'Savings':>10} {'Cmp(ms)':>10} {'Dcmp(ms)':>10}")
    print("-" * 70)
    for name, r in results.items():
        print(
            f"{name:<12} {r['original_bytes']:>12,} {r['compressed_bytes']:>12,} "
            f"{r['savings']:>9.1%} {r['compress_ms']:>9.2f} {r['decompress_ms']:>9.2f}"
        )

    # Envelope demo
    print("\n--- Envelope Demo ---")
    env = CompressedMessageEnvelope()
    test_msg = messages[0]
    wrapped = env.wrap(test_msg)
    print(f"  Original message size: {len(json.dumps(test_msg)):,} bytes")
    print(f"  Envelope payload size: {wrapped['payload_size']:,} bytes")
    print(f"  Algorithm: {wrapped['algorithm']}")
    print(f"  Savings: {1 - wrapped['payload_size']/wrapped['original_size']:.1%}")

    unwrapped = env.unwrap(wrapped)
    assert unwrapped == test_msg, "Envelope round-trip failed!"
    print("  Round-trip: ✓")

    # Stress test — sok üzenet
    print("\n--- Stress Test (1000 messages) ---")
    stress_transport = P2PCompressedTransport()
    stress_msgs = messages * 200  # 1000 üzenet
    t0 = time.perf_counter()
    for msg in stress_msgs:
        compressed = stress_transport.send(msg)
        _ = stress_transport.receive(compressed)
    elapsed = time.perf_counter() - t0
    print(f"  1000 messages compressed + decompressed in {elapsed:.3f}s")
    print(f"  Throughput: {1000/elapsed:.0f} msg/s")
    print(stress_transport.stats_report())

    print("\n✓ All tests passed!")


if __name__ == "__main__":
    main()