#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
Adaptive Rhythm: traffic-based interval scaling + P2P message batching.

Replaces fixed heartbeat + polling with:
  - Adaptive interval scaling: heartbeat interval grows/shrinks based on
    observed message traffic (more traffic -> shorter interval, less -> longer).
  - P2P message batching: outgoing messages to the same peer are batched
    into a single envelope and flushed on a timer or when batch is full.

This module is self-contained and runnable from the repo root:
    python runa_adaptive_rhythm.py
"""

from __future__ import annotations

import asyncio
import dataclasses
import hashlib
import json
import logging
import random
import time
from collections import defaultdict, deque
from dataclasses import dataclass, field
from typing import Any, Awaitable, Callable, Deque, Dict, List, Optional, Set, Tuple

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)-14s] %(levelname)-5s %(message)s",
)
log = logging.getLogger("adaptive_rhythm")

# ---------------------------------------------------------------------------
# Configuration constants
# ---------------------------------------------------------------------------

MIN_INTERVAL: float = 0.5       # seconds — fastest heartbeat when traffic is high
MAX_INTERVAL: float = 15.0      # seconds — slowest heartbeat when idle
DEFAULT_INTERVAL: float = 5.0   # starting interval
BATCH_MAX_SIZE: int = 32        # max messages per batch envelope
BATCH_MAX_AGE: float = 0.8      # seconds before a partial batch is flushed
SCALE_UP_FACTOR: float = 0.6    # multiply interval by this when traffic increases
SCALE_DOWN_FACTOR: float = 1.4  # multiply interval by this when traffic decreases
TRAFFIC_WINDOW: int = 20        # number of heartbeat cycles to average traffic over
HIGH_TRAFFIC_THRESHOLD: float = 8.0   # msgs/cycle above this -> scale up (shorter)
LOW_TRAFFIC_THRESHOLD: float = 1.0    # msgs/cycle below this -> scale down (longer)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class Message:
    """A single P2P message addressed to a peer."""
    id: str
    sender: str
    recipient: str
    payload: Dict[str, Any]
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return dataclasses.asdict(self)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Message":
        return cls(**d)


@dataclass
class BatchEnvelope:
    """A batch of messages destined for the same recipient."""
    recipient: str
    messages: List[Message]
    batch_id: str
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "recipient": self.recipient,
            "batch_id": self.batch_id,
            "created_at": self.created_at,
            "messages": [m.to_dict() for m in self.messages],
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "BatchEnvelope":
        return cls(
            recipient=d["recipient"],
            batch_id=d["batch_id"],
            created_at=d.get("created_at", time.time()),
            messages=[Message.from_dict(m) for m in d["messages"]],
        )


# ---------------------------------------------------------------------------
# Traffic tracker — sliding window of messages-per-cycle
# ---------------------------------------------------------------------------

class TrafficTracker:
    """Tracks message counts per heartbeat cycle using a sliding window."""

    def __init__(self, window_size: int = TRAFFIC_WINDOW) -> None:
        self._window: Deque[int] = deque(maxlen=window_size)
        self._current_count: int = 0

    def record_message(self) -> None:
        self._current_count += 1

    def end_cycle(self) -> int:
        """Finalize the current cycle and return its message count."""
        self._window.append(self._current_count)
        self._current_count = 0
        return self._window[-1]

    @property
    def average(self) -> float:
        if not self._window:
            return 0.0
        return sum(self._window) / len(self._window)

    @property
    def last(self) -> int:
        return self._window[-1] if self._window else 0


# ---------------------------------------------------------------------------
# Adaptive interval controller
# ---------------------------------------------------------------------------

class AdaptiveInterval:
    """
    Computes the next heartbeat interval based on traffic.

    - High traffic  -> shorter interval (faster heartbeat, quicker batching flush)
    - Low traffic   -> longer interval  (less overhead, fewer empty heartbeats)
    - Bounds kept within [MIN_INTERVAL, MAX_INTERVAL].
    """

    def __init__(
        self,
        initial: float = DEFAULT_INTERVAL,
        tracker: Optional[TrafficTracker] = None,
    ) -> None:
        self.current: float = initial
        self.tracker: TrafficTracker = tracker or TrafficTracker()

    def update(self) -> float:
        """Call at the end of each heartbeat cycle. Returns the new interval."""
        cycle_count = self.tracker.end_cycle()
        avg = self.tracker.average

        if avg >= HIGH_TRAFFIC_THRESHOLD:
            self.current *= SCALE_UP_FACTOR
            reason = f"high traffic ({avg:.1f} avg) -> shorter"
        elif avg <= LOW_TRAFFIC_THRESHOLD:
            self.current *= SCALE_DOWN_FACTOR
            reason = f"low traffic ({avg:.1f} avg) -> longer"
        else:
            reason = f"stable traffic ({avg:.1f} avg) -> keep"

        self.current = max(MIN_INTERVAL, min(MAX_INTERVAL, self.current))
        log.debug(
            "interval update: cycle_msgs=%d avg=%.1f new=%.2fs (%s)",
            cycle_count, avg, self.current, reason,
        )
        return self.current


# ---------------------------------------------------------------------------
# Message batcher — accumulates messages per recipient, flushes on size/age
# ---------------------------------------------------------------------------

class MessageBatcher:
    """
    Buffers outgoing messages per-recipient and flushes them as BatchEnvelopes
    when the batch is full (BATCH_MAX_SIZE) or aged (BATCH_MAX_AGE).
    """

    def __init__(self) -> None:
        self._buffers: Dict[str, List[Message]] = defaultdict(list)
        self._first_seen: Dict[str, float] = {}

    def add(self, msg: Message) -> None:
        self._buffers[msg.recipient].append(msg)
        if msg.recipient not in self._first_seen:
            self._first_seen[msg.recipient] = time.time()

    def add_many(self, msgs: List[Message]) -> None:
        for m in msgs:
            self.add(m)

    def flush_ready(self) -> List[BatchEnvelope]:
        """Return envelopes that are full or aged, and remove them from buffers."""
        now = time.time()
        ready: List[BatchEnvelope] = []

        for recipient in list(self._buffers.keys()):
            buf = self._buffers[recipient]
            if not buf:
                continue
            age = now - self._first_seen.get(recipient, now)
            if len(buf) >= BATCH_MAX_SIZE or age >= BATCH_MAX_AGE:
                batch_id = hashlib.sha256(
                    f"{recipient}:{now}:{random.random()}".encode()
                ).hexdigest()[:12]
                envelope = BatchEnvelope(
                    recipient=recipient,
                    messages=list(buf),
                    batch_id=batch_id,
                )
                ready.append(envelope)
                self._buffers[recipient] = []
                self._first_seen.pop(recipient, None)

        return ready

    def flush_all(self) -> List[BatchEnvelope]:
        """Force-flush all buffers (e.g. on shutdown)."""
        ready: List[BatchEnvelope] = []
        for recipient, buf in self._buffers.items():
            if not buf:
                continue
            batch_id = hashlib.sha256(
                f"{recipient}:{time.time()}:{random.random()}".encode()
            ).hexdigest()[:12]
            ready.append(BatchEnvelope(
                recipient=recipient,
                messages=list(buf),
                batch_id=batch_id,
            ))
        self._buffers.clear()
        self._first_seen.clear()
        return ready

    @property
    def pending_count(self) -> int:
        return sum(len(buf) for buf in self._buffers.values())


# ---------------------------------------------------------------------------
# Peer — a node in the mesh that uses adaptive rhythm
# ---------------------------------------------------------------------------

SendCallback = Callable[[BatchEnvelope], Awaitable[None]]
ReceiveCallback = Callable[[BatchEnvelope], Awaitable[None]]


class Peer:
    """
    A single P2P mesh node with adaptive heartbeat + message batching.

    Lifecycle:
      1. send(msg)      — queues a message (batched by recipient)
      2. heartbeat()    — flushes ready batches, delivers received batches,
                          updates adaptive interval
      3. receive(env)   — accepts an incoming batch envelope from another peer
    """

    def __init__(
        self,
        name: str,
        send_cb: Optional[SendCallback] = None,
        receive_cb: Optional[ReceiveCallback] = None,
    ) -> None:
        self.name: str = name
        self.batcher: MessageBatcher = MessageBatcher()
        self.traffic: TrafficTracker = TrafficTracker()
        self.interval_ctrl: AdaptiveInterval = AdaptiveInterval(tracker=self.traffic)
        self._send_cb: Optional[SendCallback] = send_cb
        self._receive_cb: Optional[ReceiveCallback] = receive_cb
        self.received: List[BatchEnvelope] = []
        self.sent: List[BatchEnvelope] = []
        self.running: bool = False
        self._heartbeat_task: Optional[asyncio.Task] = None

    # -- message production --------------------------------------------------

    def send(self, recipient: str, payload: Dict[str, Any]) -> Message:
        msg = Message(
            id=hashlib.sha256(
                f"{self.name}:{recipient}:{time.time()}:{random.random()}".encode()
            ).hexdigest()[:12],
            sender=self.name,
            recipient=recipient,
            payload=payload,
        )
        self.batcher.add(msg)
        self.traffic.record_message()
        return msg

    # -- heartbeat -----------------------------------------------------------

    async def heartbeat_once(self) -> List[BatchEnvelope]:
        """Execute one heartbeat cycle: flush + deliver + adapt."""
        # Flush ready batches
        envelopes = self.batcher.flush_ready()
        for env in envelopes:
            self.sent.append(env)
            if self._send_cb:
                try:
                    await self._send_cb(env)
                except Exception as exc:
                    log.warning("%s send_cb error: %s", self.name, exc)

        # Deliver any received envelopes
        while self.received:
            env = self.received.pop(0)
            if self._receive_cb:
                try:
                    await self._receive_cb(env)
                except Exception as exc:
                    log.warning("%s receive_cb error: %s", self.name, exc)

        # Adapt interval
        new_interval = self.interval_ctrl.update()
        log.info(
            "%s heartbeat: flushed=%d pending=%d next_interval=%.2fs",
            self.name, len(envelopes), self.batcher.pending_count, new_interval,
        )
        return envelopes

    async def _heartbeat_loop(self) -> None:
        self.running = True
        while self.running:
            await self.heartbeat_once()
            await asyncio.sleep(self.interval_ctrl.current)

    def start(self) -> asyncio.Task:
        self._heartbeat_task = asyncio.create_task(self._heartbeat_loop())
        return self._heartbeat_task

    async def stop(self) -> None:
        self.running = False
        if self._heartbeat_task:
            self._heartbeat_task.cancel()
            try:
                await self._heartbeat_task
            except asyncio.CancelledError:
                pass
        # Final flush
        final = self.batcher.flush_all()
        for env in final:
            self.sent.append(env)
            if self._send_cb:
                await self._send_cb(env)
        log.info("%s stopped, final flush=%d", self.name, len(final))

    # -- receiving -----------------------------------------------------------

    def receive(self, env: BatchEnvelope) -> None:
        self.received.append(env)


# ---------------------------------------------------------------------------
# Simulated mesh — wires peers together with in-memory send callbacks
# ---------------------------------------------------------------------------

class SimulatedMesh:
    """
    A minimal in-memory P2P mesh that connects Peer instances.
    send_cb routes envelopes to the recipient peer's receive() queue.
    """

    def __init__(self) -> None:
        self.peers: Dict[str, Peer] = {}

    def add_peer(self, name: str) -> Peer:
        def send_cb(env: BatchEnvelope) -> Awaitable[None]:
            recipient = self.peers.get(env.recipient)
            if recipient:
                recipient.receive(env)
                log.debug("mesh: %s -> %s (%d msgs)", env.batch_id[:6], env.recipient, len(env.messages))
            else:
                log.warning("mesh: unknown recipient %s", env.recipient)
            return _noop()

        def receive_cb(env: BatchEnvelope) -> Awaitable[None]:
            for msg in env.messages:
                log.debug(
                    "  %s received from %s: %s",
                    name, msg.sender, msg.payload.get("type", "?"),
                )
            return _noop()

        peer = Peer(name=name, send_cb=send_cb, receive_cb=receive_cb)
        self.peers[name] = peer
        return peer

    def start_all(self) -> List[asyncio.Task]:
        tasks = []
        for peer in self.peers.values():
            tasks.append(peer.start())
        return tasks

    async def stop_all(self) -> None:
        await asyncio.gather(*[p.stop() for p in self.peers.values()], return_exceptions=True)


async def _noop() -> None:
    """No-op coroutine used as a default callback."""
    return None


# ---------------------------------------------------------------------------
# Demo / simulation
# ---------------------------------------------------------------------------

async def run_demo() -> None:
    """
    Demonstrates adaptive rhythm with 3 peers.

    Phase 1 (burst):  high traffic — interval should shrink toward MIN_INTERVAL.
    Phase 2 (idle):   no traffic  — interval should grow toward MAX_INTERVAL.
    Phase 3 (mixed):  moderate traffic — interval stabilizes.
    """
    log.info("=== Adaptive Rhythm Demo ===")
    mesh = SimulatedMesh()
    alice = mesh.add_peer("alice")
    bob = mesh.add_peer("bob")
    carol = mesh.add_peer("carol")

    tasks = mesh.start_all()
    log.info("Mesh started with %d peers", len(mesh.peers))

    # --- Phase 1: burst traffic ---
    log.info("--- Phase 1: BURST traffic (many messages) ---")
    for i in range(60):
        sender = random.choice(["alice", "bob", "carol"])
        recipient = random.choice([p for p in mesh.peers if p != sender])
        mesh.peers[sender].send(recipient, {"type": "ping", "seq": i})
        await asyncio.sleep(0.02)

    await asyncio.sleep(3.0)

    # --- Phase 2: idle ---
    log.info("--- Phase 2: IDLE (no messages) ---")
    await asyncio.sleep(8.0)

    # --- Phase 3: moderate ---
    log.info("--- Phase 3: MODERATE traffic ---")
    for i in range(20):
        sender = random.choice(["alice", "bob", "carol"])
        recipient = random.choice([p for p in mesh.peers if p != sender])
        mesh.peers[sender].send(recipient, {"type": "data", "seq": i})
        await asyncio.sleep(0.3)

    await asyncio.sleep(4.0)

    # --- Summary ---
    log.info("=== Summary ===")
    for name, peer in mesh.peers.items():
        total_sent_msgs = sum(len(e.messages) for e in peer.sent)
        total_received = len(peer.received)
        log.info(
            "  %s: batches_sent=%d msgs_sent=%d received_pending=%d "
            "final_interval=%.2fs avg_traffic=%.1f",
            name,
            len(peer.sent),
            total_sent_msgs,
            total_received,
            peer.interval_ctrl.current,
            peer.traffic.average,
        )

    await mesh.stop_all()
    for t in tasks:
        t.cancel()
    log.info("=== Demo complete ===")


# ---------------------------------------------------------------------------
# Unit-style self-test (runs without asyncio if needed, but we use asyncio)
# ---------------------------------------------------------------------------

def _self_test() -> None:
    """Synchronous sanity checks for core components."""
    log.info("Running self-test...")

    # Traffic tracker
    tt = TrafficTracker(window_size=5)
    for _ in range(10):
        tt.record_message()
    assert tt.end_cycle() == 10
    assert tt.average == 10.0
    tt.end_cycle()  # 0 messages
    assert tt.last == 0

    # Adaptive interval — high traffic shrinks
    tt2 = TrafficTracker(window_size=5)
    ai = AdaptiveInterval(initial=5.0, tracker=tt2)
    for _ in range(10):
        for _ in range(20):
            tt2.record_message()
        ai.update()
    assert ai.current < 5.0, f"Expected shorter interval, got {ai.current}"
    assert ai.current >= MIN_INTERVAL

    # Adaptive interval — low traffic grows
    tt3 = TrafficTracker(window_size=5)
    ai3 = AdaptiveInterval(initial=5.0, tracker=tt3)
    for _ in range(10):
        ai3.update()  # 0 messages each cycle
    assert ai3.current > 5.0, f"Expected longer interval, got {ai3.current}"
    assert ai3.current <= MAX_INTERVAL

    # Message batcher — size flush
    mb = MessageBatcher()
    for i in range(BATCH_MAX_SIZE):
        mb.add(Message(id=f"m{i}", sender="a", recipient="b", payload={"i": i}))
    ready = mb.flush_ready()
    assert len(ready) == 1
    assert len(ready[0].messages) == BATCH_MAX_SIZE
    assert mb.pending_count == 0

    # Message batcher — age flush
    mb2 = MessageBatcher()
    mb2.add(Message(id="x", sender="a", recipient="b", payload={}))
    assert len(mb2.flush_ready()) == 0  # not aged yet
    time.sleep(BATCH_MAX_AGE + 0.1)
    ready2 = mb2.flush_ready()
    assert len(ready2) == 1
    assert len(ready2[0].messages) == 1

    # Serialization round-trip
    env = BatchEnvelope(recipient="b", messages=[
        Message(id="1", sender="a", recipient="b", payload={"k": "v"})
    ], batch_id="test123")
    env_json = json.dumps(env.to_dict())
    env_restored = BatchEnvelope.from_dict(json.loads(env_json))
    assert env_restored.recipient == "b"
    assert env_restored.batch_id == "test123"
    assert env_restored.messages[0].payload == {"k": "v"}

    log.info("Self-test PASSED ✓")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    _self_test()
    asyncio.run(run_demo())