#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generated by morzsa via A2A Mesh delegation

Heti mesh-egészségriport: vasárnaponként egy cron összegyűjti mind a 4 node
állapotát (memória/swap, lemez, PG replikáció-lag, offline queue mélység,
heartbeat kiesések) és PG-be írja. Alert csak hiba esetén megy TG-re, siker
esetén néma.

idea_id: idea_82af0d5d8f4d
Beküldte: nova
"""

import os
import sys
import json
import time
import socket
import logging
import subprocess
import argparse
from datetime import datetime, timezone, timedelta
from pathlib import Path

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
log = logging.getLogger("health_report")

# ---------------------------------------------------------------------------
# Configuration — environment variables with sensible defaults
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent

# Node definitions — 4 nodes in the mesh
DEFAULT_NODES = [
    {"name": "morzsa",  "host": os.getenv("NODE_MORZSA_HOST",  "morzsa.local"),  "pg_port": 5432},
    {"name": "nova",    "host": os.getenv("NODE_NOVA_HOST",    "nova.local"),    "pg_port": 5432},
    {"name": "echo",    "host": os.getenv("NODE_ECHO_HOST",    "echo.local"),    "pg_port": 5432},
    {"name": "sentinel","host": os.getenv("NODE_SENTINEL_HOST","sentinel.local"), "pg_port": 5432},
]

# Thresholds
THRESHOLDS = {
    "mem_used_pct":      float(os.getenv("THRESH_MEM_PCT",   "90")),   # % memory used
    "swap_used_pct":    float(os.getenv("THRESH_SWAP_PCT",  "80")),   # % swap used
    "disk_used_pct":    float(os.getenv("THRESH_DISK_PCT",  "85")),   # % disk used
    "pg_repl_lag_mb":   float(os.getenv("THRESH_REPL_MB",   "100")),  # MB replication lag
    "pg_repl_lag_sec":  float(os.getenv("THRESH_REPL_SEC",  "300")),  # seconds replication lag
    "offline_queue":    int(os.getenv("THRESH_QUEUE",       "50")),   # offline queue depth
    "heartbeat_misses": int(os.getenv("THRESH_HB_MISS",      "3")),    # heartbeat misses in last hour
}

# PostgreSQL connection (for storing reports)
PG_CONFIG = {
    "host":     os.getenv("PG_HOST", "localhost"),
    "port":     int(os.getenv("PG_PORT", "5432")),
    "dbname":   os.getenv("PG_DB",   "a2a_mesh"),
    "user":     os.getenv("PG_USER", "a2a_mesh"),
    "password": os.getenv("PG_PASSWORD", ""),
}

# Telegram alert
TG_BOT_TOKEN = os.getenv("TG_BOT_TOKEN", "")
TG_CHAT_ID   = os.getenv("TG_CHAT_ID",   "")

# SSH key for remote collection (optional)
SSH_KEY = os.getenv("SSH_KEY", os.path.expanduser("~/.ssh/id_rsa"))
SSH_USER = os.getenv("SSH_USER", "a2a")
SSH_PORT = os.getenv("SSH_PORT", "22")

# Offline queue directory (per-node)
OFFLINE_QUEUE_DIR = os.getenv("OFFLINE_QUEUE_DIR", "/var/lib/a2a_mesh/offline_queue")

# Heartbeat log file
HEARTBEAT_LOG = os.getenv("HEARTBEAT_LOG", "/var/log/a2a_mesh/heartbeat.log")

# ---------------------------------------------------------------------------
# Metric collection
# ---------------------------------------------------------------------------

def _ssh_run(host: str, command: str, timeout: int = 30) -> str:
    """Run a command on a remote host via SSH. Returns stdout or empty string on failure."""
    ssh_cmd = [
        "ssh", "-i", SSH_KEY,
        "-p", str(SSH_PORT),
        "-o", "StrictHostKeyChecking=no",
        "-o", "ConnectTimeout=10",
        "-o", "BatchMode=yes",
        f"{SSH_USER}@{host}",
        command,
    ]
    try:
        result = subprocess.run(
            ssh_cmd, capture_output=True, text=True, timeout=timeout
        )
        if result.returncode != 0:
            log.warning("SSH command failed on %s: %s", host, result.stderr.strip())
            return ""
        return result.stdout.strip()
    except subprocess.TimeoutExpired:
        log.warning("SSH timeout on %s", host)
        return ""
    except FileNotFoundError:
        log.warning("ssh not available, skipping remote collection on %s", host)
        return ""
    except Exception as e:
        log.warning("SSH error on %s: %s", host, e)
        return ""


def _local_run(command: str, timeout: int = 30) -> str:
    """Run a command locally."""
    try:
        result = subprocess.run(
            command, shell=True, capture_output=True, text=True, timeout=timeout
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except Exception as e:
        log.warning("Local command failed '%s': %s", command, e)
        return ""


def _is_local(host: str) -> bool:
    """Check if a host refers to the local machine."""
    try:
        resolved = socket.gethostbyname(host)
        local_ips = {"127.0.0.1", "0.0.0.0", "::1"}
        try:
            local_ips.add(socket.gethostbyname(socket.gethostname()))
        except Exception:
            pass
        return resolved in local_ips or host in ("localhost", "127.0.0.1")
    except socket.gaierror:
        return False


def _run(host: str, command: str) -> str:
    """Run command on host (local or remote)."""
    if _is_local(host):
        return _local_run(command)
    return _ssh_run(host, command)


# ---------------------------------------------------------------------------
# Individual metric collectors
# ---------------------------------------------------------------------------

def collect_memory_swap(host: str) -> dict:
    """Collect memory and swap usage percentages."""
    output = _run(host, "free -b")
    if not output:
        return {"mem_used_pct": None, "swap_used_pct": None, "mem_total_mb": None,
                "mem_used_mb": None, "swap_total_mb": None, "swap_used_mb": None}

    lines = output.splitlines()
    mem_total = mem_used = swap_total = swap_used = 0
    try:
        for line in lines:
            parts = line.split()
            if len(parts) < 2:
                continue
            if parts[0] == "Mem:" and len(parts) >= 3:
                mem_total = int(parts[1])
                mem_used = int(parts[2])
            elif parts[0] == "Swap:" and len(parts) >= 3:
                swap_total = int(parts[1])
                swap_used = int(parts[2])

        mem_pct = round((mem_used / mem_total * 100), 1) if mem_total > 0 else 0
        swap_pct = round((swap_used / swap_total * 100), 1) if swap_total > 0 else 0

        return {
            "mem_used_pct": mem_pct,
            "swap_used_pct": swap_pct,
            "mem_total_mb": round(mem_total / 1048576),
            "mem_used_mb": round(mem_used / 1048576),
            "swap_total_mb": round(swap_total / 1048576),
            "swap_used_mb": round(swap_used / 1048576),
        }
    except (ValueError, IndexError) as e:
        log.warning("Failed to parse free output on %s: %s", host, e)
        return {"mem_used_pct": None, "swap_used_pct": None, "mem_total_mb": None,
                "mem_used_mb": None, "swap_total_mb": None, "swap_used_mb": None}


def collect_disk(host: str) -> dict:
    """Collect disk usage for root filesystem."""
    output = _run(host, "df -B1 /")
    if not output:
        return {"disk_used_pct": None, "disk_total_gb": None, "disk_used_gb": None,
                "disk_free_gb": None}

    lines = output.strip().splitlines()
    if len(lines) < 2:
        return {"disk_used_pct": None, "disk_total_gb": None, "disk_used_gb": None,
                "disk_free_gb": None}

    try:
        parts = lines[1].split()
        total = int(parts[1])
        used = int(parts[2])
        pct_str = parts[4].rstrip("%")
        pct = float(pct_str)

        return {
            "disk_used_pct": pct,
            "disk_total_gb": round(total / 1073741824, 1),
            "disk_used_gb": round(used / 1073741824, 1),
            "disk_free_gb": round((total - used) / 1073741824, 1),
        }
    except (ValueError, IndexError) as e:
        log.warning("Failed to parse df output on %s: %s", host, e)
        return {"disk_used_pct": None, "disk_total_gb": None, "disk_used_gb": None,
                "disk_free_gb": None}


def collect_pg_replication_lag(host: str, pg_port: int) -> dict:
    """Collect PostgreSQL replication lag."""
    # Try to get replication lag via psql on the remote host
    sql = (
        "SELECT COALESCE("
        "  EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())), 0"
        ") AS lag_sec, "
        "COALESCE(pg_wal_lsn_diff(pg_current_wal_lsn(), pg_last_wal_replay_lsn()) / 1048576.0, 0) AS lag_mb, "
        "CASE WHEN pg_is_in_recovery() THEN 'standby' ELSE 'primary' END AS role;"
    )
    psql_cmd = f"psql -p {pg_port} -U {PG_CONFIG['user']} -d {PG_CONFIG['dbname']} -t -A -c \"{sql}\""
    output = _run(host, psql_cmd)

    if not output:
        return {"pg_repl_lag_sec": None, "pg_repl_lag_mb": None, "pg_role": "unknown"}

    try:
        parts = output.split("|")
        lag_sec = float(parts[0]) if parts[0] else 0.0
        lag_mb = float(parts[1]) if parts[1] else 0.0
        role = parts[2].strip() if len(parts) > 2 else "unknown"
        return {
            "pg_repl_lag_sec": round(lag_sec, 1),
            "pg_repl_lag_mb": round(lag_mb, 1),
            "pg_role": role,
        }
    except (ValueError, IndexError) as e:
        log.warning("Failed to parse PG replication output on %s: %s", host, e)
        return {"pg_repl_lag_sec": None, "pg_repl_lag_mb": None, "pg_role": "unknown"}


def collect_offline_queue(host: str) -> dict:
    """Count files in the offline queue directory."""
    # Use find to count files (works locally and remotely)
    cmd = f"find {OFFLINE_QUEUE_DIR} -type f 2>/dev/null | wc -l"
    output = _run(host, cmd)
    try:
        count = int(output.strip()) if output.strip() else 0
    except ValueError:
        count = 0
    return {"offline_queue_depth": count}


def collect_heartbeat_misses(host: str) -> dict:
    """Count heartbeat misses in the last hour from the heartbeat log."""
    # Look for lines with 'MISS' or 'TIMEOUT' in the last hour
    cmd = (
        f"awk -v cutoff=$(date -d '1 hour ago' '+%Y-%m-%dT%H:%M:%S') "
        f"'{{if ($0 ~ /MISS|TIMEOUT|FAIL/ && $1 >= cutoff) count++}} END {{print count+0}}' "
        f"{HEARTBEAT_LOG} 2>/dev/null"
    )
    output = _run(host, cmd)
    try:
        misses = int(output.strip()) if output.strip() else 0
    except ValueError:
        misses = 0
    return {"heartbeat_misses": misses}


def collect_node_state(node: dict) -> dict:
    """Collect all metrics for a single node."""
    name = node["name"]
    host = node["host"]
    pg_port = node.get("pg_port", 5432)

    log.info("Collecting metrics from node '%s' (%s:%d)...", name, host, pg_port)

    state = {
        "node_name": name,
        "host": host,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "reachable": True,
    }

    # Quick reachability check
    try:
        if not _is_local(host):
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(5)
            sock.connect((host, 22))
            sock.close()
    except Exception:
        state["reachable"] = False
        state.update({
            "mem_used_pct": None, "swap_used_pct": None,
            "mem_total_mb": None, "mem_used_mb": None,
            "swap_total_mb": None, "swap_used_mb": None,
            "disk_used_pct": None, "disk_total_gb": None,
            "disk_used_gb": None, "disk_free_gb": None,
            "pg_repl_lag_sec": None, "pg_repl_lag_mb": None,
            "pg_role": "unreachable",
            "offline_queue_depth": None,
            "heartbeat_misses": None,
        })
        log.warning("Node '%s' (%s) is unreachable", name, host)
        return state

    # Collect all metrics
    state.update(collect_memory_swap(host))
    state.update(collect_disk(host))
    state.update(collect_pg_replication_lag(host, pg_port))
    state.update(collect_offline_queue(host))
    state.update(collect_heartbeat_misses(host))

    log.info("Node '%s' collected: mem=%.1f%% swap=%.1f%% disk=%.1f%% repl_lag=%.1fs queue=%d hb_miss=%d",
             name,
             state.get("mem_used_pct") or 0,
             state.get("swap_used_pct") or 0,
             state.get("disk_used_pct") or 0,
             state.get("pg_repl_lag_sec") or 0,
             state.get("offline_queue_depth") or 0,
             state.get("heartbeat_misses") or 0)

    return state


# ---------------------------------------------------------------------------
# Threshold checking
# ---------------------------------------------------------------------------

def check_thresholds(state: dict) -> list:
    """Check a node's state against thresholds. Returns list of alert messages."""
    alerts = []
    name = state["node_name"]

    if not state.get("reachable", True):
        alerts.append(f"🔴 {name}: NODE UNREACHABLE")
        return alerts

    mem = state.get("mem_used_pct")
    if mem is not None and mem > THRESHOLDS["mem_used_pct"]:
        alerts.append(f"🟠 {name}: memory {mem}% > {THRESHOLDS['mem_used_pct']}%")

    swap = state.get("swap_used_pct")
    if swap is not None and swap > THRESHOLDS["swap_used_pct"]:
        alerts.append(f"🟠 {name}: swap {swap}% > {THRESHOLDS['swap_used_pct']}%")

    disk = state.get("disk_used_pct")
    if disk is not None and disk > THRESHOLDS["disk_used_pct"]:
        alerts.append(f"🟠 {name}: disk {disk}% > {THRESHOLDS['disk_used_pct']}%")

    lag_sec = state.get("pg_repl_lag_sec")
    if lag_sec is not None and lag_sec > THRESHOLDS["pg_repl_lag_sec"]:
        alerts.append(f"🟠 {name}: PG repl lag {lag_sec}s > {THRESHOLDS['pg_repl_lag_sec']}s")

    lag_mb = state.get("pg_repl_lag_mb")
    if lag_mb is not None and lag_mb > THRESHOLDS["pg_repl_lag_mb"]:
        alerts.append(f"🟠 {name}: PG repl lag {lag_mb}MB > {THRESHOLDS['pg_repl_lag_mb']}MB")

    queue = state.get("offline_queue_depth")
    if queue is not None and queue > THRESHOLDS["offline_queue"]:
        alerts.append(f"🟠 {name}: offline queue {queue} > {THRESHOLDS['offline_queue']}")

    hb = state.get("heartbeat_misses")
    if hb is not None and hb > THRESHOLDS["heartbeat_misses"]:
        alerts.append(f"🟠 {name}: heartbeat misses {hb} > {THRESHOLDS['heartbeat_misses']}")

    return alerts


# ---------------------------------------------------------------------------
# PostgreSQL storage
# ---------------------------------------------------------------------------

def ensure_schema(conn):
    """Create the health report table if it doesn't exist."""
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS mesh_health_reports (
            id              SERIAL PRIMARY KEY,
            report_time     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            node_name       TEXT NOT NULL,
            host            TEXT NOT NULL,
            reachable       BOOLEAN NOT NULL,
            mem_used_pct    REAL,
            mem_total_mb    INTEGER,
            mem_used_mb     INTEGER,
            swap_used_pct   REAL,
            swap_total_mb   INTEGER,
            swap_used_mb    INTEGER,
            disk_used_pct   REAL,
            disk_total_gb   REAL,
            disk_used_gb    REAL,
            disk_free_gb    REAL,
            pg_repl_lag_sec REAL,
            pg_repl_lag_mb  REAL,
            pg_role         TEXT,
            offline_queue_depth INTEGER,
            heartbeat_misses    INTEGER,
            alerts          TEXT[],
            raw_json        JSONB
        );
    """)
    cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_health_reports_time
        ON mesh_health_reports (report_time DESC);
    """)
    cur.execute("""
        CREATE INDEX IF NOT EXISTS idx_health_reports_node
        ON mesh_health_reports (node_name, report_time DESC);
    """)
    conn.commit()
    cur.close()


def store_report(conn, state: dict, alerts: list):
    """Store a single node's report in PostgreSQL."""
    cur = conn.cursor()
    cur.execute("""
        INSERT INTO mesh_health_reports (
            report_time, node_name, host, reachable,
            mem_used_pct, mem_total_mb, mem_used_mb,
            swap_used_pct, swap_total_mb, swap_used_mb,
            disk_used_pct, disk_total_gb, disk_used_gb, disk_free_gb,
            pg_repl_lag_sec, pg_repl_lag_mb, pg_role,
            offline_queue_depth, heartbeat_misses,
            alerts, raw_json
        ) VALUES (
            %s, %s, %s, %s,
            %s, %s, %s,
            %s, %s, %s,
            %s, %s, %s, %s,
            %s, %s, %s,
            %s, %s,
            %s, %s
        )
    """, (
        state["timestamp"],
        state["node_name"],
        state["host"],
        state["reachable"],
        state.get("mem_used_pct"),
        state.get("mem_total_mb"),
        state.get("mem_used_mb"),
        state.get("swap_used_pct"),
        state.get("swap_total_mb"),
        state.get("swap_used_mb"),
        state.get("disk_used_pct"),
        state.get("disk_total_gb"),
        state.get("disk_used_gb"),
        state.get("disk_free_gb"),
        state.get("pg_repl_lag_sec"),
        state.get("pg_repl_lag_mb"),
        state.get("pg_role"),
        state.get("offline_queue_depth"),
        state.get("heartbeat_misses"),
        alerts if alerts else [],
        json.dumps(state, default=str),
    ))
    conn.commit()
    cur.close()


# ---------------------------------------------------------------------------
# Telegram alerting
# ---------------------------------------------------------------------------

def send_telegram(message: str) -> bool:
    """Send a message to Telegram. Returns True on success."""
    if not TG_BOT_TOKEN or not TG_CHAT_ID:
        log.warning("Telegram not configured (TG_BOT_TOKEN/TG_CHAT_ID missing). Alert: %s", message)
        return False

    import urllib.request
    import urllib.parse
    import urllib.error

    url = f"https://api.telegram.org/bot{TG_BOT_TOKEN}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id": TG_CHAT_ID,
        "text": message,
        "parse_mode": "HTML",
        "disable_web_page_preview": "true",
    }).encode("utf-8")

    try:
        req = urllib.request.Request(url, data=data, method="POST")
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = resp.read().decode("utf-8")
            result = json.loads(body)
            if result.get("ok"):
                log.info("Telegram alert sent successfully")
                return True
            else:
                log.error("Telegram API error: %s", body)
                return False
    except urllib.error.URLError as e:
        log.error("Telegram send failed: %s", e)
        return False
    except Exception as e:
        log.error("Telegram unexpected error: %s", e)
        return False


# ---------------------------------------------------------------------------
# JSON fallback storage (when PG is unavailable)
# ---------------------------------------------------------------------------

def store_json_fallback(all_states: list, all_alerts: list):
    """Store report as JSON file when PostgreSQL is unavailable."""
    fallback_dir = REPO_ROOT / "data" / "health_reports"
    fallback_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    filepath = fallback_dir / f"health_report_{ts}.json"
    report = {
        "report_time": datetime.now(timezone.utc).isoformat(),
        "nodes": all_states,
        "alerts": all_alerts,
        "thresholds": THRESHOLDS,
    }
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, default=str, ensure_ascii=False)
    log.info("Report stored as JSON fallback: %s", filepath)
    return filepath


# ---------------------------------------------------------------------------
# Trend analysis (bonus: compare with last week)
# ---------------------------------------------------------------------------

def get_last_week_trend(conn, node_name: str) -> dict:
    """Get last week's report for comparison."""
    cur = conn.cursor()
    cur.execute("""
        SELECT mem_used_pct, swap_used_pct, disk_used_pct, pg_repl_lag_sec,
               offline_queue_depth, heartbeat_misses
        FROM mesh_health_reports
        WHERE node_name = %s
          AND report_time < NOW() - INTERVAL '6 days'
        ORDER BY report_time DESC
        LIMIT 1
    """, (node_name,))
    row = cur.fetchone()
    cur.close()
    if not row:
        return {}
    return {
        "mem_used_pct": row[0],
        "swap_used_pct": row[1],
        "disk_used_pct": row[2],
        "pg_repl_lag_sec": row[3],
        "offline_queue_depth": row[4],
        "heartbeat_misses": row[5],
    }


def format_trend(current: float, previous: float, unit: str = "") -> str:
    """Format a trend indicator."""
    if current is None or previous is None:
        return ""
    diff = current - previous
    if abs(diff) < 0.1:
        return "→"
    elif diff > 0:
        return f"↑{diff:.1f}{unit}"
    else:
        return f"↓{abs(diff):.1f}{unit}"


# ---------------------------------------------------------------------------
# Main report generation
# ---------------------------------------------------------------------------

def generate_report(nodes: list, dry_run: bool = False) -> dict:
    """Generate the weekly health report for all nodes."""
    log.info("=" * 60)
    log.info("Starting weekly mesh health report")
    log.info("Timestamp: %s", datetime.now(timezone.utc).isoformat())
    log.info("Nodes: %s", [n["name"] for n in nodes])
    log.info("=" * 60)

    all_states = []
    all_alerts = []

    # Collect metrics from all nodes
    for node in nodes:
        state = collect_node_state(node)
        alerts = check_thresholds(state)
        all_states.append(state)
        all_alerts.extend(alerts)

    # Try to store in PostgreSQL
    pg_available = False
    conn = None
    if not dry_run:
        try:
            import psycopg2
            conn = psycopg2.connect(**PG_CONFIG)
            ensure_schema(conn)
            for i, state in enumerate(all_states):
                # Find alerts for this node
                node_alerts = [a for a in all_alerts if a.startswith(("🔴", "🟠")) and state["node_name"] in a]
                store_report(conn, state, node_alerts)
            pg_available = True
            log.info("Reports stored in PostgreSQL successfully")
        except ImportError:
            log.warning("psycopg2 not installed, using JSON fallback")
        except Exception as e:
            log.error("PostgreSQL storage failed: %s", e)

    # JSON fallback
    if not pg_available and not dry_run:
        store_json_fallback(all_states, all_alerts)

    # Trend analysis
    trends = {}
    if conn:
        for state in all_states:
            trends[state["node_name"]] = get_last_week_trend(conn, state["node_name"])

    # Build summary
    summary_lines = [
        f"<b>🏥 A2A Mesh Heti Egészségriport</b>",
        f"📅 {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
    ]

    for state in all_states:
        name = state["node_name"]
        trend = trends.get(name, {})
        status = "✅" if not any(name in a for a in all_alerts) else "⚠️"

        summary_lines.append(f"<b>{status} {name}</b> ({state['host']})")

        if not state.get("reachable", True):
            summary_lines.append("  🔴 UNREACHABLE")
            summary_lines.append("")
            continue

        mem = state.get("mem_used_pct")
        mem_t = format_trend(mem, trend.get("mem_used_pct"), "%") if trend else ""
        summary_lines.append(f"  RAM: {mem}% {mem_t}" if mem is not None else "  RAM: N/A")

        swap = state.get("swap_used_pct")
        summary_lines.append(f"  Swap: {swap}%" if swap is not None else "  Swap: N/A")

        disk = state.get("disk_used_pct")
        disk_t = format_trend(disk, trend.get("disk_used_pct"), "%") if trend else ""
        summary_lines.append(f"  Disk: {disk}% {disk_t}" if disk is not None else "  Disk: N/A")

        lag = state.get("pg_repl_lag_sec")
        role = state.get("pg_role", "?")
        summary_lines.append(f"  PG: {role}, lag={lag}s" if lag is not None else f"  PG: {role}")

        queue = state.get("offline_queue_depth")
        summary_lines.append(f"  Queue: {queue}" if queue is not None else "  Queue: N/A")

        hb = state.get("heartbeat_misses")
        summary_lines.append(f"  HB misses: {hb}" if hb is not None else "  HB misses: N/A")
        summary_lines.append("")

    if all_alerts:
        summary_lines.append("<b>🚨 ALERTS:</b>")
        for alert in all_alerts:
            summary_lines.append(f"  {alert}")
    else:
        summary_lines.append("<b>✅ All nodes healthy — no alerts.</b>")

    summary = "\n".join(summary_lines)

    # Send Telegram alert ONLY if there are issues
    if all_alerts and not dry_run:
        log.info("Sending Telegram alert (%d issues found)", len(all_alerts))
        send_telegram(summary)
    elif not all_alerts:
        log.info("All nodes healthy — silent (no Telegram alert sent)")

    # Close PG connection
    if conn:
        conn.close()

    log.info("Weekly health report complete.")
    log.info("=" * 60)

    return {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "nodes": all_states,
        "alerts": all_alerts,
        "summary": summary,
        "pg_stored": pg_available,
    }


# ---------------------------------------------------------------------------
# Crontab helper
# ---------------------------------------------------------------------------

CRON_LINE = "# Weekly mesh health report — Sundays at 02:00\n" \
            "0 2 * * 0 cd /opt/a2a_mesh && /usr/bin/python3 scripts/weekly_health_report.py >> /var/log/a2a_mesh/health_report.log 2>&1\n"


def print_crontab():
    """Print the crontab entry for the user to install."""
    print("# Add this to crontab (crontab -e):")
    print(CRON_LINE)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="A2A Mesh Weekly Health Report — collects node metrics and stores in PG"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Collect metrics but don't store in PG or send alerts"
    )
    parser.add_argument(
        "--print-crontab", action="store_true",
        help="Print the crontab entry and exit"
    )
    parser.add_argument(
        "--nodes", type=str, default=None,
        help="Comma-separated list of node names to check (default: all 4)"
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Enable verbose logging"
    )
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.print_crontab:
        print_crontab()
        sys.exit(0)

    # Filter nodes if specified
    nodes = DEFAULT_NODES
    if args.nodes:
        names = [n.strip() for n in args.nodes.split(",")]
        nodes = [n for n in DEFAULT_NODES if n["name"] in names]
        if not nodes:
            log.error("No matching nodes found for: %s", args.nodes)
            sys.exit(1)

    report = generate_report(nodes, dry_run=args.dry_run)

    # Print summary to stdout
    print("\n" + "=" * 60)
    print("WEEKLY MESH HEALTH REPORT")
    print("=" * 60)
    print(report["summary"].replace("<b>", "").replace("</b>", ""))
    print("=" * 60)

    if report["alerts"]:
        print(f"\n⚠️  {len(report['alerts'])} alert(s) detected — Telegram notification sent.")
        sys.exit(1)
    else:
        print("\n✅ All nodes healthy — silent success.")
        sys.exit(0)


if __name__ == "__main__":
    main()
```

**Crontab bejegyzés (telepítés: `crontab -e`):**

```cron
# Heti mesh-egészségriport — vasárnaponta 02:00-kor
0 2 * * 0 cd /opt/a2a_mesh && /usr/bin/python3 scripts/weekly_health_report.py >> /var/log/a2a_mesh/health_report.log 2>&1
```

**Függőségek:**

```bash
pip install psycopg2-binary
```

**Használat:**

```bash
# Teszt futtatás (PG nélkül, alert nélkül)
python scripts/weekly_health_report.py --dry-run -v

# Crontab bejegyzés megjelenítése
python scripts/weekly_health_report.py --print-crontab

# Csak egy node ellenőrzése
python scripts/weekly_health_report.py --nodes morzsa

# Éles futtatás (cron-ból)
python scripts/weekly_health_report.py
```

**Környezeti változók:**

| Változó | Alapértelmezett | Leírás |
|---|---|---|
| `NODE_MORZSA_HOST` | `morzsa.local` | Morzsa node címe |
| `NODE_NOVA_HOST` | `nova.local` | Nova node címe |
| `NODE_ECHO_HOST` | `echo.local` | Echo node címe |
| `NODE_SENTINEL_HOST` | `sentinel.local` | Sentinel node címe |
| `PG_HOST` | `localhost` | PostgreSQL host |
| `PG_PORT` | `5432` | PostgreSQL port |
| `PG_DB` | `a2a_mesh` | PostgreSQL adatbázis |
| `PG_USER` | `a2a_mesh` | PostgreSQL user |
| `PG_PASSWORD` | (üres) | PostgreSQL jelszó |
| `TG_BOT_TOKEN` | (üres) | Telegram bot token |
| `TG_CHAT_ID` | (üres) | Telegram chat ID |
| `THRESH_MEM_PCT` | `90` | Memória küszöb (%) |
| `THRESH_SWAP_PCT` | `80` | Swap küszöb (%) |
| `THRESH_DISK_PCT` | `85` | Lemez küszöb (%) |
| `THRESH_REPL_SEC` | `300` | PG replikáció lag küszöb (mp) |
| `THRESH_REPL_MB` | `100` | PG replikáció lag küszöb (MB) |
| `THRESH_QUEUE` | `50` | Offline queue mélység küszöb |
| `THRESH_HB_MISS` | `3` | Heartbeat kiesés küszöb |
| `SSH_KEY` | `~/.ssh/id_rsa` | SSH kulcs útvonala |
| `SSH_USER` | `a2a` | SSH user |
| `OFFLINE_QUEUE_DIR` | `/var/lib/a2a_mesh/offline_queue` | Offline queue könyvtár |
| `HEARTBEAT_LOG` | `/var/log/a2a_mesh/heartbeat.log` | Heartbeat log fájl |