#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
Döntési lezárás: szoba végén pontozás, a top 3 ötlet automatikusan
Gitea issue-ként landol — ötletből feladat lesz, nem csak beszélgetés.

Ez a modul a szoba lezárásakor:
  1. Összegyűjti a szobában felmerült ötleteket
  2. Pontozza őket (szavazatok, reakciók, vitaliveness alapján)
  3. Kiválasztja a top 3 ötletet
  4. Gitea issue-ként létrehozza őket a megadott repóban

Futtatás a repó gyökeréből:
  python idea_closure_to_gitea.py --room-id ROOM123 --gitea-url https://gitea.example.com --gitea-token TOKEN --owner myorg --repo myrepo

Vagy dry-run módban (nem küld valódi requestet):
  python idea_closure_to_gitea.py --room-id ROOM123 --dry-run
"""

import argparse
import json
import os
import sys
import time
import hashlib
import urllib.request
import urllib.error
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Tuple


# ---------------------------------------------------------------------------
# Adatmodellek
# ---------------------------------------------------------------------------

@dataclass
class Idea:
    """Egy ötlet a szobában."""
    idea_id: str
    title: str
    description: str
    author: str
    votes_up: int = 0
    votes_down: int = 0
    reactions: Dict[str, int] = field(default_factory=dict)  # emoji -> count
    discussion_count: int = 0
    created_at: float = field(default_factory=time.time)

    def score(self) -> float:
        """
        Pontozási algoritmus:
          - votes_up - votes_down (súly: 1.0)
          - reakciók pozitív súlya (👍🚀💡❤️ = +1, 👎 = -1)
          - vitalitás: discussion_count * 0.5
          - Minél több a vita, annál érettebb az ötlet.
        """
        base = (self.votes_up - self.votes_down) * 1.0

        positive_emojis = {"👍", "🚀", "💡", "❤️", "🔥", "✅"}
        negative_emojis = {"👎", "❌", "🤔"}

        reaction_score = 0.0
        for emoji, count in self.reactions.items():
            if emoji in positive_emojis:
                reaction_score += count * 0.5
            elif emoji in negative_emojis:
                reaction_score -= count * 0.5
            else:
                reaction_score += count * 0.1  # semleges reakció kis bónusz

        vitality = self.discussion_count * 0.5

        return base + reaction_score + vitality


@dataclass
class Room:
    """Egy vitaszoba ötletekkel."""
    room_id: str
    title: str
    ideas: List[Idea] = field(default_factory=list)
    closed: bool = False
    created_at: float = field(default_factory=time.time)


@dataclass
class GiteaIssuePayload:
    """Gitea API issue payload."""
    title: str
    body: str
    labels: List[str] = field(default_factory=list)
    assignees: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Szoba-kezelés (in-memory + opcionális JSON perzisztencia)
# ---------------------------------------------------------------------------

class RoomStore:
    """Egyszerű szoba-tároló JSON fájl alapú perzisztenciával."""

    def __init__(self, storage_path: str = "data/rooms.json"):
        self.storage_path = storage_path
        self.rooms: Dict[str, Room] = {}
        self._load()

    def _load(self):
        if os.path.exists(self.storage_path):
            try:
                with open(self.storage_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                for room_id, room_data in data.items():
                    ideas = [
                        Idea(
                            idea_id=idea_data["idea_id"],
                            title=idea_data["title"],
                            description=idea_data.get("description", ""),
                            author=idea_data.get("author", "unknown"),
                            votes_up=idea_data.get("votes_up", 0),
                            votes_down=idea_data.get("votes_down", 0),
                            reactions=idea_data.get("reactions", {}),
                            discussion_count=idea_data.get("discussion_count", 0),
                            created_at=idea_data.get("created_at", time.time()),
                        )
                        for idea_data in room_data.get("ideas", [])
                    ]
                    self.rooms[room_id] = Room(
                        room_id=room_id,
                        title=room_data.get("title", ""),
                        ideas=ideas,
                        closed=room_data.get("closed", False),
                        created_at=room_data.get("created_at", time.time()),
                    )
            except (json.JSONDecodeError, KeyError) as e:
                print(f"[RoomStore] Figyelmeztetés: tároló betöltése sikertelen: {e}", file=sys.stderr)

    def _save(self):
        os.makedirs(os.path.dirname(self.storage_path) or ".", exist_ok=True)
        data = {}
        for room_id, room in self.rooms.items():
            data[room_id] = {
                "title": room.title,
                "ideas": [asdict(idea) for idea in room.ideas],
                "closed": room.closed,
                "created_at": room.created_at,
            }
        with open(self.storage_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    def get_or_create(self, room_id: str, title: str = "") -> Room:
        if room_id not in self.rooms:
            self.rooms[room_id] = Room(room_id=room_id, title=title)
            self._save()
        return self.rooms[room_id]

    def add_idea(self, room_id: str, idea: Idea):
        room = self.get_or_create(room_id)
        room.ideas.append(idea)
        self._save()

    def close_room(self, room_id: str) -> Room:
        room = self.get_or_create(room_id)
        room.closed = True
        self._save()
        return room


# ---------------------------------------------------------------------------
# Pontozás és top-N kiválasztás
# ---------------------------------------------------------------------------

class IdeaScorer:
    """Ötletek pontozása és rangsorolása."""

    @staticmethod
    def rank_ideas(ideas: List[Idea]) -> List[Tuple[Idea, float]]:
        """Visszaadja az ötleteket pontszám szerint csökkenő sorrendben."""
        scored = [(idea, idea.score()) for idea in ideas]
        scored.sort(key=lambda x: x[1], reverse=True)
        return scored

    @staticmethod
    def top_n(ideas: List[Idea], n: int = 3) -> List[Tuple[Idea, float]]:
        """Top-N ötlet kiválasztása pontszám alapján."""
        return IdeaScorer.rank_ideas(ideas)[:n]


# ---------------------------------------------------------------------------
# Gitea issue generálás
# ---------------------------------------------------------------------------

class GiteaIssueCreator:
    """Gitea API-n keresztül issue-kat hoz létre a top ötletekből."""

    def __init__(
        self,
        base_url: str,
        token: str,
        owner: str,
        repo: str,
        dry_run: bool = False,
    ):
        self.base_url = base_url.rstrip("/")
        self.token = token
        self.owner = owner
        self.repo = repo
        self.dry_run = dry_run

    def _build_issue_body(self, idea: Idea, room: Room, score: float) -> str:
        """Gitea issue body összeállítása az ötletből."""
        lines = [
            f"## {idea.title}",
            "",
            f"**Eredeti ötlet:** {idea.description}",
            "",
            f"**Beküldte:** {idea.author}",
            f"**Szoba:** {room.title} (`{room.room_id}`)",
            f"**Pontszám:** {score:.2f}",
            "",
            "### Pontozás részletek",
            f"- 👍 Szavazatok: {idea.votes_up}",
            f"- 👎 Ellenszavazatok: {idea.votes_down}",
            f"- 💬 Hozzászólások: {idea.discussion_count}",
            f"- 😊 Reakciók: {json.dumps(idea.reactions, ensure_ascii=False) if idea.reactions else 'nincs'}",
            "",
            "---",
            f"*Automatikusan generálva az A2A Mesh döntési lezárás során.*",
            f"*Idea ID: `{idea.idea_id}`*",
        ]
        return "\n".join(lines)

    def _build_payload(self, idea: Idea, room: Room, score: float) -> GiteaIssuePayload:
        return GiteaIssuePayload(
            title=f"[ötlet→feladat] {idea.title}",
            body=self._build_issue_body(idea, room, score),
            labels=["from-idea-box", "auto-generated", "a2a-mesh"],
            assignees=[idea.author] if idea.author != "unknown" else [],
        )

    def create_issue(self, idea: Idea, room: Room, score: float) -> Dict:
        """Létrehoz egy Gitea issue-t az ötletből."""
        payload = self._build_payload(idea, room, score)
        url = f"{self.base_url}/api/v1/repos/{self.owner}/{self.repo}/issues"
        body_json = json.dumps({
            "title": payload.title,
            "body": payload.body,
            "labels": payload.labels,
            "assignees": payload.assignees,
        }).encode("utf-8")

        if self.dry_run:
            print(f"[DRY-RUN] Gitea issue létrehozása: {payload.title}")
            print(f"  URL: {url}")
            print(f"  Body (első 200 char): {payload.body[:200]}...")
            return {
                "dry_run": True,
                "url": url,
                "title": payload.title,
                "idea_id": idea.idea_id,
            }

        req = urllib.request.Request(
            url,
            data=body_json,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"token {self.token}",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                response_data = json.loads(resp.read().decode("utf-8"))
                print(f"[Gitea] Issue létrehozva: #{response_data.get('number', '?')} — {payload.title}")
                return {
                    "dry_run": False,
                    "issue_number": response_data.get("number"),
                    "issue_url": response_data.get("html_url"),
                    "idea_id": idea.idea_id,
                }
        except urllib.error.HTTPError as e:
            error_body = e.read().decode("utf-8", errors="replace")
            print(f"[Gitea] HIBA {e.code}: {error_body}", file=sys.stderr)
            return {
                "dry_run": False,
                "error": True,
                "status_code": e.code,
                "body": error_body,
                "idea_id": idea.idea_id,
            }
        except urllib.error.URLError as e:
            print(f"[Gitea] Hálózati hiba: {e.reason}", file=sys.stderr)
            return {
                "dry_run": False,
                "error": True,
                "reason": str(e.reason),
                "idea_id": idea.idea_id,
            }


# ---------------------------------------------------------------------------
# Fő logika: szoba lezárása + top 3 → Gitea issues
# ---------------------------------------------------------------------------

class ClosureManager:
    """Összefogja a lezárási folyamatot: pontozás → top 3 → Gitea issues."""

    def __init__(self, room_store: RoomStore, gitea_creator: Optional[GiteaIssueCreator] = None):
        self.room_store = room_store
        self.gitea_creator = gitea_creator

    def close_room_and_export(self, room_id: str, top_n: int = 3) -> Dict:
        """
        Lezárja a szobát, pontozza az ötleteket, és a top N ötletet
        Gitea issue-ként exportálja.

        Visszatér egy összefoglaló dict-tel.
        """
        if room_id not in self.room_store.rooms:
            return {
                "error": True,
                "message": f"Szoba nem található: {room_id}",
            }

        room = self.room_store.rooms[room_id]

        if room.closed:
            print(f"[Closure] A szoba már le van zárva: {room_id}")

        if not room.ideas:
            print(f"[Closure] Nincsenek ötletek a szobában: {room_id}")
            self.room_store.close_room(room_id)
            return {
                "room_id": room_id,
                "closed": True,
                "idea_count": 0,
                "exported": [],
                "message": "Nincsenek ötletek a szobában.",
            }

        # Pontozás
        ranked = IdeaScorer.rank_ideas(room.ideas)
        print(f"\n{'='*60}")
        print(f"Szoba lezárása: {room.title} ({room_id})")
        print(f"Ötletek száma: {len(ranked)}")
        print(f"{'='*60}")
        print(f"\nRangsor:")
        for i, (idea, score) in enumerate(ranked, 1):
            marker = " ★" if i <= top_n else ""
            print(f"  {i}. [{score:6.2f}] {idea.title}{marker}")

        # Top N kiválasztása
        top = ranked[:top_n]

        # Gitea export
        exported = []
        if self.gitea_creator:
            print(f"\nTop {len(top)} ötlet → Gitea issue-k:")
            for idea, score in top:
                result = self.gitea_creator.create_issue(idea, room, score)
                exported.append(result)
        else:
            print("\n[Nincs Gitea creator konfigurálva — csak pontozás.]")

        # Szoba lezárása
        self.room_store.close_room(room_id)

        summary = {
            "room_id": room_id,
            "room_title": room.title,
            "closed": True,
            "idea_count": len(ranked),
            "ranking": [
                {
                    "rank": i + 1,
                    "idea_id": idea.idea_id,
                    "title": idea.title,
                    "score": round(score, 2),
                    "exported": i < top_n,
                }
                for i, (idea, score) in enumerate(ranked)
            ],
            "exported": exported,
            "timestamp": time.time(),
        }

        # Eredmény mentése
        self._save_closure_report(room_id, summary)

        return summary

    def _save_closure_report(self, room_id: str, summary: Dict):
        """Lezárási jelentés mentése fájlba."""
        report_dir = "data/closure_reports"
        os.makedirs(report_dir, exist_ok=True)
        report_path = os.path.join(report_dir, f"{room_id}_closure.json")
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(summary, f, ensure_ascii=False, indent=2)
        print(f"\nLezárási jelentés mentve: {report_path}")


# ---------------------------------------------------------------------------
# Demo / CLI
# ---------------------------------------------------------------------------

def seed_demo_room(store: RoomStore, room_id: str = "demo_room_001"):
    """Feltölt egy demó szobát példa ötletekkel, ha még nem létezik."""
    if room_id in store.rooms and store.rooms[room_id].ideas:
        return

    demo_ideas = [
        Idea(
            idea_id="idea_a4642c86f3cf",
            title="Döntési lezárás: szoba végén pontozás, top 3 → Gitea issue",
            description="A szoba végén az ötletek pontozást kapnak, a top 3 automatikusan "
                        "Gitea issue-ként landol — ötletből feladat lesz, nem csak beszélgetés.",
            author="runa",
            votes_up=12,
            votes_down=1,
            reactions={"👍": 8, "🚀": 5, "💡": 3, "❤️": 2},
            discussion_count=15,
        ),
        Idea(
            idea_id="idea_b123456789ab",
            title="Szoba-közi dedup: mesh-szintű egyesítés",
            description="Ugyanaz az ötlet több szobában születik → mesh-szintű egyesítés, "
                        "hogy ne fejlesszük kétszer ugyanazt.",
            author="runa",
            votes_up=9,
            votes_down=2,
            reactions={"👍": 6, "💡": 4, "🤔": 1},
            discussion_count=8,
        ),
        Idea(
            idea_id="idea_c987654321de",
            title="Konfliktus-párosítás + kompromisszum-javaslat",
            description="Ütközés-jelzés mellé generált kompromisszum-javaslat is, különben "
                        "a konfliktus csak jelzés marad megoldás nélkül.",
            author="runa",
            votes_up=7,
            votes_down=0,
            reactions={"👍": 5, "🔥": 2, "✅": 3},
            discussion_count=11,
        ),
        Idea(
            idea_id="idea_d55555555555",
            title="Ötletláda UI: szavazós kártyák",
            description="Minden ötlet egy kártyaként jelenik meg, amire lehet szavazni "
                        "és reakciókat adni.",
            author="guest",
            votes_up=4,
            votes_down=3,
            reactions={"👍": 3, "🤔": 2},
            discussion_count=5,
        ),
        Idea(
            idea_id="idea_e11111111111",
            title="Hetenti digest email a top ötletekből",
            description="Minden héten egy email a legjobb ötletekkel és azok státuszával.",
            author="guest",
            votes_up=2,
            votes_down=5,
            reactions={"👎": 3, "🤔": 1},
            discussion_count=3,
        ),
    ]

    room = store.get_or_create(room_id, title="A2A Mesh ötletláda — első kör")
    for idea in demo_ideas:
        store.add_idea(room_id, idea)

    print(f"[Demo] Szoba feltöltve: {room_id} ({len(demo_ideas)} ötlet)")


def main():
    parser = argparse.ArgumentParser(
        description="Döntési lezárás: szoba pontozása + top 3 ötlet → Gitea issue"
    )
    parser.add_argument("--room-id", required=True, help="A lezárandó szoba azonosítója")
    parser.add_argument("--gitea-url", default=os.environ.get("GITEA_URL", ""), help="Gitea base URL")
    parser.add_argument("--gitea-token", default=os.environ.get("GITEA_TOKEN", ""), help="Gitea API token")
    parser.add_argument("--owner", default=os.environ.get("GITEA_OWNER", ""), help="Gitea repó owner")
    parser.add_argument("--repo", default=os.environ.get("GITEA_REPO", ""), help="Gitea repó neve")
    parser.add_argument("--top-n", type=int, default=3, help="Hány top ötletet exportáljunk (default: 3)")
    parser.add_argument("--dry-run", action="store_true", help="Nem küld valódi Gitea requestet")
    parser.add_argument("--seed-demo", action="store_true", help="Demó szoba feltöltése példa ötletekkel")
    parser.add_argument("--storage", default="data/rooms.json", help="Szoba tároló fájl útvonala")
    args = parser.parse_args()

    # Tároló inicializálása
    store = RoomStore(storage_path=args.storage)

    # Opcionális demó adatok
    if args.seed_demo:
        seed_demo_room(store, args.room_id)

    # Gitea creator (csak ha van URL + token, vagy dry-run)
    gitea_creator = None
    if args.dry_run or (args.gitea_url and args.gitea_token and args.owner and args.repo):
        gitea_creator = GiteaIssueCreator(
            base_url=args.gitea_url or "https://gitea.example.com",
            token=args.gitea_token or "dummy-token",
            owner=args.owner or "a2a-mesh",
            repo=args.repo or "ideas",
            dry_run=args.dry_run,
        )
    else:
        print("[Info] Nincs Gitea konfigurálva. Csak pontozás lesz végrehjtva.")
        print("       Gitea exporthoz add meg: --gitea-url, --gitea-token, --owner, --repo")
        print("       Vagy használj --dry-run flaget a szimulációhoz.\n")

    # Lezárás végrehajtása
    manager = ClosureManager(store, gitea_creator)
    result = manager.close_room_and_export(args.room_id, top_n=args.top_n)

    # Eredmény kiírása
    print(f"\n{'='*60}")
    print("LEZÁRÁS EREDMÉNYE")
    print(f"{'='*60}")
    print(json.dumps(result, ensure_ascii=False, indent=2))

    # Exit code
    if result.get("error"):
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()