#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
A2A Mesh — Uptime Monitor & Restart Detector
=============================================
Idea: idea_75b84831f5a1 — Gyakori restart — morzsa uptime: 5 perc

Detects nodes with frequent restarts (uptime < threshold),
identifies root causes (OOM kill, unhandled exception, auto-updater),
and provides recommendations for achieving >24h uptime.

Run from repo root:
    python tools/uptime_monitor.py
    python tools/uptime_monitor.py --threshold 3600 --interval 30
"""

import argparse
import dataclasses
import json
import os
import re
import signal
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
STATE_DIR = REPO_ROOT / ".a2a_mesh" / "uptime_monitor"
STATE_FILE = STATE_DIR / "node_uptime_state.json"
LOG_DIR = REPO_ROOT / "logs"
REPORT_FILE = STATE_DIR / "restart_report.json"

DEFAULT_THRESHOLD_SECONDS = 3600          # 1 hour — below this = "crumb uptime"
CRUMB_UPTIME_SECONDS = 300                 # 5 minutes — the observed problem
TARGET_UPTIME_SECONDS = 86400              # 24 hours — the goal
DEFAULT_INTERVAL_SECONDS = 60              # check every 60s
MAX_HISTORY_ENTRIES = 1440                 # keep ~24h of 1-min samples

OOM_KILL_PATTERNS = [
    re.compile(r"Out of memory", re.IGNORECASE),
    re.compile(r"Killed process.*oom", re.IGNORECASE),
    re.compile(r"oom-kill", re.IGNORECASE),
    re.compile(r"MemoryError", re.IGNORECASE),
    re.compile(r"Cannot allocate memory", re.IGNORECASE),
]

CRASH_PATTERNS = [
    re.compile(r"Traceback.*most recent call last", re.IGNORECASE),
    re.compile(r"Segmentation fault", re.IGNORECASE),
    re.compile(r"core dumped", re.IGNORECASE),
    re.compile(r"Unhandled exception", re.IGNORECASE),
    re.compile(r"Fatal Python error", re.IGNORECASE),
]

UPDATE_PATTERNS = [
    re.compile(r"auto.?update", re.IGNORECASE),
    re.compile(r"rolling update", re.IGNORECASE),
    re.compile(r"restart.*update", re.IGNORECASE),
    re.compile(r"version.*changed", re.IGNORECASE),
    re.compile(r"deploy.*restart", re.IGNORECASE),
]


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclasses.dataclass
class NodeSnapshot:
    """A single point-in-time observation of a node."""
    node_id: str
    pid: Optional[int]
    uptime_seconds: float
    timestamp: str
    memory_rss_kb: int
    status: str  # "running", "stopped", "unknown"

    def to_dict(self) -> Dict[str, Any]:
        return dataclasses.asdict(self)


@dataclasses.dataclass
class RestartEvent:
    """Recorded when a node's PID changes or uptime resets."""
    node_id: str
    old_pid: Optional[int]
    new_pid: Optional[int]
    old_uptime: float
    timestamp: str
    suspected_cause: str
    evidence: List[str]

    def to_dict(self) -> Dict[str, Any]:
        return dataclasses.asdict(self)


@dataclasses.dataclass
class NodeHealthReport:
    node_id: str
    current_uptime: float
    restart_count_24h: int
    shortest_uptime: float
    longest_uptime: float
    is_crumb: bool
    suspected_causes: List[str]
    recommendation: str

    def to_dict(self) -> Dict[str, Any]:
        return dataclasses.asdict(self)


# ---------------------------------------------------------------------------
# State persistence
# ---------------------------------------------------------------------------

def ensure_dirs() -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)


def load_state() -> Dict[str, Any]:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {"nodes": {}, "restart_events": [], "history": []}


def save_state(state: Dict[str, Any]) -> None:
    ensure_dirs()
    tmp = STATE_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(STATE_FILE)


# ---------------------------------------------------------------------------
# Node discovery & uptime measurement
# ---------------------------------------------------------------------------

def discover_nodes() -> List[str]:
    """
    Discover A2A Mesh nodes by scanning for running Python processes
    that match known mesh agent patterns, plus any node registry file.
    """
    node_ids: set = set()

    # 1. Check for a node registry file
    registry_paths = [
        REPO_ROOT / ".a2a_mesh" / "nodes.json",
        REPO_ROOT / "config" / "nodes.json",
        REPO_ROOT / "nodes.json",
    ]
    for rp in registry_paths:
        if rp.exists():
            try:
                data = json.loads(rp.read_text(encoding="utf-8"))
                if isinstance(data, list):
                    for entry in data:
                        if isinstance(entry, dict) and "node_id" in entry:
                            node_ids.add(entry["node_id"])
                elif isinstance(data, dict):
                    for key in data:
                        node_ids.add(key)
            except (json.JSONDecodeError, OSError):
                pass

    # 2. Scan /proc for matching processes (Linux)
    proc_dir = Path("/proc")
    if proc_dir.exists():
        for proc_entry in proc_dir.iterdir():
            if not proc_entry.name.isdigit():
                continue
            try:
                cmdline = (proc_entry / "cmdline").read_bytes()
                if not cmdline:
                    continue
                cmd_str = cmdline.replace(b"\x00", b" ").decode("utf-8", errors="replace")
                if "a2a" in cmd_str.lower() or "mesh" in cmd_str.lower() or "runa" in cmd_str.lower():
                    # Try to extract node_id from --node-id or --name flag
                    m = re.search(r"--node-id[= ](\S+)", cmd_str)
                    if m:
                        node_ids.add(m.group(1))
                    m = re.search(r"--name[= ](\S+)", cmd_str)
                    if m:
                        node_ids.add(m.group(1))
                    # Use PID as fallback node id
                    if not node_ids:
                        node_ids.add(f"proc_{proc_entry.name}")
            except (OSError, PermissionError):
                continue

    # 3. Fallback: include "morzsa" (the node mentioned in the idea)
    if not node_ids:
        node_ids.add("morzsa")

    return sorted(node_ids)


def get_process_uptime_seconds(pid: int) -> float:
    """Get process uptime in seconds from /proc/[pid]/stat (Linux)."""
    try:
        stat_file = Path(f"/proc/{pid}/stat")
        if stat_file.exists():
            stat_data = stat_file.read_text().split()
            start_time_ticks = int(stat_data[21])
            # Read clock ticks per second
            clk_tck = os.sysconf(os.sysconf_names["SC_CLK_TCK"])
            boot_time = _get_boot_time()
            start_time_epoch = boot_time + (start_time_ticks / clk_tck)
            return max(0.0, time.time() - start_time_epoch)
    except (OSError, ValueError, IndexError, KeyError):
        pass
    return 0.0


def _get_boot_time() -> float:
    try:
        with open("/proc/stat", "r") as f:
            for line in f:
                if line.startswith("btime"):
                    return float(line.split()[1])
    except (OSError, IndexError):
        pass
    return time.time() - get_uptime_seconds()


def get_uptime_seconds() -> float:
    """System uptime in seconds."""
    try:
        with open("/proc/uptime", "r") as f:
            return float(f.readline().split()[0])
    except (OSError, IndexError):
        pass
    return 0.0


def get_process_memory_rss_kb(pid: int) -> int:
    """Get RSS memory in KB from /proc/[pid]/status."""
    try:
        status_file = Path(f"/proc/{pid}/status")
        if status_file.exists():
            for line in status_file.read_text().splitlines():
                if line.startswith("VmRSS:"):
                    return int(line.split()[1])
    except (OSError, ValueError, IndexError):
        pass
    return 0


def find_pid_for_node(node_id: str) -> Optional[int]:
    """Find the PID of a running node process."""
    proc_dir = Path("/proc")
    if not proc_dir.exists():
        return None

    for proc_entry in proc_dir.iterdir():
        if not proc_entry.name.isdigit():
            continue
        try:
            cmdline = (proc_entry / "cmdline").read_bytes()
            if not cmdline:
                continue
            cmd_str = cmdline.replace(b"\x00", b" ").decode("utf-8", errors="replace")
            if node_id in cmd_str or node_id == f"proc_{proc_entry.name}":
                return int(proc_entry.name)
        except (OSError, PermissionError):
            continue
    return None


def snapshot_node(node_id: str) -> NodeSnapshot:
    """Take a snapshot of a node's current state."""
    pid = find_pid_for_node(node_id)
    now = datetime.now(timezone.utc).isoformat()

    if pid is not None:
        uptime = get_process_uptime_seconds(pid)
        rss = get_process_memory_rss_kb(pid)
        status = "running"
    else:
        uptime = 0.0
        rss = 0
        status = "stopped"

    return NodeSnapshot(
        node_id=node_id,
        pid=pid,
        uptime_seconds=uptime,
        timestamp=now,
        memory_rss_kb=rss,
        status=status,
    )


# ---------------------------------------------------------------------------
# Log analysis for root-cause detection
# ---------------------------------------------------------------------------

def scan_logs_for_causes(node_id: str, since_iso: str) -> Tuple[str, List[str]]:
    """
    Scan log files for evidence of OOM, crash, or auto-update.
    Returns (suspected_cause, evidence_lines).
    """
    evidence: List[str] = []
    cause_scores: Dict[str, int] = {"oom": 0, "crash": 0, "auto_update": 0}

    # Determine which log files to scan
    log_files: List[Path] = []
    if LOG_DIR.exists():
        log_files.extend(LOG_DIR.glob("*.log"))
        log_files.extend(LOG_DIR.glob("*.log.*"))
    # Also check common locations
    for name in [f"{node_id}.log", f"a2a_{node_id}.log", "mesh.log", "agent.log"]:
        p = REPO_ROOT / "logs" / name
        if p.exists():
            log_files.append(p)
        p = REPO_ROOT / name
        if p.exists():
            log_files.append(p)

    # Also check dmesg for OOM killer (if accessible)
    try:
        dmesg_result = subprocess.run(
            ["dmesg", "--time-format=iso"],
            capture_output=True, text=True, timeout=5
        )
        if dmesg_result.returncode == 0:
            for line in dmesg_result.stdout.splitlines():
                for pattern in OOM_KILL_PATTERNS:
                    if pattern.search(line):
                        cause_scores["oom"] += 3
                        evidence.append(f"[dmesg] {line.strip()}")
                        break
    except (FileNotFoundError, subprocess.TimeoutExpired, PermissionError):
        pass

    # Scan log files
    for log_path in log_files:
        try:
            content = log_path.read_text(encoding="utf-8", errors="replace")
            for line in content.splitlines():
                for pattern in OOM_KILL_PATTERNS:
                    if pattern.search(line):
                        cause_scores["oom"] += 2
                        evidence.append(f"[{log_path.name}] {line.strip()}")
                        break
                for pattern in CRASH_PATTERNS:
                    if pattern.search(line):
                        cause_scores["crash"] += 2
                        evidence.append(f"[{log_path.name}] {line.strip()}")
                        break
                for pattern in UPDATE_PATTERNS:
                    if pattern.search(line):
                        cause_scores["auto_update"] += 1
                        evidence.append(f"[{log_path.name}] {line.strip()}")
                        break
        except OSError:
            continue

    # Determine primary cause
    if not evidence:
        return "unknown", []

    primary_cause = max(cause_scores, key=cause_scores.get)
    if cause_scores[primary_cause] == 0:
        return "unknown", evidence[:10]

    cause_labels = {
        "oom": "OOM kill (out of memory)",
        "crash": "Unhandled exception / crash",
        "auto_update": "Auto-updater triggered restart",
    }
    return cause_labels.get(primary_cause, "unknown"), evidence[:20]


# ---------------------------------------------------------------------------
# Core monitoring logic
# ---------------------------------------------------------------------------

def detect_restart(
    node_id: str,
    prev: Optional[NodeSnapshot],
    curr: NodeSnapshot,
) -> Optional[RestartEvent]:
    """Detect if a node has restarted between two snapshots."""
    if prev is None:
        return None

    # Restart detected if: PID changed, or uptime decreased
    pid_changed = prev.pid is not None and curr.pid is not None and prev.pid != curr.pid
    uptime_reset = prev.uptime_seconds > curr.uptime_seconds + 5  # 5s tolerance
    came_back = prev.status == "stopped" and curr.status == "running"

    if pid_changed or uptime_reset or came_back:
        cause, evidence = scan_logs_for_causes(node_id, prev.timestamp)
        return RestartEvent(
            node_id=node_id,
            old_pid=prev.pid,
            new_pid=curr.pid,
            old_uptime=prev.uptime_seconds,
            timestamp=curr.timestamp,
            suspected_cause=cause,
            evidence=evidence,
        )
    return None


def build_health_report(
    node_id: str,
    snapshots: List[NodeSnapshot],
    restart_events: List[RestartEvent],
    threshold: float,
) -> NodeHealthReport:
    """Build a health report for a single node."""
    current_uptime = snapshots[-1].uptime_seconds if snapshots else 0.0

    # Filter restart events to last 24h
    cutoff = time.time() - TARGET_UPTIME_SECONDS
    recent_restarts = [
        e for e in restart_events
        if e.node_id == node_id
        and datetime.fromisoformat(e.timestamp).timestamp() > cutoff
    ]

    # Compute uptime stats from restart events
    uptimes: List[float] = [current_uptime]
    for i, evt in enumerate(recent_restarts):
        uptimes.append(evt.old_uptime)

    shortest = min(uptimes) if uptimes else 0.0
    longest = max(uptimes) if uptimes else 0.0
    is_crumb = current_uptime < CRUMB_UPTIME_SECONDS or shortest < CRUMB_UPTIME_SECONDS

    # Aggregate suspected causes
    causes: List[str] = []
    for evt in recent_restarts:
        if evt.suspected_cause not in causes and evt.suspected_cause != "unknown":
            causes.append(evt.suspected_cause)
    if not causes and is_crumb:
        causes.append("unknown — insufficient log data")

    # Build recommendation
    if current_uptime >= TARGET_UPTIME_SECONDS:
        recommendation = "Healthy: uptime >24h. No action needed."
    elif is_crumb:
        recommendation = (
            "CRITICAL: Node exhibits 'crumb uptime' (<5min). "
            "Immediate root-cause analysis required. "
        )
        if "OOM kill" in " ".join(causes):
            recommendation += (
                "Increase memory limits or fix memory leak. "
                "Add memory monitoring and graceful degradation. "
            )
        if "crash" in " ".join(causes).lower():
            recommendation += (
                "Add try/except handlers around main loop. "
                "Implement structured logging for stack traces. "
            )
        if "auto-updater" in " ".join(causes).lower():
            recommendation += (
                "Review auto-updater policy. Add health checks before restart. "
                "Implement rolling updates with rollback support. "
            )
        recommendation += "Target: >24h uptime."
    elif current_uptime < threshold:
        recommendation = (
            f"WARNING: Uptime ({current_uptime:.0f}s) below threshold ({threshold:.0f}s). "
            "Monitor for restart patterns. Investigate logs."
        )
    else:
        recommendation = "Stable. Continue monitoring."

    return NodeHealthReport(
        node_id=node_id,
        current_uptime=current_uptime,
        restart_count_24h=len(recent_restarts),
        shortest_uptime=shortest,
        longest_uptime=longest,
        is_crumb=is_crumb,
        suspected_causes=causes,
        recommendation=recommendation,
    )


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def format_duration(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.0f}s"
    elif seconds < 3600:
        return f"{seconds/60:.1f}m"
    elif seconds < 86400:
        return f"{seconds/3600:.1f}h"
    else:
        return f"{seconds/86400:.1f}d"


def print_report(reports: List[NodeHealthReport], restart_events: List[RestartEvent]) -> None:
    print("\n" + "=" * 72)
    print("  A2A Mesh — Uptime Monitor & Restart Detector")
    print(f"  Report generated: {datetime.now(timezone.utc).isoformat()}")
    print("=" * 72)

    for report in reports:
        status_icon = "🔴" if report.is_crumb else ("🟡" if report.current_uptime < TARGET_UPTIME_SECONDS else "🟢")
        print(f"\n  {status_icon} Node: {report.node_id}")
        print(f"    Current uptime:   {format_duration(report.current_uptime)}")
        print(f"    Restarts (24h):   {report.restart_count_24h}")
        print(f"    Shortest uptime:  {format_duration(report.shortest_uptime)}")
        print(f"    Longest uptime:   {format_duration(report.longest_uptime)}")
        print(f"    Crumb detected:   {'YES' if report.is_crumb else 'no'}")
        if report.suspected_causes:
            print(f"    Suspected causes: {', '.join(report.suspected_causes)}")
        print(f"    Recommendation:   {report.recommendation}")

    if restart_events:
        print(f"\n  --- Recent Restart Events ({len(restart_events[-10:])}) ---")
        for evt in restart_events[-10:]:
            print(f"    [{evt.timestamp}] {evt.node_id}: "
                  f"PID {evt.old_pid}→{evt.new_pid}, "
                  f"prev uptime {format_duration(evt.old_uptime)}, "
                  f"cause: {evt.suspected_cause}")
            for line in evt.evidence[:3]:
                print(f"      evidence: {line}")

    # Summary
    crumb_nodes = [r for r in reports if r.is_crumb]
    print(f"\n  Summary: {len(reports)} nodes, {len(crumb_nodes)} crumb, "
          f"{len(restart_events)} total restarts recorded")
    print("=" * 72 + "\n")


def save_report(reports: List[NodeHealthReport], restart_events: List[RestartEvent]) -> None:
    ensure_dirs()
    report_data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "idea_id": "idea_75b84831f5a1",
        "target_uptime_seconds": TARGET_UPTIME_SECONDS,
        "crumb_threshold_seconds": CRUMB_UPTIME_SECONDS,
        "node_reports": [r.to_dict() for r in reports],
        "restart_events": [e.to_dict() for e in restart_events[-100:]],
    }
    REPORT_FILE.write_text(json.dumps(report_data, indent=2, ensure_ascii=False), encoding="utf-8")


# ---------------------------------------------------------------------------
# Main monitoring loop
# ---------------------------------------------------------------------------

_running = True


def _signal_handler(signum, frame):
    global _running
    _running = False
    print("\n[uptime_monitor] Shutting down gracefully...")


def run_monitor(threshold: float, interval: float, once: bool) -> None:
    global _running
    ensure_dirs()
    state = load_state()

    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)

    print(f"[uptime_monitor] Starting — threshold={format_duration(threshold)}, "
          f"interval={interval}s, once={once}")
    print(f"[uptime_monitor] State file: {STATE_FILE}")
    print(f"[uptime_monitor] Report file: {REPORT_FILE}")

    while _running:
        node_ids = discover_nodes()
        if not node_ids:
            print(f"[uptime_monitor] No nodes discovered. Using fallback 'morzsa'.")
            node_ids = ["morzsa"]

        all_reports: List[NodeHealthReport] = []
        all_restart_events: List[RestartEvent] = state.get("restart_events", [])

        for node_id in node_ids:
            curr = snapshot_node(node_id)
            prev_data = state.get("nodes", {}).get(node_id)
            prev = NodeSnapshot(**prev_data) if prev_data else None

            # Detect restart
            restart = detect_restart(node_id, prev, curr)
            if restart:
                all_restart_events.append(restart)
                print(f"[uptime_monitor] ⚠ RESTART detected: {node_id} "
                      f"(cause: {restart.suspected_cause})")

            # Update state
            state.setdefault("nodes", {})[node_id] = curr.to_dict()

            # Build report
            snapshots = [curr]  # In a full implementation, we'd keep history
            report = build_health_report(node_id, snapshots, all_restart_events, threshold)
            all_reports.append(report)

            if report.is_crumb:
                print(f"[uptime_monitor] 🔴 CRUMB: {node_id} uptime="
                      f"{format_duration(curr.uptime_seconds)}")

        # Trim history
        if len(all_restart_events) > 500:
            all_restart_events = all_restart_events[-500:]
        state["restart_events"] = all_restart_events

        # Save state
        save_state(state)

        # Print and save report
        print_report(all_reports, all_restart_events)
        save_report(all_reports, all_restart_events)

        if once:
            break

        # Wait for next interval
        wait_start = time.time()
        while _running and (time.time() - wait_start) < interval:
            time.sleep(1)

    print("[uptime_monitor] Stopped.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="A2A Mesh Uptime Monitor — detects frequent restarts and 'crumb' uptime nodes."
    )
    parser.add_argument(
        "--threshold", type=float, default=DEFAULT_THRESHOLD_SECONDS,
        help=f"Uptime threshold in seconds (default: {DEFAULT_THRESHOLD_SECONDS}s = 1h)"
    )
    parser.add_argument(
        "--interval", type=float, default=DEFAULT_INTERVAL_SECONDS,
        help=f"Check interval in seconds (default: {DEFAULT_INTERVAL_SECONDS}s)"
    )
    parser.add_argument(
        "--once", action="store_true",
        help="Run a single check and exit (no continuous monitoring)"
    )
    parser.add_argument(
        "--report-only", action="store_true",
        help="Only print the current report from saved state, no new checks"
    )
    args = parser.parse_args()

    if args.report_only:
        if REPORT_FILE.exists():
            data = json.loads(REPORT_FILE.read_text(encoding="utf-8"))
            print(json.dumps(data, indent=2, ensure_ascii=False))
            return 0
        else:
            print("No report file found. Run without --report-only first.")
            return 1

    run_monitor(
        threshold=args.threshold,
        interval=args.interval,
        once=args.once,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())