#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
[ötletláda] Inaktív szobák archiválása 48 óra után, tartalom RAG-indexelése későbbi visszakereséshez

This module implements:
1. Detection of inactive rooms (no activity for 48 hours)
2. Archiving inactive rooms to a separate archive store
3. RAG-style indexing of archived content for later retrieval
   (chunking + keyword/TF-IDF index + semantic similarity search)

Run from the repo root:
    python a2a_mesh/archive_rag_indexer.py
"""

import os
import sys
import json
import time
import math
import re
import hashlib
import pickle
import sqlite3
from datetime import datetime, timezone, timedelta
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Tuple, Any
from collections import defaultdict, Counter

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(REPO_ROOT, "data")
ROOMS_DIR = os.path.join(DATA_DIR, "rooms")
ARCHIVE_DIR = os.path.join(DATA_DIR, "archive")
INDEX_DIR = os.path.join(DATA_DIR, "rag_index")
INDEX_DB_PATH = os.path.join(INDEX_DIR, "rag_index.db")

INACTIVITY_THRESHOLD_HOURS = 48
CHUNK_SIZE = 200  # words per chunk
CHUNK_OVERLAP = 30  # overlapping words between chunks

# Hungarian + English stopwords for better indexing
STOPWORDS = {
    # Hungarian
    "a", "az", "egy", "és", "vagy", "is", "hogy", "nem", "de", "ha",
    "meg", "már", "csak", "még", "mint", "volt", "van", "lesz", "ez",
    "azt", "ezt", "ilyen", "olyan", "minden", "semmi", "valami",
    "után", "előtt", "között", "alatt", "fölött", "mellett", "nélkül",
    "vel", "nak", "nek", "hoz", "hez", "höz", "ban", "ben", "ra", "re",
    "ba", "be", "tól", "től", "ig", "ként", "kor", "képp", "on", "en", "ön",
    # English
    "the", "a", "an", "and", "or", "is", "are", "was", "were", "be",
    "been", "being", "have", "has", "had", "do", "does", "did", "will",
    "would", "could", "should", "may", "might", "must", "shall", "can",
    "this", "that", "these", "those", "i", "you", "he", "she", "it",
    "we", "they", "what", "which", "who", "when", "where", "why", "how",
    "in", "on", "at", "to", "for", "of", "with", "by", "from", "as",
    "about", "into", "through", "during", "before", "after", "above",
    "below", "up", "down", "out", "off", "over", "under", "again",
    "not", "no", "only", "just", "also", "but", "if", "then", "than",
}


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

@dataclass
class Message:
    """A single message in a room."""
    id: str
    author: str
    content: str
    timestamp: float  # unix epoch
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Room:
    """A debate/discussion room."""
    id: str
    name: str
    created_at: float
    last_activity: float
    messages: List[Message] = field(default_factory=list)
    status: str = "active"  # active, archived
    metadata: Dict[str, Any] = field(default_factory=dict)

    def is_inactive(self, threshold_hours: float = INACTIVITY_THRESHOLD_HOURS) -> bool:
        """Check if room has been inactive for longer than threshold."""
        now = time.time()
        elapsed_hours = (now - self.last_activity) / 3600.0
        return elapsed_hours >= threshold_hours


@dataclass
class Chunk:
    """A text chunk for RAG indexing."""
    chunk_id: str
    room_id: str
    room_name: str
    text: str
    tokens: List[str]
    timestamp: float
    message_ids: List[str]
    tf: Dict[str, float] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Room Storage (JSON-based)
# ---------------------------------------------------------------------------

class RoomStore:
    """Manages room persistence using JSON files."""

    def __init__(self, rooms_dir: str, archive_dir: str):
        self.rooms_dir = rooms_dir
        self.archive_dir = archive_dir
        os.makedirs(rooms_dir, exist_ok=True)
        os.makedirs(archive_dir, exist_ok=True)

    def _room_path(self, room_id: str, archived: bool = False) -> str:
        base = self.archive_dir if archived else self.rooms_dir
        safe_id = re.sub(r'[^a-zA-Z0-9_\-]', '_', room_id)
        return os.path.join(base, f"room_{safe_id}.json")

    def save_room(self, room: Room) -> str:
        path = self._room_path(room.id, archived=(room.status == "archived"))
        data = {
            "id": room.id,
            "name": room.name,
            "created_at": room.created_at,
            "last_activity": room.last_activity,
            "status": room.status,
            "metadata": room.metadata,
            "messages": [asdict(m) for m in room.messages],
        }
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return path

    def load_room(self, room_id: str, archived: bool = False) -> Optional[Room]:
        path = self._room_path(room_id, archived=archived)
        if not os.path.exists(path):
            return None
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        messages = [
            Message(
                id=m["id"],
                author=m["author"],
                content=m["content"],
                timestamp=m["timestamp"],
                metadata=m.get("metadata", {}),
            )
            for m in data.get("messages", [])
        ]
        return Room(
            id=data["id"],
            name=data["name"],
            created_at=data["created_at"],
            last_activity=data["last_activity"],
            messages=messages,
            status=data.get("status", "active"),
            metadata=data.get("metadata", {}),
        )

    def list_active_rooms(self) -> List[str]:
        """Return list of active room IDs."""
        room_ids = []
        if not os.path.exists(self.rooms_dir):
            return room_ids
        for fname in os.listdir(self.rooms_dir):
            if fname.startswith("room_") and fname.endswith(".json"):
                room_id = fname[5:-5]
                room_ids.append(room_id)
        return room_ids

    def list_archived_rooms(self) -> List[str]:
        """Return list of archived room IDs."""
        room_ids = []
        if not os.path.exists(self.archive_dir):
            return room_ids
        for fname in os.listdir(self.archive_dir):
            if fname.startswith("room_") and fname.endswith(".json"):
                room_id = fname[5:-5]
                room_ids.append(room_id)
        return room_ids

    def move_to_archive(self, room: Room) -> str:
        """Move a room from active to archive storage."""
        old_path = self._room_path(room.id, archived=False)
        room.status = "archived"
        new_path = self.save_room(room)
        if os.path.exists(old_path) and old_path != new_path:
            os.remove(old_path)
        return new_path


# ---------------------------------------------------------------------------
# Text Processing
# ---------------------------------------------------------------------------

def tokenize(text: str) -> List[str]:
    """Tokenize text into lowercase word tokens, removing stopwords."""
    text = text.lower()
    # Handle Hungarian and English word characters including accented chars
    tokens = re.findall(r'[a-záéíóöőúüű]+', text)
    return [t for t in tokens if t not in STOPWORDS and len(t) > 1]


def chunk_messages(messages: List[Message],
                   chunk_size: int = CHUNK_SIZE,
                   overlap: int = CHUNK_OVERLAP) -> List[Tuple[str, List[str]]]:
    """
    Chunk messages into overlapping text segments.
    Returns list of (chunk_text, message_ids_in_chunk).
    """
    if not messages:
        return []

    # Sort by timestamp
    sorted_msgs = sorted(messages, key=lambda m: m.timestamp)

    # Build a flat list of (word, message_id) pairs
    word_msg_pairs: List[Tuple[str, str]] = []
    for msg in sorted_msgs:
        words = msg.content.split()
        for w in words:
            word_msg_pairs.append((w, msg.id))

    if not word_msg_pairs:
        return []

    chunks: List[Tuple[str, List[str]]] = []
    i = 0
    step = max(1, chunk_size - overlap)

    while i < len(word_msg_pairs):
        end = min(i + chunk_size, len(word_msg_pairs))
        segment = word_msg_pairs[i:end]
        chunk_text = " ".join(w for w, _ in segment)
        msg_ids = list(dict.fromkeys(mid for _, mid in segment))  # preserve order, dedupe
        chunks.append((chunk_text, msg_ids))
        if end >= len(word_msg_pairs):
            break
        i += step

    return chunks


def compute_tf(tokens: List[str]) -> Dict[str, float]:
    """Compute term frequency for a list of tokens."""
    if not tokens:
        return {}
    count = Counter(tokens)
    total = len(tokens)
    return {term: freq / total for term, freq in count.items()}


# ---------------------------------------------------------------------------
# RAG Index (SQLite-based)
# ---------------------------------------------------------------------------

class RAGIndex:
    """
    SQLite-based RAG index supporting:
    - Keyword search (TF-IDF scoring)
    - Semantic similarity (cosine similarity on TF-IDF vectors)
    - Metadata filtering by room
    """

    def __init__(self, db_path: str):
        self.db_path = db_path
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        self.conn = sqlite3.connect(db_path)
        self._init_schema()

    def _init_schema(self):
        cur = self.conn.cursor()
        cur.execute("""
            CREATE TABLE IF NOT EXISTS chunks (
                chunk_id TEXT PRIMARY KEY,
                room_id TEXT NOT NULL,
                room_name TEXT NOT NULL,
                text TEXT NOT NULL,
                timestamp REAL NOT NULL,
                message_ids TEXT NOT NULL
            )
        """)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS chunk_tokens (
                chunk_id TEXT NOT NULL,
                token TEXT NOT NULL,
                tf REAL NOT NULL,
                FOREIGN KEY (chunk_id) REFERENCES chunks(chunk_id)
            )
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_chunk_tokens_token
            ON chunk_tokens(token)
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS idx_chunks_room
            ON chunks(room_id)
        """)
        # Document frequency cache
        cur.execute("""
            CREATE TABLE IF NOT EXISTS df_cache (
                token TEXT PRIMARY KEY,
                df INTEGER NOT NULL
            )
        """)
        # Room archive metadata
        cur.execute("""
            CREATE TABLE IF NOT EXISTS archived_rooms (
                room_id TEXT PRIMARY KEY,
                room_name TEXT NOT NULL,
                archived_at REAL NOT NULL,
                message_count INTEGER NOT NULL,
                chunk_count INTEGER NOT NULL,
                summary TEXT
            )
        """)
        self.conn.commit()

    def index_chunks(self, chunks: List[Chunk]) -> None:
        """Insert/update chunks in the index."""
        cur = self.conn.cursor()
        for chunk in chunks:
            # Insert chunk record
            cur.execute("""
                INSERT OR REPLACE INTO chunks
                (chunk_id, room_id, room_name, text, timestamp, message_ids)
                VALUES (?, ?, ?, ?, ?, ?)
            """, (
                chunk.chunk_id,
                chunk.room_id,
                chunk.room_name,
                chunk.text,
                chunk.timestamp,
                json.dumps(chunk.message_ids),
            ))
            # Insert token records
            for token, tf_val in chunk.tf.items():
                cur.execute("""
                    INSERT OR REPLACE INTO chunk_tokens
                    (chunk_id, token, tf) VALUES (?, ?, ?)
                """, (chunk.chunk_id, token, tf_val))
        self.conn.commit()
        self._rebuild_df_cache()

    def _rebuild_df_cache(self) -> None:
        """Rebuild document frequency cache."""
        cur = self.conn.cursor()
        cur.execute("DELETE FROM df_cache")
        cur.execute("""
            INSERT INTO df_cache (token, df)
            SELECT token, COUNT(DISTINCT chunk_id) as df
            FROM chunk_tokens
            GROUP BY token
        """)
        self.conn.commit()

    def _get_idf(self, token: str) -> float:
        """Get inverse document frequency for a token."""
        cur = self.conn.cursor()
        cur.execute("SELECT df FROM df_cache WHERE token = ?", (token,))
        row = cur.fetchone()
        if not row:
            return 0.0
        df = row[0]
        cur.execute("SELECT COUNT(DISTINCT chunk_id) FROM chunk_tokens")
        total = cur.fetchone()[0]
        if total == 0 or df == 0:
            return 0.0
        return math.log((total + 1) / (df + 1)) + 1.0

    def search(self, query: str, top_k: int = 5,
               room_id: Optional[str] = None) -> List[Dict[str, Any]]:
        """
        Search the RAG index using TF-IDF cosine similarity.
        Returns top_k results sorted by relevance.
        """
        query_tokens = tokenize(query)
        if not query_tokens:
            return []

        # Compute query TF-IDF vector
        query_tf = compute_tf(query_tokens)
        query_vec = {t: tf * self._get_idf(t) for t, tf in query_tf.items()}
        query_norm = math.sqrt(sum(v ** 2 for v in query_vec.values()))
        if query_norm == 0:
            return []

        # Find candidate chunks that share at least one token
        cur = self.conn.cursor()
        placeholders = ",".join("?" * len(query_tokens))
        if room_id:
            cur.execute(f"""
                SELECT DISTINCT ct.chunk_id
                FROM chunk_tokens ct
                JOIN chunks c ON ct.chunk_id = c.chunk_id
                WHERE ct.token IN ({placeholders}) AND c.room_id = ?
            """, (*query_tokens, room_id))
        else:
            cur.execute(f"""
                SELECT DISTINCT chunk_id
                FROM chunk_tokens
                WHERE token IN ({placeholders})
            """, query_tokens)

        candidate_ids = [row[0] for row in cur.fetchall()]
        if not candidate_ids:
            return []

        # Score each candidate
        scores: List[Tuple[str, float]] = []
        for chunk_id in candidate_ids:
            cur.execute("""
                SELECT token, tf FROM chunk_tokens WHERE chunk_id = ?
            """, (chunk_id,))
            chunk_tf = {row[0]: row[1] for row in cur.fetchall()}
            chunk_vec = {t: tf * self._get_idf(t) for t, tf in chunk_tf.items()}
            chunk_norm = math.sqrt(sum(v ** 2 for v in chunk_vec.values()))
            if chunk_norm == 0:
                continue

            # Cosine similarity (dot product over shared tokens)
            dot = sum(query_vec.get(t, 0) * chunk_vec.get(t, 0) for t in query_vec)
            score = dot / (query_norm * chunk_norm)
            scores.append((chunk_id, score))

        scores.sort(key=lambda x: x[1], reverse=True)
        top_ids = [cid for cid, _ in scores[:top_k]]

        if not top_ids:
            return []

        # Fetch full chunk data
        placeholders = ",".join("?" * len(top_ids))
        cur.execute(f"""
            SELECT chunk_id, room_id, room_name, text, timestamp, message_ids
            FROM chunks
            WHERE chunk_id IN ({placeholders})
        """, top_ids)

        results = []
        for row in cur.fetchall():
            cid, rid, rname, text, ts, mids_json = row
            score = dict(scores).get(cid, 0.0)
            results.append({
                "chunk_id": cid,
                "room_id": rid,
                "room_name": rname,
                "text": text,
                "timestamp": ts,
                "message_ids": json.loads(mids_json),
                "score": round(score, 4),
            })

        # Sort by score descending
        results.sort(key=lambda r: r["score"], reverse=True)
        return results

    def record_archive(self, room_id: str, room_name: str,
                       archived_at: float, message_count: int,
                       chunk_count: int, summary: str = "") -> None:
        """Record metadata about an archived room."""
        cur = self.conn.cursor()
        cur.execute("""
            INSERT OR REPLACE INTO archived_rooms
            (room_id, room_name, archived_at, message_count, chunk_count, summary)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (room_id, room_name, archived_at, message_count, chunk_count, summary))
        self.conn.commit()

    def list_archived(self) -> List[Dict[str, Any]]:
        """List all archived rooms with metadata."""
        cur = self.conn.cursor()
        cur.execute("""
            SELECT room_id, room_name, archived_at, message_count, chunk_count, summary
            FROM archived_rooms
            ORDER BY archived_at DESC
        """)
        return [
            {
                "room_id": row[0],
                "room_name": row[1],
                "archived_at": row[2],
                "message_count": row[3],
                "chunk_count": row[4],
                "summary": row[5],
            }
            for row in cur.fetchall()
        ]

    def close(self):
        self.conn.close()


# ---------------------------------------------------------------------------
# Room Summarizer (simple extractive)
# ---------------------------------------------------------------------------

def summarize_room(room: Room, max_sentences: int = 3) -> str:
    """
    Generate a simple extractive summary of a room's content.
    Picks the most representative sentences based on word frequency.
    """
    if not room.messages:
        return "Nincs tartalom az összefoglaláshoz."

    # Combine all message content
    full_text = " ".join(m.content for m in room.messages)

    # Split into sentences (handle . ! ? for both Hungarian and English)
    sentences = re.split(r'(?<=[.!?])\s+', full_text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 10]

    if len(sentences) <= max_sentences:
        return " ".join(sentences)

    # Score sentences by sum of token frequencies
    all_tokens = tokenize(full_text)
    token_freq = Counter(all_tokens)

    scored = []
    for i, sent in enumerate(sentences):
        sent_tokens = tokenize(sent)
        if not sent_tokens:
            continue
        score = sum(token_freq.get(t, 0) for t in sent_tokens) / len(sent_tokens)
        # Slight bonus for earlier sentences
        score *= (1.0 + 0.1 * (1.0 - i / len(sentences)))
        scored.append((score, i, sent))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = sorted(scored[:max_sentences], key=lambda x: x[1])
    return " ".join(s for _, _, s in top)


# ---------------------------------------------------------------------------
# Archive Manager
# ---------------------------------------------------------------------------

class ArchiveManager:
    """
    Orchestrates the archiving and indexing of inactive rooms.
    """

    def __init__(self, store: RoomStore, index: RAGIndex):
        self.store = store
        self.index = index

    def find_inactive_rooms(self) -> List[Room]:
        """Find all active rooms that have been inactive for 48+ hours."""
        inactive = []
        for room_id in self.store.list_active_rooms():
            room = self.store.load_room(room_id, archived=False)
            if room and room.is_inactive():
                inactive.append(room)
        return inactive

    def archive_room(self, room: Room) -> Dict[str, Any]:
        """
        Archive a single room:
        1. Generate summary
        2. Chunk content
        3. Index chunks for RAG
        4. Move room to archive storage
        5. Record archive metadata
        """
        print(f"  📦 Archiving room: {room.name} ({room.id})")

        # Generate summary
        summary = summarize_room(room)
        print(f"     Summary: {summary[:100]}...")

        # Chunk messages
        raw_chunks = chunk_messages(room.messages)
        print(f"     Chunks created: {len(raw_chunks)}")

        # Build Chunk objects with TF
        chunks: List[Chunk] = []
        for i, (text, msg_ids) in enumerate(raw_chunks):
            tokens = tokenize(text)
            chunk_id = hashlib.sha256(
                f"{room.id}:{i}:{text[:50]}".encode()
            ).hexdigest()[:16]
            chunks.append(Chunk(
                chunk_id=chunk_id,
                room_id=room.id,
                room_name=room.name,
                text=text,
                tokens=tokens,
                timestamp=room.last_activity,
                message_ids=msg_ids,
                tf=compute_tf(tokens),
            ))

        # Index chunks
        if chunks:
            self.index.index_chunks(chunks)

        # Record archive metadata
        archived_at = time.time()
        self.index.record_archive(
            room_id=room.id,
            room_name=room.name,
            archived_at=archived_at,
            message_count=len(room.messages),
            chunk_count=len(chunks),
            summary=summary,
        )

        # Move to archive storage
        archive_path = self.store.move_to_archive(room)
        print(f"     Archived to: {archive_path}")

        return {
            "room_id": room.id,
            "room_name": room.name,
            "archived_at": archived_at,
            "message_count": len(room.messages),
            "chunk_count": len(chunks),
            "summary": summary,
            "archive_path": archive_path,
        }

    def run_archive_cycle(self) -> List[Dict[str, Any]]:
        """Run a full archive cycle: find and archive all inactive rooms."""
        print("=" * 60)
        print("🔄 Archive cycle started")
        print(f"   Threshold: {INACTIVITY_THRESHOLD_HOURS} hours of inactivity")
        print(f"   Time: {datetime.now(timezone.utc).isoformat()}")
        print("=" * 60)

        inactive_rooms = self.find_inactive_rooms()
        print(f"\n📋 Found {len(inactive_rooms)} inactive room(s)")

        results = []
        for room in inactive_rooms:
            result = self.archive_room(room)
            results.append(result)

        print(f"\n✅ Archive cycle complete: {len(results)} room(s) archived")
        return results

    def retrieve(self, query: str, top_k: int = 5,
                 room_id: Optional[str] = None) -> List[Dict[str, Any]]:
        """Retrieve relevant chunks from the RAG index."""
        return self.index.search(query, top_k=top_k, room_id=room_id)


# ---------------------------------------------------------------------------
# Demo / Test Data Generation
# ---------------------------------------------------------------------------

def create_demo_rooms(store: RoomStore) -> None:
    """Create demo rooms for testing, including some that are inactive."""
    now = time.time()

    # Room 1: Inactive (3 days old, last activity 72h ago)
    room1 = Room(
        id="demo_room_001",
        name="RAG indexelés vitája",
        created_at=now - 72 * 3600,
        last_activity=now - 72 * 3600,
        messages=[
            Message(
                id="m1", author="mano",
                content="Szerintem a RAG indexelés kritikus a későbbi visszakereséshez. "
                        "Inaktív szobák tartalmát indexelni kell, különben elveszik.",
                timestamp=now - 72 * 3600,
            ),
            Message(
                id="m2", author="runa",
                content="Egyetértek. A chunking stratégiát is meg kell tervezni. "
                        "200 szavas átfedéssel működhet jól a debate kontextusban.",
                timestamp=now - 71 * 3600,
            ),
            Message(
                id="m3", author="mano",
                content="A TF-IDF alapú keresés elegendő lehet kezdetnek. "
                        "Később embedding modelleket is hozzáadhatunk.",
                timestamp=now - 70 * 3600,
            ),
        ],
    )
    store.save_room(room1)

    # Room 2: Inactive (50 hours ago)
    room2 = Room(
        id="demo_room_002",
        name="Archiválási stratégiák",
        created_at=now - 50 * 3600,
        last_activity=now - 50 * 3600,
        messages=[
            Message(
                id="m4", author="agent_alpha",
                content="Az archiválás után a szobák csak olvashatóak legyenek. "
                        "Az index viszont frissíthető marad, ha új kontextus jön.",
                timestamp=now - 50 * 3600,
            ),
            Message(
                id="m5", author="mano",
                content="Jó ötlet. Az SQLite index kompakt és elég gyors. "
                        "A koszinusz hasonlóság TF-IDF vektorokon jól működik.",
                timestamp=now - 49 * 3600,
            ),
        ],
    )
    store.save_room(room2)

    # Room 3: Active (recent activity)
    room3 = Room(
        id="demo_room_003",
        name="Aktív vita szoba",
        created_at=now - 3600,
        last_activity=now - 300,
        messages=[
            Message(
                id="m6", author="user1",
                content="Ez a szoba még aktív, nem szabad archiválni.",
                timestamp=now - 300,
            ),
        ],
    )
    store.save_room(room3)

    print(f"✅ Created 3 demo rooms (2 inactive, 1 active)")


# ---------------------------------------------------------------------------
# CLI Interface
# ---------------------------------------------------------------------------

def cmd_archive(store: RoomStore, index: RAGIndex) -> None:
    """Run the archive cycle."""
    manager = ArchiveManager(store, index)
    results = manager.run_archive_cycle()
    if results:
        print("\n📊 Archive Summary:")
        for r in results:
            print(f"  - {r['room_name']}: {r['message_count']} msgs, "
                  f"{r['chunk_count']} chunks indexed")
    else:
        print("\nℹ️  No inactive rooms found to archive.")


def cmd_search(store: RoomStore, index: RAGIndex, query: str) -> None:
    """Search the RAG index."""
    manager = ArchiveManager(store, index)
    results = manager.retrieve(query, top_k=5)
    if results:
        print(f"\n🔍 Search results for: '{query}'")
        print("-" * 60)
        for i, r in enumerate(results, 1):
            print(f"\n[{i}] Score: {r['score']} | Room: {r['room_name']}")
            print(f"    Text: {r['text'][:150]}...")
    else:
        print(f"\n🔍 No results found for: '{query}'")


def cmd_list_archived(store: RoomStore, index: RAGIndex) -> None:
    """List archived rooms."""
    archived = index.list_archived()
    if not archived:
        print("\n📂 No archived rooms yet.")
        return
    print(f"\n📂 Archived rooms ({len(archived)}):")
    print("-" * 60)
    for a in archived:
        dt = datetime.fromtimestamp(a["archived_at"], tz=timezone.utc)
        print(f"  - {a['room_name']} ({a['room_id']})")
        print(f"    Archived: {dt.isoformat()}")
        print(f"    Messages: {a['message_count']}, Chunks: {a['chunk_count']}")
        print(f"    Summary: {a['summary'][:100]}...")
        print()


def cmd_demo(store: RoomStore, index: RAGIndex) -> None:
    """Create demo data and run full cycle."""
    create_demo_rooms(store)
    cmd_archive(store, index)
    print("\n" + "=" * 60)
    print("Now testing RAG retrieval...")
    cmd_search(store, index, "RAG indexelés visszakeresés")
    cmd_search(store, index, "archiválás SQLite TF-IDF")
    cmd_list_archived(store, index)


def cmd_status(store: RoomStore, index: RAGIndex) -> None:
    """Show status of active and archived rooms."""
    active_ids = store.list_active_rooms()
    archived_ids = store.list_archived_rooms()
    print(f"\n📊 Status:")
    print(f"  Active rooms:   {len(active_ids)}")
    print(f"  Archived rooms: {len(archived_ids)}")
    for rid in active_ids:
        room = store.load_room(rid)
        if room:
            elapsed = (time.time() - room.last_activity) / 3600
            status = "⚠️ INACTIVE" if room.is_inactive() else "✅ active"
            print(f"    [{status}] {room.name} — {elapsed:.1f}h since last activity")


def main():
    """Main entry point with CLI argument handling."""
    store = RoomStore(ROOMS_DIR, ARCHIVE_DIR)
    index = RAGIndex(INDEX_DB_PATH)

    if len(sys.argv) < 2:
        print(__doc__)
        print("\nUsage:")
        print(f"  python {sys.argv[0]} demo      — Create demo data & run full cycle")
        print(f"  python {sys.argv[0]} archive   — Archive inactive rooms (48h+)")
        print(f"  python {sys.argv[0]} search <query> — Search RAG index")
        print(f"  python {sys.argv[0]} list      — List archived rooms")
        print(f"  python {sys.argv[0]} status    — Show room status")
        index.close()
        return

    cmd = sys.argv[1].lower()

    try:
        if cmd == "demo":
            cmd_demo(store, index)
        elif cmd == "archive":
            cmd_archive(store, index)
        elif cmd == "search":
            query = " ".join(sys.argv[2:]) if len(sys.argv) > 2 else ""
            if not query:
                print("Error: provide a search query")
                print(f"  python {sys.argv[0]} search \"your query here\"")
            else:
                cmd_search(store, index, query)
        elif cmd == "list":
            cmd_list_archived(store, index)
        elif cmd == "status":
            cmd_status(store, index)
        else:
            print(f"Unknown command: {cmd}")
            print(f"Run 'python {sys.argv[0]}' for usage.")
    finally:
        index.close()


if __name__ == "__main__":
    main()