#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generated by runa via A2A Mesh delegation

P50/P95 latencia-grafikon dashboard transportonként.
Időben látszódjon, melyik út (transport) romlik.

Önállóan futtatható a repó gyökeréből:
    python dashboard/latency_dashboard.py

Egy beépített HTTP szerver indít, ami egy inline HTML/CSS/JS
dashboardot szolgál ki (nincs külső függőség). A dashboard
canvas-al rajzolja a P50/P95 görbéket transportonként, időben.

Használat A2A Mesh-ből:
    from dashboard.latency_dashboard import LatencyMetrics, DashboardServer
    metrics = LatencyMetrics()
    metrics.record("websocket", 42.5)
    metrics.record("http", 120.3)
    server = DashboardServer(metrics, host="127.0.0.1", port=8765)
    server.start_background()
"""

from __future__ import annotations

import bisect
import json
import math
import threading
import time
import random
import http.server
import socketserver
from collections import defaultdict, deque
from typing import Dict, List, Tuple, Optional


# ---------------------------------------------------------------------------
# LatencyMetrics — minták gyűjtése transportonként, P50/P95 számítás
# ---------------------------------------------------------------------------

class LatencyMetrics:
    """
    Szálbiztos latencia-metrika gyűjtő transportonként.

    Minden transporthoz egy (timestamp, latency_ms) minta-sorozatot tárol
    rolling ablakkal. P50/P95 értékeket tud számolni adott időablakra.
    """

    def __init__(self, max_samples_per_transport: int = 5000,
                 retention_seconds: float = 3600.0):
        self._lock = threading.Lock()
        self._samples: Dict[str, deque] = defaultdict(
            lambda: deque(maxlen=max_samples_per_transport)
        )
        self._retention = retention_seconds
        # transport -> szín (a dashboard számára)
        self._colors: Dict[str, str] = {}
        self._palette = [
            "#4dc9f6", "#f67019", "#f53794", "#537bc4",
            "#acc236", "#166a8f", "#00a950", "#58595b",
            "#8549ba", "#991b1b", "#0d9488", "#b45309",
        ]
        self._color_idx = 0

    def _color_for(self, transport: str) -> str:
        if transport not in self._colors:
            self._colors[transport] = self._palette[
                self._color_idx % len(self._palette)
            ]
            self._color_idx += 1
        return self._colors[transport]

    def record(self, transport: str, latency_ms: float,
               timestamp: Optional[float] = None) -> None:
        """Egy latencia-minta rögzítése egy adott transportra."""
        if timestamp is None:
            timestamp = time.time()
        with self._lock:
            self._color_for(transport)
            self._samples[transport].append((timestamp, float(latency_ms)))

    def _prune(self, transport: str, now: float) -> None:
        q = self._samples[transport]
        cutoff = now - self._retention
        while q and q[0][0] < cutoff:
            q.popleft()

    @staticmethod
    def _percentile(sorted_vals: List[float], p: float) -> float:
        if not sorted_vals:
            return 0.0
        if len(sorted_vals) == 1:
            return sorted_vals[0]
        k = (len(sorted_vals) - 1) * (p / 100.0)
        f = math.floor(k)
        c = math.ceil(k)
        if f == c:
            return sorted_vals[int(k)]
        d0 = sorted_vals[int(f)] * (c - k)
        d1 = sorted_vals[int(c)] * (k - f)
        return d0 + d1

    def transports(self) -> List[str]:
        with self._lock:
            return sorted(self._samples.keys())

    def percentile_series(self, transport: str, p: float,
                          bucket_seconds: float = 30.0,
                          now: Optional[float] = None
                          ) -> List[Tuple[float, float]]:
        """
        Visszaadja a p-edik percentilis időbeli alakját bucket-ekre bontva.
        Visszatér: [(bucket_center_time, percentile_value), ...]
        """
        if now is None:
            now = time.time()
        with self._lock:
            self._prune(transport, now)
            samples = list(self._samples[transport])
        if not samples:
            return []
        start = samples[0][0]
        end = samples[-1][0]
        if end <= start:
            return [(start, self._percentile([s[1] for s in samples], p))]
        buckets: Dict[float, List[float]] = defaultdict(list)
        for ts, lat in samples:
            b = math.floor((ts - start) / bucket_seconds) * bucket_seconds + start
            buckets[b].append(lat)
        result = []
        for b in sorted(buckets.keys()):
            vals = sorted(buckets[b])
            result.append((b + bucket_seconds / 2.0,
                           self._percentile(vals, p)))
        return result

    def snapshot(self, bucket_seconds: float = 30.0) -> dict:
        """
        JSON-serializálható pillanatkép a dashboard számára.
        Tartalmazza transportonként a P50 és P95 sorozatokat, színeket,
        és az aktuális (utolsó bucket) értékeket.
        """
        now = time.time()
        data = {"now": now, "transports": []}
        with self._lock:
            transports = sorted(self._samples.keys())
            for t in transports:
                self._prune(t, now)
        for t in transports:
            p50 = self.percentile_series(t, 50, bucket_seconds, now)
            p95 = self.percentile_series(t, 95, bucket_seconds, now)
            latest_p50 = p50[-1][1] if p50 else 0.0
            latest_p95 = p95[-1][1] if p95 else 0.0
            # trend: utolsó vs előző bucket
            trend_p50 = 0.0
            trend_p95 = 0.0
            if len(p50) >= 2:
                prev = p50[-2][1] or 1e-9
                trend_p50 = (p50[-1][1] - prev) / prev * 100.0
            if len(p95) >= 2:
                prev = p95[-2][1] or 1e-9
                trend_p95 = (p95[-1][1] - prev) / prev * 100.0
            data["transports"].append({
                "name": t,
                "color": self._color_for(t),
                "p50": [{"t": ts, "v": v} for ts, v in p50],
                "p95": [{"t": ts, "v": v} for ts, v in p95],
                "latest_p50": round(latest_p50, 2),
                "latest_p95": round(latest_p95, 2),
                "trend_p50": round(trend_p50, 2),
                "trend_p95": round(trend_p95, 2),
                "sample_count": len(self._samples[t]) if t in self._samples else 0,
            })
        return data


# ---------------------------------------------------------------------------
# DashboardServer — HTTP szerver inline HTML/CSS/JS dashboarddal
# ---------------------------------------------------------------------------

DASHBOARD_HTML = r"""<!DOCTYPE html>
<html lang="hu">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>A2A Mesh — P50/P95 Latencia Dashboard</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: #0f172a; color: #e2e8f0; min-height: 100vh; padding: 20px;
  }
  h1 { font-size: 22px; margin-bottom: 4px; color: #f8fafc; }
  .sub { color: #94a3b8; font-size: 13px; margin-bottom: 20px; }
  .grid {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
    gap: 16px; margin-bottom: 20px;
  }
  .card {
    background: #1e293b; border: 1px solid #334155; border-radius: 12px;
    padding: 16px; position: relative; overflow: hidden;
  }
  .card.degraded { border-color: #f59e0b; box-shadow: 0 0 12px rgba(245,158,11,.25); }
  .card.critical { border-color: #ef4444; box-shadow: 0 0 14px rgba(239,68,68,.3); }
  .card-head { display: flex; align-items: center; gap: 8px; margin-bottom: 10px; }
  .dot { width: 12px; height: 12px; border-radius: 50%; flex-shrink: 0; }
  .tname { font-weight: 600; font-size: 15px; }
  .scnt { margin-left: auto; font-size: 11px; color: #64748b; }
  .stats { display: flex; gap: 16px; margin-bottom: 10px; }
  .stat { flex: 1; }
  .stat .lbl { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: .5px; }
  .stat .val { font-size: 20px; font-weight: 700; }
  .stat .trend { font-size: 11px; }
  .trend.up { color: #ef4444; }
  .trend.down { color: #22c55e; }
  .trend.flat { color: #64748b; }
  canvas { width: 100%; height: 120px; display: block; }
  .legend { display: flex; gap: 14px; font-size: 11px; color: #94a3b8; margin-top: 6px; }
  .legend span { display: flex; align-items: center; gap: 4px; }
  .legend i { width: 14px; height: 2px; display: inline-block; }
  .controls { margin-bottom: 16px; display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }
  .controls label { font-size: 13px; color: #94a3b8; }
  select, button {
    background: #1e293b; color: #e2e8f0; border: 1px solid #334155;
    border-radius: 6px; padding: 5px 10px; font-size: 13px; cursor: pointer;
  }
  button:hover { border-color: #475569; }
  .status { font-size: 12px; color: #64748b; margin-left: auto; }
  .empty { text-align: center; padding: 60px; color: #64748b; }
</style>
</head>
<body>
<h1>A2A Mesh — P50/P95 Latencia Dashboard</h1>
<div class="sub">Transportonkénti P50/P95 latencia időben — látszódjon, melyik út romlik.</div>
<div class="controls">
  <label>Frissítés:
    <select id="interval">
      <option value="1000">1s</option>
      <option value="2000" selected>2s</option>
      <option value="5000">5s</option>
      <option value="0">off</option>
    </select>
  </label>
  <label>Bucket:
    <select id="bucket">
      <option value="10">10s</option>
      <option value="30" selected>30s</option>
      <option value="60">60s</option>
    </select>
  </label>
  <button id="refresh">Frissít</button>
  <span class="status" id="status"></span>
</div>
<div id="grid" class="grid"></div>
<div id="empty" class="empty" style="display:none">Nincs még adat. Várj a mintákra…</div>

<script>
const grid = document.getElementById('grid');
const emptyEl = document.getElementById('empty');
const statusEl = document.getElementById('status');
let timer = null;

function fmt(v){ return v.toFixed(1) + ' ms'; }
function trendCls(v){ return Math.abs(v) < 1 ? 'flat' : (v > 0 ? 'up' : 'down'); }
function trendArrow(v){ return v > 1 ? '▲' : (v < -1 ? '▼' : '◆'); }

function drawCanvas(canvas, p50, p95, color){
  const dpr = window.devicePixelRatio || 1;
  const w = canvas.clientWidth, h = canvas.clientHeight;
  canvas.width = w * dpr; canvas.height = h * dpr;
  const ctx = canvas.getContext('2d');
  ctx.scale(dpr, dpr);
  ctx.clearRect(0,0,w,h);

  const all = p50.concat(p95);
  if(all.length === 0){
    ctx.fillStyle = '#475569'; ctx.font = '11px sans-serif';
    ctx.fillText('nincs elég adat', 10, h/2);
    return;
  }
  const tMin = Math.min.apply(null, all.map(d=>d.t));
  const tMax = Math.max.apply(null, all.map(d=>d.t)) || tMin+1;
  const vMax = Math.max.apply(null, all.map(d=>d.v)) * 1.15 || 1;
  const padL = 36, padR = 6, padT = 6, padB = 16;
  const pw = w - padL - padR, ph = h - padT - padB;

  // grid
  ctx.strokeStyle = '#334155'; ctx.lineWidth = 1; ctx.font = '9px sans-serif';
  ctx.fillStyle = '#64748b';
  for(let i=0;i<=4;i++){
    const y = padT + ph * i/4;
    ctx.beginPath(); ctx.moveTo(padL,y); ctx.lineTo(padL+pw,y); ctx.stroke();
    const val = vMax * (1 - i/4);
    ctx.fillText(val.toFixed(0), 2, y+3);
  }

  function xOf(t){ return padL + pw * (t - tMin)/(tMax - tMin || 1); }
  function yOf(v){ return padT + ph * (1 - v/vMax); }

  function drawSeries(data, col, dash){
    if(data.length < 1) return;
    ctx.strokeStyle = col; ctx.lineWidth = 1.8;
    if(dash) ctx.setLineDash([4,3]); else ctx.setLineDash([]);
    ctx.beginPath();
    data.forEach((d,i)=>{
      const x = xOf(d.t), y = yOf(d.v);
      if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y);
    });
    ctx.stroke();
    ctx.setLineDash([]);
    // utolsó pont
    const last = data[data.length-1];
    ctx.fillStyle = col;
    ctx.beginPath(); ctx.arc(xOf(last.t), yOf(last.v), 2.5, 0, Math.PI*2); ctx.fill();
  }
  drawSeries(p95, '#ef4444', true);
  drawSeries(p50, color, false);
}

function buildCard(t){
  const cls = t.latest_p95 > 500 ? 'critical' : (t.latest_p95 > 200 ? 'degraded' : '');
  const div = document.createElement('div');
  div.className = 'card ' + cls;
  div.innerHTML = `
    <div class="card-head">
      <span class="dot" style="background:${t.color}"></span>
      <span class="tname">${t.name}</span>
      <span class="scnt">${t.sample_count} minta</span>
    </div>
    <div class="stats">
      <div class="stat">
        <div class="lbl">P50</div>
        <div class="val" style="color:${t.color}">${fmt(t.latest_p50)}</div>
        <div class="trend ${trendCls(t.trend_p50)}">${trendArrow(t.trend_p50)} ${t.trend_p50.toFixed(1)}%</div>
      </div>
      <div class="stat">
        <div class="lbl">P95</div>
        <div class="val" style="color:#ef4444">${fmt(t.latest_p95)}</div>
        <div class="trend ${trendCls(t.trend_p95)}">${trendArrow(t.trend_p95)} ${t.trend_p95.toFixed(1)}%</div>
      </div>
    </div>
    <canvas></canvas>
    <div class="legend">
      <span><i style="background:${t.color}"></i>P50</span>
      <span><i style="background:#ef4444;border-top:1px dashed #ef4444"></i>P95</span>
    </div>`;
  return div;
}

async function refresh(){
  const bucket = document.getElementById('bucket').value;
  try{
    const r = await fetch('/api/snapshot?bucket=' + bucket);
    const data = await r.json();
    statusEl.textContent = 'frissítve: ' + new Date().toLocaleTimeString();
    if(!data.transports.length){
      grid.innerHTML = ''; emptyEl.style.display = 'block'; return;
    }
    emptyEl.style.display = 'none';
    grid.innerHTML = '';
    data.transports.forEach(t=>{
      const card = buildCard(t);
      grid.appendChild(card);
      const cv = card.querySelector('canvas');
      // kis késleltetés, hogy a canvas méret rendesen legyen
      requestAnimationFrame(()=>drawCanvas(cv, t.p50, t.p95, t.color));
    });
  }catch(e){ statusEl.textContent = 'hiba: ' + e.message; }
}

function setupTimer(){
  if(timer){ clearInterval(timer); timer = null; }
  const v = parseInt(document.getElementById('interval').value);
  if(v > 0) timer = setInterval(refresh, v);
}

document.getElementById('interval').addEventListener('change', setupTimer);
document.getElementById('bucket').addEventListener('change', refresh);
document.getElementById('refresh').addEventListener('click', refresh);
setupTimer();
refresh();
</script>
</body>
</html>
"""


class DashboardServer:
    """HTTP szerver, ami a latencia dashboardot szolgálja ki."""

    def __init__(self, metrics: LatencyMetrics,
                 host: str = "127.0.0.1", port: int = 8765):
        self.metrics = metrics
        self.host = host
        self.port = port
        self._httpd: Optional[socketserver.TCPServer] = None
        self._thread: Optional[threading.Thread] = None

    def _make_handler(self):
        metrics = self.metrics

        class Handler(http.server.BaseHTTPRequestHandler):
            def log_message(self, fmt, *args):
                pass  # csendes log

            def do_GET(self):
                if self.path.startswith("/api/snapshot"):
                    from urllib.parse import urlparse, parse_qs
                    q = parse_qs(urlparse(self.path).query)
                    bucket = float(q.get("bucket", ["30"])[0])
                    snap = metrics.snapshot(bucket_seconds=bucket)
                    body = json.dumps(snap).encode("utf-8")
                    self.send_response(200)
                    self.send_header("Content-Type", "application/json")
                    self.send_header("Content-Length", str(len(body)))
                    self.send_header("Access-Control-Allow-Origin", "*")
                    self.end_headers()
                    self.wfile.write(body)
                elif self.path == "/" or self.path.startswith("/dashboard"):
                    body = DASHBOARD_HTML.encode("utf-8")
                    self.send_response(200)
                    self.send_header("Content-Type", "text/html; charset=utf-8")
                    self.send_header("Content-Length", str(len(body)))
                    self.end_headers()
                    self.wfile.write(body)
                else:
                    self.send_response(404)
                    self.end_headers()

        return Handler

    def start_background(self) -> None:
        self._httpd = socketserver.TCPServer(
            (self.host, self.port), self._make_handler()
        )
        self._httpd.allow_reuse_address = True
        self._thread = threading.Thread(
            target=self._httpd.serve_forever, daemon=True
        )
        self._thread.start()

    def stop(self) -> None:
        if self._httpd:
            self._httpd.shutdown()
            self._httpd.server_close()
            self._httpd = None
        if self._thread:
            self._thread.join(timeout=5)
            self._thread = None

    def serve_forever(self) -> None:
        """Blokkoló futtatás (fő szálban)."""
        with socketserver.TCPServer((self.host, self.port),
                                    self._make_handler()) as httpd:
            httpd.allow_reuse_address = True
            self._httpd = httpd
            print(f"[dashboard] http://{self.host}:{self.port}/")
            try:
                httpd.serve_forever()
            except KeyboardInterrupt:
                print("\n[dashboard] leállítás…")
            finally:
                httpd.server_close()


# ---------------------------------------------------------------------------
# Demo mód — szintetikus latencia-adat generálása, hogy önállóan fusson
# ---------------------------------------------------------------------------

def _demo_feed(metrics: LatencyMetrics, stop_event: threading.Event) -> None:
    """
    Szintetikus latencia-mintákat generál több transportra, hogy a
    dashboard önállóan is demonstrálja a funkcionalitást.

    Néhány transport idővel 'romlik', hogy látszódjon a degradáció.
    """
    transports = {
        "websocket": {"base": 35, "jitter": 8, "drift": 0.0},
        "http":      {"base": 90, "jitter": 25, "drift": 0.0},
        "grpc":      {"base": 50, "jitter": 12, "drift": 0.0},
        "webrtc":    {"base": 70, "jitter": 30, "drift": 0.0},
    }
    t0 = time.time()
    while not stop_event.is_set():
        elapsed = time.time() - t0
        for name, cfg in transports.items():
            # http 60s után romlani kezd, webrtc 90s után
            drift = 0.0
            if name == "http" and elapsed > 60:
                drift = (elapsed - 60) * 1.8
            if name == "webrtc" and elapsed > 90:
                drift = (elapsed - 90) * 2.5
            base = cfg["base"] + drift
            # néha spike
            lat = base + random.gauss(0, cfg["jitter"])
            if random.random() < 0.05:
                lat += random.uniform(50, 200)
            lat = max(1.0, lat)
            metrics.record(name, lat)
        stop_event.wait(0.15)


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(
        description="P50/P95 latencia dashboard transportonként (A2A Mesh)"
    )
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--no-demo", action="store_true",
                        help="Ne generáljon demo adatot (csak szerver)")
    args = parser.parse_args()

    metrics = LatencyMetrics()
    stop_evt = threading.Event()
    demo_thread: Optional[threading.Thread] = None

    if not args.no_demo:
        print("[demo] szintetikus latencia-adat generálása elindítva…")
        print("[demo]  - websocket: stabil")
        print("[demo]  - grpc:      stabil")
        print("[demo]  - http:      60s után romlik")
        print("[demo]  - webrtc:    90s után romlik")
        demo_thread = threading.Thread(
            target=_demo_feed, args=(metrics, stop_evt), daemon=True
        )
        demo_thread.start()

    server = DashboardServer(metrics, host=args.host, port=args.port)
    try:
        server.serve_forever()
    finally:
        stop_evt.set()
        if demo_thread:
            demo_thread.join(timeout=2)
        server.stop()


if __name__ == "__main__":
    main()