#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
Dashboard reply-polling → pg_notify event-alapú replacement.

Replaces the 3s-interval DB polling loop (30 iterations = 90s) with a
pg_notify LISTEN/NOTIFY event-driven approach. The notify infrastructure
already exists in async_db.py; this module provides a drop-in replacement
for the dashboard's reply-wait pattern.

Usage:
    from dashboard_reply_notify import wait_for_reply

    reply = await wait_for_reply(
        conversation_id="conv_abc123",
        timeout=90.0,
    )

If pg_notify is unavailable, it transparently falls back to polling.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import time
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from typing import Any, AsyncIterator, Callable, Optional

logger = logging.getLogger("a2a_mesh.dashboard.reply_notify")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DEFAULT_TIMEOUT: float = 90.0
FALLBACK_POLL_INTERVAL: float = 3.0
NOTIFY_CHANNEL: str = "dashboard_reply"

# DB connection parameters — read from env, matching async_db.py conventions
DB_DSN: str = os.environ.get(
    "A2A_MESH_DB_DSN",
    os.environ.get("DATABASE_URL", "postgresql://mesh:mesh@localhost:5432/a2a_mesh"),
)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class ReplyEvent:
    """Parsed payload from a pg_notify notification."""
    conversation_id: str
    message_id: str
    agent_name: str
    content: str
    timestamp: float
    raw: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_payload(cls, payload: str) -> "ReplyEvent":
        data = json.loads(payload)
        return cls(
            conversation_id=data["conversation_id"],
            message_id=data.get("message_id", ""),
            agent_name=data.get("agent_name", ""),
            content=data.get("content", ""),
            timestamp=data.get("timestamp", time.time()),
            raw=data,
        )

    def matches(self, conversation_id: str) -> bool:
        return self.conversation_id == conversation_id


# ---------------------------------------------------------------------------
# pg_notify listener (primary path)
# ---------------------------------------------------------------------------

class NotifyListener:
    """
    Async pg_notify listener using psycopg (async).

    Wraps a single async connection that issues LISTEN and waits for
    notifications via conn.notifies(). When a notification arrives on
    the configured channel, it is parsed and dispatched to waiters.
    """

    def __init__(self, dsn: str = DB_DSN, channel: str = NOTIFY_CHANNEL) -> None:
        self.dsn = dsn
        self.channel = channel
        self._conn = None
        self._listen_task: Optional[asyncio.Task] = None
        self._waiters: dict[str, list[asyncio.Future[ReplyEvent]]] = {}
        self._lock = asyncio.Lock()
        self._started = False

    async def start(self) -> None:
        if self._started:
            return
        try:
            import psycopg  # type: ignore
        except ImportError:
            logger.warning("psycopg not installed — NotifyListener disabled")
            raise

        self._conn = psycopg.connect(
            self.dsn, autocommit=True, async_=True
        )
        await self._conn.execute(f"LISTEN {self.channel};")
        self._started = True
        self._listen_task = asyncio.create_task(self._listen_loop())
        logger.info("NotifyListener started on channel '%s'", self.channel)

    async def stop(self) -> None:
        if self._listen_task:
            self._listen_task.cancel()
            try:
                await self._listen_task
            except asyncio.CancelledError:
                pass
        if self._conn:
            await self._conn.close()
        self._started = False
        logger.info("NotifyListener stopped")

    async def _listen_loop(self) -> None:
        assert self._conn is not None
        try:
            async for notify in self._conn.notifiers():
                if notify.channel != self.channel:
                    continue
                try:
                    event = ReplyEvent.from_payload(notify.payload)
                except (json.JSONDecodeError, KeyError) as exc:
                    logger.error("Invalid notify payload: %s (%s)", notify.payload, exc)
                    continue
                await self._dispatch(event)
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            logger.error("Listen loop error: %s", exc)

    async def _dispatch(self, event: ReplyEvent) -> None:
        async with self._lock:
            waiters = self._waiters.get(event.conversation_id, [])
            for fut in waiters:
                if not fut.done():
                    fut.set_result(event)
            # Also dispatch to wildcard waiters
            wildcard = self._waiters.get("*", [])
            for fut in wildcard:
                if not fut.done():
                    fut.set_result(event)
            self._waiters.pop(event.conversation_id, None)

    async def wait(
        self, conversation_id: str, timeout: float = DEFAULT_TIMEOUT
    ) -> Optional[ReplyEvent]:
        loop = asyncio.get_running_loop()
        fut: asyncio.Future[ReplyEvent] = loop.create_future()
        async with self._lock:
            self._waiters.setdefault(conversation_id, []).append(fut)
        try:
            return await asyncio.wait_for(fut, timeout=timeout)
        except asyncio.TimeoutError:
            async with self._lock:
                bucket = self._waiters.get(conversation_id, [])
                if fut in bucket:
                    bucket.remove(fut)
            return None


# ---------------------------------------------------------------------------
# Fallback polling (secondary path)
# ---------------------------------------------------------------------------

async def _poll_for_reply(
    conversation_id: str,
    timeout: float = DEFAULT_TIMEOUT,
    interval: float = FALLBACK_POLL_INTERVAL,
    dsn: str = DB_DSN,
) -> Optional[dict[str, Any]]:
    """
    Fallback: poll the database every `interval` seconds until a reply
    appears or `timeout` is reached. This mirrors the original 3s/90s pattern.
    """
    try:
        import psycopg  # type: ignore
    except ImportError:
        logger.error("psycopg not installed — cannot poll")
        return None

    deadline = time.monotonic() + timeout
    query = """
        SELECT id, conversation_id, agent_name, content, created_at
        FROM mesh_messages
        WHERE conversation_id = %s
          AND role = 'assistant'
          AND created_at >= NOW() - INTERVAL '120 seconds'
        ORDER BY created_at DESC
        LIMIT 1;
    """

    conn = await psycopg.connect(dsn, autocommit=True, async_=True) \
        if hasattr(psycopg, "connect") else None

    # Use sync psycopg in executor if async connect signature differs
    if conn is None:
        import psycopg as _psycopg  # type: ignore
        sync_conn = _psycopg.connect(dsn)
        try:
            while time.monotonic() < deadline:
                with sync_conn.cursor() as cur:
                    cur.execute(query, (conversation_id,))
                    row = cur.fetchone()
                if row:
                    return {
                        "message_id": row[0],
                        "conversation_id": row[1],
                        "agent_name": row[2],
                        "content": row[3],
                        "timestamp": row[4].timestamp() if row[4] else time.time(),
                    }
                await asyncio.sleep(interval)
            return None
        finally:
            sync_conn.close()

    try:
        while time.monotonic() < deadline:
            async with conn.cursor() as cur:
                await cur.execute(query, (conversation_id,))
                row = await cur.fetchone()
            if row:
                return {
                    "message_id": row[0],
                    "conversation_id": row[1],
                    "agent_name": row[2],
                    "content": row[3],
                    "timestamp": row[4].timestamp() if row[4] else time.time(),
                }
            await asyncio.sleep(interval)
        return None
    finally:
        await conn.close()


# ---------------------------------------------------------------------------
# Public API — drop-in replacement for the old polling loop
# ---------------------------------------------------------------------------

# Module-level singleton listener so multiple waiters share one connection
_listener: Optional[NotifyListener] = None
_listener_lock = asyncio.Lock()


async def _get_listener() -> Optional[NotifyListener]:
    global _listener
    if _listener is not None and _listener._started:
        return _listener
    async with _listener_lock:
        if _listener is not None and _listener._started:
            return _listener
        listener = NotifyListener()
        try:
            await listener.start()
            _listener = listener
            return listener
        except Exception as exc:
            logger.info("pg_notify unavailable, will use polling fallback: %s", exc)
            return None


async def wait_for_reply(
    conversation_id: str,
    timeout: float = DEFAULT_TIMEOUT,
    use_notify: bool = True,
) -> Optional[ReplyEvent]:
    """
    Wait for a dashboard reply for the given conversation_id.

    Primary path: pg_notify LISTEN/NOTIFY (event-driven, instant).
    Fallback path: 3s polling for up to `timeout` seconds.

    Returns a ReplyEvent if a reply arrived, or None on timeout.
    """
    if use_notify:
        listener = await _get_listener()
        if listener is not None:
            logger.debug(
                "Waiting for reply via pg_notify (conv=%s, timeout=%.0fs)",
                conversation_id, timeout,
            )
            result = await listener.wait(conversation_id, timeout=timeout)
            if result is not None:
                return result
            logger.debug("pg_notify timed out for conv=%s", conversation_id)
            return None

    # Fallback to polling
    logger.debug(
        "Waiting for reply via polling (conv=%s, interval=%.0fs, timeout=%.0fs)",
        conversation_id, FALLBACK_POLL_INTERVAL, timeout,
    )
    row = await _poll_for_reply(conversation_id, timeout=timeout)
    if row is None:
        return None
    return ReplyEvent(
        conversation_id=row["conversation_id"],
        message_id=row.get("message_id", ""),
        agent_name=row.get("agent_name", ""),
        content=row.get("content", ""),
        timestamp=row.get("timestamp", time.time()),
    )


async def notify_reply(
    conversation_id: str,
    message_id: str,
    agent_name: str,
    content: str,
    dsn: str = DB_DSN,
) -> None:
    """
    Send a NOTIFY on the dashboard_reply channel so waiters wake up instantly.
    Call this after inserting a reply message into the DB.
    """
    payload = json.dumps({
        "conversation_id": conversation_id,
        "message_id": message_id,
        "agent_name": agent_name,
        "content": content[:500],  # truncate for NOTIFY payload limit
        "timestamp": time.time(),
    })
    try:
        import psycopg  # type: ignore
        conn = psycopg.connect(dsn, autocommit=True)
        try:
            # Escape single quotes in payload for SQL
            safe_payload = payload.replace("'", "''")
            conn.execute(f"NOTIFY {NOTIFY_CHANNEL}, '{safe_payload}';")
            logger.debug("NOTIFY sent for conv=%s", conversation_id)
        finally:
            conn.close()
    except ImportError:
        logger.warning("psycopg not installed — cannot send NOTIFY")
    except Exception as exc:
        logger.error("Failed to send NOTIFY: %s", exc)


async def shutdown_listener() -> None:
    """Clean up the module-level listener (call on app shutdown)."""
    global _listener
    if _listener is not None:
        await _listener.stop()
        _listener = None


# ---------------------------------------------------------------------------
# Setup helper — ensures the NOTIFY function/trigger exists in the DB
# ---------------------------------------------------------------------------

SETUP_SQL = """
-- Ensure a function that notifies on new assistant messages
CREATE OR REPLACE FUNCTION notify_dashboard_reply()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.role = 'assistant' THEN
        PERFORM pg_notify(
            'dashboard_reply',
            json_build_object(
                'conversation_id', NEW.conversation_id,
                'message_id', NEW.id,
                'agent_name', NEW.agent_name,
                'content', LEFT(NEW.content, 500),
                'timestamp', EXTRACT(EPOCH FROM NEW.created_at)
            )::text
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop and recreate trigger to avoid duplicates
DROP TRIGGER IF EXISTS tr_notify_dashboard_reply ON mesh_messages;
CREATE TRIGGER tr_notify_dashboard_reply
    AFTER INSERT ON mesh_messages
    FOR EACH ROW
    EXECUTE FUNCTION notify_dashboard_reply();
"""


async def setup_notify_trigger(dsn: str = DB_DSN) -> bool:
    """Create the DB trigger that fires NOTIFY on new replies."""
    try:
        import psycopg  # type: ignore
    except ImportError:
        logger.warning("psycopg not installed — cannot setup trigger")
        return False
    try:
        conn = psycopg.connect(dsn, autocommit=True)
        try:
            conn.execute(SETUP_SQL)
            logger.info("pg_notify trigger installed on mesh_messages")
            return True
        finally:
            conn.close()
    except Exception as exc:
        logger.error("Failed to setup notify trigger: %s", exc)
        return False


# ---------------------------------------------------------------------------
# Demo / self-test
# ---------------------------------------------------------------------------

async def _demo() -> None:
    """
    Self-test: attempt pg_notify path, fall back to polling, report timing.
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )
    conv_id = "demo_conv_001"

    print("=" * 60)
    print("Dashboard reply-polling → pg_notify demo")
    print("=" * 60)

    # Try to set up the trigger
    print("\n[1] Setting up pg_notify trigger...")
    trigger_ok = await setup_notify_trigger()
    print(f"    Trigger installed: {trigger_ok}")

    # Start a background task that simulates a reply after 5s
    async def simulate_reply(delay: float) -> None:
        await asyncio.sleep(delay)
        print(f"\n    >> Simulated reply arriving after {delay}s")
        await notify_reply(
            conversation_id=conv_id,
            message_id="msg_demo_001",
            agent_name="test-agent",
            content="Hello from the notify demo!",
        )

    sim_task = asyncio.create_task(simulate_reply(5.0))

    # Wait for reply via the unified API
    print(f"\n[2] Waiting for reply (conv={conv_id}, timeout=30s)...")
    t0 = time.monotonic()
    reply = await wait_for_reply(conv_id, timeout=30.0)
    elapsed = time.monotonic() - t0

    if reply:
        print(f"\n[3] ✓ Reply received in {elapsed:.2f}s")
        print(f"    agent:   {reply.agent_name}")
        print(f"    content: {reply.content}")
        print(f"    msg_id:  {reply.message_id}")
    else:
        print(f"\n[3] ✗ No reply received after {elapsed:.2f}s")

    await sim_task
    await shutdown_listener()
    print("\nDone.")


if __name__ == "__main__":
    asyncio.run(_demo())