#!/usr/bin/env python3
# Generated by runa via A2A Mesh delegation
"""
Idea: Ütköző ötletek automatikus párosítása és konfliktus-lista generálása
       a szoba végén — gyorsabb döntéshozatal

This module implements automatic detection and pairing of conflicting ideas
in A2A Mesh chat rooms. At the end of a room session, it scans all submitted
ideas, identifies semantic and structural conflicts, pairs them, and generates
a conflict-list for faster decision-making.

Features:
- Parses [ÖTLET] tagged messages from room transcripts
- Detects conflicts via keyword overlap, opposing stance markers, and
  resource/contention analysis
- Pairs conflicting ideas into conflict-pairs
- Generates a structured conflict-list report (text + JSON)
- CLI interface for standalone execution
"""

import re
import json
import os
import sys
import math
import hashlib
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Tuple, Optional, Set
from collections import Counter, defaultdict
from datetime import datetime

# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class Idea:
    """Represents a single submitted idea in a room."""
    idea_id: str
    author: str
    raw_text: str
    title: str
    body: str
    timestamp: str = ""
    tags: Set[str] = field(default_factory=set)
    keywords: Set[str] = field(default_factory=set)
    stance: str = "neutral"  # "propose", "oppose", "neutral"

@dataclass
class ConflictPair:
    """A pair of ideas that conflict with each other."""
    idea_a: Idea
    idea_b: Idea
    conflict_type: str
    conflict_score: float
    explanation: str

@dataclass
class ConflictReport:
    """Full conflict-list report for a room."""
    room_id: str
    generated_at: str
    total_ideas: int
    total_conflicts: int
    conflict_pairs: List[Dict] = field(default_factory=list)
    unpaired_ideas: List[str] = field(default_factory=list)
    summary: str = ""

# ---------------------------------------------------------------------------
# Constants & linguistic resources (Hungarian + English)
# ---------------------------------------------------------------------------

IDEA_PATTERN = re.compile(
    r'\[ÖTLET\]\s*(.+?)(?:\n|$)',
    re.IGNORECASE
)

# Opposing stance markers — words that indicate an idea is against something
OPPOSE_MARKERS = {
    "helyett", "ellenkező", "ne", "ne használj", "tiltsuk", "szüntessük meg",
    "töröljük", "kerüljük", "rossz", "hibás", "felesleges", "káros",
    "against", "instead of", "remove", "avoid", "ban", "delete", "disable",
    "stop", "cancel", "reject", "no more", "deprecate"
}

PROPOSE_MARKERS = {
    "vezessünk be", "adjunk hozzá", "hozzunk létre", "készítsünk",
    "implementáljuk", "indítsuk", "frissítsük", "bővítsük",
    "add", "create", "implement", "introduce", "start", "enable",
    "build", "generate", "launch", "update", "extend"
}

# Hungarian + English stopwords
STOPWORDS = {
    "a", "az", "egy", "azt", "ez", "ezt", "és", "vagy", "hogy", "nem",
    "igen", "is", "mint", "ha", "mert", "de", "még", "már", "csak",
    "is", "the", "a", "an", "is", "are", "was", "were", "be", "been",
    "and", "or", "but", "if", "then", "else", "when", "at", "by",
    "for", "with", "about", "against", "between", "into", "through",
    "during", "before", "after", "above", "below", "to", "from", "up",
    "down", "in", "out", "on", "off", "over", "under", "again", "further",
    "this", "that", "these", "those", "i", "you", "he", "she", "it",
    "we", "they", "me", "him", "her", "us", "them", "my", "your",
    "his", "its", "our", "their", "of", "to", "s", "t", "can", "will",
    "just", "don", "should", "now", "ötlet", "idea"
}

# Topic keywords that, when shared, increase conflict likelihood
TOPIC_BOOST_WORDS = {
    "archiválás", "archivál", "archiválják", "archive",
    "összefoglaló", "szintézis", "summary", "synthesis",
    "ütköző", "konfliktus", "conflict", "conflicting",
    "szoba", "room", "chat",
    "agent", "ágens", "bot",
    "rag", "index", "indexelés",
    "dedup", "duplikátum", "duplicate",
    "döntés", "decision", "voting",
    "üzenet", "message", "post",
    "idő", "time", "timeout", "óra", "hour",
    "szabály", "rule", "policy",
}

# ---------------------------------------------------------------------------
# Text processing utilities
# ---------------------------------------------------------------------------

def tokenize(text: str) -> List[str]:
    """Lowercase, strip punctuation, split into tokens."""
    text = text.lower()
    # Keep Hungarian accented chars
    text = re.sub(r'[^a-záéíóöőúüűñ\s\-]', ' ', text)
    tokens = text.split()
    return [t.strip('-') for t in tokens if t.strip('-') and len(t.strip('-')) > 2]

def extract_keywords(text: str, top_n: int = 15) -> Set[str]:
    """Extract meaningful keywords from text, removing stopwords."""
    tokens = tokenize(text)
    filtered = [t for t in tokens if t not in STOPWORDS]
    # Boost topic words
    counter = Counter(filtered)
    # Weight topic boost words higher
    scored = {}
    for word, count in counter.items():
        score = count
        if word in TOPIC_BOOST_WORDS:
            score += 3
        scored[word] = score
    top = sorted(scored.items(), key=lambda x: -x[1])[:top_n]
    return {w for w, _ in top}

def detect_stance(text: str) -> str:
    """Detect whether an idea proposes or opposes something."""
    lower = text.lower()
    oppose_hits = sum(1 for m in OPPOSE_MARKERS if m in lower)
    propose_hits = sum(1 for m in PROPOSE_MARKERS if m in lower)
    if oppose_hits > propose_hits:
        return "oppose"
    elif propose_hits > oppose_hits:
        return "propose"
    return "neutral"

def extract_tags(text: str) -> Set[str]:
    """Extract #hashtags from text."""
    return set(re.findall(r'#(\w+)', text))

def jaccard_similarity(set_a: Set[str], set_b: Set[str]) -> float:
    """Jaccard similarity between two sets."""
    if not set_a or not set_b:
        return 0.0
    intersection = set_a & set_b
    union = set_a | set_b
    return len(intersection) / len(union) if union else 0.0

# ---------------------------------------------------------------------------
# Idea parsing
# ---------------------------------------------------------------------------

def parse_ideas_from_messages(messages: List[Dict]) -> List[Idea]:
    """
    Parse [ÖTLET] tagged messages into Idea objects.
    Each message dict should have: author, content, timestamp (optional)
    """
    ideas = []
    for msg in messages:
        content = msg.get("content", "")
        author = msg.get("author", "unknown")
        timestamp = msg.get("timestamp", "")
        matches = IDEA_PATTERN.findall(content)
        for match in matches:
            raw = match.strip()
            # Split title and body (first sentence = title)
            parts = re.split(r'[—\-–]\s*', raw, maxsplit=1)
            if len(parts) == 2:
                title, body = parts[0].strip(), parts[1].strip()
            else:
                sentences = re.split(r'[.!?]\s+', raw, maxsplit=1)
                title = sentences[0].strip()
                body = sentences[1].strip() if len(sentences) > 1 else ""
            full_text = f"{title} {body}"
            idea_id = hashlib.md5(
                f"{author}:{raw}".encode()
            ).hexdigest()[:12]
            ideas.append(Idea(
                idea_id=idea_id,
                author=author,
                raw_text=raw,
                title=title,
                body=body,
                timestamp=timestamp,
                tags=extract_tags(full_text),
                keywords=extract_keywords(full_text),
                stance=detect_stance(full_text),
            ))
    return ideas

# ---------------------------------------------------------------------------
# Conflict detection
# ---------------------------------------------------------------------------

def compute_conflict_score(idea_a: Idea, idea_b: Idea) -> Tuple[float, str, str]:
    """
    Compute conflict score between two ideas.
    Returns (score, conflict_type, explanation).
    """
    score = 0.0
    explanations = []
    conflict_type = "none"

    # 1. Keyword overlap — high overlap + opposing stances = conflict
    kw_overlap = jaccard_similarity(idea_a.keywords, idea_b.keywords)
    if kw_overlap > 0.15:
        score += kw_overlap * 30
        shared = idea_a.keywords & idea_b.keywords
        explanations.append(
            f"Közös kulcsszavak: {', '.join(list(shared)[:5])} "
            f"(átfedés: {kw_overlap:.2f})"
        )

    # 2. Opposing stances on same topic
    if idea_a.stance != idea_b.stance and idea_a.stance != "neutral" and idea_b.stance != "neutral":
        score += 25
        conflict_type = "stance_opposition"
        explanations.append(
            f"Ellentétes álláspont: '{idea_a.stance}' vs '{idea_b.stance}'"
        )

    # 3. One proposes, other opposes with keyword overlap
    if (idea_a.stance == "oppose" and idea_b.stance == "propose") or \
       (idea_a.stance == "propose" and idea_b.stance == "oppose"):
        if kw_overlap > 0.1:
            score += 20
            if conflict_type == "none":
                conflict_type = "propose_vs_oppose"
            explanations.append(
                "Egyik javasol, másik tilt/eltávolít — ugyanazon a témán"
            )

    # 4. Same author, different approaches to same keywords
    if idea_a.author == idea_b.author and kw_overlap > 0.2:
        score += 10
        explanations.append("Ugyanaz a szerző, alternatív megközelítések")

    # 5. Tag overlap
    tag_overlap = jaccard_similarity(idea_a.tags, idea_b.tags)
    if tag_overlap > 0.3:
        score += 10
        explanations.append(f"Közös címkék: {', '.join(idea_a.tags & idea_b.tags)}")

    # 6. Direct negation detection — if one title keywords appear in other's
    # body with oppose markers
    a_title_words = set(tokenize(idea_a.title))
    b_body_lower = idea_b.body.lower()
    b_title_words = set(tokenize(idea_b.title))
    a_body_lower = idea_a.body.lower()

    direct_neg_a_in_b = any(
        word in b_body_lower for word in a_title_words
        if word not in STOPWORDS and len(word) > 3
    )
    direct_neg_b_in_a = any(
        word in a_body_lower for word in b_title_words
        if word not in STOPWORDS and len(word) > 3
    )

    if direct_neg_a_in_b or direct_neg_b_in_a:
        if any(m in b_body_lower for m in OPPOSE_MARKERS) or \
           any(m in a_body_lower for m in OPPOSE_MARKERS):
            score += 15
            if conflict_type == "none":
                conflict_type = "direct_negation"
            explanations.append("Közvetlen utalás/tiltás a másik ötlet témájára")

    # Normalize score
    score = min(score, 100.0)

    if score < 20:
        conflict_type = "none"
    elif conflict_type == "none":
        conflict_type = "topic_overlap"

    explanation = "; ".join(explanations) if explanations else "Gyenge átfedés"
    return score, conflict_type, explanation

def find_conflict_pairs(ideas: List[Idea], threshold: float = 20.0) -> List[ConflictPair]:
    """
    Find all conflicting idea pairs above the threshold.
    Uses greedy pairing: highest-scoring conflicts first, each idea
    can appear in multiple pairs (to surface all tensions).
    """
    candidates = []
    for i in range(len(ideas)):
        for j in range(i + 1, len(ideas)):
            score, ctype, expl = compute_conflict_score(ideas[i], ideas[j])
            if score >= threshold and ctype != "none":
                candidates.append((
                    score,
                    ConflictPair(
                        idea_a=ideas[i],
                        idea_b=ideas[j],
                        conflict_type=ctype,
                        conflict_score=score,
                        explanation=expl,
                    )
                ))

    # Sort by score descending
    candidates.sort(key=lambda x: -x[0])
    return [pair for _, pair in candidates]

def pair_conflicts_greedy(pairs: List[ConflictPair]) -> List[ConflictPair]:
    """
    Greedy 1-to-1 pairing: each idea gets at most one conflict pair
    (its strongest). This produces a clean conflict-list for voting.
    """
    used_ids: Set[str] = set()
    result = []
    for pair in pairs:
        if pair.idea_a.idea_id not in used_ids and pair.idea_b.idea_id not in used_ids:
            result.append(pair)
            used_ids.add(pair.idea_a.idea_id)
            used_ids.add(pair.idea_b.idea_id)
    return result

# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def generate_conflict_report(
    room_id: str,
    ideas: List[Idea],
    conflict_pairs: List[ConflictPair],
    all_pairs: Optional[List[ConflictPair]] = None,
) -> ConflictReport:
    """Generate a structured conflict-list report."""
    paired_ids = set()
    for pair in conflict_pairs:
        paired_ids.add(pair.idea_a.idea_id)
        paired_ids.add(pair.idea_b.idea_id)

    unpaired = [idea.title for idea in ideas if idea.idea_id not in paired_ids]

    # Build summary
    if not conflict_pairs:
        summary = "Nincs észlelt konfliktus az ötletek között."
    else:
        type_counts = Counter(p.conflict_type for p in conflict_pairs)
        type_str = ", ".join(f"{t}: {c}" for t, c in type_counts.most_common())
        summary = (
            f"{len(ideas)} ötletből {len(conflict_pairs)} konfliktuspár "
            f"azonosítva. Konfliktus típusok: {type_str}. "
            f"{len(unpaired)} ötlet maradt párosítás nélkül."
        )

    pair_dicts = []
    for pair in conflict_pairs:
        pair_dicts.append({
            "idea_a": {
                "id": pair.idea_a.idea_id,
                "author": pair.idea_a.author,
                "title": pair.idea_a.title,
                "stance": pair.idea_a.stance,
            },
            "idea_b": {
                "id": pair.idea_b.idea_id,
                "author": pair.idea_b.author,
                "title": pair.idea_b.title,
                "stance": pair.idea_b.stance,
            },
            "conflict_type": pair.conflict_type,
            "score": round(pair.conflict_score, 1),
            "explanation": pair.explanation,
        })

    return ConflictReport(
        room_id=room_id,
        generated_at=datetime.now().isoformat(),
        total_ideas=len(ideas),
        total_conflicts=len(conflict_pairs),
        conflict_pairs=pair_dicts,
        unpaired_ideas=unpaired,
        summary=summary,
    )

def format_report_text(report: ConflictReport) -> str:
    """Format the conflict report as readable text."""
    lines = []
    lines.append("=" * 70)
    lines.append("  KONFLIKTUS-LISTA — Ötletütközések automatikus párosítása")
    lines.append(f"  Szoba: {report.room_id}")
    lines.append(f"  Generálva: {report.generated_at}")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"Összes ötlet: {report.total_ideas}")
    lines.append(f"Konfliktuspárok: {report.total_conflicts}")
    lines.append("")
    lines.append("Összegzés: " + report.summary)
    lines.append("")
    lines.append("-" * 70)
    lines.append("KONFLIKTUSPÁROK:")
    lines.append("-" * 70)

    if not report.conflict_pairs:
        lines.append("  (nincs konfliktus)")
    else:
        for i, pair in enumerate(report.conflict_pairs, 1):
            lines.append("")
            lines.append(f"  [{i}] Konfliktus (pont: {pair['score']}, "
                        f"típus: {pair['conflict_type']})")
            lines.append(f"      A: {pair['idea_a']['title']}")
            lines.append(f"         — szerző: {pair['idea_a']['author']}, "
                        f"álláspont: {pair['idea_a']['stance']}")
            lines.append(f"      B: {pair['idea_b']['title']}")
            lines.append(f"         — szerző: {pair['idea_b']['author']}, "
                        f"álláspont: {pair['idea_b']['stance']}")
            lines.append(f"      Magyarázat: {pair['explanation']}")

    lines.append("")
    lines.append("-" * 70)
    if report.unpaired_ideas:
        lines.append("PÁROSOZATLAN ÖTLETEK (nincs észlelt konfliktus):")
        for title in report.unpaired_ideas:
            lines.append(f"  • {title}")
    else:
        lines.append("Minden ötlet párosítva.")

    lines.append("")
    lines.append("=" * 70)
    lines.append("  Javaslat: Szavazzatok a konfliktuspárokon — válasszátok")
    lines.append("  ki az A vagy B oldalt, vagy kombináljátok a kettőt.")
    lines.append("=" * 70)
    return "\n".join(lines)

# ---------------------------------------------------------------------------
# Room transcript loading (from file or inline)
# ---------------------------------------------------------------------------

def load_messages_from_jsonl(filepath: str) -> List[Dict]:
    """Load messages from a JSONL file (one JSON object per line)."""
    messages = []
    if not os.path.exists(filepath):
        return messages
    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    messages.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return messages

def load_messages_from_json(filepath: str) -> List[Dict]:
    """Load messages from a JSON file containing a list of messages."""
    if not os.path.exists(filepath):
        return []
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    if isinstance(data, list):
        return data
    elif isinstance(data, dict) and "messages" in data:
        return data["messages"]
    return []

# ---------------------------------------------------------------------------
# Main conflict-list generator
# ---------------------------------------------------------------------------

def generate_conflict_list(
    room_id: str,
    messages: List[Dict],
    output_dir: str = ".",
    threshold: float = 20.0,
    greedy: bool = True,
) -> ConflictReport:
    """
    Full pipeline: parse ideas → detect conflicts → pair → report.
    Saves report as .txt and .json in output_dir.
    """
    ideas = parse_ideas_from_messages(messages)
    if not ideas:
        print(f"[conflict_list] Nincs [ÖTLET] címkézett üzenet a szobában: {room_id}")
        return ConflictReport(
            room_id=room_id,
            generated_at=datetime.now().isoformat(),
            total_ideas=0,
            total_conflicts=0,
            summary="Nincsenek ötletek a szobában.",
        )

    all_pairs = find_conflict_pairs(ideas, threshold=threshold)

    if greedy:
        paired = pair_conflicts_greedy(all_pairs)
    else:
        paired = all_pairs

    report = generate_conflict_report(room_id, ideas, paired, all_pairs)

    # Save outputs
    os.makedirs(output_dir, exist_ok=True)
    txt_path = os.path.join(output_dir, f"conflict_list_{room_id}.txt")
    json_path = os.path.join(output_dir, f"conflict_list_{room_id}.json")

    with open(txt_path, 'w', encoding='utf-8') as f:
        f.write(format_report_text(report))

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(asdict(report), f, ensure_ascii=False, indent=2)

    print(f"[conflict_list] Riport mentve: {txt_path}")
    print(f"[conflict_list] JSON mentve: {json_path}")
    print(f"[conflict_list] {report.summary}")
    return report

# ---------------------------------------------------------------------------
# Demo / sample data
# ---------------------------------------------------------------------------

SAMPLE_MESSAGES = [
    {
        "author": "mano",
        "timestamp": "2025-01-15T10:00:00",
        "content": "[ÖTLET] Periódikus összefoglaló agent: 10+ üzenet után 3 mondatos szintézis, hogy a későn csatlakozók ne kelljen mindent visszolvasni"
    },
    {
        "author": "mano",
        "timestamp": "2025-01-15T10:01:00",
        "content": "[ÖTLET] Ütköző ötletek automatikus párosítása és konfliktus-lista generálása a szoba végén — gyorsabb döntéshozatal"
    },
    {
        "author": "mano",
        "timestamp": "2025-01-15T10:02:00",
        "content": "[ÖTLET] Inaktív szobák archiválása 48 óra után, tartalom RAG-indexelése későbbi kereséshez"
    },
    {
        "author": "runa",
        "timestamp": "2025-01-15T10:05:00",
        "content": "[ÖTLET] Összefoglaló agent tiltsuk — felesleges overhead, mindenki visszaforgatja a chatet ha kell"
    },
    {
        "author": "runa",
        "timestamp": "2025-01-15T10:06:00",
        "content": "[ÖTLET] Szobák archiválása helyett automatikus törlés 24 óra után — kevesebb tárhely, egyszerűbb rendszer"
    },
    {
        "author": "kovi",
        "timestamp": "2025-01-15T10:10:00",
        "content": "[ÖTLET] Konfliktus-lista generálása manuálisan legyen, ne automatikus — az agent ne döntse el mi ütközik"
    },
    {
        "author": "kovi",
        "timestamp": "2025-01-15T10:11:00",
        "content": "[ÖTLET] RAG-indexelés bővítsük az összes szobára, ne csak archiváltakra — valós idejű keresés"
    },
    {
        "author": "mano",
        "timestamp": "2025-01-15T10:15:00",
        "content": "[ÖTLET] Szintézis agent bővítsük: ne csak 3 mondat, hanem strukturált pontok + nyitott kérdések listája"
    },
]

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Ütköző ötletek automatikus párosítása és konfliktus-lista generálása"
    )
    parser.add_argument(
        "--room-id", default="demo_room",
        help="Szoba azonosító (default: demo_room)"
    )
    parser.add_argument(
        "--input", default="",
        help="Bemeneti fájl (.json vagy .jsonl). Ha üres, demo adatokat használ."
    )
    parser.add_argument(
        "--output-dir", default="./output",
        help="Kimeneti könyvtár (default: ./output)"
    )
    parser.add_argument(
        "--threshold", type=float, default=20.0,
        help="Konfliktus küszöbérték (default: 20.0)"
    )
    parser.add_argument(
        "--all-pairs", action="store_true",
        help="Ne greedy párosítás — mutass minden konfliktuspárt"
    )
    parser.add_argument(
        "--print", action="store_true",
        help="Nyomtassa ki a riportot a képernyőre is"
    )

    args = parser.parse_args()

    # Load messages
    if args.input:
        if args.input.endswith('.jsonl'):
            messages = load_messages_from_jsonl(args.input)
        else:
            messages = load_messages_from_json(args.input)
        if not messages:
            print(f"Hiba: nem sikerült üzeneteket betölteni: {args.input}")
            sys.exit(1)
    else:
        print("[conflict_list] Nincs bemenet megadva — demo adatok használata.")
        messages = SAMPLE_MESSAGES

    report = generate_conflict_list(
        room_id=args.room_id,
        messages=messages,
        output_dir=args.output_dir,
        threshold=args.threshold,
        greedy=not args.all_pairs,
    )

    if args.print or not args.input:
        print()
        print(format_report_text(report))

if __name__ == "__main__":
    main()